- weave/show.py
- weave/usage_analytics.py
Let users know we're working on it, and track events.
> colab user experience

- weave-js/src/core/suggest.test.ts
- weave-js/src/core/suggest.ts
> fix: suggestions edge cases related to string consts

- README.md
- pyproject.toml
Adds a path to get setup with dependencies needed to run example notebooks.
> add examples dependencies

- weave-js/src/core/ops/domain/root.ts
We have new fields in audit logs now.
> Update audit log viewer

- weave-js/src/common/css/globals.styles.ts
- weave-js/src/components/Panel2/PanelInteractContext.tsx
- weave-js/src/components/Sidebar/Outline.tsx
- weave-js/src/components/WeavePanelBank/PBSection.tsx
https://github.com/wandb/weave/assets/682653/01d76390-bf0c-48a0-8b71-15fb4bc44ea8
> feat(weave): panel/outline hover interaction

- .github/workflows/notify-wandb-core.yaml
pairs with https://github.com/wandb/core/pull/15480
> chore(weave): Enable branch level mirroring actions

- weave/logs.py
- weave/server.py
See individual comments for details.
> chore(weave): less confusing log configuration

- weave-js/src/react.tsx
- weave/ops_arrow/list_.py
- weave/ops_arrow/list_join.py
- weave/ops_primitives/list_.py
- weave/tests/test_hypothesis.py
replace joinFn1 with join1Fn and same for 2.
> Fixes Join Params to Match Weave0

- weave-js/src/common/css/color.styles.ts
https://www.figma.com/file/01KWBdMZg5QM9SRS1pQq0z/Design-System----Robot-Styles?node-id=5424%3A29155&mode=dev
> chore(weave): fix green hex values

- weave-js/src/components/Panel2/ChildPanel.tsx
- weave-js/src/components/ValidatingTextInput.tsx
https://wandb.atlassian.net/browse/WB-14149
https://github.com/wandb/weave/assets/682653/74aa41aa-8639-4d84-adb5-cbf36f41fdec
> feat(weave): auto-resize variable name input

- weave-js/.eslintrc.json
- weave-js/src/components/Sidebar/VarBar.tsx
Forces react to be imported in tsx files so we don't get that nasty react not defined error
> Force React import in .tsx files

- weave/ops_arrow/string.py
- weave/ops_primitives/string.py
- weave/tests/test_arrow_vectorizer.py
- weave/tests/test_basic_ops.py
Adds a string `.toNumber()` op and its vectorized equivalent. When the string is not numeric, returns None. 
https://wandb.atlassian.net/browse/WB-14171?filter=10506
> feature: add string.toNumber()

- weave-js/src/components/Panel2/PanelSelectEditor.tsx
- weave-js/src/contextProviders.tsx
Config and config fields are not guaranteed to be defined - using bang assertions is dangerous and leads to runtime errors
> Fixes null config error

- weave-js/src/core/ops/primitives/list.test.ts
- weave-js/src/core/ops/primitives/list.ts
This reverts commit d1843457647bd921fb711ce93e94ef2cc4bff243.
> Revert "update dropna optype (#122)"

- weave-js/src/components/Panel2/PanelTable/tableState.test.fixtures.ts
- weave-js/src/components/Panel2/PanelTable/tableState.test.ts
- weave-js/src/components/Panel2/availablePanels.test.ts
- weave-js/src/components/Panel2/migrator.test.ts
- weave-js/src/components/Panel2/plotState.test.ts
- weave-js/src/core/_external/backendProviders/serverApiTest2.ts
https://wandb.atlassian.net/browse/WB-14385
Grabs the relevant Panel2 unit tests from core and runs them under weave CI.
> chore: move tests over from core

- weave-js/src/components/Panel2/PanelTable/Link.tsx
- weave-js/src/components/Panel2/PanelTable/PanelTable.tsx
Internal Jira: https://wandb.atlassian.net/browse/WB-14367
Before:
After:
> chore: update styling of "Clear filters"

- weave-js/src/contextProviders.tsx
This reverts commit 1d409522d4f8be50d3c4ee0e8b62f706ed4d1684.
> Revert "added polling (#153)"

- weave-js/src/panel/WeaveExpression/index.tsx
Internal slack thread: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1689286856889829
> chore: slight tweak of suggestion panel display rule

- weave-js/src/components/PagePanelComponents/Home/HomeCenterEntityBrowser.tsx
- weave-js/src/components/Panel2/pyBoardGen.tsx
GitHub is warning about these in unrelated PRs.
> chore: fix lint warnings

- weave/ops_domain/run_history/run_history_v3_parquet_stream_optimized.py
- weave/tests/test_wb_history_loading_compatability.py
Fixes: https://wandb.atlassian.net/browse/WB-14552
> chore: Fix StreamTable missing data with disjoint schemas

- weave-js/src/components/PagePanelComponents/DeleteActionModal.tsx
- weave-js/src/components/PagePanelComponents/Modal.styles.tsx
- weave-js/src/components/PagePanelComponents/PersistenceManager.tsx
- weave-js/src/components/PagePanelComponents/persistenceStateMachine.ts
- weave/artifact_wandb.py
Also adds a confirmation dialog to better avoid accidental data loss.
Internal Jira: https://wandb.atlassian.net/browse/WB-14573
> feat: can now delete remote boards

- weave/wandb_client_api.py
Fixes publishing new boards in cloud weave
Tested in QA
> chore (weave): Fix publishing in app

- weave-js/src/components/Panel2/useAssetFromArtifact.ts
- weave/ops_domain/wb_util.py
- weave/runfiles_wandb.py
Properly handle media file types in `_process_run_dict_item`
> fix(weave): properly load media from run files

- weave/artifact_wandb.py
- weave/storage.py
- weave/wandb_interface/wandb_artifact_pusher.py
- weave/wandb_interface/wandb_lite_run.py
- weave/wandb_interface/wandb_stream_table.py
* Hides StreamTable runs in W&B UI
* Reduces StreamTable initialization to single run
* Prevents StreamTable runs crashing from sending alerts
Fixes https://wandb.atlassian.net/browse/WB-14574
> chore(weave): Hide StreamTable runs in W&B

- .github/workflows/test.yaml
- weave-js/.eslintrc.json
Makes eslint warnings block CI
> ci: make eslint warnings block

- weave-js/src/components/Panel2/ChildPanel.tsx
- weave-js/src/components/Panel2/ConfigPanel/index.tsx
Internal Jira: https://wandb.atlassian.net/browse/WB-14487 (partial)
Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1689744307148939
Three small changes:
* Rename "Type" to "Panel type" for clarity
* Move Input above Panel type
* Don't show `variables` header when there are no variables.
> feat: adjust order of input/panel type in config

- weave-js/src/common/css/globals.styles.ts
- weave-js/src/common/css/globals_deprecated.styles.ts
https://wandb.atlassian.net/browse/WB-14751
> chore(style): add @deprecated for deprecated globals

- requirements.txt
- weave/artifact_wandb.py
- weave/tests/fixture_fakewandb.py
- weave/tests/test_wb_data_types.py
- weave/wandb_interface/wandb_artifact_pusher.py
Fixes WB-14691
Upgraded wandb to the latest version.
CI
> chore(weave): upgrade wandb

- weave-js/src/components/PagePanel.tsx
- weave-js/src/components/PagePanelComponents/PersistenceManager.tsx
https://wandb.atlassian.net/browse/WB-14678
> chore(weave): Hide code export buttons

- weave/logs.py
Also added a warning if an invalid value is specified.
> feat: WEAVE_LOG_LEVEL now accepts lowercase value

- weave-js/src/common/util/render_babylon.ts
Resolves https://github.com/wandb/wandb/issues/5938
Demo: [Screencast from 2023-07-26 10-24-33.webm](https://github.com/wandb/weave/assets/35003073/8d3f7e29-8e96-4932-b447-57fb8756eb08)
Would appreciate any feedback!
> feat: Allow for interactive pointSize configuration in pointCloudScene 

- requirements.test.txt
Adds timestamps to test completions in our pytest setup.
> ci: add pytest timestamper

- weave-js/src/components/Panel2/PanelTraceTree/PanelTraceTreeFromHistoryTableViewer.tsx
When there are multiple runs of different shapes, the strip function was not stripping out system metrics or underscores. This fixes that implementation
> chore(weave): Fixes prompts custom columns when inputs are unions

- weave-js/src/components/Tag/Alias.tsx
- weave-js/src/components/Tag/Pill.tsx
- weave-js/src/components/Tag/RemoveAction.tsx
- weave-js/src/components/Tag/Tag.tsx
- weave-js/src/components/Tag/index.ts
- weave-js/src/components/Tag/utils.ts
Step 1 moving tag component into weave
> chore(weave): Move tag, alias, and pill components

- weave-js/index.html
- weave-js/src/components/PagePanel.tsx
- weave-js/src/components/PagePanelComponents/Home/Home.tsx
- weave-js/src/components/PagePanelComponents/Home/HomeCenterBrowser.tsx
- weave-js/src/components/PagePanelComponents/Home/HomeCenterEntityBrowser.tsx
- weave-js/src/components/PagePanelComponents/Home/HomeCenterLocalBrowser.tsx
- weave-js/src/components/PagePanelComponents/Home/HomeLeftNav.tsx
- weave-js/src/components/PagePanelComponents/Home/HomePreviewSidebar.tsx
- weave-js/src/components/PagePanelComponents/Home/LayoutElements.tsx
- weave-js/src/entrypoint.tsx
- weave-js/src/urls.ts
- weave-js/src/util/document.ts
Internal Jira: 
https://wandb.atlassian.net/browse/WB-14441
https://wandb.atlassian.net/browse/WB-14543
This adds routing to the UI, allowing you to link someone to a particular entity/project/asset and navigate between pages with the browser back button.
> feat: routing for home page

- weave-js/src/components/PagePanelComponents/Home/HomeCenterEntityBrowser.tsx
Internal Jira: https://wandb.atlassian.net/browse/WB-14944
Minor menu adjustments based on design feedback. FYI @Cecile0112358 
* Swap order of "Open board" and "Board details"
* No divider between those two
* Sentence case
> chore: update order of menu items

- weave-js/index.html
> chore(weave): Foundation for nice OpenGraph Previews

- weave-js/src/core/ops/domain/run.ts
This wires up the refinement path correctly
> chore(weave): Enable the hidden .history3 to work properly in app

- weave-js/src/components/PagePanelComponents/Home/Home.tsx
- weave-js/src/components/PagePanelComponents/Home/HomeCenterEntityBrowser.tsx
- weave-js/src/components/PagePanelComponents/Home/HomePreviewSidebar.tsx
- weave-js/src/core/server/remoteHttp.ts
- weave-js/vite-plugin-block-cjs.ts
- weave/panels_py/panel_seedboard.py
https://github.com/wandb/weave/assets/25037002/fa49dec6-5aa5-4362-a80a-f0c5d5c9ae7b
> chore(weave): add tabs, and template ui to sidebar

- weave-js/src/components/PagePanelComponents/Home/HomeCenterEntityBrowser.tsx
- weave-js/src/components/PagePanelComponents/Home/HomePreviewSidebar.tsx
on boards, create new board option was showing up
we should hide that
> chore(weave): Hide templates for boards

- weave-js/src/components/Panel2/PanelPlot/PanelPlot.tsx
- weave-js/src/components/Panel2/PanelPlot/plotState.ts
- weave-js/src/components/Panel2/PanelPlot/versions/index.ts
- weave-js/src/components/Panel2/PanelPlot/versions/v15.ts
- weave-js/src/components/Panel2/plotState.test.ts
- weave/panels/panel_plot.py
* Adds LegendSettings for pointSize, pointShape, and lineStyle dimensions
* Makes noLegend settings be correctly respected everywhere
* Updates panel_plot.py to conform to the new spec
> feat: allow more fine grained configuration of legends in panelplot 

- weave-js/env.js
- weave-js/index.html
- weave/environment.py
- weave/weave_server.py
This allows us to pipe down env settings to the frontend exposing them on `window.CONFIG`
> feat(weave): Make new dynamic env endpoint

- .github/workflows/test.yaml
Disable code autoformat until we can figure out how to make it trigger CI.
> chore: disable code autoformat

- weave-js/src/components/PagePanelComponents/Home/Home.tsx
- weave-js/src/entrypoint.tsx
- weave-js/src/urls.ts
It got lost in some of the back and forth over URL structure but we had decided there should be a leading "browse" path segment.
Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1691531852091589?thread_ts=1691445491.662569&cid=C03BSTEBD7F
> fix: URL structure was supposed to have 'browse'

- weave-js/env.js
- weave-js/index.html
- weave/environment.py
- weave/weave_server.py
This reverts commit f7748df66cdef9f81dc8557a5d7dc54b830a3f5d.
With this commit I'm unable to render Weave in notebooks on master
> chore: Revert "Make new dynamic env endpoint (#403)"

- weave-js/src/components/Panel2/ChildPanel.tsx
- weave-js/src/components/Panel2/PanelDateRange.tsx
makes headers sentence case and some small tweaks to font size and spacing
> style(weave): Some small design updates to varbar

- weave-js/src/core/ops/domain/local.ts
- weave/ops_arrow/arraylist_ops.py
- weave/ops_arrow/boolean.py
New ops were not handling tags, which broke using the LLM board on actual StreamTables
> fix: llm mon board

- weave-js/src/components/Button/Button.tsx
https://wandb.atlassian.net/browse/WB-15164
Updates `Button` disabled styles so you can tell what variant a button is even when disabled.
> feat(ui): Update disabled Button styles

- weave-js/src/assets/icons/icon-overflow-vertical.svg
- weave-js/src/components/Icon/Icon.tsx
- weave-js/src/components/Icon/index.ts
- weave-js/src/components/Icon/types.ts
> chore(ui): add icon overflow-vertical

- examples/monitoring/README.md
- examples/monitoring/openai_client_quickstart.ipynb
- examples/monitoring/openai_proxy_quickstart_enterprise_mode.ipynb
- Add `view in colab` buttons
- Move settings to top of files
- Make it clear how to target a non SaaS deployment
- better handling of enterprise mode for proxy
> chore(weave): Small touchups for upcoming release

- .github/workflows/upload-assets.yaml
- weave/frontend/bundle.sh
example end to end run: https://github.com/wandb/weave/actions/runs/5955305109/job/16153659956
> chore(dev): fix asset upload script

- weave-js/src/components/Panel2/ChildPanel.tsx
- weave-js/src/components/Panel2/PanelExpression/styles.ts
Helps with debugging via react developer tools.
> chore: add display names

- .github/workflows/cla.yaml
- .github/workflows/upload-assets.yaml
This time I actually tested the workflow :(
> chore(dev): fix typo in upload asset action

- weave-js/src/components/Sidebar/OutlineItemPopupMenu.tsx
Internal Jira: https://wandb.atlassian.net/browse/WB-15135
Also, makes "Split" only show for panels under main.
> chore: remove legacy Send to query bar action

- weave-js/src/common/css/SemanticOverride.less
- weave-js/src/globalStyleImports.ts
Internal Jira: https://wandb.atlassian.net/browse/WB-15180
Before:
After:
> chore: update dimmer background color

- weave/gql_to_weave.py
- weave/ops_domain/run_history/run_history_v1_legacy_ops.py
- weave/ops_domain/run_history/run_history_v2_parquet_media.py
- weave/ops_domain/run_history/run_history_v3_parquet_stream_optimized.py
- weave/tests/test_gql_to_weave.py
Treats `JSON[]` as `String()` in gql_mappers, improving performance of the OpenAI dashboard.
> fix: Handle json arr

- weave-js/src/common/util/hooks.ts
- weave-js/src/components/PagePanelComponents/Home/HomePreviewSidebar.tsx
- weave-js/src/components/PagePanelComponents/util.ts
- weave-js/src/components/Panel2/PanelPanel.tsx
- weave-js/src/components/Panel2/PanelPlot/PanelPlot.tsx
- weave-js/src/panel/WeaveExpression/hooks.ts
> chore(weave): Revert "chore(weave): Cleanup various memory leaks"

- weave-js/src/components/PagePanelComponents/Home/HomePreviewSidebar.tsx
Partial re-application of reverted https://github.com/wandb/weave/pull/493
> chore(weave): Mem Leak - Re-apply sidebar fix

- weave-js/src/common/util/hooks.ts
- weave-js/src/components/Panel2/PanelPlot/PanelPlot.tsx
Partial re-application of reverted https://github.com/wandb/weave/pull/493
> chore(weave): Mem Leak - Re-apply panel plot

- weave-js/src/common/util/hooks.ts
- weave-js/src/panel/WeaveExpression/hooks.ts
Partial re-application of reverted https://github.com/wandb/weave/pull/493
> chore(weave): Mem Leak - Re-apply expression hooks

- weave-js/src/components/Panel2/ChildPanel.tsx
- weave-js/src/components/Sidebar/OutlineItemPopupMenu.tsx
https://github.com/wandb/weave/assets/25037002/5885cfd1-e7ee-49c3-b24e-7a3dd9e1a071
> chore(weave): Fix delete with editor open

- weave/artifact_wandb.py
Upon investigation of https://wandb.atlassian.net/browse/WB-15392, I noticed a very large number of issues relating to invalid concats. An example is here: https://app.wandb.test/canva/kaleido-db-lora/runs/nlww09io?workspace=user-destevez-kaleido. After much investigation, I realized this occurs when the `latest` alias has been deleted. This PR protects against such cases and will dynamically return the most recent artifact version when `latest` is missing. This is similar to what we do in the js world with `resolveSequenceAliasToArtifactId`.
> chore(weave): Fix loading latest alias when it does not exist

- weave/errors.py
Simplifies fingerprint error mixin and fixes mypy type checking
> chore: fix fingerprint error mixin

- weave-js/src/common/hooks/useViewerIsWandbEmployee.tsx
- weave-js/src/components/Sidebar/OutlineItemPopupMenu.tsx
- weave-js/src/core/ops/domain/gql.ts
- weave-js/src/core/ops/domain/user.ts
- weave/ops_domain/user_ops.py
- weave/tests/test_op_coverage.py
https://wandb.atlassian.net/browse/WB-15450
https://github.com/wandb/weave/assets/17016170/58385fff-cbc0-478d-be82-75bc8f96dbc5
> feat(wir): Set up internal feature flag for report exports

- weave-js/src/components/Form/Select.tsx
https://wandb.atlassian.net/browse/WB-15453
Step 1 of moving the Select component from the app into Weave, allowing us to use it in both places.
> chore(wir): copy Select comp from core

- weave-js/src/components/PagePanel.tsx
- weave-js/src/components/Panel2/ChildPanelExportReport.tsx
- weave-js/src/components/Panel2/ChildPanelExportReport/ChildPanelExportReport.tsx
- weave-js/src/components/Sidebar/OutlineItemPopupMenu.tsx
https://wandb.atlassian.net/browse/WB-15452
https://github.com/wandb/weave/assets/17016170/40531471-4846-47af-8778-f6d795e34f71
> feat(wir): Set up report export drawer contents

- weave/node_ref.py
- weave/ops_domain/artifact_version_ops.py
Depends on https://github.com/wandb/core/pull/16594
Adds some ops for querying artifact dependencies.
> feat: add artifact dependency ops

- weave-js/src/components/Panel2/PanelPanel.tsx
- weave-js/src/components/Sidebar/Config.tsx
Internal Slack report: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1694556042689669
> fix: outline scrolls vertically when necessary

- weave/engine_trace.py
Fixes a memory leak in the weave usage sender process by making it a daemon.
> fix: fix memory leak in sender by making weave writer process daemon

- weave-js/src/components/PagePanelComponents/Home/BoardsTab.tsx
- weave-js/src/components/PagePanelComponents/Home/BoardsTabNone.tsx
- weave-js/src/components/PagePanelComponents/Home/HomePreviewSidebar.tsx
- weave-js/src/components/PagePanelComponents/Home/common.ts
- weave-js/src/components/PagePanelComponents/Home/styles.ts
- weave-js/src/components/Panel2/pyArtifactDep.tsx
- weave-js/src/core/util/string.ts
- weave/artifact_wandb.py
Internal Jira: https://wandb.atlassian.net/browse/WB-14546
> feat: display boards tab in table preview

- weave-js/src/core/suggest.ts
Internal Jira: https://wandb.atlassian.net/browse/WB-15708
Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1695653860215399?thread_ts=1695653244.383959&cid=C03BSTEBD7F
> fix: don't suggest objectConstructor-_new_* ops in expression editor

- weave-js/src/components/Panel2/PanelPlot/PanelPlot.tsx
https://www.loom.com/share/35eeae3e56644db595346da941ff5974
> fix: set max x axis label length

- weave-js/src/components/Panel2/PanelPlot/PanelPlot.tsx
- weave-js/src/components/Panel2/PanelPlot/RadioButtons.tsx
https://www.loom.com/share/9466c530c661472194e5f3dfd03bf34b
> feat: only show panel plot radio buttons on mouseover 

- weave-js/src/components/PagePanel.tsx
- weave-js/src/config.ts
- weave/weave_server.py
Makes WANDB_BASE_URL from weave server accessible to the weave frontend.
> chore: plumb wb base url through env.js

- weave/panels/panel_plot.py
- weave/stitch.py
Fixes internal JIRA ticket https://wandb.atlassian.net/browse/WB-15699
https://www.loom.com/share/33c28cab046441429db0d9c75eba8e08
> fix: fix autoboard

- examples/prompts/llm_monitoring/openai_proxy_quickstart.ipynb
need table in url to streamtable
> docs(weave): add table into url for streamtable

- weave-js/package.json
Required setup for https://github.com/wandb/core/pull/17379
> chore: Set up empty yarn generate command

- weave-js/src/core/ops/domain/local.ts
Allows selecting data from facet panels as an op.
> chore: unhide facet panel

- .github/CODEOWNERS
Requires weave-team approval on weave prs.
> ci(weave): require codeowner approval for merging

- weave-js/src/components/PagePanelComponents/PublishModal.tsx
JIRA ticket: https://wandb.atlassian.net/browse/WB-15881
> feat(weave): Typeahead for projects dropdown in publish modal

- wb_schema.gql
- weave-js/src/components/Panel2/ChildPanelExportReport/ChildPanelExportReport.tsx
- weave-js/src/components/Panel2/ChildPanelExportReport/graphql.ts
- weave-js/src/config.ts
- weave-js/src/core/_external/util/urls.ts
https://wandb.atlassian.net/browse/WB-15493
- Adds panel to report if it has an existing draft
- Error handling added [separately](https://github.com/wandb/weave/pull/700)
- New report & reports without drafts will be handled in subsequent PRs
https://github.com/wandb/weave/assets/17016170/f0dad829-0f71-4ad7-8cce-360fe589cdd1
> feat(wir): Add panel to report with existing draft

- weave-js/src/components/PagePanel.tsx
- weave-js/src/components/PagePanelComponents/Home/HomeCenterEntityBrowser.tsx
- weave-js/src/context/WeaveViewerContext.tsx
- weave-js/src/util/urls.ts
Internal Jira: https://wandb.atlassian.net/browse/WB-15842
This will also require a middleware change from https://github.com/wandb/core/pull/17442
> fix: redirect user to signup when required

- examples/experimental/llm_monitor_helper.ipynb
- weave/ops_arrow/boolean.py
- weave/panels_py/panel_llm_monitor.py
I am working with a customer and want to share this as an example of how to log llm calls directly without using any special wrappers
> chore(weave): Give simple function for logging llm logs

- integration_test/package.json
Bump deploy sentinel version to 0.8.5.
> chore: bump deploy sentinel

- weave-js/src/assets/icons/icon-overflow-vertical.svg
- weave-js/src/components/Icon/Icon.tsx
- weave-js/src/components/Icon/index.ts
- weave-js/src/components/Icon/types.ts
https://wandb.atlassian.net/browse/WB-15244
unused icon, design team doesn't want it anymore
> chore(ui): Remove overflow-vertical icon

- weave-js/src/panel/WeaveExpression/state.ts
Internal Jira: https://wandb.atlassian.net/browse/WB-15669
Recommend "Hide Whitespace" when reviewing.
> feat: show suggestions when clicking on an empty EE

- integration_test/cypress/e2e/interactive/dashboard.cy.ts
- integration_test/cypress/e2e/interactive/distribution.cy.ts
- integration_test/cypress/e2e/interactive/distribution.py
- integration_test/cypress/e2e/testlib.ts
- weave-js/src/components/Panel2/ChildPanel.tsx
- weave-js/src/components/Panel2/PanelPanel.tsx
Adds this integration test:
https://www.loom.com/share/271b0e162ae247fb9bd569dd1bc4e987
> ci: re-enable distribution integration test

- integration_test/cypress/e2e/interactive/dashboard.cy.ts
- integration_test/cypress/e2e/interactive/distribution.cy.ts
- integration_test/cypress/e2e/interactive/plotboard.cy.ts
- integration_test/cypress/e2e/testlib.ts
- weave-js/src/components/Panel2/PanelPlot/PanelPlot.tsx
Adds the following integration test:
https://www.loom.com/share/86a7904f5f4f47f3b2c0f5d498143af2
> ci: add plotboard integration test

- weave-js/src/core/ops/primitives/list.ts
- weave-js/src/core/suggest.test.ts
- weave-js/src/core/suggest.ts
Also updated the op doc for range, since this change makes it more visible.
> feat: show root ops on empty expression

- weave-js/src/components/Tag/Alias.tsx
- weave-js/src/components/Tag/Pill.tsx
- weave-js/src/components/Tag/RemoveAction.tsx
- weave-js/src/components/Tag/Tag.tsx
- weave-js/src/components/Tag/WorkspaceTag.tsx
I broke storybook, because I forgot to push the update to tags before merging
> chore(weave): fix storybook for tags

- weave-js/src/common/types/base.ts
- weave-js/src/components/Panel2/ChildPanelExportReport/ChildPanelExportReport.tsx
- weave-js/src/components/Panel2/ChildPanelExportReport/utils.ts
Setup for https://wandb.atlassian.net/browse/WB-15500
No functional changes
Testing:
- Can still export to new report
- Can still export to report without existing draft
- Can still export to report with existing draft
> refactor(wir): Break onAddPanel into smaller utils

- wb_schema.gql
- weave-js/src/components/Dialog/Dialog.tsx
- weave-js/src/components/Panel2/ChildPanelExportReport/ChildPanelExportReport.tsx
- weave-js/src/components/Panel2/ChildPanelExportReport/ReportDraftDialog.tsx
- weave-js/src/components/Panel2/ChildPanelExportReport/graphql.ts
- weave-js/vite-plugin-block-cjs.ts
Depends on https://github.com/wandb/weave/pull/791
https://wandb.atlassian.net/browse/WB-15500
Testing:
1. In core, start new draft for a report. Make some changes but do not publish.
2. In weave, export a panel to that report
3. Confirmation dialog should pop up
4. Choose "add to active draft"
5. Verify panel is added to draft
6. Repeat steps 2-3
7. Choose "discard and start new draft"
8. Verify previous draft is gone, panel is added to new draft
https://github.com/wandb/weave/assets/17016170/7a2880c3-ad09-425b-b60a-dafdbdc08270
> feat(wir): Show resume or discard report draft dialog

- weave-js/src/components/Sidebar/Outline.tsx
Internal Slack thread: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1697219819003369
> feat: improved outline icons

- weave-js/src/components/Panel2/PanelTable/PanelTable.tsx
Internal Jira: https://wandb.atlassian.net/browse/WB-14328
Removed a layer of indentation - recommend "Hide whitespace" when viewing diff.
> fix: remove empty tooltip popup on table row index

- weave-js/src/components/Form/Select.tsx
Refactoring to support exposing the aync version of react-select. Also fixes styling of the clear indicator at small sizes.
> chore: add async support to styled select

- weave-js/src/components/Panel2/ChildPanelExportReport/computeReportSlateNode.ts
- weave-js/src/components/Panel2/PanelGroup.tsx
- weave-js/src/contextProviders.tsx
https://wandb.atlassian.net/browse/WB-15556
https://github.com/wandb/weave/assets/17016170/0fb132e9-7300-4c91-ba0d-ef4a231f432b
> feat(wir): Allow manual controlBar setting for PanelGroup children

- weave-js/src/components/Dialog/Dialog.tsx
- weave-js/src/components/DropdownMenu/DropdownMenu.tsx
realized i forgot to handle these forwarded refs for some of our common comps!
recommend reviewing with whitespace hidden
> fix(ui): Set forwarded refs for radix comps

- weave-js/src/components/Panel2/ChildPanelExportReport/ChildPanelExportReport.tsx
https://wandb.atlassian.net/browse/WB-16218
before: open exporter, update panel value, submit -> exported panel is stale
https://github.com/wandb/weave/assets/17016170/67241991-5726-4bd9-86ec-d973bf0657e3
after: exported panel is correct
https://github.com/wandb/weave/assets/17016170/bd4fcd61-8f3a-4694-90f6-175b1646cd41
> fix(wir): Get latest panel config on report export

- weave-js/src/components/Panel2/ChildPanelExportReport/ReportSelection.tsx
bug bash feedback from stephen/yangyi:
https://www.notion.so/wandbai/Couldn-t-find-just-published-report-f70a7d16231a422c9c0e9a05909230e2?pvs=4
> fix(wir): Refresh reports when exporter is opened

- weave-js/tailwind.config.cjs
relates to https://github.com/wandb/core/pull/18073
> fix(ui): Add tailwind shadow config

- weave-js/tailwind.config.cjs
https://github.com/wandb/core/pull/18116
> fix(ui): Set default box shadow color for tailwind

- weave-js/src/components/Sidebar/OutlineItemPopupMenu.tsx
> chore(wir): Turn on report export for external users

- weave-js/src/components/Dialog/Dialog.tsx
https://www.figma.com/file/01KWBdMZg5QM9SRS1pQq0z/Design-System----Robot-Styles?node-id=3313%3A19615&mode=dev
> chore(ui): Apply more Dialog design styles 

- weave-js/src/components/PagePanelComponents/Home/Browse2/Browse2ObjectPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse2/LinkTable.tsx
- weave-js/src/components/PagePanelComponents/Home/query.tsx
- weave-js/src/util.ts
https://www.loom.com/share/762e8c532a2d4233a3b5f7519a6bb842
> feat(weaveflow): make versions table better

- weave-js/src/components/PagePanelComponents/Home/Browse2/SpanDetails.tsx
Adds a basic document experience to make viewing lists of strings easier.
> feat(weaveflow): add basic document experience

- weave-js/vite-plugin-block-cjs.ts
Remove mention of unused icons
> chore: remove unused icon code

- weave-js/src/core/server/remoteHttp.test.ts
- weave-js/src/core/server/remoteHttp.ts
- weave-js/src/core/util/id.ts
Adds a random UUID for each remoteHttp server request, so that requests can be matched up with backend logs and traces.
> chore: add a random UUID for each FE request

- weave-js/src/components/PagePanelComponents/Home/query.tsx
Ensures board query is correct after weaveflow merge
> chore(weave): Fix board query post-weaveflow merge

- weave-js/src/components/PagePanelComponents/Home/Browse2.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse2/Browse2EntityPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse2/Browse2HomePage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse2/Browse2ObjectPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse2/Browse2ProjectPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse2/Browse2RootObjectType.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse2/Browse2TracePage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse2/Browse2TracesPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse2/SmallRef.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse2/url.ts
- weave-js/src/entrypoint.tsx
This PR make it possible to mount `Browse2` to any subpath.
> chore(weave): Make weaveflow (browse2) mountable anywheree

- weave-js/src/components/Panel2/PanelExpression/ConfigComponent.tsx
- weave-js/src/components/Panel2/PanelPlot/PanelPlot.tsx
Internal Jira: https://wandb.atlassian.net/browse/WB-16408
Update to newer button component.
Before:
After:
> chore: update to new button component

- weave-js/src/core/ops/primitives/date.ts
- weave/ops_primitives/date.py
- weave/panels/panel_board.py
- weave/panels_py/__init__.py
- weave/panels_py/panel_observability.py
v0, but possibly still useful observability template.
> feat(launch): queue observability dashboard template

- weave/mappers_arrow.py
- weave/ops_arrow/date.py
- weave/ops_primitives/date.py
- weave/tests/test_arrow_vectorizer.py
Adds vectorized implementations of datetime add and sub.
> feat: Vectorize date ops

- weave/ops_arrow/vectorize.py
- weave/panels_py/panel_observability.py
> revert: "feat: launch qod next iteration "

- weave-js/src/core/model/helpers.ts
I think this is probably just a copy+paste bug?
> fix: isTimestamp type guard

- weave/weave_server.py
Disable weaveflow faiss import in server for now.
> chore: Fix weaveflow eager

- weave/dispatch.py
- weave/ops_arrow/date.py
- weave/ops_arrow/list_.py
- weave/storage.py
1. Prefer AWL over Mapped even with null values
2. Don't look at every value when serializing results
> chore(weave): Perf improvements for workspace plots

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimpleFilterableDataTable.tsx
> chore(weave): Makes the filter controls hidden by default

- weave/execute.py
- weave/ref_base.py
- Disable memo (i will bring back in a subsequent PR)
- Fix nested ref digests,
- Don't save const<Function> (lambdas)
> chore: Wf fixes2

- weave-js/src/components/Panel2/PanelPlot/plotState.ts
Internal Jira: https://wandb.atlassian.net/browse/WB-16644
Update the logic of assigning default X and Y selectors to allow them to take on a string value. While this won't always result in the most useful plots, it's preferable to showing the user an unclear error.
Note that there are other inputs that lead to this error, like a list of numbers, that are not addressed in this PR.
Before:
After: (Note - this is also illustrating the issue from https://github.com/wandb/weave/pull/958)
> feat: x and y columns can now default to string type columns

- weave-js/src/core/suggest.ts
- weave-js/src/panel/WeaveExpression/styles.ts
- weave-js/src/panel/WeaveExpression/suggestions.tsx
Internal Jira: https://wandb.atlassian.net/browse/WB-16503
Categorize and label expression editor sections. There might be better category labels for some of these but that should be easy to tweak once this functionality is in place.
Before:
After:
> feat: group suggestions in expression editor

- weave-js/src/components/Panel2/SelectPanelType.tsx
Just fixing a bad name from copy+paste.
> chore: fix copy-and-paste naming

- weave-js/src/core/ops/domain/run.ts
- weave/ops_domain/run_ops.py
- weave/ops_domain/wb_domain_types.py
Create a simple op that takes strings and returns a weave link. js op is stubbed and throws an error. 
https://wandb.atlassian.net/browse/WB-16622
> feat: add simple strings-to-run-link op

- weave-js/src/common/components/Monaco/Editor.tsx
https://wandb.atlassian.net/browse/WB-16744
> chore(launch): allow setting monaco wordwrap

- weave-js/src/components/Panel2/PanelPlot/columnHelpers.ts
Some helper methods that will be used in upcoming PRs that add new column selector widget.
> chore: add column helpers for plots

- weave-js/src/components/PagePanelComponents/Home/Browse2/Browse2OpDefCode.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse2/SpanDetails.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionsPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TypeVersionsPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Links.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/OpVersionCategoryChip.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimplePageLayout.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/TypeVersionCategoryChip.tsx
Contains changes from https://www.notion.so/wandbai/Simple-Weaveflow-feedback-33a4595ef08c4a3b948cea45022a8d6c
Changes:
* Better code styling
* Better metadata header views
* Direct links to calls
> chore(weave): Simplification Round 2

- weave/autopatch.py
- weave/monitoring/openai/openai.py
- weave/wandb_interface/wandb_lite_run.py
- weave/weave_init.py
Basic autopatch implementation.
- Just autopatches openai when weave.init is called for now.
> feat: autopatch implementation. autopatches openai on weave.init

- examples/experimental/Closures.ipynb
- examples/experimental/Monitor.ipynb
- examples/experimental/MonitorPanelPlot.ipynb
- examples/experimental/Table Summary Panel.ipynb
- examples/experimental/app/Eval.ipynb
- examples/experimental/app/scenario_compare.ipynb
- examples/experimental/bert_viz.ipynb
- examples/experimental/huggingface_datasets.ipynb
- examples/experimental/huggingface_models.ipynb
- examples/experimental/inference_logs.ipynb
- examples/experimental/mnist_train.ipynb
- examples/experimental/table_data_passing.ipynb
- examples/reference/create_ops.ipynb
- examples/reference/simple_api_test.ipynb
- examples/reference/vis/Distribution.ipynb
- examples/reference/vis/Scatter.ipynb
- integration_test/cypress/e2e/interactive/distribution.py
- weave/api.py
- weave/context.py
- weave/context_state.py
- weave/server.py
- update a bunch of the notebook tests to call use_lazy_execution() for now
- ensure server always uses lazy_mode
> feat: Enable eager mode by default

- weave-js/src/components/PagePanelComponents/Home/Browse3/context.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimpleFilterableDataTable.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/hooks.tsx
Adds a weave board popout for Calls page (PoC for Shawn's demo)
> chore(weave): Add of calls page popout to board

- weave-js/src/components/PagePanelComponents/Home/Browse2/Browse2OpDefCode.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse2/WeaveEditors.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse2/callTreeHooks.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
- weave-js/src/core/client/basic.ts
Puts a top level loading indicator on the app whenever a weave query is running
> chore(weave): Simple global loading indicator

- weave-js/src/components/PagePanelComponents/Home/Browse2/WeaveEditors.tsx
Internal notion: https://www.notion.so/wandbai/Weaveflow-Jan-2024-Tasks-e4f3a053bc8243738ba1dad3c4cff6d4?pvs=4#a1a58ce4eaf747edb07b6c80f72e505b
Quick fix - a better solution would get the actual total item count so we could display that.
> feat: warn user that row truncation is happening

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
Internal Notion: https://www.notion.so/wandbai/Weaveflow-Jan-2024-Tasks-e4f3a053bc8243738ba1dad3c4cff6d4?pvs=4#7161f460f3304bad8bb39fff0162db36
> fix: suppress autoscrolling span when clicking within the tree

- docs/docs/tutorial-eval.md
Only one typo fix, the other changes are automatically removing trailing whitespace.
> chore: fix typo

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage.tsx
Also trim off the "op-" prefix.
> feat: sort filters on call page

- weave-js/src/components/PagePanelComponents/Home/Browse2/WeaveEditors.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimplePageLayout.tsx
3 things:
1. Fixes values width
2. Fixes values when they are null
3. Fixes ref printing with refExtra (hides for now)
> chore(weave): Fixes issues with nested values and refs and widths

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionsPage.tsx
Alphabetizing, stripping off 'op-'
> chore: more filter improvements

- weave-js/src/components/PagePanelComponents/Home/Browse3/SideNav.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/Sidebar.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx
> chore(weave): Adds back top level naigation

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionsPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimpleFilterableDataTable.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/util.ts
> chore(weave): Makes title reflect selected category for table views

- weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
- weave-js/src/components/PagePanelComponents/Home/useDrawerResize.tsx
- weave-js/src/components/PagePanelComponents/Home/useFlexDirection.tsx
https://github.com/wandb/weave/assets/25037002/a181bc47-5179-4d53-90c7-dcc691fa3303
> chore(weave): Resize drawer

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/CategoryChip.tsx
Internal Figma: https://www.figma.com/file/27JVuBYWHbcAYc8WPb4HqA/Weaveflow-hifi?type=design&node-id=1828%3A84533&mode=design&t=KumKX9guVtxk2dre-1
I had used cactus while waiting to hear back from design.
> chore: update category chip color

- weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPage.tsx
Can further iterate when we get feedback from design.
> feat: allow filtering by any version of an op

- weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/SideNav.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPage.tsx
Eventually we should do a complete rename across the codebase if this is the terminology we're going with - just doing a tiny surface level update to see how people feel.
> chore: rename call to trace in UI

- weave-js/src/common/util/links.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse2/SmallRef.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse2/WeaveEditors.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionsPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Links.tsx
I'm sure I missed a few that we can fix as we notice them.
> chore: add secondary link styling

- weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallDetails.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPage.tsx
> chore(weave): Add child calls to call details

- weave-js/src/components/PagePanelComponents/Home/Browse3/context.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareCallsPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfInterface/naive.ts
Fixes some legacy URI parsing before the latest ref refactor
> chore(weave): Fix legacy logged URIs

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Links.tsx
Verified with design ([internal slack](https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1707416642795649?thread_ts=1706810580.965789&cid=C03BSTEBD7F))
> chore: update secondary link hover color

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionPage.tsx
Remove some Under Construction tabs
> chore: remove under construction tabs

- weave/box.py
- weave/decorator_type.py
- weave/flow/__init__.py
- weave/flow/evaluate.py
- weave/flow/obj.py
- weave/op_execute.py
- weave/tests/test_decorator_type.py
- weave/tests/test_evaluate.py
- weave/weave_types.py
Makes a copy of weaveflow/evaluate.py in the new flow/ directory, using pydantic Object instead of @weave.type, and fixes needed to make that work.
> chore: Implement evaluate with new pydantic objects.

- weave-js/src/components/PagePanelComponents/Home/Browse2/callTree.ts
- weave-js/src/components/PagePanelComponents/Home/Browse2/callTreeHooks.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/StatusChip.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/interface.ts
- weave/ops_domain/run_history/run_history_v3_parquet_stream_optimized.py
> chore(weave): Fix issues with crashed calls/scripts before data model change

- weave-js/tailwind.config.cjs
https://github.com/tailwindlabs/tailwindcss/discussions/7411#discussioncomment-2157978
> chore: Enabling optimizeUniversalDefaults for the Tailwind config

- clear_cache.py
- weave/clear_cache.py
adds print statements, and time to script
> chore(weave): clear cache script

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
Filter the displayed trace tree based on the selection in order to reduce information overload.
There's a row added for the count of hidden calls, some of the changes are because we no longer have the same data for all rows. Also had to update the state aggregation because it was previously based on rows that now may have been filtered out.
Internal figma: https://www.figma.com/file/27JVuBYWHbcAYc8WPb4HqA/Weaveflow-hifi?type=design&node-id=2799-115260&mode=design&t=R5SNTmbyBhxjmcma-0
Before:
After:
> feat: filter trace tree to reduce information overload

- weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1709052983145909
> fix: columns from other evaluations getting displayed

- weave/tests/trace_server_clickhouse_conftest.py
- weave/trace_server/clickhouse_trace_server_batched.py
- weave/trace_server/remote_http_trace_server.py
Branched from https://github.com/wandb/weave/pull/1260
> chore(weave): Refactoring batching

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClient.ts
- weave/tests/trace_server_clickhouse_conftest.py
- weave/trace_server/clickhouse_trace_server_batched.py
- weave/trace_server/clickhouse_trace_server_migrator.py
- weave/trace_server/environment.py
- weave/trace_server/migrations/001_init_calls.down.sql
- weave/trace_server/migrations/001_init_calls.up.sql
- weave/trace_server/migrations/002_init_objects.down.sql
- weave/trace_server/migrations/002_init_objects.up.sql
- weave/trace_server/remote_http_trace_server.py
- weave/weave_init.py
This PR extracts the DB initialization / migration into a standlone manager that handles UP/DOWN application
> chore(weave): Extract Trace Migrations Into Standalone Migrator

- MANIFEST.in
fixes 
https://github.com/wandb/weave/actions/runs/8103204104/job/22147343718
> chore(weave): add trace server to manifest for build

- weave-js/src/components/PagePanelComponents/Home/Browse2/SmallRef.tsx
Use the version index instead of truncated version id in small ref. Not sure if there are performance concerns but this seems a lot more usable.
Before:
After:
> feat: show version number in small ref

- weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1709314079617539?thread_ts=1709296375.364519&cid=C03BSTEBD7F
If you have selected a single op, and there are multiple versions of that op in the call table, display a column with the op version index.
> feat: column indicating op version

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
Removing code we no longer support rather than having to keep it up to date.
> chore: remove CallPageInnerHorizontal

- weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
Remove the showIO constant which has been hardcoded to true for a while now.
Recommend "hide whitespace" when reviewing.
> chore: remove dead code

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallTraceView.tsx
Because of async processing, the Evaluation-predict_and_score are ordered rather arbitrarily within the trace tree. This is a bit of a hack to sort them by dataset row # instead.
> feat: sort Evaluation-predict_and_score calls by dataset row

- weave-js/src/components/CopyableText.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseDataset.tsx
Internal Slack: https://weightsandbiases.slack.com/archives/C01T8BLDHKP/p1709759738841649
> feat: suggest short form of dataset use

- weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/FullPageButton.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/context.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallDetails.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallTraceView.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/pathPreservation.test.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/pathPreservation.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Links.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/urlQueryUtil.ts
Also attempt to preserve that descendant equivalent when navigating to a different root call.
> feat: separate root call for trace and selected descendant

- weave-js/src/components/PagePanelComponents/Home/Browse2/WeaveEditors.tsx
2 bugs:
1. Union / complex types do not display
2. Table was not properly indexing into parent
> chore(weave): Fix union displays

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallDetails.tsx
When you are not in a peek drawer there is plenty of room to interact with the table.
> chore: make child calls table interactive when not in peek drawer

- docs/docs/guides/core-types/datasets.md
- docs/docs/guides/core-types/evaluations.md
- docs/docs/guides/core-types/models.md
- docs/docs/tutorial-eval.md
Replacement for https://github.com/wandb/weave/pull/1317 which had other commits pushed, these changes were already approved by Tim on that PR.
> chore: previously approved docs from Scott

- weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
Internal design feedback: https://www.notion.so/wandbai/Notes-on-Weaveflow-UX-674af4e66c6847248aeff7b93d87dc5c?pvs=4#49d52ddbdab340b9aa60fe5f0387af56
> chore: hide selected row count in calls grid footer

- weave-js/src/components/PagePanelComponents/Home/Browse3/StyledDataGrid.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallTraceView.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPage.tsx
> chore: use Source Sans Pro in grids

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimplePageLayout.tsx
> chore: use common tab component instead of Material's

- weave/tests/test_weave_client.py
- weave/trace/serialize.py
- weave/trace/vals.py
- weave/trace_server/clickhouse_trace_server_batched.py
- weave/trace_server/refs.py
- weave/trace_server/sqlite_trace_server.py
- weave/weave_client.py
Moves /trace/refs.py to /trace_server/refs.py
> chore(weave): Fix dependency leak for trace server

- examples/agents/programmer.py
- mypy.ini
- weave/tests/test_client_trace.py
- weave/tests/test_op_versioning.py
- weave/tests/test_vals.py
- weave/tests/test_weave_client.py
- weave/tests/test_weaveflow.py
- weave/trace/vals.py
- weave/trace_server/refs.py
- weave/trace_server/tests/test_refs.py
The prior implementation wasn't quite dict or list-like. Downstream code that expects lists or dicts would fail in many cases. Should work now!
> fix: Improved dict/list objects

- weave-js/src/components/PagePanelComponents/Home/Browse2/SmallRef.tsx
Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1711475584141049
Before:
After:
> fix: show op version index instead of hash in small ref

- weave-js/package.json
- weave-js/src/integrations/analytics/datadog.ts
- weave-js/yarn.lock
> chore: update dd rum version 

- weave-js/package.json
- weave-js/src/integrations/analytics/datadog.ts
- weave-js/yarn.lock
This reverts commit 242d7001c65f8d62fb8bd7f8b7aac96dda5b341a.
Reverting this as I am not sure this upgrade is safe with our main app fe.
> revert: "chore: update dd rum version  (#1362)"

- weave/trace_server/remote_http_trace_server.py
builds off of https://github.com/wandb/core/pull/20400
> chore(weave): Consume custom 500 errors messages

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClient.ts
Adds admin mode to the headers sent to trace server
> chore(weave): Fix admin powers for trace server

- weave/ops_domain/table.py
Effectively reverts https://github.com/wandb/weave/pull/1189
> chore(weave): Fully process mixed types

- weave-js/src/components/PagePanelComponents/Home/Browse3/context.tsx
Change for internal PR https://github.com/wandb/core/pull/20239
> chore: export browse3ContextGen

- weave/weave_client.py
Depends on https://github.com/wandb/core/pull/20469
Before:
```
File "/Users/timothysweeney/Workspace/github/wandb/hooman/op_publish_1.py", line 11, in <module>
tims_adder = weave.ref("weave:///timssweeney/dev_testing/op/MISSING_OP:Scm6PWGD0r0DH9vGu9duaTnCj8osPdXMNz8eXnp130Q").get()
File "/Users/timothysweeney/Workspace/github/wandb/core/services/weave-python/weave-public/weave/trace/refs.py", line 68, in get
return gc.get(self)
File "/Users/timothysweeney/Workspace/github/wandb/core/services/weave-python/weave-public/weave/weave_client.py", line 268, in get
read_res = self.server.obj_read(
File "/Users/timothysweeney/Workspace/github/wandb/core/services/weave-python/weave-public/weave/trace_server/remote_http_trace_server.py", line 173, in obj_read …
```
> chore(weave): Better error message for missing object

- requirements.test.txt
- weave/api.py
- weave/cli.py
- weave/deploy/gcp/__init__.py
- weave/deploy/modal/__init__.py
- weave/deploy/modal/stub.py
- weave/serve_fastapi.py
- weave/tests/test_weave_client.py
- weave/trace/vals.py
- use new-style uris and refs
- need to determine served function's type signature slightly differently
- disable "weave ui"
- add unit test for api.serve
> fix: "weave serve" and "weave deploy"

- weave/init_message.py
- weave/trace_server/remote_http_trace_server.py
- weave/weave_init.py
Picks up changes from https://github.com/wandb/core/pull/20474
> chore(weave): Error if below min weave version

- weave-js/src/components/Panel2/PanelExpression/ConfigComponent.tsx
> chore(weave): change weave panel settings to query panel settings

- weave/weave_init.py
> chore(weave): Fix init message

- weave/tests/test_client_trace.py
- weave/trace/serialize.py
- weave/weave_client.py
Adds tuple support for args and returns
> chore(weave): Tuple support

- weave/init_message.py
- weave/urls.py
Internal Notion: https://www.notion.so/wandbai/Not-properly-encoding-space-in-object-links-that-are-printed-afbee3cf5a95492fb0d538decbbc3efc?pvs=4
> fix: urlencode spaces in project and object names

- weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1711569709468729
Before:
After:
> fix: op version column

- weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
Reverts wandb/weave#1420
See internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1712058927199889
> revert: "chore(weave): Correct output expansion"

- weave/trace/object_record.py
Adds an exception catch to inspect.getmembers, so we dont error out while walking the object
> chore(weave): Safer obj walk

- docs/docs/tutorial-eval.md
- examples/text-extract/evaluate.py
- weave/flow/eval.py
- weave/flow/scorer.py
- weave/tests/test_client_trace.py
- weave/tests/test_evaluate.py
- weave/tests/test_weave_client.py
- change prediction to model_output in scorers
- change MulticlassF1Score to MultiTaskBinaryClassificationF1
> chore(weave): Final name adjustments to scorers

- weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/Browse3SideNav.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallOverview.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimplePageLayout.tsx
> chore(weave): make headers 55px

- docs/docs/guides/core-types/datasets.md
- docs/docs/guides/core-types/models.md
- docs/docs/guides/tools/serve.md
- docs/docs/guides/tracking/objects.md
- docs/docs/guides/tracking/ops.md
- docs/docs/guides/tracking/tracing.md
- docs/docs/introduction.md
- docs/docs/quickstart.md
- docs/docs/tutorial-eval.md
- tutorial_scripts/01_quickstart.py
- tutorial_scripts/02_in_app_quickstart.py
- tutorial_scripts/03_models.py
- tutorial_scripts/04_datasets.py
- tutorial_scripts/05_eval_pipeline.py
- tutorial_scripts/06_eval_pipeline_all.py
- tutorial_scripts/07_objects.py
- tutorial_scripts/08_ops.py
- tutorial_scripts/09_tracing.py
- tutorial_scripts/10_model_serve.sh
- tutorial_scripts/11_deploy.sh
End-to-end run through using a fresh user changes:
1. All projects are now `intro-example`
2. Added imports and inits where necessary so all code blocks can be run in isolation
3. Some small cosmetic things
4. Fixes params
> chore(weave): Pre-release doc script audit

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPage.tsx
> chore(weave): max width the ops filter

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallOverview.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/CallId.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Links.tsx
Internal notion: https://www.notion.so/wandbai/Tooltip-for-call-ID-e4a4475adfc54eafaa05311af0d280a7?pvs=4
> chore: show tooltip for Call ID

- weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallSummary.tsx
Internal notion: https://www.notion.so/wandbai/Show-better-latency-for-unfinished-call-92fb1320c66d4f3487bcbeff6dab4fb1?pvs=4
> chore: don't show latency while call is in progress

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionPage.tsx
https://github.com/wandb/weave/assets/25037002/2e115d3a-c222-4bd7-8ca7-dc6da14b8ee0
> chore(weave): move obj view calls to tab

- weave/tests/test_client_trace.py
- weave/trace_server/clickhouse_trace_server_batched.py
- weave/trace_server/sqlite_trace_server.py
- weave/trace_server/trace_server_interface.py
Adds general-purpose sorting to the server
> chore(weave): Add sorting to the server (first step to server-side pagination)

- weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
Re-enables filtering on columns that support it nicely and column management.
> chore(weave): Re-enable functioning filters and column management

- weave-js/src/components/PagePanelComponents/Home/Browse2/Browse2OpDefCode.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx
1. Makes sure you can correctly close expanded cells when expanded mode is set
2. Better loading size / spacing
> chore(weave): Fix code expansion again

- weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
- weave-js/src/components/UserLink.tsx
* Move UserId and Time to the end
* Center the circle elements
> chore(weave): Slight Column Mod for Calls

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
Fixes bug introduced in https://github.com/wandb/weave/pull/1534/files
> chore(weave): Fixes caching bug with ref extra

- weave-js/src/components/Tailwind.tsx
Weave and app versions of this component have gotten out of sync. These changes were previously approved in internal PR https://github.com/wandb/core/pull/19512
> chore: sync tailwind wrapper with app

- weave-js/src/common/css/globals_deprecated.styles.ts
> chore: remove some unused deprecated styles

- weave-js/src/common/components/Monaco/schemas/sweep-config-schema.json
- weave-js/src/common/components/Vega3/CustomPanelRenderer.tsx
- weave-js/src/common/util/media.tsx
- weave-js/src/common/util/string.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/cgDataModelHooks.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
- weave-js/src/components/PagePanelComponents/Home/HomeFeaturedTemplates.tsx
- weave-js/src/components/Panel2/ChildPanelExportReport/utils.ts
- weave-js/src/components/Panel2/ControlPage.styles.ts
- weave-js/src/components/Panel2/PanelGroup.tsx
- weave-js/src/components/Panel2/PanelPlot/ConfigSelect.tsx
- weave-js/src/components/Panel2/PanelStringHistogramWeave.tsx
- weave-js/src/components/Panel2/PanelTable/tableState.ts
- weave-js/src/components/Panel2/PanelWeaveLink.tsx
- weave-js/src/components/Panel2/panelTree.ts
- weave-js/src/components/Panel2/panellib/types.ts
- weave-js/src/components/Panel2/toWeaveType.tsx
- weave-js/src/components/Tag/utils.ts
- weave-js/src/core/code.ts
- weave-js/src/core/graphqlOps.test.ts
- weave-js/src/core/language/js/parser/index.ts
- weave-js/src/core/language/js/parser/js-grammar/README.md
- weave-js/src/core/ll.test.ts
- weave-js/src/core/ops/domain/local.ts
- weave-js/src/core/ops/primitives/tsne.ts
- weave-js/src/core/util/localStorage.ts
- weave-js/src/core/util/string.ts
Inspired by @moredatarequired, here are some mistakes identified by [typos](https://github.com/crate-ci/typos).
> chore: fix typos

- weave/trace_server/clickhouse_trace_server_batched.py
Makes the ref batch resolver parallelized
> chore(weave): Parallelize ref batch resolution

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/EmptyContent.tsx
Before: 
Use evaluations to track model performance across datasets.
Learn [evaluation basics](https://wandb.me/weave_evals) or see how you can [use models an evaluation pipeline](http://wandb.me/weave_eval_tut).
After
Use evaluations to track the performance of your application.
Learn [evaluation basics](https://wandb.me/weave_evals) or follow our tutorial to [set up an evaluation pipeline](http://wandb.me/weave_eval_tut).
> chore: update evals placeholder

- weave-js/tailwind.config.cjs
Keeping it in sync with core's tailwind config, after change made in https://github.com/wandb/core/pull/21108
> chore: add new breakpoint in tailwind config

- weave/trace/op.py
- weave/trace/tests/test_op_argument_forms.py
Internal Jira: https://wandb.atlassian.net/browse/WB-18509
> feat: allow @weave.op with no args

- weave/init_message.py
Updates "W&B" to "Weights & Biases" as per brand & marketing guidelines.
> chore(weave): Update Logged in message

- docs/docs/guides/core-types/evaluations.md
> chore: docs fixes #1571

- weave-js/package.json
- weave-js/src/components/PagePanelComponents/Home/Browse2/CellValue.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse2/CellValueImage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueView.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueViewImage.tsx
- weave-js/yarn.lock
Internal Jira: https://wandb.atlassian.net/browse/WB-18639
Button in calls grid:
Thumbnail in object viewer:
Clicking either to open in lightbox:
> feat: add data URL rendering for images

- weave/weave_client.py
- weave/weave_init.py
https://wandb.atlassian.net/browse/WB-18544
Before:
After:
> chore(weave): check weave and wandb run equivalence on weave init

- weave/weave_client.py
- weave/weave_init.py
fast follow for: https://github.com/wandb/weave/commit/d912bb52c723ec6a07df6b188ceb3d5bf570033b
- refactors wandb run checking logic 
- also check on calls, to catch cases where wandb run is initted after weave
> chore(weave): refactor wandb run equality check and add callsite

- weave/wandb_api.py
- weave/weave_init.py
> chore(weave): Check the logged in apikey, and baseURL

- weave-js/src/components/Panel2/PanelHistogram/Component.tsx
fixes this project 
https://wandb.ai/wandb-smle/registry/model?selectionPath=wandb-smle%2Fmodel-registry%2FMNIST+Production&view=versions
https://weightsandbiases.slack.com/archives/C01KQ5KTDC3/p1715373448212519
> fix(weave): adds null check in panel histogram

- weave-js/src/components/CopyableText.tsx
CSS change requested by design team.
> chore: round borders on use tab

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/utilities.ts
- weave-js/src/react.test.ts
- weave-js/src/react.tsx
This changes UI side ref parsing; I believe we still have some related problems in backend code.
Internal Jira:
https://wandb.atlassian.net/browse/WB-18522
https://wandb.atlassian.net/browse/WB-18743
> fix: allow slashes in weave ref object ids

- weave/trace_server/environment.py
> chore(weave): fix typo in comment

- weave/tests/test_client_trace.py
- weave/trace_server/clickhouse_trace_server_batched.py
- weave/trace_server/interface/query.py
- weave/trace_server/remote_http_trace_server.py
- weave/trace_server/sqlite_trace_server.py
- weave/trace_server/trace_server_interface.py
These are the backend changes from https://github.com/wandb/weave/pull/1656. Please see that PR for details, comments, and full change log
> chore(weave): Call Table Migration - Backend

- weave/flow/eval.py
> fix: better error message when passing a class as Scorer (#1680)

- weave/trace_server/migrations/003_feedback.down.sql
- weave/trace_server/migrations/003_feedback.up.sql
Internal Jira: https://wandb.atlassian.net/browse/WB-18696
> chore: migrations for feedback schema

- weave/trace_server/clickhouse_trace_server_batched.py
In preparation for adding mongo-style filters to the feedback APIs, make the functions less calls table specific.
> chore: make mongo filter conversion less calls specific

- weave/trace_server/clickhouse_trace_server_batched.py
Turns out you can extract the summary from stream queries!
> chore(weave): Improve logging such that we capture summary data for streams

- weave/trace_server/clickhouse_trace_server_batched.py
- weave/trace_server/remote_http_trace_server.py
Followup to related work on the server
> chore(weave): Modifies logging to use the `extra` field for structured logs

- weave/weave_client.py
- weave/weave_init.py
internal jira
https://wandb.atlassian.net/browse/WB-19182
> chore(weave): allow double init

- docs/docs/guides/core-types/evaluations.md
- docs/docs/tutorial-eval.md
- docs/docs/tutorial-rag.md
https://github.com/wandb/weave/pull/1552 was out of date so this adds his changes to a fresh branch
Thanks @NiWaRe for the contribution!
> docs: Add Nico's custom scorer tutorial

- weave/trace_server/errors.py
This code was previously approved in reverted PR https://github.com/wandb/weave/pull/1718 - pulling out some of the pieces that don't need changes for easier review of bits that do.
> chore: add InvalidRequest error

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClient.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
> chore(weave): callsSteamQuery -> callsStreamQuery

- weave/tests/test_client_trace.py
> chore(weave): Skip flakey test

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallTraceView.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CustomGridTreeDataGroupingCell.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/TraceUsageStats.tsx
- weave-js/src/util/llmTokenCosts.ts
adds trace usage stats to the trace tree
> feat(weave): Add trace usage stats to trace tree

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallTraceView.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CustomGridTreeDataGroupingCell.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/TraceUsageStats.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableColumns.tsx
- weave-js/src/util/llmTokenCosts.ts
> chore(weave): Add cost and token column to calls table

- weave/integrations/anthropic/anthropic_sdk.py
Internal Jira: https://wandb.atlassian.net/browse/WB-19332
> fix: fix anthropic import

- weave/trace/vals.py
Fixes an issue where Tables did not auto-deref as expected when `weave.init` was not first explicitly called.
> fix(weave): Allow client to get ref without explicit `weave.init`

- pyproject.toml
- weave/exception.py
- weave/infer_types.py
- weave/server_error_handling.py
- weave/trace_server/async_batch_processor.py
First commit enables rule: https://docs.astral.sh/ruff/rules/fits-on-one-line/
Second commit is manual fixes.
> chore: Enable ruff D200 fits-on-one-line

- pyproject.toml
- weave/tests/test_gql_to_weave.py
- weave/tests/test_graph_debug.py
- weave/tests/test_wb_domain_ops.py
- weave/trace_server/clickhouse_trace_server_migrator.py
First commit is config change, second commit is rule applied.
> chore: enable ruff W291 - no trailing whitespace

- weave/conftest.py
- weave/tests/test_client_trace.py
Followup on comment from Jamie
> chore(weave): Fix sqlite name in code

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/utilities.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts
- weave-js/src/react.test.ts
- weave-js/src/react.tsx
Add support for parsing call refs in the frontend.
> chore: add support for call refs

- docs/docs/tutorial-rag.md
uptakes changes here: https://github.com/wandb/weave/pull/1725
> chore(weave): Fix RAG Docs

- weave-js/src/common/hooks/useViewerInfo.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/EmojiButton.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/EmojiDetails.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/Notes.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/Reactions.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/ReactionsLoaded.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/WeaveEmojiPicker.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallOverview.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableColumns.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClient.ts
Internal Jira: 
https://wandb.atlassian.net/browse/WB-18700
https://wandb.atlassian.net/browse/WB-18699
Add emoji and note display in calls grid and call details header.
> feat: add UI to add notes and emoji reactions on calls

- pyproject.toml
Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1718924661894309
> chore: sort wandb imports with third party libraries

- weave/legacy/ops_domain/artifact_version_ops.py
- weave/weave_inspector.py
Fixes issue discovered here: https://weightsandbiases.slack.com/archives/CD72PQ03B/p1718996585814879 when the producing run for an artifact was later deleted!
> fix: Fixes issue when run is not found

- docker_build.py
- pyproject.toml
- weave/deploy/modal/__init__.py
- weave/flow/util.py
- weave/node_ref.py
- weave/stitch.py
- weave/storage.py
- weave/trace_server/calls_query_builder.py
- weave/weave_types.py
- weave/weavejs_fixes.py
https://docs.astral.sh/ruff/rules/no-blank-line-after-function/
First commit is config change, second is result of autofix.
> chore: enable Ruff D202 - no blank line after function

- weave/call_context.py
- weave/legacy/monitoring/openai/openai.py
- weave/parallelism.py
- weave/tests/test_monitoring_openai.py
- weave/tests/test_weaveflow.py
- weave/trace/op.py
This PR tries to rename all instances of "run" that should now be "call"
> chore(weave): Rename "run" to "call"

- weave-js/src/react.test.ts
- weave-js/src/react.tsx
Internal Jira: https://wandb.atlassian.net/issues/WB-19525
> fix: allow capital letters in entity name during ref parsing

- .vscode/settings.json
This PR lets you run tests in the editor
> chore(weave): Add testing settings for vscode

- docs/docs/guides/integrations/llamaindex.md
> chore(weave): unbreak docs

- weave/flow/eval.py
- weave/flow/scorer.py
Resolves:
- https://wandb.atlassian.net/browse/WB-19041
> fix(weave): Fix evals (and remove WeaveList dep)

- .github/workflows/deploy.yaml
- docs/docusaurus.config.ts
adds an integration to docs
update build to use api key
internal jira
https://wandb.atlassian.net/browse/WB-19318
> analytics(weave): add segment events to weave

- docs/docusaurus.config.ts
Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1720104688407169
> chore: don't load segment plugin if no apikey

- weave/tests/test_ref_trace.py
- weave/tests/test_vals.py
- weave/tests/test_weave_client.py
- weave/trace/refs.py
- weave/trace/vals.py
- weave/weave_client.py
This PR changes refs to be immutable!
Aside: Now that they are hashable, we can implement ref/object caching
> fix(weave): Make refs immutable

- weave/integrations/litellm/cassettes/litellm_test/test_model_predict.yaml
- weave/integrations/litellm/litellm_test.py
- weave/weave_client.py
Fixes summary rollups so that we don't operate on refs!
> chore(weave): Fix LiteLLM + Anthropic Issue

- weave-js/src/common/hooks/useViewerInfo.ts
- weave-js/src/common/hooks/useViewerUserInfo.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/EmojiButton.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/EmojiDetails.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/Notes.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/Reactions.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/ReactionsLoaded.tsx
Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1720477278890919
I didn't consider public projects and anonymous users when implementing the feedback UI.
> fix: feedback was crashing for anonymous viewer

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/TraceUsageStats.tsx
> chore(weave): add estimated cost title

- weave/tests/test_evaluations.py
- weave/trace_sentry.py
Combines:
* https://github.com/wandb/weave/pull/1945
* https://github.com/wandb/weave/pull/1944
In order to unblock CI
> chore: Fix CI - Combination PR

- weave/trace/op.py
Resolves:
- https://wandb.atlassian.net/browse/WB-19834
> fix(weave): Don't show ".<locals>." as part of op name

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooksEvaluationComparison.ts
don't display eval selection tooltip on trace page
> fix: wrong disabled+tooltip state in trace table

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/ManageColumnsButton.tsx
Internal Jira: https://wandb.atlassian.net/browse/WB-19854
Updates from design:
* Header styling, remove close button
* Show number of hidden columns
* Show/Hide actions only apply to columns in filtered view - this allows rapidly hiding e.g. 111 inputs columns.
Before:
After:
> feat: updated column management dialog

- docs/docs/guides/core-types/evaluations.md
- docs/docs/guides/integrations/index.md
- docs/docs/guides/integrations/local_models.md
- docs/docs/guides/integrations/together_ai.md
- docs/docs/tutorial-eval.md
Noticed a typo ("Togeher") so ran [typos](https://github.com/crate-ci/typos) and fixed a few others. Also added Groq to the integrations index page.
> docs: fix typos

- weave/deploy/gcp/__init__.py
- weave/deploy/modal/__init__.py
Same fix in https://github.com/wandb/weave/pull/2001 plus one for modal deployment.
> fix: broken imports

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooksEvaluationComparison.ts
Probably should have adaptive latency like the main grid, but at least this fixes the problem
> fix: Correct latency units

- weave-js/src/components/UserLink.tsx
Fix this developer console warning:
> chore: dev console warning from UserLink

- weave/trace_server/clickhouse_schema.py
- weave/trace_server/clickhouse_trace_server_batched.py
just moving code around
necessary to import clickhouse schema to other files
> chore(weave): move ch stuff to its own file

- weave/trace_server/migrations/005_add_cost.down.sql
- weave/trace_server/migrations/005_add_cost.up.sql
> chore(weave): add llm_token_prices table

- weave/trace_server/orm.py
- weave/trace_server/tests/test_orm.py
> chore(weave): Add join and group by to orm

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimpleFilterableDataTable.tsx
Internal Jira: https://wandb.atlassian.net/browse/WB-20382
Recommend "Hide whitespace" for review.
> feat: add filtering and column management to evaluations page

- weave/legacy/wandb_interface/project_creator.py
- weave/trace_server/external_to_internal_trace_server_adapter.py
- weave/trace_server/remote_http_trace_server.py
- weave/trace_server/trace_server_interface.py
- weave/weave_client.py
- weave/weave_init.py
https://wandb.atlassian.net/browse/WB-20396
> fix: update weave client with formatted project name

- weave-js/src/components/PagePanelComponents/Home/Browse3/NotFoundPanel.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionPage.tsx
> fix: Empty panels now have nicer not found messages

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallSummary.tsx
Fixes https://github.com/wandb/weave/issues/2161
> fix: scroll overflow on call summary tab

- weave/flow/model.py
1. Adds `invoke` as an option for inference method
- https://wandb.atlassian.net/browse/WB-20407
> chore(weave): Add `invoke` as a valid "infer method"

- weave/trace_api.py
1. This imports the type serialization stuff so that it's actually registered!
> fix(weave): Fix image serializer not registered issue

- docs/docs/guides/tracking/feedback.md
Copy of https://github.com/wandb/weave/pull/2158/files to work around CLA issues.
> chore(weave): Document feedback feature with call UUID examples

- examples/get_started.ipynb
- examples/reference/WB_API.ipynb
- examples/reference/create_plots_ui_guide.ipynb
- examples/reference/vis/Scatter.ipynb
- integration_test/cypress/e2e/interactive/blank.py
- integration_test/cypress/e2e/interactive/distribution.py
- integration_test/cypress/e2e/interactive/scatter.py
- weave/legacy/panel.py
- weave/legacy/show.py
- weave/legacy/wandb_interface/wandb_stream_table.py
- weave/tests/legacy/test_api.py
- weave/tests/legacy/test_show.py
Split out from: https://github.com/wandb/weave/pull/2182
This slice moves the following to `legacy`:
- `show`
> chore(weave): Legacy Refactor pt5

- README.md
Just remove an empty line from readme
> chore: Bump core update

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTableButtons.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClientTypes.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts
Frontend for https://github.com/wandb/weave/pull/2137
> chore: frontend to allow expanded ref export

- weave/tests/fixture_fakewandb.py
- weave/trace/weave_init.py
Fixes uninteresting type errors raised about the `wandb` package as a result of repo shifting
> chore(weave): fix extraneous typing issues

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueView.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/CompareEvaluationsPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ExampleCompareSection/ExampleCompareSection.tsx
Allows images to display in compare view
Manual
> feat: Image Support in Eval Compare

- dev_docs/RELEASE.md
> chore(weave): Update release doc

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTableButtons.tsx
Filters was broken in last PR, thread: https://weightsandbiases.slack.com/archives/C01T8BLDHKP/p1725473906932569?thread_ts=1725467720.046389&cid=C01T8BLDHKP
> fix: simplify and fix python filter export

- weave-js/src/components/FancyPage/FancyPageMenu.tsx
- Fixes https://weightsandbiases.slack.com/archives/C050NM2AVMW/p1725550529818559
Visiting `/oxa/mlops-test` locally to see the error, then after this change to see it is no longer there.
> fix(app): omit falsey menu items

- weave-js/src/apollo.ts
- weave-js/src/common/hooks/useOrganization.ts
- weave-js/src/common/hooks/useViewerInfo.ts
- weave-js/src/common/hooks/useViewerUserInfo.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
- weave-js/src/components/UserLink.tsx
- weave-js/src/entrypoint.tsx
Internal Jira: https://wandb.atlassian.net/browse/WB-20703
Allows the gorillaGQL url to be passed into browse3.
> fix: Fix Feedback for dedicated by using correct Apollo hook

- weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
> chore: Fix lint

- docs/docusaurus.config.ts
- docs/package-lock.json
- docs/package.json
- docs/yarn.lock
adds google tag packages
theres some whitespace changes in docusaurus.config.js
> chore(docs): add google tags to weave docs

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallTraceView.tsx
- weave-js/src/integrations/analytics/userEvents.ts
Track all clicks in the trace tree view, to determine how much use this gets.
> analytics: track user clicks in the trace tree view

- weave/tests/trace/test_evaluate.py
This keeps flaking: https://github.com/wandb/weave/actions/runs/10743506822/job/29798390411?pr=2319
> test: fix test mean latency flake

- weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/EmojiDetails.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/Notes.tsx
Internal Jira: https://wandb.atlassian.net/browse/WB-20778
> chore: Fixes service account names in feedback modals.

- weave/trace/call_context.py
Not sure what this was intended for, but it doesn't appear to be used anywhere.
> chore: remove unused code

- weave/tests/trace/test_call_behaviours.py
- weave/trace/op.py
Resolves: https://wandb.atlassian.net/browse/WB-20883
> fix(weave): Show link when calling async ops

- weave/tests/trace/test_client_cost.py
- weave/tests/trace/trace_server_clickhouse_conftest.py
- weave/trace/weave_client.py
Make add cost take in explicit fields and not cost create input
> chore(weave): add_costs -> more clear add_cost

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx
-Fixes https://wandb.atlassian.net/browse/WB-20839
https://weightsandbiases.slack.com/archives/C01T8BLDHKP/p1726001368443599
> fix(weave): Object viewer properly expands refs on expand all

- weave/legacy/weave/weave_types.py
Ran int this issue when implementing LangGraph implementation.
> fix: Raise correct error in Types

- docs/scripts/generate_service_api_spec.py
> chore: ensure .cache directory exists

- weave/legacy/tests/test_wb_data_types.py
Fixes CI to deal with symbol moves here: https://github.com/wandb/wandb/commit/08ba4610f3d100f51ca98f2d75684d2148c607cc#diff-ef46c76ff8110672223e0626edbff068575372f0707a2bb3d2e716c6737198f8
> chore: Fix CI for new wandb package

- docs/CONTRIBUTING_DOCS.md
- requirements.dev.txt
Most changes are autoformatting. The only real changes are:
Adding playwright to requirements.dev.txt (used by generate_images.py)
Noting the `playwright install` step in the contributing docs.
> chore: Add playwright to requirements

- weave/trace_server/calls_query_builder.py
- weave/trace_server/errors.py
- Fixes [WB-20985](https://wandb.atlassian.net/browse/WB-20985)
Raises a more specific error that can be handled as 403
Depends on: https://github.com/wandb/core/pull/23966
[WB-20985]: https://wandb.atlassian.net/browse/WB-20985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: add invalid field 403 error

- weave-js/src/components/PagePanelComponents/Home/Browse2/CellValueString.tsx
Internal Jira: https://wandb.atlassian.net/browse/WB-21033
> fix: code editor in string popup was not scrolling with trackpad

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ExampleCompareSection/ExampleCompareSection.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ScorecardSection/ScorecardSection.tsx
Internal Jira: https://wandb.atlassian.net/browse/WB-21083
Reduce font size in evaluation comparison from 16px to 14px and change monospace font to Inconsolata (see 'g' in `git`)
Before:
After:
> chore: update font size/family in evaluation comparison

- .github/workflows/test.yaml
- weave/conftest.py
- weave/trace_server/calls_query_builder.py
Adds back missing Clickhouse tests that were accidentally turned off while shifting our code
> chore(weave): Re-enable missing Clickhouse tests

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
Internal Jira: https://wandb.atlassian.net/browse/WB-21141
Hiding evaluation tab until it works better for single evals.
> chore: disable Evaluation tab until it is better for single evals

- .github/CODEOWNERS
updates CODEOWNERS to expande fe-infra approval scope
> chore(app): Update CODEOWNERS to allow FE infra to approve component changes

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/ChatView.tsx
Fixes https://wandb.atlassian.net/browse/WB-21120
> feat: autoscroll chat view to output

- weave-js/src/components/FancyPage/useProjectSidebar.ts
Part of visual updates from design team:
https://www.notion.so/wandbai/Nav-bar-f9ddbab018824a59b30b0d0ff17d7de6
> chore: nav bar design tweaks

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallTraceView.tsx
Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1727222449689159
Before:
After:
> chore: remove horizontal lines from trace tree

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx
Internal Slack: https://weightsandbiases.slack.com/archives/C05DURZNT41/p1727290816712279
See https://github.com/mui/mui-x/issues/13524 for explanation.
> fix: object viewer height not updating correctly

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Id.tsx
> chore: revert change id display from four digits to three

- .github/workflows/upload-assets.yaml
- weave/trace/weave_init.py
> chore(weave): Refactor hotfixes

- weave_query/pyproject.toml
- weave_query/requirements.legacy.txt
Associated PR:
https://github.com/wandb/core/pull/24333
> chore(weave): Refactor hotfixes3

- .gitattributes
- .github/workflows/release.yaml
- .github/workflows/upload-assets.yaml
- .gitignore
- MANIFEST.in
- build_dist.py
- pyproject.toml
- scripts/build_frontend.sh
- setup.py
- weave/version.py
- weave_query/.vscode/settings.json
This PR updates paths for the `frontend` dir and deletes extraneous optional deps
> chore(weave): Refactor hotfixes4

- docs/docs/guides/tracking/costs.md
- weave/trace/weave_client.py
> chore(weave): update cost docs

- .vscode/settings.json
> chore(weave): Remove .vscode

- weave/trace_server/table_query_builder.py
10k row dataset, 10kb per row.
- (offset 200, limit 100)
- Prod: Elapsed: 1.439s Read: 33,970 rows (225.50 MB)
- _Master: Elapsed: 5.691s Read: 4,481,567 rows (18.02 GB)_
- **PR: Elapsed: 0.098s Read: 34,531 rows (225.53 MB)**
- Filtered by Digest
- Prod: Elapsed: 0.163s Read: 31,321 rows (225.39 MB)
- _Master: Elapsed: 7.913s Read: 4,481,939 rows (18.02 GB)_
- **PR: Elapsed: 0.052s Read: 24,222 rows (20.48 MB)**
> perf: Improve Table Query Performance

- weave/integrations/langchain/langchain_test.py
Langchain flakes on non-deterministic ordering. This fixes that
> chore: Fix Langchain flake

- CONTRIBUTING.md
> chore(weave): Add new` CONTRIBUTING.md`

- weave-js/src/components/Button/Button.tsx
- weave-js/src/components/Button/types.ts
adds an outline button from this figma
https://www.figma.com/design/01KWBdMZg5QM9SRS1pQq0z/Design-System----Robot-Styles?node-id=15434-9056&node-type=frame&t=YePyIFcejrLEMy0U-0
hover is teal
> chore(weave): add outline button

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTableButtons.tsx
before
after
https://github.com/user-attachments/assets/e54de2c0-22e3-4ef7-abf3-a332d2b271f7
> style(weave): Add pagination component and move calls table pagination controls

- pyproject.toml
- weave/deploy/gcp/__init__.py
- weave/trace/api.py
- weave/trace/autopatch.py
- weave/trace/call_context.py
- weave/trace/cli.py
- weave/trace/op.py
- weave/trace/op_type.py
- weave/trace/refs.py
- weave/trace/trace_sentry.py
- weave/trace/weave_init.py
- weave/trace_server/clickhouse_schema.py
- weave/trace_server/clickhouse_trace_server_batched.py
- weave/trace_server/external_to_internal_trace_server_adapter.py
- weave/trace_server/feedback.py
- weave/trace_server/orm.py
- weave/trace_server/sqlite_trace_server.py
- weave/trace_server/token_costs.py
- weave/trace_server/trace_server_converter.py
- weave/trace_server/trace_server_interface.py
- weave/trace_server/trace_server_interface_util.py
- weave/trace_server/validation.py
- weave/trace_server/validation_util.py
- weave/type_serializers/__init__.py
Cleans up relative imports and adds new lint rule
> chore(weave): Dont use relative imports

- weave-js/src/components/Panel2/PanelTable/ColumnHeader.tsx
Fixes compilation issue w/ weave-js
> fix: Use explicit type for component style

- weave-js/src/components/Panel2/PanelTable/PanelTable.tsx
Fixes a warning during vite build -
[vite] warning: The "??" operator here will always return the left operand
Yarn lint, yarn test
> chore(weave): fix vite warning about ?? operator

- pyproject.toml
- weave/__init__.py
Moves to hatch build and simplifies what gets included in the pkg!
> chore(weave): Move to hatch build

- .github/workflows/test.yaml
- noxfile.py
- Save another 40s on `trace` shard by parallelizing
> chore(weave): Speed up tests by 14%

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
https://github.com/user-attachments/assets/b5d10289-2c72-4b0e-9bf3-306167ecf65d
hide delete when no calls are selected
https://www.notion.so/wandbai/Traces-table-d0abd588c49e4a77a213db27af717b4f?pvs=4#10ae2f5c7ef38069b152fe682f222b31
> style(weave): hide delete if no calls are selected

- weave-js/src/components/PagePanelComponents/Home/Browse2.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
Updated license key value from Shawn. (Fixes watermark in dev.)
> chore: update license key for MUI data grid

- weave_query/.vscode/settings.json
- weave_query/tests/test_op_def.py
Fixes vscode settings to allow unit tests to be discoverable in vscode.
> chore: fix vscode test config

- tests/trace/type_serializers/Image/image_test.py
> chore: Fix flakey image test

- tests/trace/test_dataset.py
Just a test that already passes (:
> fix: Python-side duplicate dataset rows

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewerSection.tsx
This thread
https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1728135230056479
> chore(weave): update expand to 200 ids

- .gitignore
- noxfile.py
- pyproject.toml
Add pytest-cov based test coverage report.
`open tests/htmlcov/index.html`
> chore: add pytest code coverage report

- docs/notebooks/notdiamond_custom_routing.ipynb
1. Adds missing metadata tag
2. Clears outputs
> chore(weave): Update NotDiamond docs

- pyproject.toml
Seems to be broken from: https://github.com/BerriAI/litellm/pull/6158
> chore(weave): Pin notdiamond litellm dep

- weave_query/requirements.legacy.txt
companion: https://github.com/wandb/core/pull/24765
Reduces flake in core CI.  There seem to be several large changes since AnyIO 3 -> 4:
https://anyio.readthedocs.io/en/stable/versionhistory.html
> chore(weave): Pin `weave_query` packages

- weave/trace_server/clickhouse_trace_server_migrator.py
- weave/trace_server/costs/insert_costs.py
- weave/trace_server/costs/tests/test_insert_costs.py
The target db of the client passed in was incorrect, specify the target db for insert costs
running make migrate local
> chore(weave): fix seed costs

- docs/docs/guides/integrations/google-gemini.md
- docs/docs/guides/integrations/groq.md
- tests/integrations/google_ai_studio/google_ai_studio_test.py
Fixes some typos in Gemini docs.
> fix(weave): Typos in Google Gemini docs

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooksCallRefExpansion.ts
Have you been plagued by ghost columns? Columns that shouldn't be in the normal view but seem to be left over from the last one? Yah, me to. It was because of me.
Anyway, the fix is to correctly _not_ update the state if by the time the network requests complete, the new dependency has changed. Classic react bug.
> fix(ui): Fix "Ghost" columns in tables

- weave-js/src/integrations/analytics/Analytics.ts
> chore(ui): fix comment typos

- weave/trace/util.py
> chore(weave): fix typo

- tests/integrations/dspy/dspy_test.py
- tests/integrations/google_ai_studio/google_ai_studio_test.py
- tests/trace/test_client_trace.py
- tests/trace/test_evaluations.py
- tests/trace/test_weave_client.py
- weave/trace/serialize.py
See internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1729185249582949
> fix(weave): restore previous fallback encoding behavior

- tests/trace/test_op_versioning.py
Adds a test for code saving of an object that could have sensitive keys.
> chore(weave): add test for instance code saving

- weave-js/src/components/Panel2/PanelTable/util.ts
This PR includes that same numerical type check as [this past PR](https://github.com/wandb/weave/pull/2670). Forgot to add these changes in the previous PR 🤦 
Visually
> fix(ui): Add numerical type checks to columnFormat

- tests/trace/test_actions.py
- weave/trace_server/clickhouse_trace_server_batched.py
- weave/trace_server/external_to_internal_trace_server_adapter.py
- weave/trace_server/interface/base_models/action_base_models.py
- weave/trace_server/interface/base_models/base_model_registry.py
- weave/trace_server/interface/base_models/feedback_base_model_registry.py
- weave/trace_server/sqlite_trace_server.py
- weave/trace_server/trace_server_interface.py
- weave/trace_server_bindings/remote_http_trace_server.py
Part 1 of Hackweek:
1. Defines & implements `execute_batch_action` as interface method
2. Creates a standard layout for defining known model types
3. Correctly extracts bases from objects
4. Allows type-safe object and feedback creation via api
> chore(weave): Add Object and Feedback Action Objects - Hackweek 1

- docs/docs/reference/gen_notebooks/audio_with_weave.md
- docs/notebooks/audio_with_weave.ipynb
Fixes missing title and errant TODO statement.
> docs(weave): Fix for cookbook Audio with weave #2792

- weave-js/src/common/components/Markdown.tsx
- weave-js/src/css/wandbTailwindPreflight.css
> chore(ui): ejecting markdown from tailwind defaulting

- weave-js/src/components/PagePanelComponents/Home/Browse2/Browse2OpDefCode.tsx
Extremely simple language detection :) 
> feat(ui): Add simple language detection for code browser

- docs/docs/guides/core-types/prompts.md
- docs/sidebars.ts
- tests/trace/test_prompt.py
- tests/trace/test_prompt_easy.py
- weave-js/src/components/FancyPage/useProjectSidebar.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabPrompt.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseCall.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseDataset.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseModel.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseObject.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseOp.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUsePrompt.tsx
- weave/__init__.py
- weave/flow/prompt/common.py
- weave/flow/prompt/prompt.py
- weave/integrations/openai/openai_sdk.py
- weave/trace/op.py
- weave/trace/refs.py
First release of first-class Prompt object including SDK, UI, and docs.
https://wandb.atlassian.net/browse/WB-20795
https://wandb.atlassian.net/browse/WB-20796
> feat(weave): prompts as first class objects

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallChat.tsx
[WB-21702](https://wandb.atlassian.net/browse/WB-21702)
Prod:
This branch:
👀 
[WB-21702]: https://wandb.atlassian.net/browse/WB-21702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(weave): openai chat view stutter

- docs/sidebars.ts
- weave-js/src/components/FancyPage/useProjectSidebar.ts
Shawn has asked that we hold off on publicizing the Prompts stuff for some further discussion.
> chore(ui): hide Prompts feature

- sdks/node/examples/evaluate.ts
- sdks/node/examples/evaluateWithColumnMapping.ts
- sdks/node/examples/quickstartEvaluate.ts
Resolves an issue where incorrect keys were passed in eval examples
Manual testing
> chore(weave_ts): Fix eval examples

- .pre-commit-config.yaml
- pyproject.toml
This adds, but does not currently enforce pyright.  Please start using this tool to improve our code!
> chore(weave): Add pyright

- pyproject.toml
- **test**
- **extraneous fmting**
- **test**
> chore(weave): Dont report missing imports pyright

- tests/trace_server/test_calls_query_builder.py
- weave/trace_server/calls_query_builder.py
- weave/trace_server/clickhouse_trace_server_batched.py
[WB-21741](https://wandb.atlassian.net/browse/WB-21741)
- revert 2 part calls query
👀 
[WB-21741]: https://wandb.atlassian.net/browse/WB-21741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(weave): revert 2 part calls query 

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Links.tsx
Fix copy+paste error (not user visible)
> chore(ui): fix react display name

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimplePageLayout.tsx
updates this border color to style guide color
> style(weave): update border color

- weave-js/package.json
- weave-js/yarn.lock
Important for https://github.com/wandb/core/pull/25103/, must be merged at the same time.
> chore(ui): Upgrade to React18. Does not include typedef changes.

- weave-js/src/assets/icons/icon-overflow-vertical.svg
- weave-js/src/components/Icon/Icon.tsx
- weave-js/src/components/Icon/index.ts
- weave-js/src/components/Icon/types.ts
> chore(ui): add overflow-vertical icon

- .pre-commit-config.yaml
- pyproject.toml
Many checks are disabled.  We should gradually improve and re-enable checks
> chore(weave): Add pyright to CI

- pyproject.toml
- weave/trace/cli.py
> chore(weave): pyright: enable reportFunctionMemberAccess

- pyproject.toml
- weave/integrations/instructor/instructor_iterable_utils.py
- weave/trace/cli.py
- **test**
- **test**
- **test**
> chore(weave): pyright: enable reportOptionalSubscript

- pyproject.toml
- tests/trace/test_weave_client.py
- tests/trace_server/test_validation.py
Implements: https://docs.astral.sh/ruff/rules/unnecessary-generator-list/
> chore(weave): ruff: enable C400

- pyproject.toml
- tests/trace/test_exec.py
- weave/flow/eval.py
- weave/trace/settings.py
Implements: https://docs.astral.sh/ruff/rules/blank-line-with-whitespace/
> chore(weave): ruff: enable W293 and cleanup selected lint checks

- docs/scripts/generate_images.py
- pyproject.toml
- tests/trace/test_op_return_forms.py
- weave/trace/op.py
- weave/trace/refs.py
- weave/trace/weave_client.py
- weave/trace_server/clickhouse_trace_server_migrator.py
Implements: https://docs.astral.sh/ruff/rules/raise-vanilla-class/
> chore(weave): ruff: enable TRY002

- noxfile.py
- pyproject.toml
- tests/integrations/google_ai_studio/google_ai_studio_test.py
Our retries didn't work because the required package was not installed :)
This also adds a check for unknown markers so we don't run into this issue in future
> chore(weave): Add pytest retry

- weave-js/src/components/Form/TextField.tsx
Add step for number based text input.
> chore(weave): add optional step to text field input

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundSettings/PlaygroundSettings.tsx
> chore(weave): add settings drawer with simple toggle

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundSettings/PlaygroundSettings.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundSettings/PlaygroundSlider.tsx
https://github.com/user-attachments/assets/d0fe4b58-e37b-4e4e-84d1-1c52c2d5ed20
> chore(weave): add slider settings to setttings drawer

- weave-js/src/components/FancyPage/useProjectSidebar.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/context.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/ActionSpecsTab.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/AnnotationsTab.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/CoreScorersTab.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/ScorersPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/EmptyContent.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/TypeVersionCategoryChip.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/constants.ts
Setups up hidden Scorers Page for development on Scorers UI.
The names can be changed, this is just the scaffolding so we can colaborate
> chore(weave): Setup hidden Scorers Page

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundSettings/PlaygroundSettings.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundSettings/StopSequenceEditor.tsx
https://github.com/user-attachments/assets/8361ca3e-5210-46bc-be3c-2e431476f4c8
> chore(weave): stop sequence editor

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundSettings/FunctionDrawer.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundSettings/FunctionEditor.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundSettings/PlaygroundSettings.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/StyledTextarea.tsx
https://github.com/user-attachments/assets/5d475158-bdce-4e3d-b6ea-1dba03775b2a
> chore(weave): function editor

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewerSection.tsx
when small
when expand is too big
> chore(weave): update tooltip depending on if we can expand all

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/PlaygroundChat.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/PlaygroundChatInput.tsx
adds chat input, no functionality on send or add yet
https://github.com/user-attachments/assets/a9d94e11-5002-4c88-9702-03b147d73076
> chore(weave): add chat input

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClientTypes.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerDirectClient.ts
Addes the TS interface for `POST /actions/execute_batch`
> chore(weave): Add TS interface for Execute Batch Action

- weave/integrations/openai/openai_sdk.py
Adds tracking for openai's `parse` apis
UI inspection
> feat(weave): Add tracking for openai beta parse api

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/AnnotationsTab.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/CoreScorersTab.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/EmptyContent.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/TypeVersionCategoryChip.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/constants.ts
Add basic types and page scaffolding for annotation specs. 
> chore(ui): add basic annotation scaffolding

- weave-js/src/components/PagePanelComponents/Home/Browse3/ReusableDrawer.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/NewScorerDrawer.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/ScorerForms.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/ScorersPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimplePageLayout.tsx
Updates:
1. Header tabs with icons
2. Common create form
3. Common infra
> chore(weave): Update Scorers tab to match design

- tests/integrations/google_ai_studio/google_ai_studio_test.py
Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1731696753600349
> chore(weave): Skip google tests

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/ZodSchemaForm.tsx
pr:
- removes console log
- fixes mui icon dependency
> chore(weave): clean up zod form

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimplePageLayout.tsx
> chore(weave): Fixes tab overflow

- pyproject.toml
> chore(weave): Fix deps

- pyproject.toml
Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1732136198575819
> chore(weave): Pin pydantic

- docs/docs/guides/tools/playground.md
https://wandb.atlassian.net/browse/DOCS-1065
This PR takes existing [Playground docs](https://weave-docs.wandb.ai/guides/tools/playground) and does the following:
- Updates language / page structure
- Adds intro and features list
- Restructures so usage prereqs are clear
- Adds subsections about function calling and model comparison
> docs(weave): Update Playground docs

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTableButtons.tsx
> chore(ui): recyle -> refresh button

- pyproject.toml
- weave/trace/vals.py
- weave/trace_server/calls_query_builder.py
- weave/trace_server/interface/query.py
Added special handling for pydantic 2.10.0+ to avoid infinite recursion issue.
Related threads:
- https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1732218568853419
- https://github.com/wandb/weave/pull/3034
> fix(weave): Fix issue where getting an attribute of a pydantic object would infinitely recurse

- weave-js/src/core/ops/domain/artifactVersion.ts
Fixes [WB-21719](https://wandb.atlassian.net/browse/WB-21719)
See https://github.com/wandb/weave/pull/3058 for full context. This PR was created after the fact to separate backend and frontend changes to prevent issues from deploy ordering.
* Manually
**Here's some weave0 screenshots**
Before:
After (yes, I should have used different images that weren't a green rectangle 😅):
[WB-21719]: https://wandb.atlassian.net/browse/WB-21719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(weave_query): Add artifactVersion-file type refinement to weave-js

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/useChatFunctions.tsx
some users want to remove the last message, should not force users to have a message in the playground
> chore(weave): Allow removing the system message

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/PlaygroundChat.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/PlaygroundChatInput.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/useChatCompletionFunctions.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundContext.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/types.ts
allows user to add and send system prompt messages
> chore(weave): system message role

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/LLMDropdown.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/llmMaxTokens.ts
adds providers to the llmMaxToken.ts
adds headers to llm dropdown
https://github.com/user-attachments/assets/22e3f326-911b-443b-84d4-beada057e855
> chore(weave): add headers to llm dropdown

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/EmptyContent.tsx
Change docs link to match: https://github.com/wandb/weave/pull/3093
> chore(ui): change human annotation docs link

- docs/docs/guides/tracking/feedback.md
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/EmptyContent.tsx
https://wandb.atlassian.net/browse/DOCS-1067
Updates existing Feedback feature docs https://weave-docs.wandb.ai/guides/tracking/feedback/
> docs(weave): Update new feedback docs

- docs/docs/guides/tools/playground.md
Addresses https://wandb.atlassian.net/browse/DOCS-1089
Adds Bedrock models and note about credentials to existing Playground docs edited in https://wandb.atlassian.net/browse/DOCS-1065
> docs(weave): Update Playground docs with Bedrock info

- weave/flow/prompt/prompt.py
Uses classmethod instead of staticmethod for alternate contructors (more standard)
> chore(weave): Use classmethods for from_* methods

- docs/docs/guides/tracking/tracing.mdx
> docs(weave): Update `create_call` python snippet in tracing.mdx

- sdks/node/package-lock.json
- sdks/node/package.json
- sdks/node/tsconfig.json
Updates `package.json` and `tsconfig.json` so that `npm install weave` works as expected
> chore(weave_ts): Update packaging

- weave/type_serializers/Image/image.py
> chore(weave): Tidy image serializer import check

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/llmMaxTokens.ts
> chore(weave): add o1-preview back and latest 4o

- weave/trace/op.py
1. Remove used vars
2. Clean up mistral import (it resolves to None anyways)
3. Change sentinel lookup to use "in"
> chore(weave): Tidy op.py

- tests/trace/test_trace_server_common.py
- weave/trace_server/clickhouse_trace_server_batched.py
- weave/trace_server/trace_server_common.py
Introduces `DynamicBatchProcessor` class to improve batch processing efficiency in the trace server. This class handles dynamic batch sizes that grow over time up to a configured maximum size. The implementation replaces the previous manual batch processing logic in `calls_query_stream` with a more maintainable and reusable solution.
Also refactors the call hydration logic by splitting the feedback handling into a separate method for better code organization.
- Added comprehensive unit tests for the new `DynamicBatchProcessor` class verifying:
- Correct batch size progression (2 -> 4 -> 8)
- Proper handling of remaining items
- Complete processing of all input data
- Existing trace server functionality remains covered by previous tests
> chore(weave): add DynamicBatchProcessor class for call stream batching 

- weave-js/tailwind.config.cjs
https://wandb.atlassian.net/browse/WB-22246
core PR: https://github.com/wandb/core/pull/26149
Updates tailwind shadow configs with new values provided by design team. Existing values were left in place but are deprecated.
> style(app): Update tailwind shadow configs

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
> chore(ui): fix typo

- weave/trace/weave_client.py
Internal Jira: https://wandb.atlassian.net/browse/WB-22256
Internal Slack: https://weightsandbiases.slack.com/archives/C0785BR1RNZ/p1733840385675099
Updates some error strings to give a better indication about what happened / how to fix it.
> chore(weave): ui_url error gives a hint about the problem

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
Internal Slack:
https://weightsandbiases.slack.com/archives/C01T8BLDHKP/p1733946783246119?thread_ts=1733944173.057389&cid=C01T8BLDHKP
Internal Slack:
https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1733463440023509?thread_ts=1733463089.291039&cid=C03BSTEBD7F
> chore(weave): hide admin only scorers tabs

- weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
Removing some code that is never enabled. Getting closer to being able to remove the `@mui/icons-material` dependency. 
After this lands there would be some additional cleanup to remove the `hideHeader` prop on `Browse3`.
> chore(ui): remove some unused code

- weave-js/package.json
uuid should be in dependencies instead of devDependencies now
> chore(ui): uuid should be in dependencies now

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/ChoicesViewCarousel.tsx
> chore(weave): Update choice carousel tooltip copy

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundSettings/FunctionDrawer.tsx
> style(weave): Hide function drawer textarea draggable

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallDetails.tsx
> chore(weave): Fixes error overflow

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundPage.tsx
https://wandb.ai/shawn/programmerjs-swebenchcode-junk2/weave/calls/0193d638-3602-7316-ba5a-f242fe4a5408
this open in playground, didnt load the call because the call query fails with include_cost
temporary fix until I fix cost query
> chore(weave): Fix call query on the Playground

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/llmMaxTokens.ts
groups the openai models properly, and adds o1-12-17
> chore(weave): add o1-12-17 to playground

- pyproject.toml
Temporary pin to resolve issue: https://github.com/kevin1024/vcrpy/issues/888
> chore(weave): Pin vcrpy for tests

- weave/trace/sanitize.py
- weave/trace/serialize.py
- weave/trace/weave_client.py
ensures redaction is case insensitive
> chore(weave): make redaction case insenstive

- weave/trace_server/async_batch_processor.py
Currently we re-raise errors in the call batch processor thread. This is pretty bad since it kills the background thread and results in no additional calls being logged.
> chore(weave): Better error handling in sender thread

- docs/docs/reference/gen_notebooks/audio_with_weave.md
- docs/docs/reference/gen_notebooks/notdiamond_custom_routing.md
- docs/docs/reference/gen_notebooks/online_monitoring.md
- docs/docs/reference/gen_notebooks/weave_via_service_api.md
- docs/notebooks/audio_with_weave.ipynb
- docs/notebooks/notdiamond_custom_routing.ipynb
- docs/notebooks/online_monitoring.ipynb
- docs/notebooks/weave_via_service_api.ipynb
https://wandb.atlassian.net/browse/DOCS-1154
Fixes bad header metadata tags so that notebook titles and headers render correctly
> docs(weave): Fix bad headers and titles in NBs

- tests/trace/test_redaction.py
- weave/trace/op_type.py
Resolves: https://wandb.atlassian.net/browse/WB-22604
Before
After
> feat(weave): Make redaction applied to captured code

- weave-js/src/components/PagePanelComponents/Home/Browse3/compare/ComparePage.tsx
Fix a TODO - Comparison docs page didn't exist at the time component was created but it does now. This is low importance because user can't encounter this page normally anyway.
> chore(weave): add a docs link now that page exists

- weave-js/src/components/Button/Button.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse2/CellValueString.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse2/CollapseHeader.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse2/ExpandHeader.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/ReusableDrawer.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/compare/CompareGridGroupingCell.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterBar.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterRow.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewerGroupingCell.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewerSection.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTableButtons.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/ManageColumnsButton.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/ChoicesViewCarousel.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/PlaygroundMessagePanelButtons.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/PlaygroundMessagePanelEditor.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/ToolCalls.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/SummaryPlotsSection/MetricsSelector.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/SummaryPlotsSection/SummaryPlotsSection.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/PlaygroundCallStats.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/NewScorerDrawer.tsx
- weave-js/src/components/Panel2/PanelTable/PanelTable.tsx
https://wandb.atlassian.net/browse/WB-22659
"quiet" button variant is being deprecated. updates all weave instances of "quiet" to "ghost"
Spot checked in workspaces/reports. Will recruit weave team for additional spot checks.
> chore(app): Update all quiet buttons to ghost

- docs/docs/guides/tracking/ops.md
Fix header level and text.
Before:
After:
> docs(weave): fix header level

- .github/CODEOWNERS
Give the docs team the ability to approve changes within the docs directory. (Will rely on docs team judgement for when to wait for an engineer to approve PRs.)
Syntax reference: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax
> chore(dev): Update CODEOWNERS

- tests/trace/test_client_trace.py
- weave/trace/weave_client.py
Resolves https://wandb.atlassian.net/browse/WB-22609
> chore(weave): Make CallsIter support len

- weave-js/src/core/suggest.ts
JIRA: https://wandb.atlassian.net/browse/WB-21774
Old:
New:
Local FE
> chore(app): remove runColors as a suggestion from query panels

- weave-js/src/common/css/globals.less
- weave-js/src/components/FancyPage/FancyPageSidebar.tsx
https://wandb.atlassian.net/browse/WB-19489
https://wandb.atlassian.net/browse/WB-19999
There are some scrolling issues with the runs table on mobile. The main fix is in this [core PR](https://github.com/wandb/core/pull/26776), but these minor CSS changes are also required to fully address the issues.
See core PR
> style(app): Fix runs table scroll in mobile

- weave/trace_server/costs/cost_checkpoint.json
> chore(weave): Update cost checkpoint

- tests/scorers/test_bias_scorer.py
- tests/scorers/test_toxicity_scorer.py
- weave/scorers/moderation_scorer.py
Add toxicity and bias scorers based on Celadon and custom model.
- Requires https://github.com/wandb/weave/pull/3412
> feat(weave): Add toxicity and bias scorers 2/N

- docs/docs/guides/tracking/tracing.mdx
Minor fix on top of https://github.com/wandb/weave/pull/3448
> docs(weave): small docs fix

- Makefile
- dev_docs/RELEASE.md
- weave/scripts/prerelease_dry_run.py
I got tired of the manual verification of the latest package build so I made a make command that sets up an ephemeral env to ensure pip installing will work with no other deps
> chore(weave): Dry Run Script

- tests/trace/test_dictifiable.py
I had stashed this test and forgot to actually check it in. It passes (:
> chore(weave): Adds test for recent dictify change

- weave/flow/obj.py
Hides ref to make repr less noisy
> chore(weave): Remove Ref from Object repr

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClientTypes.ts
Fix typing for object delete endpoint in frontend
> chore(weave): fix object delete typing

- weave-js/src/components/PagePanelComponents/Home/Browse3/typeViews/PIL.Image.Image/PILImageImage.tsx
> chore(ui): remove unused method

- weave/trace/util.py
Context:
After some deep diving into our data flow, I identified at least one mem leak in the `ContextAwareThreadExecutor`. I am not sure this is a huge one, but does have some impact.
Before:
After:
---
Summary:
This pull request includes changes to the `weave/trace/util.py` file to improve the handling of contexts in the `submit` and `map` methods. The most important changes include modifying how contexts are managed and passed to the `_run_with_context` method, ensuring better context handling and reducing complexity.
Context handling improvements:
* [`weave/trace/util.py`](diffhunk://#diff-bb390e76b5555c67339ae3a82e757d5c601d508aa7ba7b9db4aebfc04332a537L64-L92): Removed the `contexts` attribute from the class and updated the `submit` method to pass the context directly to the …
> chore(weave): Cleanup a mem leak in our ThreadExecutor

- weave-js/src/common/hooks/useViewerInfo.ts
Export some types that will be used in upcoming Saved Views code.
> chore(ui): Export some user info types

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectsPage/ObjectVersionPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/TypeVersionCategoryChip.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/constants.ts
Set the color and icon for SavedView objects.
> chore(ui): add SavedView object color and icon

- weave/trace_server/refs_internal.py
- weave/trace_server/refs_internal_server_util.py
- weave/trace_server/validation_util.py
Extracting just the trace server changes from https://github.com/wandb/weave/pull/2920 so they can be reviewed and deployed separately. These changes were authored by the artifact team; I reviewed and have made only one minor tweak.
> chore(weave): artifact ref trace server changes

- weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/DatasetVersionPage.tsx
> chore(weave): createdby placement adjustment for dataset version page

- weave-js/src/components/PagePanelComponents/Home/Browse2/CellValue.tsx
> chore(ui): remove dead code

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
> chore(ui): fix typo in variable name

- docs/docs/guides/tracking/index.md
Update tracing page with an FAQ section.
> docs(weave): what gets logged

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/ChoicesDrawer.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/MessagePanel.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/ShowMoreButton.tsx
Small styling tweaks for playground.
- Added system message background.
- Tightened up spacing in trials and message panel area.
| ![before](https://github.com/user-attachments/assets/1dd93bcc-e5bc-461c-9af8-7e6f21ef372f) | ![after](https://github.com/user-attachments/assets/4708f95e-fd6b-4861-9bb1-2754a67dff96) |
| ![before-1](https://github.com/user-attachments/assets/4e4d9565-3993-43cb-8ded-086411b300a7) | ![after-1](https://github.com/user-attachments/assets/eea64d35-0131-4957-a327-fdf897a6e9e1) |
| ![before-2](https://github.com/user-attachments/assets/adff54bc-dfb4-4be1-9c28-d558aff52546) | ![after-2](https://github.com/user-attachments/assets/07168840-9ba2-426e-8bbb-d0c460a3bc7c) |
> chore(ui): playground: added background large system prompt, smaller spacing between trials / message panel

- weave/trace_server/costs/cost_checkpoint.json
> chore(weave): Update costs 1/30/25

- weave/trace_server/llm_completion.py
- weave/trace_server/model_providers/model_providers.json
- weave/trace_server/model_providers/model_providers.py
Adds Azure to our list of providers in the playground
adds some logic to get specific secrets for Azure
> chore(weave): update model providers, add azure

- pyproject.toml
> chore(weave): Pin Shapely in CI

- .github/workflows/slack-digest.yml
- gh_actions/slack_digest.py
Fixes our dev bot (tested and verified)
> chore(weave): Small tweak to GH Action

- weave-js/src/components/FancyPage/FancyPageSidebarSection.tsx
Internal slack: https://weightsandbiases.slack.com/archives/C01KQ5KTDC3/p1738346408521569
Internal Jira: https://wandb.atlassian.net/browse/WB-23060
> fix(ui): automation button positioning

- weave-js/src/components/Tooltip.tsx
Adds an option to `Tooltip` to handle some positioning issues.
> chore(ui): add noTriggerWrap option to Tooltip

- docs/docs/guides/platform/weave-self-managed.md
Fix formatting issues with self managed page
- viewed locally
> docs(weave): fix formatting on self-managed doc

- docs/docs/guides/tools/playground.md
> chore(weave): update playground docs for azure and new llms

- sdks/node/src/__tests__/integrations/openai2.test.ts
- sdks/node/src/__tests__/op.test.ts
- sdks/node/src/integrations/openai.ts
- sdks/node/src/op.ts
- sdks/node/src/opType.ts
Resolves: https://wandb.atlassian.net/browse/WB-22980
> fix(weave_ts): Fix issue where concurrent streams could share the same state

- weave-js/src/common/components/elements/Toast.tsx
Make toasts remain dark in night mode 🌔
> chore(weave): make toast night aware

- weave-js/src/components/Panel2/PanelRunHistoryTablesStepper/index.tsx
Fixes https://app.circleci.com/pipelines/github/wandb/core/182845/workflows/64158ad3-8180-4255-bd29-43b73f7fa415/jobs/5066914/tests that was failing due to https://github.com/wandb/weave/commit/c393bc5766e1269b5b8199abd1b8001182f14b92
> test(dev): remove runs history table stepper as a panel function

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/cost/costUtils.ts
> chore(weave): when cost is 0 show 0

- weave-js/src/components/Button/Button.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/StyledDataGrid.tsx
Adding some display names for easier debugging in React developer tools.
> chore(ui): add display names

- docs/docs/quickstart.md
- Fixes https://wandb.atlassian.net/browse/DOCS-1250
Fixes broken link on quickstart
> docs(weave): fix broken link on quickstart

- docs/docs/guides/evaluation/builtin_scorers.mdx
Update the docs to built-in scorers to showcase the litellm upgrade.
> chore(weave): Update docs for litellm changes

- tests/trace/test_table_query.py
- weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/EditableDatasetView.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClientTypes.ts
- weave/trace_server/clickhouse_trace_server_batched.py
- weave/trace_server/sqlite_trace_server.py
- weave/trace_server/table_query_builder.py
- weave/trace_server/trace_server_interface.py
> revert(weave): sort datasets while editing

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ModsPage.tsx
This alters the way we authenticate the iframe, adds some error messages and updates the visible mods.
> feat(weave): Use new iframe postMessage, show errors, update mods

- tests/trace/test_table_query.py
- weave/trace_server/clickhouse_trace_server_batched.py
- weave/trace_server/sqlite_trace_server.py
- weave/trace_server/table_query_builder.py
- weave/trace_server/trace_server_interface.py
Return absolute index of each row when serving rows from a table. This enables more powerful UIs for editing datasets.
> chore(weave): table row response includes absolute row indices

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/llmMaxTokens.ts
- weave/trace_server/model_providers/model_providers.json
ran make update_model_providers
add claude 3-7 to llm dropdown
> chore(weave): Add Claude 3-7 to playground

- weave-js/src/components/PagePanelComponents/Home/Browse3/filters/SelectDatetimeDropdown.tsx
Optional calendar for the fancy datetime input selection.
> chore(ui): Datetime optional calendar

- docs/docs/guides/tracking/redact-pii.md
Add back that feature is only available in Python sdk per feedback from PM
- Fixes #NNNN
> docs(weave): Add note that redaction only available in Python sdk

- tests/trace/test_evaluate.py
Actually test what I changed in https://github.com/wandb/weave/pull/3939
> test(weave): improve download images eval test

- weave-js/src/components/FancyPage/useProjectSidebar.ts
> chore(weave): show overview for weave

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/DatasetsPage/DatasetsPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/EmptyContent.tsx
| ![CleanShot 2025-03-25 at 09 12 07](https://github.com/user-attachments/assets/a4fb46f2-75e9-4613-90b4-21daf8361f33) | ![CleanShot 2025-03-25 at 09 12 41](https://github.com/user-attachments/assets/14a5e2d8-03fd-4fac-9cf2-3d4be5c57a79) |
Updated onboarding for adding a new dataset to include CTA and positive copy.
> chore(ui): Onboarding: New dataset empty space

- weave-js/src/common/hooks/useHandleScroll.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OverviewPage/AddProviderDrawer.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OverviewPage/AddProviderDrawerFormComponents.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OverviewPage/ProvidersTab.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OverviewPage/useCustomProviders.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/llmMaxTokens.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/ResizableDrawer.tsx
https://github.com/user-attachments/assets/708234bb-8132-4fa4-8a08-7200a525d8d6
> feat(weave): Add custom providers table to providers tab

- docs/docs/guides/integrations/index.md
- docs/intro_notebook.ipynb
- weave-js/src/common/hooks/useHandleScroll.ts
- weave-js/src/components/FancyPage/useProjectSidebar.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OverviewPage/AddProviderDrawer.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OverviewPage/AddProviderDrawerFormComponents.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OverviewPage/ProvidersTab.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OverviewPage/useCustomProviders.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/LLMDropdown.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/LLMDropdownOptions.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/useChatCompletionFunctions.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/llmMaxTokens.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/ResizableDrawer.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/TypeVersionCategoryChip.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/constants.ts
https://github.com/user-attachments/assets/f202a797-041b-473f-9f5c-7f7c6d204bb8
> feat(weave): Custom providers in the playground

- weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/CreateDatasetDrawer.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/CreateDatasetDrawerContext.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/__tests__/csvUtils.test.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/__tests__/jsonUtils.test.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/csvUtils.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/fileFormats.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/jsonUtils.ts
Adds support for creating new datasets by uploading tsv, json, or jsonl files. Previously, only csv uploads were supported.
> feat(ui): support json[l], tsv dataset uploads

- docs/docs/guides/tools/playground.md
adds docs for deepseek provider and a callout that this does not work with localhost
> docs(weave): Add ngrok callout

- docs/docs/guides/tools/playground.md
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OverviewPage/AddProviderDrawer.tsx
callout was not closed
updates doc link in drawer
> chore(weave): update docs and docs link for custom providers

- docs/docs/guides/tracking/faqs.md
- Fixes https://wandb.atlassian.net/browse/DOCS-1359
Add FAQ entries for rendering datetime and Markdown objects in the Weave UI.
> docs(weave): FAQ items about new inline custom object support with datetime and markdown use cases

- weave-js/src/components/Panel2/PanelMolecule.tsx
- Fixes [WB-14439](https://wandb.atlassian.net/issues/WB-14439)
Local FE Invoker
https://github.com/user-attachments/assets/3af68d56-b5dd-4b65-a72a-66071be662a4
[WB-14439]: https://wandb.atlassian.net/browse/WB-14439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(app): add support for .cif files in weave molecule panels

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/DraggableSection/DraggableItem.tsx
Juice the z index on the draggable item overflow menu.
> fix(ui): make DraggableItem overflow menu visible

- weave-js/src/components/PagePanelComponents/Home/Browse3/components/TraceNavigator/TraceViews/TreeView.tsx
Fixes https://wandb.atlassian.net/browse/WB-24204
Before:
After:
> fix(ui): improve night mode styling for tree view

- tests/conftest.py
- tests/trace/test_client_trace.py
This PR adds 3 unit tests to guarantee some baseline scenarios for [PR 3998](https://github.com/wandb/weave/pull/4027/files)
The PR is the tests.
> chore(weave): Follow up with some test cases for PR 3998

- weave/trace_server/costs/cost_checkpoint.json
> chore(weave): Update costs 4/4

- docs/docs/guides/tracking/tracing.mdx
- Fixes https://wandb.atlassian.net/browse/DOCS-1392
Describes basic use of `autopatch` in `weave.init()`
> docs(weave): document basic autopatch usage

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectsPage/ObjectVersionsTable.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimpleFilterableDataTable.tsx
Remove unused props, changes from https://github.com/wandb/weave/pull/1059/ over a year ago.
> chore(ui): remove unused props

- weave_query/weave_query/execute.py
Fixes [WB-24254](https://wandb.atlassian.net/jira/software/c/projects/WB/boards/138?selectedIssue=WB-24254)
This handles a long standing intermittent panel crash. I do not know the root cause, but I was able to reproduce the panel crash and the same FileNotFoundError by deleting the cached `_rows` directory.
* Forward node of `file-table` is executed
* Use the input nodes to get input refs and use the refs with the op_def to get a `run_key` (cache key)
* Get the `run` value from TRACE_LOCAL using the `run_key`
* `run.output.get()` is called, then the AWL attempts to load its instance from disk. This fails because the file is not on disk
This PR handles the error by try-catching the ref load and deleting the corrupted artifact which will be re-created as execution goes down the cache miss …
> fix(weave_query): gracefully handle cached local artifacts error

- docs/docs/guides/tools/playground.md
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/llmMaxTokens.ts
- weave/trace_server/model_providers/model_providers.json
- weave/trace_server/model_providers/model_providers.py
Groq api key shouldnt be named gemma
2 line change
ran make update_model_providers
> chore(weave): correctly name GROQ_API_KEY

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/llmMaxTokens.ts
https://wandb.atlassian.net/browse/WB-24312
Remove deprecated models
add new llama models
tested each individually
> chore(weave): update groq models

- weave-js/src/core/ops/primitives/boolean.ts
- weave-js/src/core/ops/primitives/number.ts
- weave_query/tests/ops_arrow/test_boolean.py
- weave_query/tests/ops_primitives/test_boolean.py
- weave_query/tests/ops_primitives/test_number.py
- weave_query/weave_query/ops_arrow/boolean.py
- weave_query/weave_query/ops_primitives/boolean.py
- weave_query/weave_query/ops_primitives/number.py
Adds 3 new ops.
**Boolean `all`**
* Takes in a list of booleans and returns whether all the values are `True`. Null values are ignored so that the python implementation matches the [pyarrow compute function](https://arrow.apache.org/docs/python/generated/pyarrow.compute.all.html)
* Empty lists are vacuously true
**Boolean `any`**
* Takes in a list of booleans and returns whether any of the values are `True`. Null values are ignored so that the python implementation matches the [pyarrow compute function](https://arrow.apache.org/docs/python/generated/pyarrow.compute.all.html) 
* Empty arrays are vacuously false
**Number `isInteger`**
* Takes in a numerical value and returns whether it is integral or not. 
Unit tests & Local Invoker
> feat(weave_query): Add ops for boolean all, boolean any, and number isInteger

- pyproject.toml
- tests/trace_server/test_opentelemetry.py
- weave/trace_server/clickhouse_trace_server_batched.py
- weave/trace_server/opentelemetry/attributes.py
- weave/trace_server/opentelemetry/python_spans.py
- weave/trace_server/sqlite_trace_server.py
- weave/trace_server/trace_server_interface.py
WB-24307
WB-24308
Requires #4050
Semantic conventions parsing for OTEL and OpenInference LLM/GenAI traces
Added tests for parsing OTEL/OpenLLMetry, OpenInference and Custom conventions
> feat(weave): Semantic conventions parsing for OTEL and OpenInference

- weave/trace_server/clickhouse_trace_server_batched.py
> chore(weave): remove unused code

- docs/docs/guides/tools/otel.md
- Fixes https://wandb.atlassian.net/browse/DOCS-1390
> docs(weave): Correct endpoint and clarify snippet instructions in OpenTelemetry docs

- docs/docs/guides/tools/otel.md
Adds examples which can be run in a single step once proper API keys and entity are defined. Also adds an example for submitting traces without instrumentation.
> chore(weave): Improve OpenTelemetry examples and add non-instrumented example

- docs/docs/guides/platform/weave-self-managed.md
Fix wrong bucket endpoint configuration.
Running the doc platform locally.
> fix(weave): Fix ClickHouse config in Weave self-managed deployment doc

- weave/trace_server/clickhouse_trace_server_batched.py
- weave/trace_server/environment.py
Adds a ramp env variable: `WF_FILE_STORAGE_PROJECT_RAMP_PCT` to the trace server allowing us to incrementally crank up file storage
> chore(weave): Enable ramping of bucket storage

- docs/docs/guides/tools/playground.md
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/llmMaxTokens.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/usePlaygroundState.ts
- weave/trace_server/costs/cost_checkpoint.json
- weave/trace_server/model_providers/model_providers.json
> chore(weave): Add o4-mini and o3 to playground

- weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/CreateDatasetDrawer.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/CreateDatasetDrawerContext.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/DatasetsPage/DatasetsPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/EmptyContent.tsx
https://wandb.atlassian.net/browse/WB-24474
Adds missing dataset saving hooks for the `create your first dataset` button on the empty datasets page.
> fix(ui): create your first dataset button works upload-first-works

- weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/useDatasetSaving.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/DatasetsPage/DatasetsPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/EmptyContent.tsx
> chore(dev): introduce common hook for saving new datasets

- .github/workflows/tldr.yaml
Adds a github action for running PR summarization with tldr. See the comment tldr left on this PR for a description
> chore(dev): tldr github action

- weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterBar.tsx
Fixes dark styles for the filterbar.
| ![image](https://github.com/user-attachments/assets/194cdd25-a10e-4c7d-a361-5592befe238e) | ![image](https://github.com/user-attachments/assets/8c3b857a-abba-4ec9-99fc-ccfe894afb66) |
> chore(ui): Dark fixes for filterbar

- weave-js/src/components/Panel2/WeaveAnimatedLoader.tsx
Add display name for react dev tools.
> chore(ui): add display name

- docs/docs/guides/tools/playground.md
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundPage.tsx
Removed playground pill
Before
After
> feat(weave): Take Playground GA

- tests/trace/test_evaluation_imperative.py
- weave/__init__.py
- weave/flow/eval_imperative.py
- weave/flow/obj.py
- weave/integrations/integration_utilities.py
- weave/trace/op.py
- weave/trace/serialization/op_type.py
This is the SDK portion of the larger Framework-agnostic Eval API improvements
https://github.com/wandb/weave/pull/4005
> feat(weave): Imperative Evaluation APIs

- weave/trace_server/clickhouse_trace_server_batched.py
adds some additional datadog tracking for bytes read and written to different storage providers
> chore(weave): Add additional datadog logging to bucket storage

- weave-js/src/components/Panel2/PanelExpression/ConfigComponent.tsx
- weave-js/src/components/Panel2/PanelExpression/hooks.ts
- Fixes [WB-24476](https://wandb.atlassian.net/browse/WB-24476)
https://github.com/user-attachments/assets/12646437-87a5-46e3-ae7f-3581054dde1d
[WB-24476]: https://wandb.atlassian.net/browse/WB-24476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(app): Render As dropdown shows currently selected value

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/LLMDropdownOptions.tsx
> chore(weave): Fix overlap of show more button

- weave-js/src/components/Panel2/PanelExpression/Component.tsx
- weave-js/src/components/Panel2/PanelTable/PanelTable.tsx
- weave-js/src/panel/WeaveExpression/hooks.ts
- weave-js/src/panel/WeaveExpression/index.tsx
- weave-js/src/panel/WeaveExpression/styles.ts
Internal JIRA: [WB-24356](https://wandb.atlassian.net/browse/WB-24356)
This PR restyles the editor according to this doc from the design team: https://www.notion.so/wandbai/RFC-Query-panels-Table-usability-improvements-Draft-1a4e2f5c7ef380cf8d3fd7c28c51b992?pvs=4
Summary of changes:
1. Added a border radius with border color applied when hovering and focusing to the editor
2. Added a placeholder
3. Removed border between editor and content
4. Changed apply button to have a transparent background color
5. Removed "run" text from apply button
manually and visually thru invoker
https://github.com/user-attachments/assets/67d1ca22-1ba2-45a3-8513-8f3cf5b65140
[WB-24356]: https://wandb.atlassian.net/browse/WB-24356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …
> chore(app): Query panel expression editor restyling

- tests/integrations/dspy/dspy_test.py
Newer versions have worse performance - adjusting in CI.
> chore(weave): Fix DSPy in CI

- weave/trace_server/costs/cost_checkpoint.json
> chore(weave): Update costs 4/14

- docs/CONTRIBUTING_DOCS.md
- Fixes https://wandb.atlassian.net/browse/DOCS-1428
Describe https://github.com/wandb/weave/blob/master/docs/scripts/update_playground_models.py usage in the contribution guide
> docs(weave):  Describe usage of update_playground_models.py

- weave-js/src/components/PagePanelComponents/Home/Browse3/compare/hooks.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx
> chore(ui): fix typos in comments

- docs/docs/guides/platform/weave-self-managed.md
This change fixes the docs to prevent users from deploying the latest version of the Bitnami helm chart, which wasn't tested and doesn't work with the configuration from this document.
- Remove image reference (breaks the config if not using Bitnami image)
- Fix the persistence volume size
- Fix the cache size
- Fix the install command
- Remove namespace references.
Running the docs system locally.
> fix(weave): Fix Weave self-managed docs

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimplePageLayout.tsx
Putting some test ids on components for the purposes of testing. No tests in this PR.
> chore(dev): add test id to weave page titles

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
> revert(weave): dump option click filter values to string

- .github/workflows/test.yaml
- pyproject.toml
- tests/trace/test_evaluation_imperative.py
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/ecpTypes.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ExampleCompareSection/ExampleCompareSection.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ExampleCompareSection/exampleCompareSectionUtil.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/heuristics.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooksEvaluationComparison.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/views/Leaderboard/query/leaderboardQuery.ts
- weave/__init__.py
- weave/flow/eval_imperative.py
This PR primarily updates the UI to support imperative evaluations, and limited internal-only API changes to support that.
> feat(weave): UI and API improvements for Imperative Evals

- weave_query/weave_query/filesystem.py
- weave_query/weave_query/weave_http.py
Supplement span with the size of the downloaded file and increase granularity of the events with more spans
> chore(weave_query): add more trace data to download_file_task

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/ecpTypes.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ExampleCompareSection/ExampleCompareSection.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/heuristics.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooksEvaluationComparison.ts
- weave/flow/eval_imperative.py
This makes it so individual scores show up and link back to their calls
> chore(weave): Add individual scores to Imperative Evals UI

- weave/trace_server/clickhouse_trace_server_batched.py
Fixes a production issue impact some of the users.
TBD
> fix(weave): fixes an issue that impacts product

- tests/trace/test_client_trace.py
- weave/trace/api.py
Adds a simple helper to get objects from URIs in Weave
> chore(weave): Add `weave.get`

- tests/trace/test_trace_settings.py
Removes duplicate piece of test.
test
> chore(weave): slightly faster client parallelism test

- tests/trace/test_client_trace.py
Slightly faster test by reducing sleeps
test
> chore(weave): slightly faster mapper test

- tests/trace/test_saved_view.py
- weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterTagStatus.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/filters/ValueInputStatus.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPageLoadView.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPageLoadViewWithUser.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPageLoaded.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/RedirectToLastView.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableQuery.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectsPage/ObjectVersionPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectsPage/Tabs/TabUseSavedView.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/SavedViews/ConfirmDeleteDialog.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/SavedViews/DropdownSwitchView.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/SavedViews/DropdownViewActions.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/SavedViews/PanelSwitchView.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/SavedViews/PanelView.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/SavedViews/SavedViewPrefix.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/SavedViews/SavedViewSuffix.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/SavedViews/SavedViewSuffixTimestamp.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/SavedViews/ViewName.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/SavedViews/ViewNameEditing.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/SavedViews/savedViewUtil.test.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/SavedViews/savedViewUtil.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/tabularListViews/operators.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/objectClassQuery.ts
- weave/__init__.py
- weave/flow/saved_view.py
- weave/trace/context/weave_client_context.py
- weave/trace/rich/pydantic_util.py
Internal Jira: https://wandb.atlassian.net/browse/WB-21701
Adds "Saved Views" to the UI and SDK. Views are saved as Weave objects. Table settings on the Traces and Evaluations pages like filters, sorting, page size, column visibility, and column pinning are stored in the view object.
New views can be saved, views can be updated, renamed, and deleted.
> feat(ui): Saved Views

- tests/trace/test_evaluate.py
- weave/trace/vals.py
This pr: 
- pulls out constant page size
- monkeypatches the value and lowers it for tests
test
> chore(weave): fix slow table tests

- tests/trace/test_weave_client.py
> chore(weave): test sometimes flakes, fixed

- docs/CONTRIBUTING_DOCS.md
- Fixes https://wandb.atlassian.net/browse/DOCS-1445
A few things:
- Adds info about using `make docs` 
- States that it should run on all docs contributions
- Explains why it's used
- Updates overall writing and tone of doc (technically out of scope of the ticket but might as well 😃 )
> docs(weave): update CONTRIBUTING_DOCS.md

- weave/flow/eval_imperative.py
From #4308 credit to @wangbooth
Reopening here to trigger CI
> fix(weave): datetime import error ci

- tests/trace/test_evaluations.py
[Flaked test](https://github.com/wandb/weave/actions/runs/14713744237/job/41292286900?pr=4297)
test
> chore(weave): increase latency tolerance eval test

- weave-js/src/common/types/media.ts
https://wandb.atlassian.net/browse/WB-24614
Creating this util to better refine the type to use `keyToMediaCardType`
> chore(app): Create a util for isMediaCardString

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/SavedViews/savedViewUtil.ts
Accidentally left a debugger statement in.
> chore(ui): remove dev track

- README.md
Revert https://github.com/wandb/weave/pull/4296 per slack thread 
https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1745615675314659
> docs(weave): Re-Update README.md

- weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/CreateDatasetDrawer.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/DatasetPublishToast.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/DatasetVersionPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/EditableDatasetView.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Empty.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/EmptyContent.tsx
Throwing some tests ids on some components.
> chore(dev): add test ids to dataset components

- weave-js/src/components/Panel2/ControlImageOverlays.tsx
- Followup to [WB-24353](https://wandb.atlassian.net/browse/WB-24353), additional context in https://weightsandbiases.slack.com/archives/C083KQFTAQ4/p1744832169882319
- Fixes the 👁️ icon so that it toggles the entire class set on/off
https://github.com/user-attachments/assets/20e195ba-13c8-4a4f-9b46-84bdeef2d641
[WB-24353]: https://wandb.atlassian.net/browse/WB-24353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(app): eyeball icon can toggle image mask sets on/off

- weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterBar.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/filters/common.ts
Adds the ability to filter by trace name.
Branch:
> chore(weave): filter by trace name

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/compositeMetricsUtil.ts
> fix(weave): Make "Example Filter" work for imperative evals

- weave_query/tests/test_wb_end_to_end.py
- weave_query/weave_query/weave_http.py
Extends https://github.com/wandb/weave/pull/4287. `iter_chunked` can return chunks of size smaller than the 8MB we've set so we can still run into issues with a long tail of writes. We can make writes that are closer to 8MB by first writing to an in-memory buffer and only writing to disk once the buffer has at least 8MB on content.
Used local invoker to verify that only a single write occurs for each file in https://wandb.ai/wandb/2-million-row-repro (since each table is smaller than 8MB). Also verified that the table doesn't crash with this scheme. Unable to provide accurate timing estimates though since everything loads fairly quickly locally.
> chore(weave_query): buffer writes on table downloads until chunk size is reached

- weave-js/src/common/components/TraceCountDisplay.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableQuery.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/context.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts
Addresses comments made to https://github.com/wandb/weave/pull/4269
Branch:
> chore(weave): add helper useProjectHasCalls + comment param names

- weave-js/src/components/Panel2/PanelString.tsx
Context: https://weightsandbiases.slack.com/archives/C07NE3Z41A6/p1744825523826409
Adjusts the node to account for custom run names when we detect that the string panel is receiving the output of the `run.name` op
* Verified that the custom run name appears
* Verified that the custom run names don't affect other panel grids
* Verified that the display name is returned if a custom run name was not set
https://github.com/user-attachments/assets/b3700b40-184d-4a1c-865f-3db13ec6a978
> fix(app): use custom run name if available when displaying run.name

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
Fix query result handling! Causing all pages to default to weave!
> fix(weave): count query returns a count!

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/heuristics.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooksEvaluationComparison.ts
Also include predict and score functions from sdks that use camel case. 
Tests in this thread: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1746058529208239
> fix(weave): show examples in eval compare for js evals

- weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterTagStatus.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/filters/ValueInputStatus.tsx
Fix https://wandb.atlassian.net/browse/WB-24739
Before:
After:
> fix(weave): night mode for status chips in filters

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/SavedViews/SavedViewSuffix.tsx
Update tooltip text on Reset View action for clarity. (Feedback from Adam)
> chore(ui): update tooltip text for Reset View action

- weave/__init__.py
Add the new `get` method from https://github.com/wandb/weave/pull/4274 to `__docspec__`
yarn start in docs
> docs(weave): include new get method

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/LLMDropdown.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/LLMDropdownOptions.tsx
After
https://github.com/user-attachments/assets/ac0aaf49-9405-441e-bde2-e4428674249e
before
> style(weave): Move configure provider options to nested dd

- weave/trace/api.py
Allows `get` to operate on both uris and refs
> chore(weave): Allow get to operate on both uris and refs

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/PlaygroundChat.tsx
| ![image](https://github.com/user-attachments/assets/aeff36d3-cd7c-4594-a30a-56fb7d642ad7) | ![image](https://github.com/user-attachments/assets/ff4f1f8f-d562-4f65-9abd-c8a5b5cfd999) |
- Small visual fix for the border color if no LLM provider is present
> chore(ui): Playground - border fix, no LLM provider

- .github/workflows/test.yaml
- Fixes #NNNN
This PR removed HF tests for now. 
> chore(weave): remove HF tests

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/tabularListViews/operators.ts
[WB-24853](https://wandb.atlassian.net/browse/WB-24853)
Fix for a bug introduced in [this](https://github.com/wandb/weave/pull/4385) pr, overeager refactoring...
Before:
After:
[WB-24853]: https://wandb.atlassian.net/browse/WB-24853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(weave): fix bool filter operator conversion

- weave/trace_server/costs/cost_checkpoint.json
> chore(weave): update costs 5/7

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/llmMaxTokens.ts
- weave/trace_server/model_providers/model_providers.json
- weave/trace_server/model_providers/model_providers.py
add mistral to supported providers
run make update_model_providers
add models to dropdown
Individually tested each added model
> chore(weave): add mistral to playground

- weave-js/src/components/PagePanelComponents/Home/Browse3/typeViews/moviepy.video.VideoClip/VideoPlayer.tsx
Fixes a regression that occurred in later stages of previous PR
> fix(weave): Fix video display in trace view

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts
Add a `useCall2` clone of `useCall` which will enable this refactor https://github.com/wandb/weave/pull/4389
> chore(weave): add useCall2

- weave_query/weave_query/ops_domain/table.py
https://wandb.atlassian.net/browse/WB-20520
This PR changes the implementation for loading up incremental tables to handle the scenario where incremental artifacts are received by the backend in different orders.
The artifacts system will be eventually consistent in the sense that all table increments will be present in the final version of the artifact.
Based on that eventual consistency, on the SDK, we store the artifact urls for the previous increment paths. which guarantees the contents and the order of the increments for the history row at the time the increment was logged.
Query engine uses the `previous_increments_paths` list to load up the incremental table with its data in the correct order.
locally invoker.ini
> chore(weave_query): Use previous increment paths to handle artifact ordering

- weave-js/src/components/PagePanelComponents/Home/Browse3/typeViews/Audio/AudioPlayer.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/typeViews/CustomWeaveTypeDispatcher.tsx
Requires: #4363
- Fixes WB-24097
Adds MP3 Support for frontend
> feat(weave): MP3 support on frontend

- weave-js/package.json
- weave-js/src/components/PagePanelComponents/Home/Browse3/typeViews/CustomWeaveTypeDispatcher.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/typeViews/File/FileView.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/typeViews/File/PDFView.tsx
- weave-js/tsconfig.json
- weave-js/yarn.lock
- weave/__init__.py
- weave/trace/serialization/mem_artifact.py
- weave/type_handlers/File/file.py
- weave/type_handlers/__init__.py
Fixes https://wandb.atlassian.net/browse/WB-24856 and https://wandb.atlassian.net/browse/WB-24857
* Added PDF and CSV file examples to `wf`.
* Single-page PDF - renders without counter, thumbnails, arrows
* PDF with images - OK, screenshot above
* 26MB, 50+ page PDF - OK, lazy rendering of pages, loading indicators
> feat(ui): Add generic file handling and PDF viewer support

- .github/workflows/check-which-tests-to-run.yaml
- .github/workflows/test.yaml
- sdks/node/package.json
- sdks/node/src/__tests__/clientApi.test.ts
- sdks/node/src/__tests__/wandb/settings.test.ts
- sdks/node/src/clientApi.ts
- sdks/node/src/generated/traceServerApi.ts
- sdks/node/src/opType.ts
- sdks/node/src/urls.ts
This PR simply takes the changes from running "pnpm run format".
For context, please read the discussion in https://github.com/wandb/weave/pull/4353
> chore(weave): apply prettier formatting.

- sdks/node/README.md
- sdks/node/package.json
- Updates the Node SDK README with documentation for class method decorators with `@weave.op`
- Bumps package version from 0.7.6 to 0.8.0, preparing for release
> docs(weave): Introduce decorator usage and bump version for release

- tests/trace/test_client_trace.py
- tests/trace/test_evaluations.py
- tests/trace/test_weave_client.py
- tests/trace_server/test_calls_query_builder.py
- weave/trace/weave_client.py
- weave/trace_server/calls_query_builder/calls_query_builder.py
- weave/trace_server/sqlite_trace_server.py
- weave/trace_server/trace_server_common.py
- weave/trace_server/trace_server_interface.py
Contains the python-side changes for https://github.com/wandb/weave/pull/4415. See that PR for notes
> feat(weave): Add first-class "descendant_error" state (python side)

- docs/docs/reference/gen_notebooks/ocr-pipeline.md
Updates broken links to Github and Collab for the OCR VLM pipeline notebook
Used playwright and yarn to test locally. Passes all tests!
> docs(weave): fixed broken notebook links for collab and github

- weave-js/src/components/Panel2/PanelTable/tableType.ts
- weave_query/weave_query/derive_op.py
This disables the codepath to load incremental tables for now.
> chore(app): Disable incremental table op from being used for now

- docs/docs/guides/tracking/video.md
https://wandb.atlassian.net/browse/DOCS-1535
1. Moves `moviepy==1.0.3.` req info to prereq section
2. `moviepy` -> `moveiepy.editor`
> docs(weave): update video.md

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
Specifically, there was a bug when:
1. User expanded first level of input/output ref
2. User expands the first child ref of that recently expanded parent ref.
Low level: fixes `useRefsReadBatch` to not return stale data.
---
Some technical details... the pattern that was happening was:
1. user expands Ref X
2. useRefsReadBatch is called with [X]
3. user expands Y
4. useRefsReadBatch is called with [Y] -> returns immediately with stale X data
5. React component puts X's data inside Y, creating an inf recursion!
> fix(weave): Fixes inf loop when expanding inputs & outputs

- weave-js/src/components/Panel2/PanelImage.tsx
- weave-js/src/components/Panel2/controlsImage.ts
Fixes https://weightsandbiases.slack.com/archives/C083KQFTAQ4/p1744832169882319
Local FE Tilt
https://github.com/user-attachments/assets/0b421886-df9b-4135-b640-d3774236eb75
> fix(app): correctly render images in the flexbox

- weave-js/src/components/Panel2/PanelTable/tableType.ts
Re-enables incremental table loading in run workspaces
invoker fe_prod
> chore(app): renable incrementally logged tables in run workspace

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/CompareEvaluationsPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ExampleCompareSection/ExampleCompareSectionDetail.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ExampleCompareSection/ExampleCompareSectionTable.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ExampleFilterSection/ExampleFilterSection.tsx
Removed for a whole 24 hours, they are back!
> chore(weave): Re-enable Regression Filters

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/llmMaxTokens.ts
- weave/trace_server/costs/cost_checkpoint.json
- weave/trace_server/model_providers/model_providers.json
run make update_costs
run make update_model_providers
update dropdown
Add Claude 4 costs and playground
> chore(weave): Add Claude 4 costs and playground

- tests/flow/test_evaluation_imperative.py
CI is red due to this test flaking consistently on inconsistent inputs. Temporarily disabling it.
> chore(weave): Skip flow test that consistently flakes

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
> chore(ui): fix typo in comment

- weave_query/weave_query/environment.py
revert some change from https://github.com/wandb/weave/pull/4602 which impacts weave_query service
not tested
> chore(weave): revert changes about .netrc handling

- weave-js/package.json
- weave-js/yarn.lock
[Motion](https://motion.dev/) is an animation library I'll be using - handles things like fading out, smoothly transitioning position, etc.
> chore(ui): add motion library

- docs/docs/guides/tracking/tracing.mdx
- sdks/node/README.md
- https://wandb.atlassian.net/browse/DOCS-1563
This addresses some left over code review comments from https://github.com/wandb/weave/pull/4612
Not tested
> docs(weave): TS SDK doc improvement

- tests/trace/test_import.py
Internal Slack reference:
https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1749174124042979
https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1749241103979319
See also https://github.com/wandb/weave/pull/3395
> chore(dev): increase import time threshold for CI

- weave-js/src/common/types/base.ts
These will be used by upcoming routes, pulled out for separate fe-infra-reviewers stamp.
> chore(ui): add match params

- .github/dependabot.yml
This is a very limited PR to get started with Dependabot.  It doesn't actually do anything yet, except check for pydantic updates.
The dependabot file needs to be in master for us to start using it
> chore(weave): Add initial Dependabot for testing

- .github/dependabot.yml
> chore(weave): More dependabot testing

- .github/dependabot.yml
> chore(weave): Dependabot2

- weave-js/src/components/PagePanelComponents/Home/Browse3/inference/ModelDetailsLoaded.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/inference/modelsBegin.json
- weave-js/src/components/PagePanelComponents/Home/Browse3/inference/modelsFinal.json
- weave-js/src/components/PagePanelComponents/Home/Browse3/inference/navigate.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/inference/types.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/LLMDropdownOptions.tsx
Moving to being more explicit about the meaning of different fields in our model catalog data and using them consistently. This fixes a bug Deok reported with the wrong value showing up in the Playground select widget, and I think should get the correct model string to the Trace Server for it to pass on to the Inference Service.
> chore(weave): clarify role of model id and idPlayground

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/llmMaxTokens.ts
Marketing request to use titlecase.
Internal Notion: https://www.notion.so/wandbai/What-names-should-be-used-in-the-Product-UI-210e2f5c7ef3800db3bec4bd7c587191?source=copy_link
> chore(weave): uppercase Inference

- weave-js/src/components/PagePanelComponents/Home/Browse3/views/Leaderboard/LeaderboardGrid.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/views/Leaderboard/query/leaderboardQuery.ts
Adds a status chip to let the user know that an eval is currently running for a model in the Leaderboard.
> chore(ui): Leaderboard: Running eval status icon

- examples/text-extract/example_data/Generate AOI.ipynb
- pyproject.toml
- tests/flow/test_weaveflow.py
- tests/integrations/cohere/cohere_test.py
- tests/integrations/langchain/langchain_test.py
- tests/integrations/openai/openai_test.py
- tests/trace/test_client_server_caching.py
- tests/trace/test_client_trace.py
- tests/trace/test_dataset.py
- tests/trace/test_op_generators.py
- tests/trace/test_op_return_forms.py
- tests/trace/test_weave_client.py
- weave/flow/chat_util.py
- weave/flow/eval.py
- weave/integrations/openai/openai_sdk.py
- weave/trace/grid.py
- weave/trace_server/clickhouse_trace_server_batched.py
- weave/trace_server/sqlite_trace_server.py
- **test**
- **fix unsafe**
- **fix**
> chore(weave): Add B007 lint rule

- weave-js/src/components/PagePanelComponents/Home/Browse3/inference/ModelDetailsLoaded.tsx
Just adding tooltip prop to a button.
> chore(weave): add tooltip to code sample copy button on model details page

- weave-js/src/components/PagePanelComponents/Home/Browse3/inference/ModelDetailsLoaded.tsx
> chore(ui): use new icon for license

- weave/trace_server/clickhouse_trace_server_batched.py
Now that DNS is setup, use the preferred hostnames in Trace Server.
> chore(weave): update prod inference service hostname

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableFilter.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/MonitorsPage/MonitorFormDrawer.tsx
- weave-js/yarn.lock
Removing "All Ops" option from the monitor ops dropdown.
> feat(weave): Remove all ops option from monitor ops dropdown

- weave-js/src/components/PagePanelComponents/Home/Browse3/inference/ModelTile.tsx
Removing drop shadow on selection per Lauralee.
> chore(ui): remove model tile drop shadow

- docs/docs/guides/integrations/inference.md
- Fixes https://wandb.atlassian.net/browse/DOCS-1584
Per product team, we refer to the service as W&B Inference, not Weights & Biases Inference
> docs(weave): inference docs branding update

- .gitignore
> chore(weave): Ignore personal rules

- weave-js/src/components/FancyPage/useProjectSidebar.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
- weave-js/src/config.ts
Pick up feature flag from core to use as feature-flag.
> feat(weave): Pick up dedicated feature flag from core

- pyproject.toml
Temporarily pin smolagents to unblock CI
> chore(weave): Temporarily pin smolagents<1.19.0

- pyproject.toml
- tests/scorers/test_trust_scorer.py
https://docs.astral.sh/ruff/rules/incorrect-dict-iterator/
> chore(weave): Add PERF102 lint rule

- weave/trace_server/file_storage.py
Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1750870196368879?thread_ts=1750870107.254709&cid=C03BSTEBD7F
master branch broken in CI because of new ruff lint rule.
> fix(weave): CI issue with ruff

- weave-js/src/components/FancyPage/useProjectSidebar.ts
Lift the admin-only feature gate for online evals.
> feat(weave): Lift online eval feature gate

- docs/docs/guides/integrations/inference.md
Fixes [DOCS-1602](https://wandb.atlassian.net/browse/DOCS-1602)
Fixes broken link
[DOCS-1602]: https://wandb.atlassian.net/browse/DOCS-1602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(weave): Fix pricing link

- pyproject.toml
> chore(weave): Temporarily pin mcp<1.10.0

- docs/docs/guides/core-types/datasets.md
- tests/trace/test_dataset.py
- weave/flow/dataset.py
Adds simple `to_hf` and `from_hf` methods to `weave.Dataset` so we can do the processing leveraging the fast and battle tested datasets library.
> feat(weave): HF.Datasets <-> weave.Dataset

- weave-js/src/components/PagePanelComponents/Home/Browse3/inference/ModelDetailsLoaded.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/inference/ModelTile.tsx
Let the availability state of model catalog pages and feature be driven by context values, allowing us to better centralize the logic.
> chore(weave): cleanup inference service availability message

- .github/workflows/cla.yaml
- .github/workflows/pr.yaml
Whitelist dependabot so it can submit PRs
> chore(weave): Add dependabot to CLA whitelist

- .github/dependabot.yml
Switch dependabot to target the master branch
> chore(weave): Enable dependabot on master branch

- weave/trace/weave_client.py
> chore(weave): delete duplicate line in weave client

- pyproject.toml
- weave/trace_server/calls_query_builder/calls_query_builder.py
https://docs.astral.sh/ruff/rules/import-shadowed-by-loop-var/
> chore(weave): Add F402 lint rule

- pyproject.toml
- tests/trace/test_file_storage_credentials.py
- weave/trace_server/calls_query_builder/calls_query_builder.py
- weave/trace_server/opentelemetry/constants.py
https://docs.astral.sh/ruff/rules/multi-value-repeated-key-literal/
> chore(weave): Add F6 lint rule

- .github/dependabot.yml
Ignore the weave_query subdir... hopefully this works
> chore(weave): Make dependabot ignore weave_query

- docs/notebooks/weave_via_service_api.ipynb
- pyproject.toml
- weave/scorers/prompts.py
- weave/trace_server/trace_server_interface.py
https://docs.astral.sh/ruff/rules/ambiguous-unicode-character-string/
> chore(weave): Add RUF001 lint rule

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/MonitorsPage/MonitorPage.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/MonitorsPage/MonitorsPage.tsx
This fixes the displayed filter value.
Before
After
> fix(weave): "Go to table" button linked to page with wrong filter

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/MonitorsPage/ScorerForms/LLMAsAJudgeScorerForm.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/EmptyContent.tsx
Update links for more tracking.
> chore(weave): Update doc links to use wandb.me

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/LLMDropdown.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/PlaygroundChatTopBar.tsx
While building the monitor creation form I duplicated a bunch of code. This cleans it up.
> chore(weave): DRY LLMDropdown code

- pyproject.toml
- weave/scorers/__init__.py
https://docs.astral.sh/ruff/rules/undefined-export/
> chore(weave): Add F822 lint rule

- docs/notebooks/pii.ipynb
- pyproject.toml
- weave/scorers/__init__.py
https://docs.astral.sh/ruff/rules/mutable-class-default/
> chore(weave): Add RUF012 lint rule

- weave/trace_server/costs/cost_checkpoint.json
- weave/trace_server/model_providers/model_providers.json
Runs make update_costs
Runs make update_model_providers
> chore(weave): Update costs and model providers 7/03

- weave-js/src/components/PagePanelComponents/Home/Browse3/components/TraceNavigator/TraceViews/utils.ts
[WB-25981](https://wandb.atlassian.net/browse/WB-25981)
Prod:
Branch:
[WB-25981]: https://wandb.atlassian.net/browse/WB-25981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(weave): 1 liner to fix ui error

- weave_query/weave_query/ops_domain/table.py
Revert JSON parsing via orjson since it's causing issues, see https://weightsandbiases.slack.com/archives/C07NE3Z41A6/p1751469346652329
Loaded various tables with local weave_query
https://github.com/user-attachments/assets/9ca12631-dc27-4f87-8d55-0576d552c132
> chore(weave_query): revert parsing via orjson

- weave/trace_server/costs/cost_checkpoint.json
> chore(weave): Update costs 7/7

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTableButtons.tsx
[WB-26054](https://wandb.atlassian.net/browse/WB-26054)
Prod
Branch
[WB-26054]: https://wandb.atlassian.net/browse/WB-26054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(weave): empty list handling export trace modal

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/PlaygroundChat.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/PlaygroundChatInput.tsx
Working on making Playground components reusable for prompt editing, noticed this prop is unused.
> chore(ui): remove unused prop

- pyproject.toml
Previously pinned waiting for a PR that has now merged
> chore(weave): Unpin pillow dependency for video support

- weave/scorers/__init__.py
https://wandb.atlassian.net/browse/WB-26086
> chore(weave): Add better error message for missing imports in scorers

- docs/sidebars.ts
- Fixes #NNNN
This PR updates the sidebar.ts with the link to `verdict.md`.
> docs(weave): Add verdict docs to sidebar

- tests/trace_server/test_trace_server_evaluation_apis.py
- weave/trace_server/clickhouse_trace_server_batched.py
- weave/trace_server/methods/evaluation_status.py
- weave/trace_server/sqlite_trace_server.py
- weave/trace_server/trace_server_interface.py
Implements the Evaluation status method for both backends
> chore(weave): Implement Evaluation status

- docs/scripts/generate_images.py
- gh_actions/slack_digest.py
- pyproject.toml
- weave/integrations/autogen/autogen_sdk.py
- weave/integrations/patcher.py
- weave/trace/concurrent/futures.py
- weave/trace_server/costs/insert_costs.py
- weave/trace_server/environment.py
- weave/trace_server/file_storage.py
- weave/trace_server_bindings/async_batch_processor.py
- weave/trace_server_bindings/caches.py
- weave/trace_server_bindings/caching_middleware_trace_server.py
- weave/type_handlers/File/file.py
https://docs.astral.sh/ruff/rules/verbose-log-message/
> chore(weave): Add TRY401 lint rule

- pyproject.toml
- tests/trace/test_client_trace.py
https://docs.astral.sh/ruff/rules/pytest-patch-with-lambda/
> chore(weave): Add PT008 lint rule

- .pre-commit-config.yaml
- examples/weaveflow/get_started.ipynb
- tests/integrations/mcp/mcp_test.py
- tests/scorers/test_presidio_guardrail.py
- tests/trace/test_client_trace.py
- tests/trace/test_evaluations.py
- tests/trace/test_feedback.py
- tests/trace/test_trace_settings.py
- tests/trace/type_handlers/Video/video_test.py
- tests/trace_server/test_custom_provider.py
- tests/trace_server/test_threads_query_builder.py
- tests/trace_server_bindings/test_async_batch_processor.py
- weave/flow/eval_imperative.py
- weave/scorers/hallucination_scorer.py
- weave/scorers/scorer_types.py
- weave/trace_server/file_storage_credentials.py
Updates lint check ruff formatter to `v0.12.3`
> chore(weave): Update ruff formatter

- docs/docs/guides/integrations/inference.md
Only content change is adding MoonshotAI Kimi K2 row to models table, remainder of changes are autoformatting.
yarn start in docs dir, manual review
> docs(weave): Add MoonshotAI Kimi K2 to inference docs page

- .pre-commit-config.yaml
- sdks/node/README-DEV.md
- sdks/node/src/utils/commonJSLoader.ts
> chore(weave): Fix typos in sdks/

- weave-js/src/components/PagePanelComponents/Home/Browse3/inference/ExplorerLoaded.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/inference/ModelTile.tsx
- weave-js/src/components/PagePanelComponents/Home/Browse3/inference/modelsBegin.json
- weave-js/src/components/PagePanelComponents/Home/Browse3/inference/modelsFinal.json
- weave-js/src/components/PagePanelComponents/Home/Browse3/inference/types.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/LLMDropdownOptions.tsx
- Updated model pricing
- Add new indicators and use in popularity sorting.
> chore(weave): update Kimi pricing

- docs/scripts/generate_python_sdk_docs.py
- pyproject.toml
- tests/integrations/autogen/autogen_test.py
- weave/integrations/llamaindex/llamaindex.py
https://docs.astral.sh/ruff/rules/needless-else/
> chore(weave): Add RUF047 lint rule

- docs/notebooks/audio_with_weave.ipynb
- docs/notebooks/ocr-pipeline.ipynb
- examples/mcp_demo/example_client.py
- pyproject.toml
- tests/integrations/google_genai/test_google_genai.py
- tests/trace_server/conftest_lib/clickhouse_server.py
- weave/scorers/bedrock_guardrails.py
- weave/trace/serialization/op_type.py
- weave/trace_server/environment.py
- weave/trace_server/file_storage.py
- weave/trace_server/llm_completion.py
- weave/trace_server/validation_util.py
https://docs.astral.sh/ruff/rules/explicit-f-string-type-conversion/
> chore(weave): Add RUF010 lint rule

- pyproject.toml
- weave/scorers/context_relevance_scorer.py
https://docs.astral.sh/ruff/rules/unnecessary-cast-to-int/
> chore(weave): Add RUF046 lint rule

- pyproject.toml
- weave/integrations/verdict/verdict_sdk.py
- weave/trace_server/clickhouse_trace_server_batched.py
https://docs.astral.sh/ruff/rules/incorrectly-parenthesized-tuple-in-subscript/
> chore(weave): Add RUF031 lint rule

- pyproject.toml
- tests/conftest.py
- weave/trace/api.py
- weave/trace/serialization/op_type.py
- weave/type_handlers/Audio/audio.py
https://docs.astral.sh/ruff/rules/not-in-test/
> chore(weave): Add E713 lint rule

- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/llmMaxTokens.ts
- weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/usePlaygroundState.ts
Adds grok 4 to playground
manually
> chore(weave): add grok 4 to playground

- pyproject.toml
- rules/legacy_methods.py
- tests/integrations/anthropic/anthropic_test.py
- tests/integrations/autogen/autogen_test.py
- tests/integrations/bedrock/bedrock_test.py
- tests/integrations/cerebras/cerebras_test.py
- tests/integrations/cohere/cohere_test.py
- tests/integrations/crewai/crewai_test.py
- tests/integrations/dspy/dspy_test.py
- tests/integrations/google_ai_studio/google_ai_studio_test.py
- tests/integrations/google_genai/test_google_genai.py
- tests/integrations/groq/groq_test.py
- tests/integrations/huggingface/test_huggingface_inference_client.py
- tests/integrations/instructor/instructor_test.py
- tests/integrations/langchain/langchain_test.py
- tests/integrations/langchain_nvidia_ai_endpoints/langchain_nv_ai_endpoints_test.py
- tests/integrations/litellm/litellm_test.py
- tests/integrations/llamaindex/llamaindex_test.py
- tests/integrations/mcp/mcp_test.py
- tests/integrations/mistral/mistral_test.py
- tests/integrations/notdiamond/custom_router_test.py
- tests/integrations/notdiamond/tracing_test.py
- tests/integrations/openai/openai_test.py
- tests/integrations/smolagents/test_smolagents.py
- tests/integrations/verdict/verdict_test.py
- tests/integrations/vertexai/vertexai_test.py
- tests/trace/test_evaluation_performance.py
- tests/trace/test_op_decorator_behaviour.py
Adds an autofix rule to convert all `client.call -> client.get_calls`
> chore(weave): Update client.calls -> client.get_calls

- pyproject.toml
- tests/integrations/llamaindex/llamaindex_test.py
Pin before this version: https://pypi.org/project/llama-index/0.12.50/
test
> fix(weave): llamaindex pin

- docs/docs/guides/tools/playground.md
- Fixes https://wandb.atlassian.net/browse/DOCS-1559
Add subsection to https://weave-docs.wandb.ai/guides/tools/playground#saved-models to describe structured json output and changing response format
> docs(weave): structured output

- .github/workflows/check-which-tests-to-run.yaml
- .github/workflows/notify-wandb-core.yaml
- .github/workflows/test.yaml
Remove weave-js lint and compile steps from ci since this is no longer where the code lives.
> chore(dev): remove weave-js lint ci

- .github/workflows/release.yaml
> chore(weave): Make test pypi publish verbose

- pyproject.toml
- Fixes Deploy process
Uses our custom published pypi package as a dependency
> fix(weave): Use polyfile-weave

- weave/trace_server/costs/cost_checkpoint.json
- weave/trace_server/model_providers/model_providers.json
Runs 
make update_costs
make update_model_providers
> chore(weave): Update Costs 7/28

- weave/trace_server/model_providers/model_providers.json
> feat(weave): Openai inference in playground providers

- tests/integrations/litellm/client_completions_create_test.py
Updates expectations as of `litellm==1.75.0`
> chore(weave): Update litellm tests

- tools/codegen/generate.py
Typer is nicer and easier to use now that we are using `uv run` for this script.
> chore(weave): Use typer for codegen CLI

- pyproject.toml
- tools/codegen/generate.py
Adds a step in the generator to automatically create a branch in the `weave_server_sdk` repo that mirrors the current branch of the `weave` repo.
> chore(weave): Update stainless generator to automatically create a branch in the `weave_server_sdk` repo that mirrors the current branch

- pyproject.toml
Reorganizes comments that have drifted over time
> chore(weave): Tidy pyproject.toml

- pyproject.toml
> chore(weave): Temporarily pin dspy to unblock ci

- tests/flow/test_weaveflow.py
- tests/trace/test_op_versioning.py
- weave/trace/api.py
- weave/trace/op.py
- weave/trace/weave_client.py
These old methods are not used anywhere
> chore(weave): Remove unused api methods

- weave/trace_server/model_providers/catalog_augment_hf.py
Updates our model catalog data update script to set the "isNew" flag for models that were launched less than 30 days ago instead of having this be a manual process.
Internal Slack reference:
https://weightsandbiases.slack.com/archives/C08RU04P36G/p1754421191418409?thread_ts=1754414069.539649&cid=C08RU04P36G
> chore(weave): compute isNew flag from date instead of setting it manually

- pyproject.toml
- weave/version.py
> chore(weave): Manually bump weave to 0.52.2-dev0

- weave/trace_server/workers/evaluate_model_worker/evaluate_model_worker.py
Adds metadata to the attributes so we know which evals were run by the worker
> chore(weave): Add a data marker for evaluation worker evaluations

- weave/trace_server/costs/cost_checkpoint.json
- weave/trace_server/costs/update_costs.py
Fixes https://wandb.atlassian.net/browse/WB-26160
Updates script to add costs
runs make update_costs
manually
> feat(weave): Add cw costs, to cost checkpoint

- weave/trace_server/model_providers/model_providers.json
Add DeepSeek v3.1 to Inference
> chore(weave): add deepseek v31 to model providers

- weave/trace_server/costs/cost_checkpoint.json
> chore(weave): add deepseek v31 to costs

- tests/conftest.py
- tests/trace/test_client_trace.py
- weave/trace/api.py
- weave/trace/context/weave_client_context.py
- weave/trace/refs.py
- weave/trace/weave_init.py
- weave/trace_server/isolated_client_executor.py
> chore(weave): Remove InitializedClient

- weave/telemetry/trace_sentry.py
- weave/trace_server_bindings/async_batch_processor.py
https://github.com/wandb/weave/issues/5228
We still have sentry on by default, but allow users to uninstall if they want
> chore(weave): Dont crash if sentry is not installed

- .github/workflows/test.yaml
- README.md
- codecov.yml
- noxfile.py
> chore(weave): Add codecov

- tests/trace/test_weave_init_auth.py
- weave/trace/api.py
- weave/trace/weave_init.py
https://wandb.atlassian.net/browse/WB-24532
Disallows empty string
> fix(weave): Don't allow project to be empty in init

- docs/docs/guides/tracking/redact-pii.md
- tests/utils/test_sanitize.py
- weave/utils/sanitize.py
https://wandb.atlassian.net/browse/WB-25127
https://wandb.atlassian.net/browse/WB-27218
Exposes a simple API for redacting keys
> feat(weave): Give user control over what keys to redact

- tests/scorers/test_call_apply_scorer.py
- tests/trace/test_scored_calls_query.py
- weave/evaluation/eval.py
- weave/evaluation/eval_imperative.py
- weave/flow/casting.py
- weave/flow/model.py
- weave/flow/scorer.py
- weave/integrations/autogen/autogen_sdk.py
- weave/integrations/dspy/dspy_utils.py
- weave/integrations/langchain_nvidia_ai_endpoints/langchain_nv_ai_endpoints.py
- weave/integrations/openai/openai_sdk.py
- weave/object/obj.py
- weave/trace/api.py
- weave/trace/call.py
- weave/trace/op.py
- weave/trace/op_caller.py
- weave/trace/op_protocol.py
- weave/trace/serialization/custom_objs.py
- weave/trace/serialization/op_type.py
- weave/trace/weave_client.py
This helps improve import times
> chore(weave): Move Op protocol into its own file

- weave/evaluation/eval_imperative.py
https://wandb.atlassian.net/browse/WB-27229
Adds a better error message that references the correct class name when passing an invalid name
> chore(weave): Add better error message for invalid class names

- weave/trace/op.py
- weave/type_handlers/Video/video.py
https://wandb.atlassian.net/browse/WB-27204
Saves about 1s of import time
> perf(weave): Significantly improve import time by deferring imports until needed

- weave/type_handlers/Video/video.py
Cleans up some func signatures
> chore(weave): Tidy video.py

- weave/type_handlers/Audio/audio.py
Improves `weave.init` performance
> perf(weave): Defer weave.Audio imports

- weave/trace_server/costs/cost_checkpoint.json
> chore(weave): Update costs 9/3

- weave/trace/api.py
- weave/trace/autopatch.py
https://wandb.atlassian.net/browse/WB-27477
Adds a note that `autopatch_settings` is deprecated and how to proceed instead
> chore(weave): Add autopatch deprecation note

- tests/trace/test_deepcopy.py
- weave/trace/box.py
Removes numpy from our boxing impl.  This doesn't seem to be very valuable, and improves import times
> perf(weave): Remove numpy from boxing impl

- pyproject.toml
- tests/flow/test_weaveflow.py
- tests/integrations/autogen/autogen_test.py
- tests/integrations/openai/test_openai_sdk.py
- tests/trace/concurrent/test_futures.py
- tests/trace/test_dictifiable.py
- tests/trace/test_grid.py
- tests/trace/test_serialize.py
- tests/trace/test_vals.py
- tests/trace_server/isolated_client_executor/cross_process_trace_server.py
- tests/trace_server/isolated_client_executor/test_cross_process_trace_server.py
- tests/trace_server/isolated_client_executor/test_isolated_client_executor.py
- weave/initialization/moviepy_video_thread_safety.py
- weave/initialization/pil_image_thread_safety.py
- weave/integrations/patcher.py
- weave/trace/context/call_context.py
- weave/trace/ref_util.py
- weave/trace/vals.py
- weave/trace_server/errors.py
- weave/trace_server/orm.py
- weave/utils/paginated_iterator.py
Adds the B lint rule.  Some B rules were already added.  This adds the full set of B rules
https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
> chore(weave): Add B lint rule

- weave/trace_server/costs/cost_checkpoint.json
- weave/trace_server/model_providers/model_providers.json
ran 
make update_model_providers
make update_costs
manually
> chore(weave): Add claude sonnet 4.5, to provider backend and costs
