weave-js/package.json
weave-js/src/components/PagePanelComponents/Home/Browse2.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/StyledDataGrid.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/FeedbackGridInner.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/grid/pin.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallTraceView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/DataTableView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableColumns.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/tabularListViews/columnBuilder.tsx
weave-js/yarn.lock

Several internal and external customers have been affected by this issue where one or more cells in the objectviewer get into a resizing loop with scrollbars appearing and disappearing.
https://wandb.atlassian.net/browse/WB-21047
From what I could determine, it appears to be a bug in Material UI data grid when you use auto with getRowHeight rather than our code. While digging into that I discovered that the grid code has changed a lot between v6 and v7. On a hunch, I tried upgrading to 7 to see if it resolves the issue and I think so. This PR fixes the other things necessary to upgrade the library.
https://mui.com/x/migration/migration-data-grid-v6/#start-using-the-new-release
https://mui.com/x/migration/migration-data-grid-v6/#removed-props …

chore: upgrade Material grid to v7.18.0

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimplePageLayout.tsx

Page header styling update, reduce font size, remove bottom border.
Internal Notion: https://www.notion.so/wandbai/Traces-table-d0abd588c49e4a77a213db27af717b4f?pvs=4#10ae2f5c7ef38072a561ea59775d964c
Before:
After:

chore: update page header styling

---

docs/docusaurus.config.ts
docs/src/components/DesktopImage/index.tsx

We were zooming on everything! Even buttons and such. This scopes the zoom to just the images in the special viewer

chore: Fix image zoom in docs

---

weave/tests/trace/test_weave_client.py
weave/trace_server/clickhouse_trace_server_batched.py

Digest filtering must occur outside of both count and dedupe subqueries. 
When specifying the digest, we can't use that to filter out the other objects with the same ID but different digests in the middle level subquery. When reading to a specific digest, we don't care about any other objects, which is why correctness checks pass for the existing query. **However**, we calculate the version index in this step (not obvious from looking at the query) so we actually need to grab ALL the objects even if we specify just a single one. 
This reduces the performance impact of the[ original pr](https://github.com/wandb/weave/pull/2412), but isn't bugged.

fix: version index on obj/read bug

---

weave-js/src/components/PagePanelComponents/Home/Browse2/CollapseGroupHeader.tsx
weave-js/src/components/PagePanelComponents/Home/Browse2/ExpandHeader.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/StyledDataGrid.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/tabularListViews/columnBuilder.tsx

Internal Notion: https://www.notion.so/wandbai/Traces-table-d0abd588c49e4a77a213db27af717b4f?pvs=4#10ae2f5c7ef380499df8df28dabbf12f
Before:
After:

chore: remove semibold styling from table headers

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx

Internal Notion: https://www.notion.so/wandbai/Traces-table-d0abd588c49e4a77a213db27af717b4f?pvs=4#10ae2f5c7ef38061b3fbc12015136df4
Before:
After:

chore: use smaller checkbox in call grid

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableColumns.tsx

Internal Notion: https://www.notion.so/wandbai/Traces-table-d0abd588c49e4a77a213db27af717b4f?pvs=4#10ae2f5c7ef380678bf4df103783509a
Before:
After:

chore: make trace links teal colored

---

weave/tests/trace/test_client_trace.py
weave/tests/trace/test_weave_client.py
weave/tests/trace/util.py

Adds test for fetching an object with a specific version, like: `obj = weave.ref("weave:///griffin/proj/object/obj:v2")`
This does not work in sqlite....

test: add test for string version object read

---

weave-js/src/common/util/links.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/FeedbackGrid.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Empty.tsx

Internal Notion: https://www.notion.so/wandbai/Empty-state-for-Feedback-tab-10ae2f5c7ef380f9af66d14cabd23a19?pvs=4
Before:
After:

chore: update empty feedback styling

---

weave/trace/op.py
weave/trace/op_extensions/accumulator.py

While debugging a different issue with @vanpelt, I noticed something alarming: We were printing an error while iterating through stream data.
This lead to an investigation and this PR. This PR:
1. Critically: we re-raise in our iterator! `if isinstance(e, (StopAsyncIteration, StopIteration)):`. In current release, we actually capture this error, but very critically, the `on_yield` contract is to raise an exception when it is finished with the accumulation! This was causing breakages as noted below
2. Adds one more try/except to the entry-point of an op to ensure we handle that gracefully.
3. Improves some logging text
Note: When doing async, the data is still logged, but non async crashes!!
Further note: this specific case was not caught in tests since we auto raise in tests to be more …

fix: Stop printing errors with OpenAI Stream + error handling

---

weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimplePageLayout.tsx

Internal notion: https://www.notion.so/wandbai/Update-drawer-headers-10ae2f5c7ef380b78ec7de4d47dc105b?pvs=4#10ae2f5c7ef3805cb76bc52b3780f6d5
Before:
After:

chore: reduce header height and font size

---

weave-js/src/components/PagePanelComponents/Home/Browse2/CollapseHeader.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/tabularListViews/columnBuilder.tsx

Component was renamed from `CollapseGroupHeader` to `CollapseHeader` in https://github.com/wandb/weave/pull/1692, update props and filename to match.

refactor: rename file to match component name

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimplePageLayout.tsx

Internal Notion: https://www.notion.so/wandbai/Update-drawer-headers-10ae2f5c7ef380b78ec7de4d47dc105b?pvs=4#10ae2f5c7ef380a78bb5d5b2739906ab
This only updates object header, not call header.
Before:
After:

chore: add icon to object header instead of chip

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx

First cut at this was too conservative, we also want to restrict the query to metadata only when the `objectId` is set. This query is used twice, once to get the list of objects and another time once we have drilled down. We want `metadataOnly` the first time, and then values the second. 
For a monster project: 
Prod:
This branch:
While maintaining the correct functionality:

chore: objects query conditionally use metadataOnly

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallTraceView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SplitPanel.tsx

Internal Notion: https://www.notion.so/wandbai/Trace-drawer-specific-items-43c3106f7d2848758d02f89cee2b3540?pvs=4#10ae2f5c7ef3804a99d3e2d32d1ecb12
Things improved:
* background color 
* hide border artifacts at top and bottom
* Divider now positioned with absolute positioning, allowing us to extend left and main panels underneath border
Before:
After:

chore: trace tree styling

---

weave-js/src/components/Form/AutoComplete.tsx

- Fixes #NNNN
Adds minWidth param and ref to the autocomplete component so we can measure the full width of the text input for use in https://github.com/wandb/core/pull/24247.

chore(weave): add width to autocomplete

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallOverview.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/EditableCallName.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimplePageLayout.tsx

Internal Notion: https://www.notion.so/wandbai/Trace-drawer-specific-items-43c3106f7d2848758d02f89cee2b3540?pvs=4#10ae2f5c7ef380c19132fe89cc3ed3ea
Reduce height and font sizes, remove border, move status to front.
Before:
After:

chore: update call details header styling

---

weave-js/src/components/PagePanelComponents/Home/Browse3/filters/common.ts

Some field IDs changed in https://github.com/wandb/weave/pull/2339 but the filters UI was still referring to the previous values, causing them to not get filtered out as they should be.

fix: some unfilterable cols showing up in filters

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTableButtons.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClientTypes.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts

- Fixes [WB-21009](https://wandb.atlassian.net/browse/WB-21009)
Adds the option to include feedback made on traces during trace export. 
This branch:
[WB-21009]: https://wandb.atlassian.net/browse/WB-21009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: optionally include feedback in calls export

---

weave-js/src/components/PagePanelComponents/Home/Browse2/CellValueString.tsx

Internal Notion: https://www.notion.so/wandbai/Popovers-style-10ae2f5c7ef380f48cc0c438a8212732?pvs=4
Some changes like grab handle still to come.
Before:
After:

chore: update string popup styling

---

weave/integrations/mistral/v0/mistral_test.py
weave/integrations/mistral/v1/mistral_test.py

Cleans up imports and removes the use of lower level `tsi` in tests

chore(weave): Cleanup mistral integration tests

---

weave/trace/env.py

Handles the case where `env_api_key` or `netrc_api_key` is `None`

chore(weave): Fix api key check

---

weave/tests/trace/test_client_trace.py
weave/trace_server/clickhouse_trace_server_batched.py

Simplify dynamic batch size calculation in calls stream to be `10` then `100` then a max of `500`

fix: `include_feedback` breaks when > 10 results AND no expand fields listed

---

.github/workflows/check-which-tests-to-run.yaml
.github/workflows/notify-wandb-core.yaml
.github/workflows/test.yaml

1. Conditionally runs tests based on which dirs have changed.
2. Updates the notify job payload to also include a signal for whether or not core integration tests should be run.  Core is always notified and the commit is always added, but tests are conditionally run based on the payload
This PR cannot be fully tested e2e until both sides are merged into master because `repository_dispatch` only applies on the master branch (of core), but I have tested the individual pieces and it seems to work
Companion to: https://github.com/wandb/core/pull/24362

chore(weave): Add conditional ci

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/ToolCalls.tsx

Internal Slack: https://weightsandbiases.slack.com/archives/C01T8BLDHKP/p1727885436333269
Wrap text and add syntax highlighting, use standard code font.
Before:
After:

fix: tool call text overflow

---

weave-js/src/react.tsx

This PR adds explicit sentry handling for a throw that is generatic about 25% of the "new issues" being reported in the user-interface sentry project today. The exception is now captured explicitly and given a static fingerprint so it does not register as new in sentry due to differences in the stack trace.

chore(dev): static fingerprint for error with useNodeValue

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallDetails.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableColumns.tsx

https://wandb.atlassian.net/browse/WB-21218
Also sorts attributes after inputs and output in the column management modal.
Before:
After:

fix: select columns for child call table preview

---

weave-js/src/components/Panel2/PanelTable.styles.ts
weave-js/src/components/Panel2/PanelTable/ColumnHeader.tsx
weave-js/src/components/Panel2/PanelTable/PanelTable.tsx
weave-js/src/components/Panel2/PanelTable/util.ts
weave-js/src/components/Panel2/WeaveFormatContext.tsx

**Internal JIRA:** [WB-17238](https://wandb.atlassian.net/browse/WB-17238)
The JIRA reports a difficulty in difficulty in reading Tables because column header cells are left justified while numerical value cells are right justified.
This PR fixes that by **using the same text alignment for the column header cell as the value cell**. This solution differs from the proposed solution on the JIRA (center all header cells and cells) because typically numerical columns are right justified for visual clarity. It's easier to interpret the magnitude of cells when numerical values have the same level of precision. Non-numerical column header cells are defaulted to `center` text alignment.
Previous PR that introduced the issue: https://github.com/wandb/weave/pull/875
I leveraged the new …

fix(weave): align tables column header cell text based on panel type

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/DataTableView.tsx

Missed necessary colspec adjustment in https://github.com/wandb/weave/pull/2455
Before:
After:

fix: ref alignment in grid cell

---

weave/trace/op.py
weave/trace/weave_client.py

Removes old decorator overloads and makes a much nicer op decorator!

chore(weave): Remove old decorator overloads

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Links.tsx

Internal Notion: https://www.notion.so/wandbai/Traces-table-d0abd588c49e4a77a213db27af717b4f?pvs=4#10ae2f5c7ef380678bf4df103783509a
Makes Op and Obj links in their respective grids teal. This makes them consistent with Calls grid.
Before:
After:

chore: make op and obj links teal in grid first col

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx

Fixes https://wandb.atlassian.net/browse/WB-21208
https://github.com/wandb/weave/pull/2076 added display of object properties as columns in the grid when viewing all versions. Unfortunately, it is possible that a property name conflicts with the field IDs that are used for the non-dynamic columns, and this was happening for the first column, "object" in this case.
There's certainly a more robust fix possible here, did a quick one in the interests of time.
In the before image, note how the first column is getting overwritten by the "object" column definition from the sixth column due to the field ID conflict. This also generates a bunch of developer console errors.
Before:
After:

fix: broken obj grid links

---

weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterBar.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTableButtons.tsx

moves the refresh button and changes it to outline
adds some styling to op filter
adds some styling to filter button
https://www.notion.so/wandbai/Traces-table-d0abd588c49e4a77a213db27af717b4f?pvs=4#506f99cfe16644898101ff903a3dabf4

chore(weave): move refresh button, minor style to op filter, and filter

---

weave/trace/op.py
weave/trace/weave_client.py

Adds the ability to set a "finish" handler on an Op. The intended use is as an extension point for integrations. For example, I intend to use this functionality in the Gemini integration to copy information about token usage from the Gemini call response object (whose structure only the Gemini integration should have to know anything about) into our standard token usage format in the call's summary dictionary.

feat: add finish handler for ops

---

weave-js/src/common/util/sentry.ts

Introduces a library `sentry.ts` to `weave-js/src/common/util`. Includes functions for capturing issues in sentry manually without having them duplicated when an error boundary is hit or a `console.error` is issued.

chore(dev): add sentry helpers for the core app to common/util

---

docs/docs/guides/core-types/evaluations.md
docs/docs/guides/tracking/tracing.mdx
tests/trace/test_weave_client.py
weave/trace/op.py

Adds `__weave` dictionary when calling ops that can be used to set settings (to avoid name collisions), in this case `display_name`. Also shows how this can be used to name evals.

feat: Add display_name to ops

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueViewString.tsx

Fixes https://wandb.atlassian.net/browse/WB-21455
The markdown renderer can cause the page to freeze for several seconds on long content, turning off autoselection of it as a quick fix.

fix: don't autoselect markdown renderer

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallSummary.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CostTable.tsx

Partial update of call summary tab, incremental progress towards internal Figma:
https://www.notion.so/wandbai/Trace-drawer-items-43c3106f7d2848758d02f89cee2b3540?pvs=4#10ae2f5c7ef3808e8e5de7424dfa0584
Moved usage data to top, adjusted padding. I also right aligned the numeric column headers to match column data.
Before:
After:

chore: move Usage table in Call summary

---

noxfile.py

Notdiamond doesn't support python 3.13 yet because `tokenizers` doesn't: 
```
Using Python 3.13.0 environment at .nox/tests-3-13-shard-notdiamond
Resolved 103 packages in 1.76s
error: Failed to prepare distributions
Caused by: Failed to fetch wheel: tokenizers==0.20.1
Caused by: Build backend failed to build wheel through `build_wheel` (exit status: 1)
```
[link to failing test](https://github.com/wandb/weave/actions/runs/11278758434/job/31368473846?pr=2665)

chore: skip notdiamond in py313

---

weave-js/src/react.tsx

Dedupes the recording of the `useNodeValue` error in sentry. Uses a helper to throw the error with a suffix attached that causes the sentry capture at the error boundary to be ignored since we have already captured the error.

chore(dev): fix sentry dedupe of useNodevalue error

---

docs/docs/guides/tracking/tracing.mdx
docs/docs/reference/gen_notebooks/01-intro_notebook.md
docs/docs/reference/gen_notebooks/chain_of_density.md
docs/docs/reference/gen_notebooks/custom_model_cost.md
docs/docs/reference/gen_notebooks/dspy_prompt_optimization.md
docs/docs/reference/gen_notebooks/feedback_prod.md
docs/docs/reference/gen_notebooks/import_from_csv.md
docs/docs/reference/gen_notebooks/online_monitoring.md
docs/docs/reference/gen_notebooks/pii.md
docs/intro_notebook.ipynb
docs/notebooks/chain_of_density.ipynb
docs/notebooks/custom_model_cost.ipynb
docs/notebooks/dspy_prompt_optimization.ipynb
docs/notebooks/feedback_prod.ipynb
docs/notebooks/import_from_csv.ipynb
docs/notebooks/online_monitoring.ipynb
docs/notebooks/pii.ipynb
weave_query/examples/experimental/prompts_dev/generate_synth_mon_board.ipynb
weave_query/examples/experimental/prompts_dev/synthetic_openai_data.ipynb
weave_query/examples/prompts/llm_monitoring/openai_client_quickstart.ipynb
weave_query/examples/prompts/llm_monitoring/openai_proxy_quickstart.ipynb
weave_query/examples/prompts/trace_debugging/dev/synthetic_trace_data.ipynb
weave_query/examples/prompts/trace_debugging/trace_quickstart_langchain.ipynb

A few cosmetic things in docs:
1. Remove the `W&B` logo in notebooks since it is broken in Safari
2. Adjust the discussion in `tracing.md` to highlight the non-`.call` based calling.
3. Adjust numbering in tracing.md

chore: Cleanup some docs

---

tests/trace/test_evaluations.py
weave/trace/vals.py

I introduced a bug: https://github.com/wandb/weave/pull/2434 which resulted in the `predict_and_score` (and child calls) having an incorrect input refs getting assigned to the input. The result is that the inputs are effectively all the same (however the outputs are different). This results in a number of odd effects since the system thinks all the predictions are against the same row:
So, what was the issue here? Well a classic case of mutating a closure variable before executing the function! duh!
For more details, consider this basic example:
```python
for ndx, row in enumerate(self._prefetched_rows):
next_id_future = wc.future_executor.defer(    # <--- this `defer` schedules the function to be ran in a new thread.
lambda: cached_table_ref.row_digests[ndx]   # <---- this `ndx` is …
```

fix: Evaluations no longer associate incorrect inputs with predictions

---

docs/scripts/generate_notebooks.py

Previously, generated image paths were at the wrong because of a relative path issue.
This fixes the links

chore(weave): Fix image docgen

---

tests/trace/test_op_coroutines.py
tests/trace/test_op_decorator_behaviour.py
weave/trace/op.py
weave/trace/weave_client.py

I am working on another feature and needed to use the `Op.call` pattern. I realized that the typing for this was not exactly correct AND we did not use the same code as the wrapper logic.
So, this PR:
1. Adds a bunch of tests to ensure we do the correct thing for coroutines
2. Shares as much code as possible between `call`, `async wrapper` and `wrapper`
3. Improves typing in various locations

chore: Test all coroutine patterns and refactor op call

---

weave-js/src/components/Panel2/PanelTable/util.ts

I noticed one of my tables didn't have correct formatting on numerical columns. Didn't realize there were additional numerical types. This PR adds a type check for `float` and `int` to set the column formatting.
**Before**
**After**
Visually

fix(ui): Add additional numerical types for table formatting

---

weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/context.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx

Use the correct routerContext constructor for URL construction when selecting metrics (and evaluationIDs)
👁️ 👁️

fix(ui): use correct router context for eval compare URL construction

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ExampleCompareSection/exampleCompareSectionUtil.ts

Fix for issue raised in [this](https://weightsandbiases.slack.com/archives/C01T8BLDHKP/p1728947773955989) thread, eval comparison crashes when drilling down into examples.
This pr:
- don't filter down example composite data by selected metrics, this section ignores selected metrics. 
clicked around

chore(ui): example section must have all the metrics -- fix

---

weave-js/src/components/Panel2/AudioViewer.tsx

- Fixes [WB-10297](https://wandb.atlassian.net/browse/WB-10297)
- Fixes [#3875](https://github.com/wandb/wandb/issues/3875)
This PR addresses an issue where long captions in the AudioViewer component could not be fully read when the caption did overflow. The fix ensures that the horizontal scrollbar only appears when the caption content overflows. The solution replaces overflow: 'hidden' with overflowX: 'auto' and overflowY: 'hidden', preventing unnecessary scrollbars when the content fits within the container.
- Locally tested the AudioViewer component (with `governor start invoker_fe_prod.ini`) in different scenarios where the caption both exceeds and fits within the container.
- Verified that the horizontal scrollbar only appears when necessary (i.e., when the caption content …

fix(ui): add caption overflow scrollbar in AudioViewer component

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueView.tsx

Design guidelines are to use sentence case.
Before:
After:

chore(ui): use sentence case

---

tests/integrations/dspy/dspy_test.py
tests/trace/test_client_trace.py
tests/trace/test_evaluations.py
tests/trace/test_serialize.py
tests/trace/test_weave_client.py
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueView.tsx
weave/trace/serialize.py

Instead of giving up and resorting to `repr` we try to recursively convert objects into a dict.
See internal doc https://www.notion.so/wandbai/Better-Rendering-of-Gemini-Calls-114e2f5c7ef38037953df7b7a9e5a52b?pvs=4 for more details. This will allow us to build a chat view for Gemini and solves other problems with not logging important data in the trace.
Before:
After:

feat(weave): dictify unknown class instances

---

weave-js/src/core/ops/primitives/number.test.ts
weave-js/src/core/ops/primitives/number.ts
weave_query/weave_query/ops_primitives/number.py

[Internal Jira [WB-19303]](https://wandb.atlassian.net/browse/WB-19303)
This PR adds a docstring stating the expected time unit for the to_timestamp op.
[WB-19303]: https://wandb.atlassian.net/browse/WB-19303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(ui): Adjust weave0 timestamp resolver and documentation for parity

---

.github/workflows/release.yaml

Disable the doc build during SDK publish added in https://github.com/wandb/weave/pull/2682 - it is causing publish to fail. Doing this in parallel with another approach to fix in https://github.com/wandb/weave/pull/2722

chore(weave): disable docs build in release

---

weave-js/src/components/PagePanelComponents/Home/Browse3/typeViews/Audio/AudioPlayer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/typeViews/CustomWeaveTypeDispatcher.tsx
weave-js/src/components/Panel2/AudioViewer.tsx

https://wandb.atlassian.net/browse/WB-21558
Very simple UI for playing audio. There are three different states the new `AudioPlayer` component can be in: 
- controls: has a play/pause button and the timestamps
- slider: show play/pause, the time, a download link, and a scrubbable waveform visualization
- mini: show play/pause
The width of the component determines what state the viewer will be in. Because columns are restricted to 150px minimum in the calls table there doesn't appear to be any place where we use the mini viewer. 
TODO:
- better support for expanding the viewer. When its small there should be some indication that it can get larger.

chore(ui): audio player for logged wav objects

---

dev_docs/RELEASE.md

Minor dev doc update on release process.

chore(weave): minor release note update

---

weave_query/tests/test_wb.py
weave_query/weave_query/artifact_wandb.py
weave_query/weave_query/ops_domain/wb_util.py

JIRA: [WB-21299](https://wandb.atlassian.net/browse/WB-21299)
When the artifact URI does not have a version, but the path has a colon (`:`), our current implementation to find the path will mistakenly treat part of it as the version string. Instead of splitting on the version delimiter (`:`) and then trying to find the path, we can reverse the order and split on the path delimiter (`/`) first, allowing paths to include `:`.
The PR also updates the tests to include the following cases:
* Standard artifact path: `<name>:<version>/<path>`
* No version and path does not have `:`
* With version and path has `:`
* No version and path has `:` (this is the case we were previously erroring on)
* Added unit tests 
* Verified that `test_zlib_playback` now passes
[WB-21299]: …

fix(weave_query): Handle paths with colons when escaping artifact path

---

weave-js/src/components/Panel2/AudioViewer.tsx

- Fixes [WB-10297](https://wandb.atlassian.net/browse/WB-10297)
- Fixes https://github.com/wandb/wandb/issues/3875
This follow-up PR further refines the styling of audio captions in the AudioViewer component. The previous fix #2689  addressed horizontal scroll overflow but did not fully resolve readability issues with long captions.
In this update:
- A vertical scrollbar has been introduced instead of a horizontal one for better user experience
- Captions are now split across up to 3 lines to prevent clipping and enhance readability
- Captions are left-aligned for consistency and improved visual structure
- Locally tested the AudioViewer component with various long captions (with `governor start invoker_fe_prod.ini`)
before:
after:
[WB-10297]: …

fix(ui): improve styles of audio caption for better readability

---

weave/flow/chat_util.py

Causes: 
```bash
File "/Users/griffin/.pyenv/versions/weave-python-service/bin/programmer", line 8, in <module>
sys.exit(main())
File "/Users/griffin/.pyenv/versions/3.10.8/envs/weave-python-service/lib/python3.10/site-packages/programmer/programmer.py", line 199, in main
programmer()
File "/Users/griffin/.pyenv/versions/3.10.8/envs/weave-python-service/lib/python3.10/site-packages/programmer/programmer.py", line 194, in programmer
session(agent, state)
File "/Users/griffin/Desktop/core/services/weave-python/weave-public/weave/trace/op.py", line 575, in wrapper
res, _ = _do_call(
File "/Users/griffin/Desktop/core/services/weave-python/weave-public/weave/trace/op.py", line 393, in _do_call
execute_result = _execute_call(
File …
```

chore(weave): ChatCompletion not imported

---

weave-js/package.json
weave-js/src/common/util/markdown.ts
weave-js/yarn.lock

`unist-util-visit@2.x` will sometimes resolve to using the 3.x version of `unist-util-visit-parents`, which is incompatible with it. Rather than figure out how to get it to resolve the right old version, creep forward with the dependency a little bit, which resolves the problem.

fix(ui): Bump version of `visit` to resolve import error

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallSummary.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimplePageLayout.tsx

- Fixes #NNNN
- add bytes usage (size of input message + size of output) to `summary` tab in the Call page
- add bytes usage (size of data.result[0]) to `object` page 
"Bytes stored" in summary tab:
https://github.com/user-attachments/assets/247702dc-1a6c-44cd-be57-1aec300ae90b
"Bytes stored" in object page:
https://github.com/user-attachments/assets/a9429bd4-c445-42f6-809a-6ac1d80e500f

feat(weave): add byte usage to summary tab and object page

---

docs/docs/guides/core-types/media.md

`PIL.Image` -> `PIL.Image.Image`

chore(weave): media docs copy change

---

weave-js/src/components/RadixTooltip/index.tsx

Updates the tooltip style to inherit the cursor of the element as opposed to the default cursor. This helps with tooltips that are on clickable targets (ie the Workspace section headers)

chore(ui): updating default style for radix tooltip

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx

@harukatab noticed that if you click the empty space at the left bottom of the calls table and click arrow key up and down you get a focus outline that doesn't look very good.
Before:

chore(ui): don't show focus outline on calls grid

---

weave-js/src/common/components/WandbLoader.test.tsx
weave-js/src/common/components/WandbLoader.tsx
weave-js/src/components/Loaders/WaveLoader.tsx
weave-js/tailwind.config.cjs

Preliminary work for WB-21477
Extends the tracked loader to use a new loading animation. Extends the tailwind config to support the animation.

chore(ui): Creating a wave loader to start migrating app loaders

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/context.tsx

This basically reverts the cleanup from https://github.com/wandb/weave/pull/2132. I believe that the limit issue should've been fixed in https://github.com/wandb/weave/pull/2420, so hopefully we should be able to check if a project has weave data more quickly.
This should have no effect since it's unused, will follow up in core with a change similar to this https://github.com/wandb/core/pull/20661/commits/3ca824472beff5023cd0c4926e1f95d9cbc63f1c and see how the performance is now.

chore(weave): Add back hook to check for weave data

---

weave/trace/refs.py

We don't need to check `if gc is None:` here - it has to be or we'd have returned right above this at line 156

chore(weave): remove unnecessary conditional

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/Exceptions.tsx

- Added a copy button to the exception which copies the traceback from a call to the clipboard.
- Helps the user easily take the problem and look it up elsewhere > like via an LLM.

chore(ui): Added copy button for exception trace

---

weave/trace/refs.py

Fixes https://wandb.atlassian.net/browse/WB-20811 
This currently works and assumes latest version:
```
weave.init("entity/project")
weave.ref("my_obj").get()
```
However, if you specify:
```
weave.ref("weave:///entity/project/object/my_obj").get()
```
It will raise a `ValueError: not enough values to unpack (expected 2, got 1)`.
This fixes it to assume latest.

chore(weave): assume latest version if no digest/alias specified

---

weave-js/src/components/Callout/Callout.tsx

add night-aware class on Callouts so they look right in dark mode
before/after:
https://github.com/user-attachments/assets/272699b6-7753-4f64-acb1-847aa29c395e

style(ui): Fix night colors for Callout

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimplePageLayout.tsx

[WB-21703](https://wandb.atlassian.net/browse/WB-21703)
Always default to the leftmost tab, unless the user has explicitly selected a tab. In practice, this now defaults to the chat view even if the previous call you were looking at did not have a chat tab. If you only want to look at the call details, you can select it and subsequent navigations should respect that.
Prod:
Branch:
👀 
[WB-21703]: https://wandb.atlassian.net/browse/WB-21703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(weave): smart tab defaults w/ chat in call peek drawer

---

tests/trace/test_leaderboard.py
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/generatedBaseObjectClasses.zod.ts
weave/flow/leaderboard.py
weave/trace/api.py
weave/trace/urls.py
weave/trace_server/interface/base_object_classes/base_object_registry.py
weave/trace_server/interface/base_object_classes/generated/generated_base_object_class_schemas.json
weave/trace_server/interface/base_object_classes/leaderboard.py

Extracts the non-ui (client & backend) from https://github.com/wandb/weave/pull/2634 for safer decoupling and deployment

feat(weave): Client & Backend support for Leaderboards

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx

Tiny usability improvement, make the label on this switch clickable.
Other changes are lint-fix.

chore(ui): make metrics switch label clickable

---

weave/trace_server/clickhouse_trace_server_migrator.py

- [WB-21739](https://wandb.atlassian.net/browse/WB-21739)
Prevent automatic down migration (but still allow manual down migrations when specifying a target version)
Manual tested for now
[WB-21739]: https://wandb.atlassian.net/browse/WB-21739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(weave): do not automatically apply down migrations

---

tests/integrations/google_ai_studio/google_ai_studio_test.py
tests/trace/test_client_trace.py
tests/trace/test_serialize.py
tests/trace/test_weave_client.py
weave/integrations/google_ai_studio/google_ai_studio_sdk.py
weave/trace/sanitize.py
weave/trace/serialize.py
weave/trace/weave_client.py

Internal Jira: https://wandb.atlassian.net/browse/WB-21699
Adds sanitization to the dictify method, then turns dictify back on for call inputs and outputs only. (An explicit flag needs to be passed for `to_json` to dictify, so code saving won't use it.)
For later we should also take a closer look at why code saving is using to_json - it doesn't seem right to me as you're not going to get runnable code from that and also I think the memory address that is part of the default repr is going to cause your op versions to increase unexpectedly.
---
Update: @tssweeney pointed out that dictify'ing the output of dspy made it unusable when previously it was OK (due to the custom repr). Given the purpose of a repr, it seemed to me that if a custom one was made we should by default use that instead …

feat(weave): enable dictify of inputs and outputs

---

tests/integrations/litellm/client_completions_create_test.py
tests/integrations/litellm/litellm_test.py

A minor version must have changed the response format - just adding some null values coming out.

chore(weave): Fix LiteLLM Tests

---

tests/integrations/google_ai_studio/google_ai_studio_test.py

There is a retry but it seems to retry too fast which causes flake

chore(weave): Add delay to Google live test retries

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx

chore(ui): fix typo in variable name

---

weave-js/src/components/Panel2/PanelTable/tableState.ts

JIRA: [WB-16067](https://wandb.atlassian.net/browse/WB-16067)
- Quick fix to prevent table crashes during ungrouping when there exists sorting is enabled on a column with aggregated data
- Disables sorting before the ungroup and re-enables it after the ungrouping. Note that sorting isn't allowed on the aggregated column after ungrouping anyway so no existing functionality is broken.
Old behaviour:
https://github.com/user-attachments/assets/a5a04f4f-8b91-4efc-8260-801e1b71f4c8
New behaviour:
https://github.com/user-attachments/assets/8f956a5b-b703-46a5-aadc-8d47ca3715fa
Existing behaviour when no sorting is applied (the fix aligns with the existing behaviour):
https://github.com/user-attachments/assets/1e6d5424-f469-4e0c-a0c3-a7c98e28c5be
[WB-16067]: …

fix(ui): Sorted aggregated columns no longer crash tables during ungrouping

---

pyproject.toml
weave/scorers/llm_utils.py

Implements: https://docs.astral.sh/ruff/rules/non-pep604-annotation/

chore(weave): ruff: enable UP007

---

pyproject.toml
weave/scorers/llm_utils.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/sqlite_trace_server.py
weave/trace_server_bindings/remote_http_trace_server.py

Implements: https://docs.astral.sh/ruff/rules/yield-in-for-loop/

chore(weave): ruff: enable UP028

---

pyproject.toml
tests/trace_server/test_validation.py

Implements: https://docs.astral.sh/ruff/rules/unnecessary-literal-within-tuple-call/

chore(weave): ruff: enable C409

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/MessagePanelPart.tsx

markdown has been causing crashes or slow down in chat views with a lot of messages, disable for now
internal notion
https://www.notion.so/wandbai/Minimal-Weave-roadmap-item-specs-11fe2f5c7ef38004b8f3c413b536823e?pvs=4#11fe2f5c7ef3802f86e4ed254cd3250c

chore(weave): disable markdown in chat view

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx

[WB-21591](https://wandb.atlassian.net/browse/WB-21591)
This PR refetches the calls query when filters have changed. This normally happens automatically, except in the case when the `effectiveFilter` changes without any actual change to the backend query. This frequently occurs during interactions in the UI when navigating back to an already loaded table; the filter changes `frozen` status but none of the actual filter variables. 
👀 
[WB-21591]: https://wandb.atlassian.net/browse/WB-21591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ui): refetch when changing filter state from frozen -> not frozen

---

tests/trace/test_deepcopy.py
weave/trace/box.py

Follow-up to:
https://github.com/wandb/weave/pull/2868
Adds `__deepcopy__` methods to boxed types which resolves issues when using `Model.predict` with `litellm`
Unit tests and manual testing of the e2e LiteLLM evaluation example

fix(weave): Add deepcopy methods for boxed types

---

tests/trace/test_evaluations.py
weave/flow/eval.py
weave/trace/box.py
weave/trace/weave_client.py

Correctly reports runnable refs when the scorer is an object.
Now that I am getting into the nitty-gritty of getting scorers to work, i realized we are not reporting the Evaluation scorer feedback ref correctly when the scorer is an object. Today, we are reporting the Scorer.score fn, not the parent Scorer object. This fixes and tests for that

chore(weave): Class-based scorer runnable ref fix

---

weave-js/src/components/PagePanelComponents/Home/Browse2/Browse2OpDefCode.tsx
weave-js/src/util/sanitizeSecrets.test.ts
weave-js/src/util/sanitizeSecrets.ts

https://wandb.atlassian.net/browse/WB-21683
After:

chore(ui): check Op code for literal credentials

---

weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/index.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/llmMaxTokens.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/types.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/usePlaygroundState.ts

Adds a route /playground (you can go there explicitly but not in sidebar)
sets up the state for the playground
if theres a call-id in the url, fetch the call and load the call settings into state

chore(weave): scaffolding for playground page

---

weave_query/weave_query/wandb_interface/wandb_stream_table.py

Fixes the error:
`ImportError: cannot import name 'get_printer' from 'wandb.sdk.lib.printer' `

fix(weave_query): Remove unused import blocking server startup

---

tests/integrations/litellm/test_actions_lifecycle_llm_judge.py
tests/trace/test_actions_lifecycle.py
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/generatedBaseObjectClasses.zod.ts
weave/trace_server/actions_worker/actions/contains_words.py
weave/trace_server/actions_worker/actions/llm_judge.py
weave/trace_server/actions_worker/dispatcher.py
weave/trace_server/interface/base_object_classes/actions.py
weave/trace_server/interface/base_object_classes/base_object_registry.py
weave/trace_server/interface/base_object_classes/generated/generated_base_object_class_schemas.json

This is our only chance to change this (before it ships). Let's get it right

chore(weave): Rename ActionDefintion to ActionSpec to match naming patterns

---

tests/trace/test_custom_objs.py
weave/trace/custom_objs.py

https://wandb.atlassian.net/browse/WB-21517
- Prefer using the SDK's local registered deserializer instead of the saved deserializer for known types like Images
Unit tests and manual testing

fix(weave): Use sdk-local deserializer instead of saved deserializer for known types like Images

---

weave_query/tests/test_basic_ops.py
weave_query/weave_query/ops_primitives/string.py

- Handles [WB-16442](https://wandb.atlassian.net/browse/WB-16442)
- Creates a new string op that will parse numbers with a thousands separator.
Added unit tests
[WB-16442]: https://wandb.atlassian.net/browse/WB-16442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(weave_query): Add string op to parse number with thousands and decimal separators

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx

after
before
from this old thread
https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1728600051481949?thread_ts=1728599689.095469&cid=C03BSTEBD7F

style(weave): move the show more buttons to the left

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClient.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts

Automatically requery the object versions query when an object is created. 

chore(ui): re-query on object creation

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/EmptyContent.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/TypeVersionCategoryChip.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/constants.ts

Adds the `ActionSpec` to the known types and creates empty state. This is part of the LLM Judge project

chore(weave): Add `ActionSpec` to known types

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts

Hack fix for this sentry event: https://weights-biases.sentry.io/issues/6062366781/?project=1201719&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&statsPeriod=1h&stream_index=2
The only way I can get a non `[]` res.objs is when viewing a project that I don't have access to...

chore(ui): objs query handles null case (??)

---

tests/trace_server/test_calls_query_builder.py
weave/trace_server/token_costs.py

adds a where clause to the cost query, costs from other projects would be used if there existed no cost within the project
filters out costs that are not in the project, null, or default
https://wandb.atlassian.net/browse/WB-21847
https://wandb.atlassian.net/browse/WB-21851

fix(weave): add where clause to cost query

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts

Fixes failing local tests on project page because the query from here https://github.com/wandb/core/pull/25123 didn't skip properly when there would be no TraceServerClientContext because Weave isn't available.
Tested using governor start invoker and hardcoding removing the context provider that the error doesn't appear anymore because the query is skipped properly.

fix(weave): Fix skip in query to fix project page

---

weave-js/package.json
weave-js/yarn.lock

Removed the "canvas" module that we were not using. It was causing problems installing on node 22 due to it being unmaintained.
`rm -rf node_modules/ && yarn && yarn test` in weave-js on both node 22 and node 20

chore(weave): remove unused canvas dev dependency

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/ActionScorerForm.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/ActionSpecsTab.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/FormComponents.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/LLMJudgeScorerForm.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/LLMJudgesTab.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/NewScorerDrawer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/ScorerForms.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/ScorersPage.tsx

This PR:
1. Renames all components to be `LLM Judge` not "Action"
2. Corrects pluralization of headers
3. Adds the MVP LLM Judge listing page

chore(weave): Prep for LLM Judges UI

---

weave-js/src/core/ops/primitives/string.test.ts
weave-js/src/core/ops/primitives/string.ts

- Accompanies https://github.com/wandb/weave/pull/2864
- Fixes [WB-16442](https://wandb.atlassian.net/browse/WB-16442)
- Adds new string op to the FE to  parse numbers with a thousands and decimal separator.
- Unit tests
- Manually with local FE
[WB-16442]: https://wandb.atlassian.net/browse/WB-16442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(app): Add corresponding string op to FE to parse number with thousands and decimal separators

---

weave/trace/api.py
weave/trace/concurrent/futures.py
weave/trace/context/call_context.py
weave/trace/context/tests_context.py
weave/trace/context/weave_client_context.py
weave/trace/custom_objs.py
weave/trace/env.py
weave/trace/exception.py
weave/trace/feedback.py
weave/trace/init_message.py
weave/trace/mem_artifact.py
weave/trace/object_record.py
weave/trace/op.py
weave/trace/op_extensions/accumulator.py
weave/trace/patcher.py
weave/trace/pypi_version_check.py
weave/trace/refs.py
weave/trace/serialize.py
weave/trace/serializer.py
weave/trace/table.py
weave/trace/trace_sentry.py
weave/trace/util.py
weave/trace/weave_client.py
weave/trace/weave_init.py

Move to modern python syntax:
https://peps.python.org/pep-0604/
This excludes files that define classes that derive from `BaseModel` because it can cause strange behaviour in py39.  Once we move to py310+, we can update that code

chore(weave): Move to future annotations for weave_client

---

docs/docs/guides/tracking/ops.md

Adds documentation about the new WEAVE_PRINT_CALL_LINK environment variable. When `WEAVE_PRINT_CALL_LINK=false`, logging of urls is suppressed.
Fixes https://wandb.atlassian.net/browse/DOCS-1045

docs(weave): new feature WEAVE_PRINT_CALL_LINK

---

weave-js/src/components/PagePanelComponents/Home/Browse2/Browse2RootObjectVersionOutputOf.tsx
weave-js/src/components/PagePanelComponents/Home/Browse2/SpanDetails.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/common.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallSummary.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/DataTableView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ExampleCompareSection/ExampleCompareSection.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ScorecardSection/ScorecardSection.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/LeaderboardPage/leaderboardConfigEditorHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/KeyValueTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/views/Leaderboard/LeaderboardGrid.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/views/Leaderboard/query/leaderboardQuery.ts
weave-js/src/react.tsx

Copies `parseRefMaybe` from `SmallRef` to `react.tsx`. All other changes are updating import paths (with lint-fix combining a few things unrelated to this change). There is a reference to the SmallRef version in `core` that needs to be updated before we can delete it from SmallRef to complete the move.
This is done to break some import cycle problems that SmallRef has, though others remain. I believe it shouldn't introduce any new problems because anything that imported parseRefMaybe from SmallRef would have transitively depended on parseRef in react. `react.tsx` and the proximity to the `parseRef` method also seems like a better logical location to me.
Results of `npx madge --circular /Users/jamie/source/wandb/core/services/weave-python/weave-public/weave-js/src/components/PagePanelCompon …

refactor(ui): break import cycle

---

weave-js/src/components/PagePanelComponents/Home/Browse2/SmallRef.tsx

Last change related to https://github.com/wandb/weave/pull/2994 and https://github.com/wandb/core/pull/25684 - remove old copy of parseRefMaybe as part of breaking import cycles.

chore(ui): remove old parseRefMaybe

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/MessagePanel.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/ShowMoreButton.tsx

show more gradient wasnt acting enough as a background, make it not absolute for now

style(weave): make show more button not absolute

---

weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/StructuredFeedback/FeedbackSidebar.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/StructuredFeedback/HumanAnnotation.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/StructuredFeedback/humanAnnotationTypes.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/StructuredFeedback/tsHumanFeedback.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/PaginationControls.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableColumns.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/AnnotationScorerForm.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/NewScorerDrawer.tsx
weave-js/src/integrations/analytics/viewEvents.ts

Crush a bunch of human feedback rough edges. 
This pr: 
+ Sidebar:
- Store boolean types as boolean, not string
- add better loading state, don't show CTA when still loading
- add analytics event
- increase "save" button padding
+ Trace table:
- fix paging to keep feedback expanded when changing calls
- swap icon position (feedback/trace expand)
- `hide/show feedback sidebar` -> `hide/show feedback`
- correctly display bool types in trace table 
+ Create form:
- Add integer type (disallows float)
- "enum" -> "options"
- fix annotation form default state
- description optional 
- zod number `min/max` -> `minimum/maximum`
- after scorer creation, set form data to null

chore(weave): human annotation labeling review comments

---

tests/trace/test_annotation_feedback.py
weave/trace_server/interface/base_object_classes/annotation_spec.py

use the correct `minimum` and `maximum` in the test and example to show in UI, aligning.

chore(weave): cosmetic tweak to examples obj and test for annotation spec

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/PlaygroundChat.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/PlaygroundChatTopBar.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/useChatCompletionFunctions.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/useChatFunctions.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundContext.tsx

creates useChatCompletionFunctions
- handle send, sends a message to chat completions and adds it to state
- handle retry, removes all messages after the retried message, and sends it to completion, saves to state
https://github.com/user-attachments/assets/cb9d4b53-aa52-441b-9344-5c8593b022a4

chore(weave): Wire up completions

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx

In the objects listing grid, the "Category" column is not resizable. The hardcoded width was causing the AnnotationSpec pill to get truncated - that label is longer than other values.

chore(ui): fix Category pill column truncation

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CustomGridTreeDataGroupingCell.tsx

Lighten trace tree lines per design.
Internal Notion: https://www.notion.so/wandbai/Trace-tree-lines-10de2f5c7ef3801899dfc0f37ecbd317?pvs=4#143e2f5c7ef3806b9abee486a42a0cca
Before:
After:

chore(ui): lighten trace tree lines

---

weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/CodeDiff.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/CompareGrid.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/CompareGridCell.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/CompareGridCellValue.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/CompareGridCellValueCode.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/CompareGridCellValueTimestamp.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/CompareGridGroupingCell.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/CompareGridPill.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/CompareGridPillNumber.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/ComparePage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/ComparePageCalls.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/ComparePageObjects.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/ComparePageObjectsLoaded.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/ShoppingCart.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/ShoppingCartItem.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/compare.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/hooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/refUtil.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/types.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/context.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueViewNumberTimestamp.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/traverse.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTableButtons.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/urlQueryUtil.ts

Adds initial implementation of object/call comparison view.

feat(ui): object comparison

---

tests/trace/test_evaluations.py
weave/flow/eval.py
weave/scorers/__init__.py
weave/scorers/base_scorer.py

Resolves an issue where a scorer with both `output` and `model_output` could cause issues with argument parsing.  This PR prevents having both of these params specified because it's ambiguous which is the intended "output" and which is just another kwarg
Internal thread:
https://weightsandbiases.slack.com/archives/C01T8BLDHKP/p1732122258661749
Unit tests, manual testing

fix(weave): Fix issue where Evaluation can raise unexpectedly due to bad scorer

---

docs/docs/guides/tracking/tracing.mdx

- Fixes https://wandb.atlassian.net/browse/DOCS-1049
Fixes indentation issue in code sample by removing the magic comment `#highlight-next-line` in the Python code sample on L197 of `weave/docs/docs/guides/tracking/tracing.mdx`. See https://weightsandbiases.slack.com/archives/C01DX8LRZEJ/p1732038958244399?thread_ts=1732032632.859409&cid=C01DX8LRZEJ for context
> The long term fix here would be to fiddle with the CSS. However, this at least prevents the issue on this page.
1. Viewed in prod docs and confirmed indentation issue was present
2. Viewed in local docs and confirmed that no indentation issue was present.
3. Inspected HTML on both local and prod, confirmed that prod HTML has CSS class `#theme-code-block-highlighted-line` that appears to be indenting the block
4. Confirmed that …

docs(weave): Remove `#highlight-next-line` to fix indentation issue

---

weave/trace/weave_client.py

chore(weave): Cleanup save object basic

---

weave-js/src/react.tsx

This PR rethrows the `useExpandedNode` original error instead of using the original error as a message to the Error constructor.
Pic below shows how the error shows up in DD currently:

chore(weave): Rethrow useExpandedNode error for proper serialization

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/DataTableView.tsx

Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1732142002439589
Continuing on path of removing the `@mui/icons-material` dependency. Per discussion with design, changing to show a link with truncated id instead of updating the icon.
Before:
After:

chore(ui): change dataset link

---

weave-js/src/components/Panel2/PanelExpression/hooks.ts
weave-js/src/react.tsx

- Fixes [WB-15574](https://wandb.atlassian.net/browse/WB-15574)
The panel op, **`.table()`** crashes the panel when it is used in the following manner:
- `runs.summary["table"].run.table`
- `runs.summary["table"].table.run.table`
The error occurs from a var node being sent to the query engine service. After much debugging and pairing on this with @shawnlewis, we determined that the **`useExpandedNode`** hook was not receiving the frame with the `runs` node, so the solution was to pass in `newVars` from the **`usePanelExpressionState`** hook.
No longer crashes:
* Manually
[WB-15574]: https://wandb.atlassian.net/browse/WB-15574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(weave_query): Ensure newVars are passed in when expanding a panel op

---

weave-js/src/components/PagePanelComponents/Home/Browse3/compare/CompareGridCellValue.tsx

Boolean values in comparison grid were not rendering.
Before:
After:

fix(ui): compare cells with boolean values appearing empty

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/cost/costUtils.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableQuery.ts

This pr removes all expensive columns from the second calls query intended to inject costs into the calls table. There are currently many queries that fail in the UI due to the sheer amount of data required to load the trace page, either causing a memory exception or a timeout on formatting. Most of these errors occur in the full fat cost query, lets see if this reduces the impact of these.
👀 
Prod: 
This branch:
Prod:
This branch:

perf(ui): second cost query ignore all expensive columns

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallTraceView.tsx

Fast follow to: https://github.com/wandb/weave/pull/3077
Also does cost query improvements to the trace tree.
Benefits: 
- costs load much faster (2-10x)
- lower chance of timeout in ch

chore(ui): improve cost query perf in trace tree too

---

weave-js/src/components/FancyPage/FancyPageSidebarSection.tsx

Remove ugly console error. We don't need the key here.
This error now no longer appears

chore(ui): fix error message in console, key prop in jsx

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx

Unhide marker edit button
Blocked on: https://github.com/wandb/weave/pull/3025

chore(ui): unhide annotation sidebar edit button

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallTraceView.tsx

[This pr](https://github.com/wandb/weave/commit/c16ac3dcae10c8d02117898c361073af67e0988b) broke the summary in top level trace tree components. 
Trace tree blows away existing summary by updating twice. Set the costs once at the source of truth.

chore(ui): call tree costs fix

---

sdks/node/src/__tests__/login.test.ts
sdks/node/src/clientApi.ts

- Fixes [WB-22046](https://wandb.atlassian.net/browse/WB-22046)
This PR resolves an issue in the Weave JS SDK's login method where the `.netrc` file was being modified or created incorrectly if the `apiKey` arg was empty.
Changes:
- Added a validation check to ensure the `apiKey` is provided and non-empty
- Throws an error if the `apiKey` is missing
- Prevents overwriting existing `.netrc` entries unless both `host` and `apiKey` are valid and non-empty
Key fixes:
- Ensures that `.netrc` entries remain intact and prevent removal of the password line for existing entries
- Avoids introducing extra blank lines between machine blocks in the `.netrc` file
To reproduce the issue:
- Start with an existing `.netrc` file containing valid machine entries
- Execute the following JS script where …

fix(weave): netrc entry handling in Weave JS SDK login method

---

weave/trace_server/llm_completion.py

chore(weave): hide litellm from error messages

---

weave-js/src/components/PagePanelComponents/Home/Browse3/compare/CodeDiff.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/CodeView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/CompareGrid.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/CompareGridCell.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/CompareGridCellValue.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/CompareGridCellValueCode.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/CompareGridPill.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-22043
This PR handles a few problems with the comparison page:
* We were autoexpanding all groups. With large objects this causes the page to repeatedly freeze for several seconds. Two mitigations:
* Limit the depth we'll consider auto expanding for
* Don't autoexpand rows with no changes (a better UX for emphasizing differences anyway)
* The code editor component was capturing scroll events, which could make the page appear frozen as you tried to scroll. 
* For non-ref objects and arrays, we now display a key/item count and a pill if it has changed. This helps user understand the change (especially if not expanded) but also mentally prepare for possible slowness expanding large objects.

fix(ui): improved comparison performance and object handling

---

weave-js/src/components/Panel2/PanelTable/config.ts
weave-js/src/components/Panel2/PanelTable/util.test.ts
weave-js/src/components/Panel2/PanelTable/util.ts

- Fixes [WB-17336](https://wandb.atlassian.net/browse/WB-17336)
There was a user experience issue causing a table's state (derived columns, sorting, etc) to be wiped when the user logged an additional column with their table in a subsequent run.
Initially I couldn't reproduce it, but realized the issue only occurs after the first new column is added-- subsequent added columns did not reset the table state.
**Root cause**: the **`typeShapesMatch`** util function (only used to determine if tableState should be migrated) does not handle the case of a `type` being a `union<typedDict, typedDict>` and the `toType` being a `typedDict` where the union members match the property types of the `toType`'s `typedDict`.
This fix adds a check when the `toType` is a `typedDict` and the `type` is a …

fix(weave_query): prevent table state loss when encountering a new logged column

---

weave-js/src/core/ops/domain/artifactVersion.ts
weave_query/weave_query/ops_domain/artifact_version_ops.py

Fixes [WB-21719](https://wandb.atlassian.net/browse/WB-21719)
A user attempted to render a list of images from an artifact version using **`project.artifactVersion("<art_name>", "<version>").files.content`** which crashes the panel because the **`.content()`** op is meant to display the contents of a text file, not a png.
Since the intention of the user is to render a list of images and the expression **`project.artifactVersion().file("<image.(png|jpg|jpeg)>")`** renders one image file with a `PanelImage`, the **`.files()`** op should also render a list of images.
I added a refinement op for the **`artifactVersion-files`** op.
Accompanying weave-js changes: https://github.com/wandb/weave/pull/3083
Before:
After:
My dev setup doesn't properly show the image assets due to an ssl issue, but …

fix(weave_query): add refinement op to get types for artifactVersion-files op

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallTraceView.tsx

Uses costs from trace tree to render the callSummary costs. 
Prod: 
Branch:

chore(ui): add back costs to call summary page

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/PlaygroundChatInput.tsx

- Fixes z-index position of chat input area to not overlap the main nav overflow menu.
- Main nav overflow menu has z-index of 2.

fix(ui): Fixes z-index issue with Playground and navigation sidebar

---

weave-js/src/components/PagePanelComponents/Home/Browse3/context.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/PaginationControls.tsx

When the human feedback drawer is closed, don't add a url param. (Assume `undefined` = `false`)
Prod:
"/wandb-designers/martin-weave-test/weave/traces?peekPath=...calls%2F01935651-cb1f-7643-9e96-fd3cc263f579%3F**tracetree%3D1**"
Branch:
"/wandb-designers/martin-weave-test/weave/traces?peekPath=...calls%2F01935651-cb1f-7643-9e96-fd3cc263f579%3F"

chore(ui): hide feedbackSidebar url param if false

---

pyproject.toml

Resolves a bad interaction between the instructor 1.7.0 release and our use of `from __future__ import annotations`

chore(weave): Pin instructor for python3.9

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableColumns.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Links.tsx

While adding support for maintaining show-annotation state, I broke the trace tree defaults. Specifically we want to be able to show or hide the trace tree when the user sets it, but default to showing when a trace is normal, or hiding when the trace is an evaluation.

fix(ui): better defaults for trace/eval trace tree

---

weave-js/src/components/FancyPage/FancyPageMenu.tsx

Make text color for overflow menu in nav consistent
Before:
After:

chore(ui): night mode text color for More link in nav

---

weave/__init__.py

Adds the `StringPrompt` and `MessagesPrompt` classes to our generated API docs.
Still needed followups are improving the docstrings on the classes and executing `make generate_python_sdk_docs`

docs(weave): Include Prompt classes in generated API docs

---

weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/EmojiDetails.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/FeedbackGridInner.tsx

While watching GA release video I saw that emojis in places were getting incorrectly inverted by night mode.
https://www.youtube.com/watch?v=IQcGGNLN3zo&t=113s
Before:
After:

fix(ui): emojis looking bad in night mode

---

tests/trace_server/test_remote_http_trace_server.py
weave/trace_server_bindings/remote_http_trace_server.py

- Fixes WB-21911
Remote http trace server client now retries 500 errors. The trace server used to send back 500 for things that should have been 400, fixed here https://github.com/wandb/core/pull/25931

chore(weave): remote trace server client retries http 500

---

weave/trace_server/migrations/009_increase_call_timestamp_resolution.down.sql
weave/trace_server/migrations/009_increase_call_timestamp_resolution.up.sql

- Fixes WB-18987
Changes the type of 4 columns across 2 tables in the clickhouse database from `DateTime64(3)` (millisecond resolution) to `DateTime64(6)` (microsecond resolution).  The  columns migrated are the `started_at` and `ended_at` columns of `call_parts` and `calls_merged` tables.
The migration was tested up and down manually against a database with tens of millions of rows. The `ALTER TABLE` statements finish almost immediately and do not change the way that the underlying data is stored.
`calls_merged` is aggregated with a materialized view from `call_parts`. To make sure inserts between steps of the migration would not result in data loss, I tested what would happen if I inserted into `call_parts` while its timestamp columns had microsecond resolution but the corresponding …

chore(weave): increase call start/end timestamp resolution to microseconds

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsCharts.tsx

Internal Slack: 
https://weightsandbiases.slack.com/archives/C01T8BLDHKP/p1733198885250169
Calls with `null` ended_at values were not getting filtered out of graph, resulting in huge negative values.
Before:
After:

fix(ui): latency chart with unfinshed calls

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/NewScorerDrawer.tsx

Internal Slack: https://weightsandbiases.slack.com/archives/C01T8BLDHKP/p1733244393638349
Re-enable the scorer tabs for demos, still only available to W&B admins, but without text indicating that.
After:

chore(ui): unhide scorer, no admin text

---

tests/trace/test_exec.py
tests/trace/test_trace_settings.py
weave/trace/op.py

We always had this, it just wasn't easily accessible.

feat(weave): Expose simple way to get the captured code for an op

---

weave-js/src/components/FancyPage/useProjectSidebar.ts

Internal Slack: https://weightsandbiases.slack.com/archives/CA4PBB2TF/p1733261109636749?thread_ts=1732492325.984729&cid=CA4PBB2TF
Design team asked to move the Overview button in nav sidebar back to the top for Models-only projects.
Before:
After:

chore(ui): move Overview back to sidebar top for Models-only projects

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsCharts.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/Charts.tsx

Change size of metric charts section to be full container width instead of fixed based on window size.
Create plotly chart directly in the component render for metric charts, instead of in an effect that depends on only a few of the props.
Adds a 200ms debounce to all metric chart updates so resizing the drawer doesn't cause excessive re-rendering of the plots.
before:
after:

chore(ui): right drawer doesn't occlude call metrics charts

---

weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/PaginationControls.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
weave-js/src/components/PagePanelComponents/Home/TableRowSelectionContext.tsx

Pure refactor, breaking some import cycles that cause reloading problem in development. 
Before:
```
npx madge --circular  /Users/jamie/source/wandb/core/services/weave-python/weave-public/weave-js/src/components/PagePanelComponents/Home/Browse3.tsx  | grep Browse3.t
✖ Found 142 circular dependencies!
139) Browse3.tsx > Browse3/pages/CallPage/CallPage.tsx
141) Browse3.tsx > Browse3/pages/CallPage/CallPage.tsx > Browse3/pages/CallPage/CallDetails.tsx > Browse3/pages/CallsPage/CallsTable.tsx
142) Browse3.tsx > Browse3/pages/CallPage/CallPage.tsx > Browse3/pages/CallPage/PaginationControls.tsx
```
After:
```
npx madge --circular  /Users/jamie/source/wandb/core/services/weave-python/weave-public/weave-js/src/components/PagePanelComponents/Home/Browse3.tsx  | grep Browse3.t
✖ Found 139 …
```

refactor(ui): break an import cycle

---

tests/integrations/instructor/instructor_test.py
tests/integrations/openai/openai_test.py
weave/integrations/openai/openai_sdk.py

Openai integration captures the request id from completion responses and adds them to `request_id` on the call output.

chore(weave): capture request id for openai completions

---

weave-js/src/assets/icons/icon-filled-circle.svg
weave-js/src/components/Icon/Icon.tsx
weave-js/src/components/Icon/index.ts
weave-js/src/components/Icon/types.ts

addicon codegen. An initial planned use is to replace the circle icon from material icons that we are using here:

chore(ui): add filled circle icon

---

weave-js/src/components/FancyPage/FancyPageMenu.tsx

Fix this developer console warning:

chore(ui): fix warning about key attr spread

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx

[WB-22059](https://wandb.atlassian.net/browse/WB-22059)
This pr: 
- refactors the OpSelector to its own component
- wraps relevant functions in callbacks to prevent re-renders 
There is still a bit of lag as the call table renders, but unless we lock the dropdown while MUI renders i'm not sure if there is an easy fix. 
Can no longer reproduce the jumping to top behavior
[WB-22059]: https://wandb.atlassian.net/browse/WB-22059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(weave): ui op selecter jump back to top fix

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Links.tsx

Before:
After:
This should still work with the styling changes coming in https://github.com/wandb/weave/pull/3049

chore(ui): pluralize calls link

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/ChatView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/MessagePanel.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/PlaygroundMessagePanelButtons.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/PlaygroundMessagePanelEditor.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/PlaygroundChat.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/PlaygroundChatTopBar.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimplePageLayout.tsx

|  Updated playground  | Chat view |
| ![updated playground](https://github.com/user-attachments/assets/86862fac-1bc9-4a1c-8eed-e76d24125190) | ![chat view](https://github.com/user-attachments/assets/69944f85-a215-4240-a86c-124d776204be) |
Updated Playground view:
- Added background to header bar.
- Simplified inline action buttons on chat view.
- Updated spacing.

chore(ui): Playground design tweaks (header, buttons)

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTableButtons.tsx

Disables refresh button while calls are loading, either on page load or refresh click

chore(ui): disable refresh while refreshing

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/hooks.ts

Internal Jira: https://wandb.atlassian.net/browse/WB-22255
The Chat View originally only supported OpenAI format, then we added Gemini support. A user wrote in because the Chat View was missing things - it turns out that they were using Anthropic and its format is close enough to OpenAI format that the Chat View was turning on, but it wasn’t handling the Anthropic system prompt or completion output.

feat(ui): Support Anthropic calls in Chat View

---

weave-js/src/components/Tag/Pill.tsx

https://wandb.atlassian.net/browse/WB-22253
Add `ExpandingPill` component, a variant of the `Pill` component that starts as an icon-only pill but can expand to display the label as well
Storybook https://github.com/wandb/core/pull/26170
https://github.com/user-attachments/assets/5bb0379e-efae-4365-8330-ba6e21ed3caa

feat(ui): Add ExpandingPill component

---

weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/StructuredFeedback/FeedbackSidebar.tsx

Fixes header div being massive. 
Prod:
Branch:

fix(ui): feedback header when empty

---

weave-js/src/components/ToggleButtonGroup.tsx

Fixes nested button error in console, and fixes disabling individual options.
Tested on historic usage chart here https://github.com/wandb/core/pull/26192

chore(weave): Update ToggleButtonGroup to allow disabling individual options

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooksEvaluationComparison.ts

We don't need to check the name of the op - this is too fragile and overly restrictive

chore(weave): Fix predict detection heuristic for evals

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/SummaryPlotsSection/SummaryPlotsSection.tsx

https://wandb.atlassian.net/browse/WB-22272
This pr: 
- slightly refactors the summary plot data generation hooks to allow for only normalizing the data for radar plots, while keeping the dar plot data clean. 
Prod: 
Branch:

fix(ui): Evaluations -- normalize radar data, show real values for bar charts

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundSettings/PlaygroundSettings.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/types.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/usePlaygroundState.ts

Show completion iterations in Playground settings
Rearranged the settings menu a little to be more in line with designs
before
After

chore(weave): unhide completion iterations

---

tests/conftest.py
tests/integrations/openai/cassettes/test_autopatch/test_configuration_with_dicts.yaml
tests/integrations/openai/cassettes/test_autopatch/test_disabled_integration_doesnt_patch.yaml
tests/integrations/openai/cassettes/test_autopatch/test_enabled_integration_patches.yaml
tests/integrations/openai/cassettes/test_autopatch/test_passthrough_op_kwargs.yaml
tests/integrations/openai/test_autopatch.py
weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/StructuredFeedback/FeedbackSidebar.tsx
weave/integrations/openai/openai_sdk.py
weave/scorers/llm_utils.py
weave/trace/api.py
weave/trace/autopatch.py
weave/trace/patcher.py
weave/trace/weave_init.py

This PR adds a new kwarg to `weave.init`, called `autopatch_settings`.
Normally, we provide sane defaults to autopatched functions.  However, some users may want to customize how that patching happens, e.g.:
1. Configuring a custom `postprocess_inputs` to strip out PII
2. Configuring the names of autopatched functions
3. Disabling patching altogether
Now, users can configure this easily at init time before patching:
```py
client = weave.init(
...,
autopatch_settings={
"openai": {
"op_settings": {
"postprocess_inputs": ...,
"postprocess_output": ...,
}
},
"anthropic": {
"enabled": False,
}
},
)
```
---
This PR provides the core functionality and implements OpenAI to show what integration changes would look like.  A second fast-follow PR implements the remaining integrations: …

feat(weave): Support op configuration for autopatched functions (starting with OpenAI)

---

weave-js/package.json
weave-js/yarn.lock

We're not using this library in many places, but it would be nice to use it more e.g. for generating request IDs.
Upgrading allows us to remove `@types/uuid`
https://github.com/uuidjs/uuid/blob/HEAD/CHANGELOG.md
We also have our own implementation of v4 in the codebase we could likely get rid of.
https://github.com/wandb/weave/blob/master/weave-js/src/core/util/id.ts#L8

chore(ui): update UUID dependency to v11 (latest)

---

weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/StructuredFeedback/HumanAnnotation.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/AnnotationScorerForm.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/FormComponents.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/NewScorerDrawer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ScorersPage/ZodSchemaForm.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimplePageLayout.tsx

https://wandb.atlassian.net/browse/WB-22274
This pr: 
- Does another pass on annotation design tweaks, fixing small spacing issues. 
- Better handles Create Scorer form state, when closing the drawer all fields are reset to default. 
- Fixes a bug in the Zod array element where when specifying a # of minimum elements the form would not correctly display an empty field. This was due to an upstream state issue, we were not listening for config updates, and thus adding an empty element to the array did not cause re-render. 
- Add border and change spacing around Zod array element to conform with design spec, and add + icon to button
More zod form tweaks: better padding, bigger title and buttons, add border around enum section

chore(ui): Create scorer drawer style + small annotation drawer style tweaks

---

weave-js/src/components/ErrorBoundary.tsx
weave-js/src/components/ErrorPanel.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseCall.tsx
weave-js/src/errors.ts

Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1733949860779329
Adds a "Copy error details" button to our large error panel. This copies a bunch of useful information to the clipboard in JSON format. Note the TabUseCall change here is just for testing and will be removed before merge.
Example error details from FeatureBee:
```
{
"uuid": "0193b9da-ee39-752f-a112-76066dfa2d03",
"url": "https://beta.wandb.ai/jamie-rasmussen/2024-12-12_intro-example/weave/traces?cols=%7B%22attributes.weave.client_version%22%3Afalse%2C%22attributes.weave.os_name%22%3Afalse%2C%22attributes.weave.os_release%22%3Afalse%2C%22attributes.weave.os_version%22%3Afalse%2C%22attributes.weave.source%22%3Afalse%2C%22attributes.weave.sys_version%22%3Afalse%7D&peekPath=%2Fjamie-rasmussen%2F2024-12-12 …
```

feat(ui): Add error details button

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CustomGridTreeDataGroupingCell.tsx

- One-liner that aligns the line with the trace-tree to the center of the call title (vs. the center of the call card).
| Before    | After |
| ![CleanShot 2024-12-12 at 11 55 57@2x](https://github.com/user-attachments/assets/e501e454-3260-4085-8ea5-7e054072fab4)  | ![CleanShot 2024-12-12 at 11 57 55@2x](https://github.com/user-attachments/assets/a20ec022-8f80-413f-8ecc-2be1cf906a80) |

chore(ui): Trace tree: center line to point to the title of the call

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/MessagePanel.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/PlaygroundMessagePanelEditor.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/StyledTextarea.tsx

Editor is currently setting a max-height when auto-expanding. 
If we unlock max-height the editing view could be too long, pushing away the Cancel and Save controls.
- Added a resizeable condition to the editor input component (disable if autogrow is enabled).
- Gave it a larger starting height.
- Disabled `setIsShowingMore` for max-height on edit so the user can expand the input.
Could we keep passing that generated height of the message content into the editor component?
- I think the perfect solution would be to un-cap the editor and have it auto-grow - we'd need some form of sticky action bar for the editor though to solve the issue addressed above.
- This PR will help fix the immediate usability issue though.

chore(ui): Playground: make editor component resizeable

---

weave-js/src/components/Form/TextField.tsx

https://wandb.atlassian.net/browse/WB-22311
If an element has the `night-aware` class, its contents won't receive the default "invert colors" treatment. Instead, dark mode styling should be explicitly defined for all inner contents. However, if you have a night-aware element _inside_ another night-aware element, this messes up the inner element and displays it with light colors instead. I'm actually not sure how this interaction works exactly, I just know that if you remove the `night-aware` class from the inner element, the problem is fixed.
Many of our common comps have `night-aware` class attached by default and have specific dark mode styling defined. This becomes an issue if you every need to use of them inside another night-aware component. For example, if you're working on a …

chore(app): Allow skipping night-aware class for TextField

---

tests/trace/test_client_trace.py

Set the seed for this trace sampling test, was causing flake.

chore(weave): set seed in op sampling test

---

docs/docs/guides/evaluation/scorers.md
docs/docs/tutorial-eval.md
docs/docs/tutorial-rag.md
docs/docs/tutorial-weave_models.md

https://wandb.atlassian.net/browse/DOCS-1107
Replaces `:::warning` callouts with `:::important` where we don't need to scare the reader 👻

docs(weave): Don't use scary warnings if we don't need to

---

scripts/benchmark_import.py
tests/trace/test_import.py

This PR adds a benchmarking script and a test to make sure import times don't exceed 2s.  As of writing, the import time is ~1.3s on an M1 MBP

chore(weave): Add import time benchmarking script

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/ChoicesDrawer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundSettings/PlaygroundSettings.tsx

fixes two small ui things
Changes this from Completion iterations -> Number of trials
adds a background to this

chore(weave): small ui changes

---

dev_docs/RELEASE.md

Minor clarification and links added to release instructions.

chore(weave): add some links to Release instructions

---

docs/intro_notebook.ipynb
docs/notebooks/audio_with_weave.ipynb
docs/notebooks/chain_of_density.ipynb
docs/notebooks/codegen.ipynb
docs/notebooks/dspy_prompt_optimization.ipynb
docs/notebooks/feedback_prod.ipynb
docs/notebooks/multi-agent-structured-output.ipynb
docs/notebooks/notdiamond_custom_routing.ipynb
examples/tutorial_scripts/05_eval_pipeline.py
examples/tutorial_scripts/06_eval_pipeline_all.py
weave_query/examples/prompts/llm_monitoring/openai_proxy_quickstart_enterprise_mode.ipynb

All our colab notebooks fail right now which is pretty ugly. This is because OpenAI has a bug: https://community.openai.com/t/error-with-openai-1-56-0-client-init-got-an-unexpected-keyword-argument-proxies/1040332/15. The fix is to ensure httpx<0.28 since OpenAI uses a now-removed keyword and does not pin that httpx version.
This PR ensures that all our notebooks that install openai correctly install a version of httpx<0.28.
Further, notebooks that use `model_output` for scorers have been refactored to just use `output` so no warnings are shown.

chore(weave): Fix notebook docs: OpenAI and model_output

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/LLMDropdown.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/llmMaxTokens.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/usePlaygroundState.ts

update headers
sort llms 
simple defaulting for model

style(weave): LLM dropdown UX improvements

---

weave-js/src/common/components/PopupDropdown.tsx

chore(ui): Fix React warning in PopupDropdown

---

tests/integrations/litellm/litellm_test.py
weave/integrations/anthropic/anthropic_sdk.py
weave/integrations/cerebras/cerebras_sdk.py
weave/integrations/cohere/__init__.py
weave/integrations/cohere/cohere_sdk.py
weave/integrations/dspy/dspy_sdk.py
weave/integrations/google_ai_studio/google_ai_studio_sdk.py
weave/integrations/groq/groq_sdk.py
weave/integrations/instructor/instructor_iterable_utils.py
weave/integrations/instructor/instructor_partial_utils.py
weave/integrations/instructor/instructor_sdk.py
weave/integrations/litellm/litellm.py
weave/integrations/mistral/__init__.py
weave/integrations/mistral/v0/mistral.py
weave/integrations/mistral/v1/mistral.py
weave/integrations/notdiamond/__init__.py
weave/integrations/notdiamond/tracing.py
weave/integrations/vertexai/vertexai_sdk.py
weave/trace/autopatch.py

This is a fast-follow PR to: https://github.com/wandb/weave/pull/3197
It implements op kwarg passthrough for the remaining integrations, except Langchain and Llamaindex because they don't use the op decorator.

feat(weave): Support op configuration for autopatched functions for remaining integrations

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/LLMDropdown.tsx

Allows searching for stuff like aws and google, which werent included in the search before
https://github.com/user-attachments/assets/34e97a5e-cc9d-40dc-ae10-f5cd7d7b30bd

chore(weave): add better search function to llm dropdown

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/PlaygroundChat.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/PlaygroundChatInput.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/useChatCompletionFunctions.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/usePlaygroundState.ts

If in an empty chat box you hit send you get an error in playground 

fix(weave): Prevent sending null message in playground

---

weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/FeedbackGridInner.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/StructuredFeedback/humanAnnotationTypes.ts

[WB-22443](https://wandb.atlassian.net/browse/WB-22443)
- Adds the correct spacing around annotation feedback types
- removes quotes around string annotation values
Prod:
Branch:
[WB-22443]: https://wandb.atlassian.net/browse/WB-22443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(ui): fix spacing for annotation types in feedback grid

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/ChoiceView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/ChoicesDrawer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/ChoicesViewCarousel.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/PlaygroundMessagePanelButtons.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/PlaygroundChat.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/useChatCompletionFunctions.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundPage.tsx

on any state change we would reload the intial trace
deleting choices was broken
if you deleted all the choices it would break as well

fix(weave): Unbreak editing and deleting choices

---

sdks/node/src/__tests__/weaveClient.test.ts
sdks/node/src/weaveClient.ts

Fixes an issues where batch processing could crash for batches that are too large.
Now the batches are put back in the queue and retried up until a limit.
Resolves: https://wandb.atlassian.net/browse/WB-22435

fix(weave_ts): Fix issue where batch processing could crash

---

weave-js/src/components/DropdownMenu/DropdownMenu.tsx

Re: https://weightsandbiases.slack.com/archives/C072533MCA1/p1735677532676429
The separators on our radix dropdown menu are changing height when zooming out, see https://stackoverflow.com/questions/63991447/why-do-elements-with-the-same-height-look-differently-when-zoom-changes that Connie shared. We need to use a border instead of height to avoid this.
Before:
https://github.com/user-attachments/assets/68217a22-84d7-4fbe-947a-918854948d1e
After:
https://github.com/user-attachments/assets/a92d0ebd-1499-4f37-a6dc-565458345870

fix(app): dropdown separator width fluctuates on zoom out

---

weave/integrations/vertexai/vertexai_sdk.py

We need to `model_dump` to get back a dict instead of the same object

chore(weave): Fix typo in vertex wrapper settings

---

weave-js/src/common/components/FileBrowser.tsx

- Fixes WB-22387
This PR memoizes the code preview component, isolates the scroll to only the preview, and removes highlighting when the file gets large enough. This isn't a perfect solution but at least before the code freeze the page becomes usable.
Tested on open ai large files >8MB

fix(app): improve rendering code preview on large files

---

tests/integrations/langchain_nvidia_ai_endpoints/cassettes/langchain_nv_ai_endpoints_test/test_chatnvidia_async_quickstart.yaml
tests/integrations/langchain_nvidia_ai_endpoints/cassettes/langchain_nv_ai_endpoints_test/test_chatnvidia_async_stream_quickstart.yaml
tests/integrations/langchain_nvidia_ai_endpoints/cassettes/langchain_nv_ai_endpoints_test/test_chatnvidia_quickstart.yaml
tests/integrations/langchain_nvidia_ai_endpoints/cassettes/langchain_nv_ai_endpoints_test/test_chatnvidia_stream_quickstart.yaml
tests/integrations/langchain_nvidia_ai_endpoints/cassettes/langchain_nv_ai_endpoints_test/test_chatnvidia_tool_call.yaml
tests/integrations/langchain_nvidia_ai_endpoints/cassettes/langchain_nv_ai_endpoints_test/test_chatnvidia_tool_call_async.yaml
tests/integrations/langchain_nvidia_ai_endpoints/cassettes/langchain_nv_ai_endpoints_test/test_chatnvidia_tool_call_async_stream.yaml
tests/integrations/langchain_nvidia_ai_endpoints/cassettes/langchain_nv_ai_endpoints_test/test_chatnvidia_tool_call_stream.yaml
tests/integrations/langchain_nvidia_ai_endpoints/langchain_nv_ai_endpoints_test.py
weave/integrations/langchain_nvidia_ai_endpoints/langchain_nv_ai_endpoints.py

Previous impl relied on openai being installed for typing. That has been removed.
This also adds original inputs to the input / output reported
All tests updated.

fix(weave): ChatNVIDIA shouldn't depend on openai being installed

---

pyproject.toml

Unpins VCR from https://github.com/wandb/weave/commit/709e145650b1b357b9ecc863cfa3fad5ac3f9179#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R115 in order to fix deploy

chore(weave): Fix deploy by unpinning vcr

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseCall.tsx

Remove unintended whitespace prefix in TypeScript call use code example. We might also consider writing a general purpose dedent method for uses like this.
Before:
After:

chore(ui): Call Use TypeScript indentation

---

tests/trace/test_annotation_feedback.py
weave/trace/feedback.py
weave/trace/refs.py

[WB-22606](https://wandb.atlassian.net/browse/WB-22606)
Add annotation feedback with an annotation spec ref like: 
```python
spec_name = "wandb.annotation.number-spec"
annotation_ref = ref.uri()
payload = {"value": 3}
call.feedback.add(spec_name, payload, annotation_ref=annotation_ref)
```
Add test
[WB-22606]: https://wandb.atlassian.net/browse/WB-22606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(weave): allow call.feedback.add() for annotations

---

weave/flow/eval.py
weave/flow/model.py
weave/scorers/base_scorer.py
weave/trace/op_caller.py

This is another refactor PR to decouple Scoring and model prediction mechanics from the eval api itself. This builds off of https://github.com/wandb/weave/pull/3325. There should be no functional changes to the user. Specifically:
* `weave/trace/op_caller.py` now contains the helper functions for `async_call` and `async_call_op` which unifies op calling for async and sync calls under the same API.
* Extracts `apply_scorer_async` into `weave/scorers/base_scorer.py` prepping for re-use elsewhere
* Extracts `apply_model_async` into `weave/flow/model.py` for similar reasons.

chore(weave): Extract common functions in `eval.py` into re-usable common modules.

---

weave/flow/eval.py
weave/flow/model.py
weave/scorers/base_scorer.py
weave/trace/isinstance.py
weave/trace/op_caller.py

This is a pure refactor PR and should not change user experience. I am working on a larger refactor of this part of the code base but wanted to extract this portion as an incremental change. Specifically:
1. More strictly defines the dataset list to be a list of dicts (already enforced in application logic) allowing 2 branches to be removed.
2. Expose `_post_init_dataset` and `_post_init_scorers` properties in order to have more tightly defined symbols during execution.
3. Remove unreachable code due to the above.
_Note: Recommend hiding whitespace when reviewing due to indentation changes_
Now includes changes from https://github.com/wandb/weave/pull/3328

chore(weave): Remove dead code paths from `Evaluation.evaluate` by implementing correct typing.

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableColumns.tsx

[WB-22621](https://wandb.atlassian.net/browse/WB-22621)
Make the calls table annotation values clickable 
[WB-22621]: https://wandb.atlassian.net/browse/WB-22621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(weave): make annotation values in the traces table clickable

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/ecpConstants.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ComparisonDefinitionSection/EvaluationDefinition.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ExampleCompareSection/ExampleCompareSection.tsx

Continuing quest to only use our own icon library.
Note: our filled circle icon at its default size renders the circle slightly smaller than what we had with Material, going from 13.33x13.33 to 11.67x11.67. But I think this actually looks a bit better with the font size it accompanies.
Before:
After:

chore(ui): replace circle icon

---

weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/FeedbackGrid.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/FeedbackGridInner.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/StructuredFeedback/humanAnnotationTypes.ts

[WB-22624](https://wandb.atlassian.net/browse/WB-22624)
Add an annotation type name to the feedback table when there are annotation types in the table. Also tidy up a bit of spacing to squeeze out more real estate.
Prod:
Branch:
[WB-22624]: https://wandb.atlassian.net/browse/WB-22624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(weave): add annotation spec name to feedback grid

---

sdks/node/src/urls.ts

The URL generation logic correctly handles default `https://api.wandb.ai` url by changing trace url to `https://trace.wandb.ai`, but for non default hosts it fails to define traces url correctly (just uses `https://${resolvedHost}`).
Fix is to append `/traces` to the url for non default hosts.

chore(weave): Fixes dedicates instance connection issues with traces API

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClient.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClientTypes.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerDirectClient.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts

Adds necessary types and methods to `wfReactInterface` for the UI to hit the `objs/create` and `table/update` endpoints. Boilerplate.

chore(weave): add obj create and table update bindings to wf react interface

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/DataTableView.tsx

[WB-22420](https://wandb.atlassian.net/browse/WB-22420)
The following screenshot shows the issues, where there is at least one screen render where the query returns as "loaded" but the data does not exist in the object we pass to the table yet. This results in flashing the "no results found". Solution: set another loaded var at the same time we set the data.
prod:
branch:
[WB-22420]: https://wandb.atlassian.net/browse/WB-22420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(ui): add a loading state var to avoid "no results" on load

---

weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/DatasetVersionPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionPage.tsx

The `ObjectVersionPage` changes its display style significantly based on the type of object being displayed, with datasets being one special case. This PR refactors the component to render the dataset page in a separate component.
The intent here is to decouple the displays for each type of object versions as we start to make each UI more specialized and feature rich. This PR is in the immediate service of implementing a dataset editor in the dataset version display. Decoupling this UI from the other object version UIs makes the implementation much cleaner.

refactor(weave): dedicated component for dataset versions

---

tests/trace/test_obj_delete.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/sqlite_trace_server.py

Refs read batch is a bulk read action, I think we should resolve as many refs as we can, instead of erroring. 
Now, we return `null` for any refs that are deleted. For any given ref if we don't find anything (even a deleted object), we still raise an exception. 
Example:
```python
v0 = weave.publish({"i": 1}, name="obj_1")
v1 = weave.publish({"i": 2}, name="obj_1")
v2 = weave.publish({"i": 3}, name="obj_1")
v1.delete()
ref_res = client.server.refs_read_batch(
tsi.RefsReadBatchReq(
project_id=client._project_id(),
object_ids=["obj_1"],
refs=[v0.uri(), v1.uri(), v2.uri()],
)
)
assert refs_res == [v0.digest, null, v2.digest]
```
Changed tests to satisfy new paradigm.

chore(weave): refs read batch handles deleted objs silently

---

weave_query/weave_query/artifact_wandb.py

- Fixes [WB-22356](https://wandb.atlassian.net/browse/WB-22356)
- Raise a `WeaveArtifactCollectionNotFound` error whenever the artifact is unresolved. This error is already handled during op execution when we attempt to download the artifact, see: https://github.com/wandb/weave/blob/master/weave_query/weave_query/derive_op.py#L256-L269
Able to load the user's panel when running locally with the `invoker_weave_prod.ini` profile
[WB-22356]: https://wandb.atlassian.net/browse/WB-22356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(weave_query): prevent full panel crashes if a row contains an unresolved artifact

---

tests/trace/test_postprocessing.py
weave/trace/api.py
weave/trace/weave_client.py

Resolves: https://wandb.atlassian.net/browse/WB-22599
This allows users to configure custom post-processing functions to be applied globally and is intended to be give users fine-grain control over what data they actually want to log to weave.
For example, you can define a custom `redact_keys` function to hide anything with "key" in the name:
```py
import weave
def redact_keys(d: dict) -> dict:
for k in d:
if "key" in k.lower():
d[k] = "REDACTED"
return d
client = weave.init("testing306", global_postprocess_inputs=redact_keys)
@weave.op
def func(api_key: str, key_secret: str, name: str) -> int:
return f"Hi {name}!"
func("123", "456", "John")
```

feat(weave): Add global post-processing options

---

docs/docs/guides/core-types/datasets.md
docs/docs/guides/core-types/media.md
docs/docs/guides/core-types/models.md
docs/docs/guides/evaluation/scorers.md
docs/docs/guides/integrations/nvidia_nim.md
docs/docs/guides/integrations/openai.md
docs/docs/guides/tracking/costs.md
docs/docs/guides/tracking/feedback.md
docs/docs/guides/tracking/objects.md
docs/docs/guides/tracking/ops.md
docs/docs/quickstart.md
docs/docs/tutorial-eval.md
docs/docs/tutorial-rag.md
docs/docs/tutorial-tracing_2.md
docs/docs/tutorial-weave_models.md

Change is find+replace. This keeps the programming-language selection state in the URL, allowing us to link people to pages with TypeScript examples selected.
Internal Slack: https://weightsandbiases.slack.com/archives/C01T8BLDHKP/p1736373512488929
Ref: https://docusaurus.io/docs/next/markdown-features/tabs#query-string
Command: `find . -type f -name "*.md" -exec sed -i '' -e 's|<Tabs groupId="programming-language">|<Tabs groupId="programming-language" queryString>|g' {} +`

chore(weave): Keep programming language selection state in URL

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CustomGridTreeDataGroupingCell.tsx

Continuing effort to only use our own icon library for consistency.
Before:
After:

chore(ui): using internal icons

---

weave-js/src/components/ErrorBoundary.tsx

I'm not sure why, but in development an older version of the uuid library is sometimes referenced instead of the ^11.0.3 version our package.json specifies. The older version doesn't support v7. Since we don't really need v7 for the React Error Boundary use case I'm switching it to use v4.
Before:
After:

chore(dev): Use uuid v4 instead of v7 in error boundary

---

tests/trace/test_obj_delete.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/errors.py
weave/trace_server/sqlite_trace_server.py

Add the `deleted_at` time to the objectDeletedError so clients can handle these errors better

chore(weave): add deleted_at to weave object deleted error

---

weave-js/src/components/Button/Button.tsx
weave-js/src/components/Button/types.ts

Cloned #3361 for CI problems.
https://wandb.atlassian.net/browse/WB-22661
Removes "quiet" button variant now that we're deprecating it in favor of the "ghost" variant.

chore(weave): removing quiet button variant

---

docs/docs/reference/generated_typescript_docs/intro-notebook.md

https://wandb.atlassian.net/browse/DOCS-1172
Updates the language, style, and other various writing things for the new `docs/docs/reference/generated_typescript_docs/intro-notebook.md`
@ash0ts I edited the MD file directly because that was easier than editing the TS notebook - goal was to get this out the door for ya, I can go back and edit the NB later. Also, just a general note that we are trying to keep emojis out of headers moving forward, so I removed those

docs(weave): update TS intro nb

---

docs/docs/guides/tools/playground.md

https://wandb.atlassian.net/browse/DOCS-1141
Adds subsection to https://weave-docs.wandb.ai/guides/tools/playground describing how to adjust number of trials per https://weightsandbiases.slack.com/archives/C01T8BLDHKP/p1734390374060869?thread_ts=1734390374.060869&cid=C01T8BLDHKP

docs(weave): Document adjusting number of trials in Playground

---

weave/trace/serialize.py
weave/trace/weave_client.py

See https://github.com/wandb/weave/issues/3379 - we were getting an AttributeError: `object has no attribute 'lower'` when attempting sensitive key redaction on dicts with non-str keys.
```
from weave.trace.weave_client import redact_sensitive_keys
d = {1: 2}
redact_sensitive_keys(d)
```

fix(weave): don't check non-string dict keys for sensitive key redaction

---

tests/trace/test_import.py

We bumped from 3s to 4s in https://github.com/wandb/weave/pull/3272 but it flaked again for me:
```
E       AssertionError: Import time was 4.160144319999972 seconds
E       assert 4.160144319999972 < 4
```
Internal slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1734388464060729

chore(weave): increase CI test timeout

---

tests/trace/test_dataset.py
weave/flow/dataset.py

Resolves: https://wandb.atlassian.net/browse/WB-22736

chore(weave): Make Dataset support len and limited indexing

---

docs/docs/guides/integrations/cohere.md

Cloning https://github.com/wandb/weave/pull/3326 since our CI doesn't work with branches in forked repos.

docs(weave): Update docs to reuse the new method for initializing the cohere_patcher

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewerSection.tsx

If you hide an input/output section in the call details or set it to JSON mode, and then change the selected call in the trace tree, you would get a crash. This is because we simulate clicking on the tree expand or collapse buttons, but `apiRef.current` is null.

fix(ui): object viewer crash when json/hidden selected and change trace

---

weave-js/src/common/components/elements/LegacyWBIcon.tsx

- Part of implementation for https://wandb.atlassian.net/browse/WB-9465
Exposes a `disabled` property to allow for controlling that attribute from parent components.
Underlying `Icon` component already handled the property, but the containing `LegacyWBIcon` didn't expose it.
Tested locally, verified proper addition of value-less attribute.

feat(app): expose disabled property through icon

---

tests/trace/test_image_thread_safety.py
weave/__init__.py
weave/initialization/__init__.py
weave/initialization/pil_image_thread_safety.py

See comments in code:
```
This file exposes a function that makes the PIL ImageFile thread-safe: `make_image_file_thread_safe`.
There is a discussion here: https://github.com/python-pillow/Pillow/issues/4848#issuecomment-671339193 in which
the author claims that the Pillow library is thread-safe. However, my reasoning leads me to a different conclusion.
Specifically, the `ImageFile.load` method is not thread-safe. This is because `load` will both close and delete
an open file handler as well as modify properties of the ImageFile object (namely the `im` property which contains
the underlying image data). Inside of Weave we use threads to parallelize work which may involve Images. This bug
has presented itself not only in our own persistence layer, but also in user code where they are …
```

chore(weave): Make PIL images threadsafe

---

weave_query/weave_query/ops_domain/table.py

Fixes the panel crash reported in [WB-22355](https://wandb.atlassian.net/browse/WB-22355)
The panel crash happens due to an unhandled 'stale file handle' error when query engine is executing `file-table.` See screenshot below from [this trace](https://us5.datadoghq.com/apm/trace/5279186285891044226?graphType=flamegraph&highlight=gorilla&panel_tab=flamegraph&shouldShowLegend=true&sort=time&spanID=10465109557340666463&spanViewType=errors&timeHint=1734124764441).
This panel crash happens very rarely as it took almost a week for repro & trace capture. We're unsure to what causes this, but we're handling the error by returning a None value for the file-table op which is consistent with how we handle pulling files from run summary.
Using the `invoker.ini` dev environment.
I simulated a stale …

fix(weave_query): Handle stale file handle os errors on table load

---

scripts/benchmark_init.py
weave/trace/autopatch.py

Gives users the ability to disable autopatching, giving improved `weave.init` performance by almost a second if the user does not need integrations. An example use: a script that doesn't need to log any traces, like the benchmarking script included here.
For discussion related to https://github.com/wandb/weave/issues/3441
Before: Can disable individual integrations
After: Can also easily disable all integrations
Future?: Can selectively enable integrations
Integrations enabled:
```
python benchmark_init.py 
Logged in as Weights & Biases user: jamie-rasmussen.
View Weave data at https://wandb.ai/jamie-rasmussen/2025-01-20_benchmark_init/weave
1.981088749999799
1.254892750000181
1.242289083000287
1.322170541999185
1.3297177079994071
1.2651509999996051
1.3684602919993267
1.268961792000482 …
```

feat(weave): allow disabling autopatch

---

weave/trace/serialization/dictifiable.py
weave/trace/serialize.py

With dictify=false on inputs and outputs, we lost the ability to respect to_dict. This patches in a little hack to put that back

chore(weave): Re-enable to_dict support in serialization layer

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpsPage/OpVersionPage.tsx

Wasn't immediately obvious to me if this button only deleted the version or all versions of the Op - added a tooltip.

chore(ui): add tooltip to Op version delete button

---

weave-js/src/components/PagePanelComponents/Home/Browse3/grid/pagination.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallDetails.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTableButtons.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/views/Leaderboard/LeaderboardGrid.tsx

Currently we have no UI for setting pageSize and default to 100 rows, though we respect other values in query parameters.
This PR adds a small control to allow the user to set. (Does not persist yet, but should in a saved view.)
The motivation is that some users with huge traces get poor performance or failures if they try to load 100 traces at once.
This PR also changes the default page size to 50 and reduces the number of rows loaded in the peek drawer "table preview button" from 100 to 10.
Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1737131400397869

feat(ui): allow specifying page size in grid

---

docs/docs/guides/tracking/objects.md
docs/docs/guides/tracking/ops.md

Minimal docs for sdk object and op deletion

docs(weave): add .delete() to object doc page

---

weave_query/tests/test_propagate_gql_keys.py
weave_query/weave_query/propagate_gql_keys.py

Fixes [WB-21889](https://wandb.atlassian.net/browse/WB-21889)
`runs.loggedArtifactVersions` causes a panel crash for users with the error:
```No ops found for "tag-run" with first arg "TaggedValueType({['project', 'indexCheckpoint']}, artifactVersionType({'id': 'String()'}))"```
The `tag-run` op expects an input type that's tagged with the `run`, but the tag is missing during compilation.
I added logic to handle propagating tags onto mapped run ops because the existing logic (`should_tag_op_def_outputs`) will only create a TaggedValueType if the opdef's input is a `ProjectType` or a singular `RunType`. In the case of mapped run ops, the inputs will always be a `List` of `RunType`s. This specifically happens in run ops that are `gql_connection_op.`
Other mapped run ops have tags properly …

fix(weave_query): propgate tags on mapped run ops during gql key propagation

---

tests/trace/image_patch_test.py
tests/trace/type_handlers/Image/image_test.py
weave/initialization/pil_image_thread_safety.py

Modifies the patching logic such that order of construction is irrelevant. Currently this will fail:
```python
import PIL
image = PIL.Image.new("RGB", (10, 10))
with NamedTemporaryFile(suffix=".png") as f:
image.save(f.name)
image = PIL.Image.open(f.name)
image.crop((0, 0, 10, 10)) # <---- Attribute error on `_weave_load_lock`
```
This modified implementation uses a `TheadSafeLockLookup` to ensure that the `_weave_load_lock` is always available for any object requesting it and only minted once per object.

chore(weave): Improve Weave patch to support pre-constructed images

---

weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/DatasetVersionPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectsPage/ObjectVersionPage.tsx

Adds the created timestamp to the metadata displayed for an object version.
Before:
After:

chore(ui): show object version timestamp in header metadata

---

weave/trace_server_bindings/remote_http_trace_server.py

Speed up object parsing by using `model_validate_json` instead of `model_validate(json.loads(...))`
Perf example is for 1 Call object

perf(weave): Speed up json object parsing

---

tests/trace/test_objectify.py
tests/trace/test_uri_get.py
weave/trace/objectify.py

More testing to assert behaviours

chore(weave): Add tests for other expected behaviours in objectify

---

docs/docs/guides/core-types/datasets.md
tests/trace/test_call_object.py
tests/trace/test_dataset.py
weave/flow/dataset.py
weave/trace/weave_client.py

Resolves: https://wandb.atlassian.net/browse/WB-22700

feat(weave): Allow Dataset to be constructed from Calls

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectsPage/ObjectDeleteButtons.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpsPage/OpVersionPage.tsx

[WB-22873](https://wandb.atlassian.net/browse/WB-22873)
When in fullscreen mode, deleting an op or object does not redirect properly. Now, check if we are fullscreen, and navigate to the "versions" page. 
[WB-22873]: https://wandb.atlassian.net/browse/WB-22873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(weave): navigate properly when deleting obj/op version fullscreen

---

tests/trace/test_weave_client.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/sqlite_trace_server.py
weave/trace_server/trace_server_interface.py

[WB-22880](https://wandb.atlassian.net/browse/WB-22880)
Adds a `metadata_only` field to the `obj_read` request. 
add to existing test
[WB-22880]: https://wandb.atlassian.net/browse/WB-22880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(weave): add metadata_only to obj_read

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableQuery.ts

Micro perf improvement by not querying for costs when we have no calls to display.
in prod we actually query for costs twice even when there are no calls. 
Prod:
Branch:

chore(ui): dont do the cost query if no calls found

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTableButtons.tsx

Fix for frontend export code gen. Fixes 2 cases: 
- no need for expandColumns (sdk resolves refs)
- when selected calls, extra `}`

fix(ui): remove expandColumns with get_calls

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpsPage/OpVersionPage.tsx

Follow up to https://github.com/wandb/weave/pull/3464 adding timestamp to op page metadata.
Before:
After:

chore(ui): show op version timestamp in header metadata

---

weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/CellRenderers.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/DatasetEditorContext.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/DatasetVersionPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/EditPopover.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/EditableDatasetView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/editors/CodeEditor.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/editors/DiffEditor.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/editors/TextEditor.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/DataTableView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectsPage/ObjectVersionPage.tsx

- Fixes WB-22674
Introduces a UI for editing datasets. When viewing dataset objects in weave, an edit button is now shown in the top right corner of the dataset version page. Clicking this button takes the user into the dataset edit experience.
This editor allows:
- prepending new rows to a dataset
- removing rows from a dataset
- modifying existing values in a dataset
At any in the editing process, as long as edits have been made, the user can click publish in the top right corner of the dataset version page to publish a new version with their changes or click the adjacent cancel button to abandon their changes.
- `DatasetEditContextProvider` is introduced around the dataset version page and exposes state and callbacks for the editor, including: edited cell values, added row values, …

feat(weave): dataset editing UI

---

docs/docs/guides/troubleshooting.md
docs/sidebars.ts

- https://wandb.atlassian.net/browse/DOCS-1186
Adds Troubleshooting page to the docs, with first tip from [this slack convo](https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1736846808980349).
We don't currently have a great place to put this page without a larger menu reorg, so slotting into Product Walkthrough for now
- `yarn start` on local

docs(weave): Add troubleshooting page

---

weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterBar.tsx

[WB-22888](https://wandb.atlassian.net/browse/WB-22888)
Debounce typing in the trace table filter bar. 
Prod:
Branch:
[WB-22888]: https://wandb.atlassian.net/browse/WB-22888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(ui): debounce server requests while typing in filter bar

---

weave-js/src/components/UserName.tsx

Internal Figma: https://www.figma.com/design/mufhcDVpsRg9HJrLM61PCN/Weave-(Latest)?node-id=1171-39648&t=8BgGWBWWbfr8U32t-1
In Saved Views the data model uses userId's like "VXNlcjo0NTI1NDQ=". At display time, we want to convert that into something like "Jamie Rasmussen", which we have to query for.
Responsibility for design special cases like showing the text "you" for the current viewer is handled above this component.

chore(ui): add component for displaying user name

---

docs/docs/guides/integrations/azure.md
docs/docs/guides/integrations/bedrock.md
docs/docs/guides/integrations/google-gemini.md
docs/docs/guides/integrations/nvidia_nim.md

https://wandb.atlassian.net/browse/DOCS-1224
Requested by partner team as part of larger marketing strategy. For the following Integrations pages, adds appropriate links to partner pages with text similar to “For latest tutorials, click [here](https://wandb.ai/site/partners/nvidia)”:
- AWS
- Azure
- Gemini
- NVIDIA NIM

docs(weave): Partner team request - add links in Integrations to partner pages

---

.github/workflows/test.yaml
weave-js/src/components/TooltipDeprecated.tsx

Runs testci during weave-js test step. This will let us not run it in core, as there are no core dependencies
run ci. see commit history for example change to actually trigger js tests
https://github.com/wandb/weave/actions/runs/12891921201/job/35945037394

chore(dev): run testci during weave-js test step

---

weave-js/src/components/ToggleButtonGroup.tsx

Since the value of each item has to be a unique string for Radix https://www.radix-ui.com/primitives/docs/components/toggle-group, we can't just omit the value from the option. This adds an optional option field that lets you decide whether to show the value string or just the icon.
Tested on https://github.com/wandb/core/pull/26984

chore(app): Update ToggleButtonGroup to allow icon only buttons

---

tests/trace/test_flow_util.py
weave/flow/util.py

Context:
Currently the `async_foreach` method used in eval loop eagerly exhausts the passed in iterable which makes streaming datasets not possible. 
This is part 1 of a few PRs that build up to streaming support in evals & support for huggingface datasets.
---
Summary:
This pull request includes significant improvements to the `async_foreach` function in `weave/flow/util.py` and adds comprehensive tests for this functionality in `tests/trace/test_flow_util.py`. The changes enhance the documentation, error handling, and concurrency control of the `async_foreach` function.
Enhancements to `async_foreach`:
* [`weave/flow/util.py`](diffhunk://#diff-4ea0910967848b60c0a39eef3ba931abba8016263740bba2b083a94bf26ebf87R19-R96): Added detailed docstring to `async_foreach` explaining its …

chore(weave): Streaming Evals Pt1: lazy `async_foreach`

---

weave-js/src/components/PagePanelComponents/Home/Browse2/SmallRef.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClientTypes.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts

[WB-22881](https://wandb.atlassian.net/browse/WB-22881)
When rendering object refs, no need to load the actual object value. Make sure not to cache when getting metadata_only.
Depends on:
- https://github.com/wandb/weave/pull/3462 
👀 
[WB-22881]: https://wandb.atlassian.net/browse/WB-22881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(ui): move smallref onto metadata_only obj_read

---

wb_schema.gql
weave-js/src/common/hooks/useArtifactWeaveReference.ts
weave-js/src/common/util/artifacts.ts
weave-js/src/components/PagePanelComponents/Home/Browse2/CellValue.tsx
weave-js/src/components/PagePanelComponents/Home/Browse2/SmallRef.tsx
weave-js/src/components/PagePanelComponents/Home/Browse2/url.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/common.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueView.tsx
weave-js/src/react.tsx

Pulling frontend changes out of https://github.com/wandb/weave/pull/2920/ and updating them to resolve merge conflicts 
Before:
After:
Now that the changes in https://github.com/wandb/weave/pull/3484 have been deployed, these changes can be tested against the prod trace server backend. I used a tweaked version of the script from the original PR.
```
from typing import List
import weave
import wandb
PROJECT = "2025-01-23_artref"
TEAM_ENTITY = "jamie-team"  # MAKE SURE THIS IS NOT A PERSONAL ENTITY
PERSONAL_ENTITY = "jamie-rasmussen" # Most likely your username
ORG_ENTITY = "wandb-jamie"  # Fetch this from the UI banner {BASE_URL}/orgs/wandb/registry/model
artifact_name = "test"
run = wandb.init(project=PROJECT, entity=PERSONAL_ENTITY)
model_artifact = wandb.Artifact(name=artifact_name, …
```

feat(ui): artifact ref links

---

tests/trace/type_handlers/Image/image_test.py

Fix this warning in tests:
```
tests/trace/type_handlers/Image/image_test.py::test_images_in_load_of_dataset
/home/runner/work/weave/weave/.nox/tests-3-9-shard-trace/lib/python3.9/site-packages/_pytest/python.py:163: PytestReturnNotNoneWarning: Expected None, but tests/trace/type_handlers/Image/image_test.py::test_images_in_load_of_dataset returned ObjectRef(entity='shawn', project='test-project', name='Dataset', _digest='PJ3hsmfcP6fkaYlocbpAzkZpo5tKeYJFWBAWa8zk5cE', _extra=()), which will be an error in a future version of pytest.
```

chore(weave): fix pytest warning

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/tabularListViews/CollapseHeader.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/tabularListViews/ExpandHeader.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/tabularListViews/columnBuilder.tsx

Move some components out of Browse2 and closer to only use in Browse3.

refactor(ui): move header components out of Browse2

---

weave/trace/settings.py
weave/trace/weave_client.py

Internal Slack: https://weightsandbiases.slack.com/archives/C072S236A75/p1738168167702489
Adds the ability to disable capture of contextual information such as Weave client version and operating system.

feat(weave): allow disabling capture of context

---

docs/docusaurus.config.ts
docs/src/css/custom.scss

1. Remove unused styles
2. Defined a clear header size scale (previously bottomed out at h2)
3. Reduced footer size and moved links into header
4. Slight refresh of sidebar for a cleaner look
After (left) Before (Right)

chore(weave): Subtle docs style adjustments

---

weave-js/src/components/ToggleButtonGroup.tsx

Follow up to https://github.com/wandb/core/pull/25697#discussion_r1933003640 - adds `className` as a prop to `ToggleButtonGroup` common component.
Adding the `className` prop to the Storybook example successfully changes styling:

chore(ui): add className prop to ToggleButtonGroup component

---

weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/EditableDatasetView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/typeViews/PIL.Image.Image/PILImageImage.tsx

Partial fix for https://wandb.atlassian.net/browse/WB-21609
Brings back a lightbox viewer for logged images, also with a preview on hover, which we didn't have before.
Tested with new `wf` example, Image-Eval which creates a Weave dataset and evaluation from a W&B artifact that contains 100 image generation prompts and the dall-e output for them.
Before:
After:

feat(ui): lightbox for images

---

weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterRow.tsx

[WB-22869](https://wandb.atlassian.net/browse/WB-22869)
While the first filter always works, additional filters have a string operator by default, no matter the type. This pr fixes that by looking up a smart default (that should match the dropdown).
prod:
branch:
[WB-22869]: https://wandb.atlassian.net/browse/WB-22869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ui): additional filters lookup the proper operator

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/objectClassQuery.test.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClientTypes.ts

Adding `deleted_at` field to TypeScript side to match Python declaration.
https://github.com/wandb/weave/blob/master/weave/trace_server/trace_server_interface.py#L181
I think the field has to always exist because of the default value, so `| null` seemed more correct than the `?` we have for `base_object_class` and `wb_user_id`.

chore(ui): add missing field to TraceObjSchema

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/llmMaxTokens.ts

Adds grok 2 and gemini flash 2 to playground models

chore(weave): Add grok2 and gemini flash 2

---

weave-js/src/components/Panel2/PanelTable/PanelTable.tsx

- Addresses [WB-21904](https://wandb.atlassian.net/browse/WB-21904)
- Include the current columns as new variables into the stack for the inner table component to consume
Local FE
https://github.com/user-attachments/assets/492f9c02-32b8-4516-8949-000fdc02da2e
[WB-21904]: https://wandb.atlassian.net/browse/WB-21904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(app): allow derived columns to be used as variables in weave expression editor

---

weave_query/tests/test_wb_end_to_end.py
weave_query/weave_query/graph.py
weave_query/weave_query/ops_primitives/_dict_utils.py

Fixes [WB-22947](https://wandb.atlassian.net/browse/WB-22947), which was occurring due to 2 related issues:
1. The history columns are unescaped, so the value inside the node needs to also be the unescaped key. (This is the change in `weave_query/weave_query/graph.py`)
2. The history data returned to us is already flattened. So we can access it directly with the nested key instead of walking the history data. (This is the change in `weave_query/weave_query/ops_primitives/_dict_utils.py`)
* i.e. When the data is in this shape: `{ 'key_1': { 'key_1_1': 0 }}`, the `_any_val_for_path` function will attempt to walk the dictionary, looking for `key_1`, then `key_1_1`. However, the history data is being returned as `{ 'key_1.key_1_1': 0 }`, so we can access the data directly with the nested key …

fix(weave_query): Unescape nested dictionary keys before GQL retrieval and during typedDict-pick

---

wb_schema.gql
weave-js/src/common/hooks/useProjectInfo.ts

A project like `jamie-rasmussen/2025-01-30_wf` has both an "id" and an "internalId". If you decode them they look like:
id: `Project:v1:2025-01-30_wf:jamie-rasmussen`
internalId: `ProjectInternalId:40869716`
So somewhat unexpectedly, the "id" value changes when you rename the project. The "internalId" does not change.
In the upcoming Saved Views work, we use local storage to remember the last view you used, on a per-project (and per-page, traces or evaluations) basis. This hook allows us to query for the "internalId" of the project, so that we can use it as part of the key.

chore(ui): Add useProjectInfo hook

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/utilities.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/smallRef/SmallRefIcon.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/smallRef/SmallRefLoaded.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/smallRef/SmallWeaveRef.tsx

Fixes https://wandb.atlassian.net/browse/WB-21887
This improves a number of things about SmallRef.
* Currently, the component renders once with a version hash, then with the version number, and again but in a bolder font. I change it to show a loading dots indicator, and then the final form.
* We were showing a generic icon instead of a more specific one for prompts, models, datasets, etc.
* Deleted refs now have a tooltip with more information.
Before:
After:

fix(ui): more specific icons shown in SmallRef

---

weave-js/src/components/Panel2/PanelTable/PanelTable.tsx

Fix table row size controls. See internal Slack:
https://weightsandbiases.slack.com/archives/C02U6LLHP9S/p1738347523801469
https://weightsandbiases.slack.com/archives/C06CCH5PH3L/p1738629213010689
Before:
After:

fix(ui): new tooltip broke table row size

---

weave/scorers/llm_utils.py
weave/scorers/moderation_scorer.py

Two unrelated changes.
1. Per [OpenAI docs](https://platform.openai.com/docs/guides/moderation) `text-moderation-latest` is now legacy and `omni-moderation-latest` is recommended. (Among other things it adds an "illicit" category.)
2. `response.categories` is a `openai.types.moderation.Categories` object and not a dict, so we were getting `AttributeError: 'Categories' object has no attribute 'items'`

fix(weave): AttributeError with OpenAIModerationScorer

---

weave-js/src/common/types/file.ts
weave-js/src/common/types/run.ts
weave-js/src/common/util/table.ts
weave-js/src/components/Panel2/PanelExpression/hooks.ts
weave-js/src/components/Panel2/PanelRegistry.tsx
weave-js/src/components/Panel2/PanelRunHistoryTablesStepper/index.tsx
weave-js/src/components/Panel2/PanelRunsTable/index.tsx
weave-js/src/components/Panel2/panellib/libpanel.ts

- Addresses [WB-23061](https://wandb.atlassian.net/browse/WB-23061) ([Story ticket](https://wandb.atlassian.net/browse/WB-22173))
- Introduces new panel to display a paginated table of the history tables for a given table name 
- The pagination is controlled by a slider and respects the `_step` value associated to each table version
Local FE
https://github.com/user-attachments/assets/a0b22b97-adbf-4399-97cf-eed0659079d4
https://github.com/user-attachments/assets/1c16fbfe-4376-43f9-8d22-fb5880ec6d11
https://github.com/user-attachments/assets/1682ba51-aad0-4d55-a450-6c77ef8c3bb0
[WB-22173]: https://wandb.atlassian.net/browse/WB-22173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WB-23061]: …

feat(app): Runs History Tables Scrubber

---

weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/AddToDatasetDrawer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/EditAndConfirmStep.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/SchemaMappingStep.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/SelectDatasetStep.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/ResizableDrawer.tsx

General:
- Tightened up padding across views.
Drawer / header / footer:
- Swapped in the resizeable drawer component.
- Tweaked close / back controls for page 1/2 of the drawer.
- Added fullscreen control for editing the dataset rows.
- Tweaked back button to secondary / tweaked Add text (to Add to dataset).
ResizeableDrawer component enhancements:
- Increased min-width to match peek drawer component.
- Added a proper height to account for the header bar for the fixed component.
Mapping:
- Feature: Added latest dataset selector to dropdown (revert [this commit](https://github.com/wandb/weave/pull/3588/commits/d6d1e5433d5befbbae2e566ef6e31b558d73bb29) to remove).
- Made the dropdown columns liquid vs. fixed.
- Added a max height / wrap / overflow scroll for the `from:` field mapping since …

chore(ui): Add to dataset design edits

---

weave-js/src/components/Panel2/PanelPlot/PanelPlot.tsx
weave-js/src/components/Panel2/PanelTable/PanelTable.tsx
weave-js/src/components/Panel2/PanelTable/util.ts

- Fixes [WB-23058](https://wandb.atlassian.net/browse/WB-23058)
- Followup to https://github.com/wandb/weave/pull/3518. Allows users to use their derived columns as plot dimensions by passing the columns from table state onto the stack during `PanelPlot` render.
Local FE
https://github.com/user-attachments/assets/7d119569-976b-4737-9a70-aadf463a6d43
[WB-23058]: https://wandb.atlassian.net/browse/WB-23058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(app): pass derived columns as new variables onto the stack in panel plots

---

weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/FeedbackGridActions.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/ScoresFeedbackGridInner.tsx

When deleting scores in the UI, the dialog is using the noun "feedback". While scores are a type of feedback, I think that's a little confusing because we have a separate "feedback" tab that scores are filtered out of.
Before:
After:

chore(ui): text in Score delete dialog

---

weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/ScorerFeedbackGrid.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/ScoresFeedbackGridInner.tsx

Fix naming of props type in ScorerFeedbackGrid. Removed an unused prop. Also wondering if the inner component naming of "Scores" was intentional instead of "Scorer".

chore(ui): fix scorer grid props naming

---

weave-js/src/components/Panel2/PanelProjectionConverter/util.ts

JIRA: [WB-23076](https://wandb.atlassian.net/browse/WB-23076)
**Issue**: The incoming `inputColumnNames` from the config could be either a string (when the config is single select) or an array (when the config is multi-select) and since `.length` is defined on either, we would run through the same logic for either type.
**Fix**
In the single select case, there is an added case to handle incoming strings. There is a bit of refactoring of the logic, which should be equivalent to what we had before:
* The default is the first element of `validEmbeddingColumns`, if it exists, and an empty array otherwise
* When the incoming `inputColumnNames` is an array, we take the first element, if it exists in `validEmbeddingColumns`
* When the incoming `inputColumnNames` is a string, we use it if it …

fix(app): handle singular embedding columns in combined 2D projection panel

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/utilities.ts

Deletes the unused `useParentCall` function. More importantly, this allows us to break an import cycle that causes an infinite reloading problem in development.
Cycle: context.tsx > tsDataModelHooks.ts > utilities.ts > context.tsx
`npx madge --circular src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/utilities.ts`

chore(ui): break import cycle

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CustomGridTreeDataGroupingCell.tsx

Adds back hidden siblings, errantly removed in this pr: https://github.com/wandb/weave/pull/2945

fix(weave): show hidden sibling count

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CustomGridTreeDataGroupingCell.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/OpVersionText.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableFilter.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ComparisonDefinitionSection/ComparisonDefinitionSection.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpsPage/OpVersionPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpsPage/OpVersionsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/EditableCallName.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Links.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/opNiceName.ts

Breaking another import cycle causing infinite reloading problem in development.
Cycle was Links.tsx > context.tsx > callsTableFilter.ts > Links.tsx
`npx madge --circular src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx`

chore(ui): break opNiceName cycle

---

weave-js/src/components/Panel2/PanelTable/ColumnHeader.tsx
weave-js/src/panel/WeaveExpression/state.ts

* Add `Apply` button to address [WB-23056](https://wandb.atlassian.net/browse/WB-23056) 
* Related: We want to compare the text of `workingSelectFunction` and `propsSelectFunction`, since `workingSelectFunction` is an `EditingNode` and `propsSelectFunction` is a `NodeOrVoidNode`.
* Remove the early return to fix [WB-23159](https://wandb.atlassian.net/browse/WB-23159). We always want to set `pendingExpr`, which is initialized to the original expression. Our current logic is the following
```js
// newExpr is the incoming change
if (pendingExpr == newExpr) {
return;
} else {
// fire off setExpression hook
return;
}
// update pendingExpr = newExpr
```
Incoming `newExpr`s will fire off the `setExpression` hook but never update `pendingExpr` so if we revert `newExpr` back to the original …

feat(app): add apply button to column header popup

---

docs/docs/guides/core-types/prompts.md

- Fixes https://wandb.atlassian.net/browse/DOCS-1257
Add callout to Prompts page that feature is only Python for now. 

docs(weave): Add Python-only callout to Prompts page

---

dev_docs/BuiltinObjectClasses.md

The only actual change I made is changing the name `useCreateBaseObjectInstance` to `useCreateBuiltinObjectInstance`, the rest is autoformatting.

docs(dev): fix useCreateBuiltinObjectInstance method name

---

tests/trace/test_scored_calls_query.py
weave/trace/weave_client.py

[WB-23221](https://wandb.atlassian.net/browse/WB-23221)
The query parameter can limit results, it must be passed to the calls stats function to get the length as well as the main streaming endpoint. 
Also move the query construction code to where the other helper is, for clarity on main client endpoint. 
add test
[WB-23221]: https://wandb.atlassian.net/browse/WB-23221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(weave): add query to calls_query_stats in `get_calls`

---

tests/trace/test_table_query.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/sqlite_trace_server.py
weave/trace_server/table_query_builder.py
weave/trace_server/trace_server_interface.py

Return absolute index of each row when serving rows from a table. This enables more powerful UIs for editing datasets.

chore(weave): table row response includes absolute row indices

---

weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/EditableDatasetView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClientTypes.ts

Make datasets sortable in edit mode and preserve row indices during sorting operations.

chore(weave): sort datasets while editing

---

tests/trace/test_evaluate.py
weave/trace/op_caller.py

Once again allow sync functions to execute in parallel, respecting `WEAVE_PARALLELISM` in evaluations. 
Broken by [this](https://github.com/wandb/weave/pull/3325/files#diff-6d28dd17dfc8f677f389cf6cd48c8842b00294dc8f5c1f0f03ce835bf487ae9d) refactor
Branch:
Master:

fix(weave): run sync eval predict functions in parallel

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsCharts.tsx
weave-js/src/integrations/analytics/userEvents.ts

Add analytics for the metrics plot. Includes a latency metric which could be interesting to see if users are running into perf issues.

chore(ui): add analytic event to metrics chart views

---

weave-js/src/components/Panel2/PanelRunHistoryTablesStepper/index.tsx

- Implements [WB-23062](https://wandb.atlassian.net/browse/WB-23062)
- Followup to https://github.com/wandb/weave/pull/3459
- The panel now retrieves history data from all runs (instead of just the latest) and performs the following query:
```
runs.history.concat.filter((row) => row['step'] == <step>)[<table>]
```
for the specified `<step>` (given by the slider on the bottom) and `<table>` (selected in the config)
Local FE
https://github.com/user-attachments/assets/9e39f2b9-6465-46ee-9d6b-c2735e297dae
[WB-23062]: https://wandb.atlassian.net/browse/WB-23062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(app): extend runs history step slider to include history tables from all runs

---

README.md

There was a missing full stop in the README. MY minor OCD couldn't look past it.

docs(weave): Full stop is a must 

---

weave-js/src/components/PagePanelComponents/Home/Browse3/components/TraceNavigator/TraceScrubber/components/StackBreadcrumb.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/components/TraceNavigator/TraceScrubber/index.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/components/TraceNavigator/TraceScrubber/styles.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/components/TraceNavigator/TraceViews/TreeView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/cost/TraceCostStats.tsx

Based off of:
https://github.com/wandb/weave/pull/3834
WIP: DNM
Trace tree:
- Conditionally hid parent/root call show and tell when disabled.
- Updated search to show children and parents.
- Added highlight to searched text in nodes.
- Added line-work to help illustrate hierarchy. 
- Added tooltips to call names for truncated calls.
- Moved call category icons to right side.
- Updated icons to make them smaller
- Colored based on category "types" (Identifiers, Completions/Tools, Evals, Other).
- Added token count into token cost tooltip - consolidated into one column.
- Added button to swap between token cost and latency.
Scrubbers:
- Updated scrubber colors.
- Add expand and collapse to show one or many scrubbers (pushes on and off page).
Tooltip (component):
- Updated tooltip divider …

feat(weave): New trace view: design tweaks

---

weave-js/src/components/PagePanelComponents/Home/Browse3/typeViews/PIL.Image.Image/PILImageImage.tsx
weave/type_handlers/Image/image.py

Internal slack: https://weightsandbiases.slack.com/archives/C02UKHHN83G/p1742351127929729
The PIL Image serializer will convert unknown image types to PNG. This change allows webp images to be serialized as such and for the frontend to be able to render them.
Added webp inline and pillow to wf values example: https://github.com/wandb/wf/pull/84

feat(weave): improve webp image support

---

weave-js/src/components/Panel2/ImageWithOverlays.tsx
weave-js/src/components/Panel2/PanelImage.tsx
weave-js/src/core/model/media/mediaImage.ts
weave-js/src/core/model/media/mediaTable.ts
weave-js/src/core/model/media/mediaTypes.ts
weave-js/src/core/model/types.ts

- Partial progress for [WB-22188](https://wandb.atlassian.net/browse/WB-22188)
- Re-merging https://github.com/wandb/weave/pull/3807. This PR only contains the FE portion of the changes 
- This PR allows the FE to accept `caption` as a property of incoming `image-file` data and adjusts the UI to display the caption.
- There's also a small addition to keep the image at 100% height if the caption is not present and 80% otherwise. (This avoids an awkward blank area under the image)
Tested with local FE. The changes will not yet be visible until the BE passes `caption` data, so we should not see any changes (or errors) in the UI. This is verified in the video below:
https://github.com/user-attachments/assets/1960e115-e49b-4e8f-8b11-98798371645a
With `weave0` on, we can see what the changes …

chore(app): Accept image caption property in weave panels

---

weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterBar.tsx

missed a callsite when transitioning from length-based-ids to max/length. this enables more complex filter assignments.
In prod, we assign ids based on the length of the array. when you delete items, this then reassigns those ids and they can collide.  
Prod:
Branch:

chore(weave): fix adding and deleting filter rows

---

weave/integrations/openai/openai_sdk.py

Internal Slack: https://weightsandbiases.slack.com/archives/C053FHBH73P/p1740558111134829?thread_ts=1740124248.544159&cid=C053FHBH73P
Per the OpenAI SDK, the `delta` field of a `Choice` is not `Optional`.
https://github.com/openai/openai-python/blob/3e69750d47df4f0759d4a28ddc68e4b38756d9ca/src/openai/types/chat/chat_completion_chunk.py#L88
However, the Azure implementation can return a `None` value for the delta. This issue notes one triggering condition which I was able to reproduce, which is when you have enabled custom content filtering settings with the Asynchronous_filter streaming setting.
https://github.com/openai/openai-python/issues/1677
A similar previous PR: https://github.com/wandb/weave/pull/3736

fix(weave): handle noncompliant chunk response from Azure

---

weave-js/src/components/PagePanelComponents/Home/Browse3/StyledTextField.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterBar.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterPanel.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTableButtons.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/ManageColumnsButton.tsx

| ![CleanShot 2025-03-22 at 19 09 21](https://github.com/user-attachments/assets/763c20a3-43c8-45d8-90d7-c08615abad18) | ![CleanShot 2025-03-22 at 19 11 03](https://github.com/user-attachments/assets/708fff86-7595-4f27-a343-9f8635f5376f) |
- Visual changes for trace / eval page header update.
- Emphasizes actions which can be taken after row selection.
- Adds a bar which calls out how many traces are selected
- Updated default button styles to reduce line-work.
- Updated Ops selector to use the proper Source Sans Pro font.

chore(ui): Header update (visuals only)

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectsPage/ObjectVersionPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectsPage/ObjectVersionsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpsPage/OpVersionPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpsPage/OpVersionsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts

[WB-22878](https://wandb.atlassian.net/browse/WB-22878)
This pr: 
- changes objects and ops table text from "Created" to "Last updated"
- changes object and op pages to use "Last updated by" text
- adds user information to ops table and op page
Op:
Object:
Op:
Object:
[WB-22878]: https://wandb.atlassian.net/browse/WB-22878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(weave): change object tables copy and add user to ops

---

weave-js/src/components/Form/Select.tsx
weave-js/src/components/Form/TextField.tsx

Pre-req for https://wandb.atlassian.net/browse/WB-23683
We're building a new UI that displays a multi-select field next to a plain text field: https://www.figma.com/design/8v53a9ldK9DcVUkILt4CIn/Scratchpad?node-id=3102-175949&m=dev
But there are some styling discrepancies between our `TextField` and `Select` comps that are especially prominent when the two are displayed right next to each other.
- height: multi-select is taller than TextField (40px vs 32px)
- placeholder text: multi-select is smaller than TextField (14px vs 16px)
- border-radius: multi-select is rounder than TextField (4px vs 2px)
- ...these are actually both wrong, it should be 5px [per design specs](https://www.figma.com/design/01KWBdMZg5QM9SRS1pQq0z/Design-System----Robot-Styles?node-id=16374-60224&t=ARJuNYDjkamP6I9W-0) …

style(ui): Update Select component styles

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/usePlaygroundState.ts

https://wandb.atlassian.net/browse/WB-23842
the link in this ticket now loads instead of a full page crash
important for failed calls that might not have output

fix(weave): add a null check to prevent playground crash

---

weave_query/tests/ops_arrow/test_string.py
weave_query/weave_query/ops_arrow/string.py

JIRA: https://wandb.atlassian.net/browse/WB-23892
Follow-up to https://github.com/wandb/weave/pull/3905. This PR fixes the following ops:
* split
* partition
* startswith
* endswith
* join\_to\_str
* to_number 
A couple things to note:
* In several instances, we weren't handling null value cases (either for `arrow_data` or for the input string argument to the op). These are fixed and included in the tests.
* The `toNumber` op does not completely work correctly as floating point numbers will not be converted (e.g. 123.45) due to `utf8_is_numeric` ([docs](https://arrow.apache.org/docs/python/generated/pyarrow.compute.utf8_is_numeric.html)) considering that string to not be numeric. I tried fixing this for a bit, but it looks like most workarounds are pretty hacky. Since the focus of this PR …

chore(weave_query): Handle DictionaryArray inputs for another subset of AWL string ops

---

docs/docs/guides/integrations/index.md

We had a couple of integrations that were only added to the sidebar and not to the integrations index page. 
yarn start on docs

docs(weave): add 3 integrations to index page

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx

| ![before](https://github.com/user-attachments/assets/1573ce11-9e7c-4ddc-8014-030a2f9f5ea5) | ![after](https://github.com/user-attachments/assets/91ff36b3-a44c-4b8a-bddc-1c0ee4d080ab) |
This was present on old version of header bar, but is more apparent now.
When switching between Traces and Evals the selection doesn't clear - selecting Compare on Eval with the traces selected can cause a stalled page.
- Clears evals / traces when switching between views.
- Also adds / removes "s" on multiple traces / evals selected.

fix(ui): Clear traces / evals on page change

---

weave-js/src/react.tsx
weave/trace_server/validation.py
weave/trace_server/validation_util.py

- Fixes WB-23975
Modify regex matching on frontend to match any ID with or without dashes to support OTEL style ID strings. Change validation of call IDs and trace IDs to include OTEL style ID strings.

chore(weave): allow otel style ids for calls

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx

When clicking a ButtonOverlay component to navigate to a new URL, the navigation process was creating an unnecessary history entry. This happened because:
1. ButtonOverlay would navigate to the new URL
2. The already-mounted CallsTable component would then update the URL again by adding its column visibility state (`cols` parameter)
3. This resulted in two history entries: one for the navigation and one for the column visibility update
I refactored the column visibility state management to separate concerns:
1. Renamed props to be more explicit about their purpose:
```typescript
// Before
columnVisibilityModel?: GridColumnVisibilityModel;
setColumnVisibilityModel?: (newModel: GridColumnVisibilityModel) => void;
// After
columnVisibilityModelUrlParam?: GridColumnVisibilityModel; …
```

fix(weave): Prevent Double URL State Update in ButtonOverlay Navigation

---

weave-js/src/components/PagePanelComponents/Home/Browse2/CellValueImage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueViewImage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/typeViews/PIL.Image.Image/PILImageImage.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-23981
By default the `maxZoomPixelRatio` for our lightbox component is 1, meaning you can't zoom in beyond the image's actual size. This changes the max ratio to 5, which can be helpful for e.g. reading small text in an image.
https://yet-another-react-lightbox.com/plugins/zoom#Documentation
wf values example

feat(ui): allow zooming images in lightbox to 5x natural pixel size

---

weave/trace/op.py

- Fixes WB-23983
Provide a warning message to the user informing them that their traces will not be logged when weave.init has not been called.

chore(weave): warn user when weave is being used without `weave.init`

---

weave-js/src/components/Panel2/PanelDir/Component.tsx

- Fixes [WB-23664](https://wandb.atlassian.net/browse/WB-23664)
Passes down configuration information to Directory View Panel component. This is to allow blocking downloads of artifact files. 
Tested on local UI
[WB-23664]: https://wandb.atlassian.net/browse/WB-23664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ui): support blocking downloading files in directory view

---

docs/docs/guides/tools/playground.md

- Fixes https://wandb.atlassian.net/browse/DOCS-1358
Adds a section describing how to add a custom provider in Playground to https://weave-docs.wandb.ai/guides/tools/playground

docs(weave): document custom providers in playground

---

weave-js/src/components/Panel2/PanelRunHistoryTablesStepper/index.tsx

Step slider should skip over steps when no table (of the selected table key) was logged at that step.
Local FE
https://github.com/user-attachments/assets/4405a4c5-d199-4c4b-9269-5804d71eb47e

chore(app): Filter steps to non-null tables in runs history step slider

---

tests/trace/test_grid.py
weave/trace/grid.py

As part of the work on Saved Views in Python, I created this general purpose in-memory Grid class, included in 
https://github.com/wandb/weave/pull/3854
Pulling it out as a separate PR to reduce the size of the Saved Views PR and because it will be useful for query API evaluation. @tssweeney I believe you've already looked at this code.
Basic features include creating a table with typed columns, with rich-based display including interactively paging through larger tables. Grids can be converted to/from pandas for further analysis or conversion. Row/Column accessors are useful for things like unit testing.
Includes unit tests.

chore(weave): Add Grid utility

---

weave_query/tests/test_wb_data_types.py
weave_query/tests/test_wb_tables.py
weave_query/weave_query/ops_domain/table.py
weave_query/weave_query/ops_domain/wbmedia.py

- Follow-up to https://github.com/wandb/weave/pull/3807
- Implements the BE portion to enable https://wandb.atlassian.net/browse/WB-22188
- There's some un-related linting changes that got included so I've added some comments on the functional changes which is effectively just adding the attribute to the dataclass and providing a value for it when the `file-media` op is called.
* Local invoker on personal test workspace and also made sure some of the workspaces from the [sentry](https://weights-biases.sentry.io/issues/6360852706/?alert_rule_id=11833737&alert_timestamp=1741211855806&alert_type=email&environment=prod&notification_uuid=dee6ae8c-9ea3-4f5a-8c5d-d83352e7356b&project=6620563) we triggered before isn't crashing with the changes. …

feat(weave_query): Provide caption attribute in ImageArtifactFileRef

---

weave_query/tests/ops_arrow/test_string.py
weave_query/weave_query/ops_arrow/string.py

JIRA: https://wandb.atlassian.net/browse/WB-23892
Previous PRs: 
- Part 1: https://github.com/wandb/weave/pull/3905
- Part 2: https://github.com/wandb/weave/pull/3942
This should be the final PR and fixes the following ops to handle `DictionaryArray`s:
* \_\_eq\_\_
* \_\_ne\_\_
* \_\_contains\_\_ - Note: corrected the behaviour of this op a bit to handle null/`None` values based on how `pyarrow.compute.match_substring` handles null values
* string_add
* append
* prepend
Skipped the following ops that were planned to be modified:
* string\_right\_add - Not sure how this is supposed to differ from `string_add` or `append` and it also doesn't seem to be used anywhere so we can ignore this for now
* in\_\_ - This is hidden on the FE
Unit Tests, Local Invoker (see CSVs and screenshots in JIRA)

chore(weave_query): Handle DictionaryArray inputs for remaining AWL string ops

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/MessagePanelPart.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/types.ts

It turns out according to Anthropic docs:
> The result of the tool, as a string (e.g. "content": "15 degrees") or list of nested content blocks
This PR takes this into account.
- Tested on my own project with string results
- Tested on Sam's skills-assembly project

fix(weave): Fix Anthropic tool call results when content is array of blocks

---

tests/trace/test_server_file_storage.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/environment.py

Adds a comma-seperated `WF_FILE_STORAGE_PROJECT_ALLOW_LIST` to the file storage env variables to allow incremental rollout. Note: will need to use the internal project id.
A value of "*" enables for all projects

chore(weave): Add a project allow list to the bucket rollout

---

weave-js/src/components/Tag/Alias.tsx
weave-js/src/components/Tag/Tag.tsx

`RemovableTag` and `RemovableAlias` with truncated texts cause this console error:
https://github.com/user-attachments/assets/19d82512-9b7c-4278-a260-379839fb43aa
This is because we wrap the tag/alias in a tooltip when truncated. Tooltip triggers get `button` role for accessibility. The remove icon button is included as part of the tooltip trigger, which is the problem. This change moves the remove button outside of the truncation wrapper.
Console error no longer appears
https://github.com/user-attachments/assets/a5211b7f-950f-47db-a9d6-f13ce23f593a

chore(ui): Fix nested buttons in removable tag/alias

---

weave-js/src/components/PagePanelComponents/Home/Browse3/filters/SelectDatetimeDropdown.tsx
weave-js/src/components/Timestamp.tsx
weave-js/src/util/date.ts

Fix an issue with the datetime selector where the displayed Time was correct but the backend filter was incorrect. The backend filter was converting utc to local.
Now we just store everything in local where we can. 
prod:
branch:

chore(weave): fix hour bias by simplifying utc handling

---

weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/schemaUtils.ts

Always exclude `inputs.self` from the available call fields in the add to dataset flow.

chore(weave): exclude inputs.self from call data in add to dataset

---

weave-js/src/components/Panel2/PanelDir/Component.tsx

…or restricted viewers
Artifact file names turn blue over cursor hover, which misleads users into thinking the file is clickable/downloadable. This code removes that visual cue for restricted viewers.
Tested locally in SaaS
This is what the artifact file looks like on hover if you are not a restricted viewer:
If you are a restricted viewer who cannot download files:

chore(ui): Remove visual cue that artifact file is selectable for restricted viewers

---

weave-js/src/components/Panel2/PanelPlot/PanelPlot.tsx
weave-js/src/components/Panel2/PanelPlot/PanelPlot2Inner.tsx

Tracking JIRA: https://wandb.atlassian.net/browse/WB-24060
Adds a wrapper component around the inner panel plot components 😓 to compute the column variables for the latest panel context. We need to delay this until the refined node type is ready but also can't call the `useAutomatedTableState` React hook conditionally. 
This is part of a set of 3 PRs to get stepped plots work:
1. Refactor history runs table stepper (https://github.com/wandb/weave/pull/3992)
2. Refactor PanelPlots (This PR)
3. Add the plots stepper functionality (https://github.com/wandb/weave/pull/3995)
Local FE Invoker - Verified that plots still work with derived columns
https://github.com/user-attachments/assets/6f6fac03-8e79-4cc8-ace4-65f4cb02805f

chore(app): Delay computing column variables until typed node is ready

---

weave-js/src/components/Panel2/PanelExpression/hooks.ts
weave-js/src/components/Panel2/PanelRegistry.tsx
weave-js/src/components/Panel2/PanelRunsWithStepper/Plots.tsx
weave-js/src/components/Panel2/panellib/libpanel.ts

Tracking JIRA: https://wandb.atlassian.net/browse/WB-24060
**Note the base branch is `npun-wb-24060`**
Extends history tables stepper to plots. The config is slightly different from the tables case since we also need to render the `PanelPlot` config component
This is part of a set of 3 PRs to get stepped plots work:
1. Refactor history runs table stepper (https://github.com/wandb/weave/pull/3992)
2. Refactor PanelPlots (https://github.com/wandb/weave/pull/3994)
3. Add the plots stepper functionality (This PR)
Local FE Invoker
https://github.com/user-attachments/assets/62e09310-eda7-4f15-bc06-93e1f26a3732

feat(app): Implement runs history plots stepper

---

weave-js/src/util/date.ts

Previous handling attempted to ensure parsing made sense, but instead is way too strict. Remove footgun. 
| prod | branch | 
| ----- | ----- |
| <img width="679" alt="Screenshot 2025-03-28 at 12 51 17 PM" src="https://github.com/user-attachments/assets/f323b5c9-ced2-4d19-9126-5a815df0753c" /> | <img width="671" alt="Screenshot 2025-03-28 at 12 51 03 PM" src="https://github.com/user-attachments/assets/25d4ec82-bd6e-4ae2-b980-3a104dda5f40" /> |

chore(weave): remove footgun datetime handling

---

docs/CONTRIBUTING_DOCS.md
docs/scripts/generate_notebooks.py

- Fixes https://wandb.atlassian.net/browse/DOCS-1365
updates the generate_notebooks.py script to support converting a single .ipynb notebook to Markdown by passing the notebook path as a command-line argument. If no argument is provided, the script defaults to its original behavior of exporting all notebooks in the notebooks/ directory along with the intro notebook.
Also updates usage instructions in docs/CONTRIBUTING_DOCS.md
- yarn start  on local
- run script locally on single file to generate MD equivalent, confirm you can actually do this locally

docs(weave): improve python notebook conversion script

---

weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/environment.py

Add `WF_CLICKHOUSE_MAX_MEMORY_USAGE` to control the single query maximum ch memory

chore(weave): parameterize clickhouse single query max mem usage

---

tests/conftest.py

By default when running test against clickhouse-backed trace server, the test run will erase the data in the `default` database, which jeopardizes the local dev environment. One way to work around it is to use WF_CLICKHOUSE_DATABASE env var.
However, when I use this command to run a test against the clickhouse server:
```
WF_CLICKHOUSE_DATABASE=test nox -e "tests-3.12(shard='trace')" -- --weave-server=clickhouse
```
Because the conftest is hard coded to use the `default` database, the execution will fail. This PR fixes that. 
However I recommend using an alternative port, which is also supported in [this internal PR](https://github.com/wandb/core/pull/28414).
Locally verified by running test.

chore(weave): read CH database settings in test

---

tests/trace/test_traverse.py
weave/trace/traverse.py

Extracted from https://github.com/wandb/weave/pull/3854/
As part of Saved Views you can specify a path to an item within a JSON object representation, drilling in by object key or array index. This is used e.g. for extracting `inputs.foo[2].bar` as a column. This Python code for traversing objects is inspired by similar methods we have in the UI.
@tssweeney I believe you've looked at this code previously.
Includes unit tests

chore(weave): Add object traversal utilities

---

weave-js/src/components/Panel2/PanelDir/Component.tsx

This removes the hover effect for files that are not downloadable or clickable.
Files that are downloadable over hover:
Files that are NOT downloadable over hover:
Tested locally in SaaS
Registry available for testing: https://wandb.ai/orgs/wandb/registry/ruhi-test-registry

style(ui): Disable hover effect on non-downloadable files

---

weave-js/scripts/generate-schemas.sh
weave-js/scripts/resolve_schema_circular_refs.py
weave/scripts/resolve_schema_circular_refs.py
weave/trace_server/interface/builtin_object_classes/generated/generated_builtin_object_class_schemas.json

When generating zod types, circular references cause issues. This PR identifies circular references and fixes them before generation occurs. More advanced replacement could be designed in the future if desired.
This unblocks saved views using Query in the type definition.
I explored more creative ways for unrolling nested structures, but they got overly complicated. Can always make this better in the future.

chore(weave): Fix type generation to replace circular references with Anys

---

docs/docs/guides/evaluation/weave_local_scorers.md
docs/sidebars.ts

- Fixes https://wandb.atlassian.net/browse/DOCS-1387
1. docs/docs/guides/evaluation/weave_local_scorers.md was missing from sidebar, this adds it in 
2. Fixes various grammar and spelling issues in file

docs(weave): Add local weave scorers doc to sidebar, cosmetics

---

tests/trace/test_client_trace.py
tests/trace_server/test_calls_query_builder.py
tests/trace_server/test_clickhouse_trace_server_batched.py
tests/trace_server/test_sqlite_trace_server.py
weave/trace_server/calls_query_builder.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/sqlite_trace_server.py
weave/trace_server/trace_server_interface.py

This PR adds the ability to query storage size information for calls in the trace server. It introduces two new features:
1. Individual call storage size
2. Rolled-up storage size for entire traces
- Added new fields to `CallSchema`:
- `storage_size_bytes`: Size of metadata storage for individual calls
- `total_size_bytes`: Total size of metadata storage for entire traces
- Added new query parameters to `CallsQueryReq`:
- `include_storage_size`: Returns storage size for each call
- `include_rolled_up_storage_size`: Returns total size for root calls only
- Implemented storage size calculation in both SQLite and ClickHouse trace servers
- Added unit tests for both features
- For SQLite: Uses `length()` function to calculate storage size from JSON fields
- For ClickHouse: Uses …

feat(weave): adds api capability to include storage size

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/generatedBuiltinObjectClasses.zod.ts
weave/trace_server/interface/builtin_object_classes/builtin_object_registry.py
weave/trace_server/interface/builtin_object_classes/generated/generated_builtin_object_class_schemas.json
weave/trace_server/interface/builtin_object_classes/saved_view.py

Add and registers the builtin object definition of a Saved View. First commit is the actual change, second commit is the codegen.
Saved View Python API tests. (Will be in future PR)

chore(weave): Saved View builtin object definition and registry

---

weave-js/src/common/components/elements/NumberInput.tsx

The arrows could be pushed out of the input box if the input was less wide, because the number input has a default margin right of 4 px. We can just set it to 0px.
Before:
After:

chore(app): Fix alignment of arrows on NumberInput

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTableNoRowsOverlay.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableQuery.ts

Simplify datetime handling for older projects. This pr: 
- Show the correct either no traces or none within the filter range screen for the evaluation page too (even though we don't do defaults on the top level, you can get there by clicking on evaluation children)
- Now, if we don't find any calls in the last 30 days, we don't even try to set a default. The motivation for this is that very high velocity projects probably will have logged in the past month. We never want users of old projects to see no traces, this ensures that. 
- Now when you click the "expand daterange" button we skip 90 and 180 days, just go from 30 days to 1y. 
- When we clear the daterange after expanding, change the text to reflect that 
Using tims really old hooman …

chore(weave): less aggressive default date filters

---

weave-js/src/components/Timestamp.tsx

[WB-24241](https://wandb.atlassian.net/browse/WB-24241)
Convert anything thats a nice even (ish) multiple of a year into `1y` in the timestamp filter bar.
prod:
branch:
[WB-24241]: https://wandb.atlassian.net/browse/WB-24241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(weave): convert 12m to 1y

---

weave-js/src/react.tsx

- Fixes WB-23821
- Fixes WB-21343
There's no point in restricting artifact names to only ASCII characters.
If we need these checks, they should be handled at the server or SDK level (during creation).
Since users often use CJK characters for dataset names and other objects without issues, I'm temporarily relaxing the frontend regex restrictions.
I tested the scenario of 
1. Getting the dataset details which uses CJK characters
2. Compare evaluations using a dataset with CJK characters
These scenarios were previously broken without this change.

fix(weave): Loosen the regex check to accept potentially CJK characters

---

pyproject.toml

Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1744045751469129
The scorers shard of our CI tests was broken. The symptom is `NameError: name 'init_empty_weights' is not defined` - I think this was caused by the [April 5th release of the transformers library](https://pypi.org/project/transformers/#history) - it looks like a [fix landed today](https://github.com/huggingface/transformers/pull/37337) - but since we don't know when that will get released I am pinning to an older version for now.

chore(weave): pin transfomers library

---

weave-js/src/components/Panel2/PanelRunsWithStepper/HistoryTables.tsx
weave-js/src/components/Panel2/PanelRunsWithStepper/base.tsx
weave-js/src/components/Panel2/PanelTable/PanelTable.tsx
weave-js/src/components/Panel2/PanelTable/config.ts

- Implements [WB-24174](https://wandb.atlassian.net/browse/WB-24174)
- Moves the filter button out into an action bar above PanelTable
- Additionally adds a button to allow for selection between tables (when the appropriate config fields are passed into the component)
- Move the current table selection in the stepper from the Query Panel config to the action bar
Local Invoker FE
Verify filtering still works:
https://github.com/user-attachments/assets/5217d92f-1665-467f-a532-feeb7091c62d
Verify table selection works:
https://github.com/user-attachments/assets/c0f74693-4bc4-4f55-9e5a-664cb62b3d3b
Verify filtering works with regular tables (e.g. `run.summary[<table>]`)
https://github.com/user-attachments/assets/9baa49e7-89c1-4a7e-ac75-1294db4b9190
[WB-24174]: …

chore(app): Create an action bar for PanelTable and include filter and table selection options

---

weave/integrations/openai_agents/openai_agents.py

The openai-agents sdk integration looks for usage data in a place on the `GenerationSpanData` that does not exist and deterministically crashes the user process. This PR updates the attribute access to read from the correct field.

fix(weave): remove deterministic attribute error from openai agents integration

---

weave/trace/wandb_termlog_patch.py
weave/trace/weave_init.py

This is a temporary patch for `wandb` in order to implement basic referrer tracking in
auth URLs. This commit: https://github.com/wandb/wandb/commit/5db4d763516ba2a3e8d94a85ba67bdf6fc124423 adds a utility for referrer tracking, but is not yet released. Once released, this patch can be removed and instead https://github.com/wandb/weave/pull/4004/files can be merged. Since this will take more than a month, we need a short-term patch to ensure that we can start to track referrers.

chore(weave): Temporary patch for auth url referrer

---

weave-js/src/components/Timestamp.tsx

one-liner fix for displaying week timestamps when actually a week. 0 weeks is not valid.
Prod:
Branch:

chore(weave): dont show weeks unless at least one week

---

pyproject.toml

`import weave` fails with `ModuleNotFoundError: No module named 'opentelemetry'`. This PR moves `opentelemetry-proto` from an optional to required dependency. It's eagerly imported by `trace_server_interface.py` which runs on `import weave`. Alternate approach would be to conditionally import.

fix(weave): require opentelemetry proto

---

weave-js/src/components/PagePanelComponents/Home/Browse3/components/TraceNavigator/TraceViews/TreeView.tsx

- On expanding trace tree nodes, leave descendants collapsed.
- Allows for quicker parsing of large complex trace trees.

chore(ui): Trace tree - leave descendants collapsed on expanding

---

weave-js/src/components/PagePanelComponents/Home/Browse3/components/TraceNavigator/TraceViews/TreeView.tsx

| ![Screenshot 2025-04-08 at 3 28 19 PM](https://github.com/user-attachments/assets/f0a11e16-01ec-4e3b-9cb5-e40cef9e9bd3) | ![Screenshot 2025-04-08 at 3 27 23 PM](https://github.com/user-attachments/assets/a7bd5490-0460-4917-9576-57cc3800783d) |
- Fixes padding on un-nested node levels to match nested text (since they're on the same level).

chore(ui): Trace tree - fix padding on un-nested node levels

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallDetails.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx

- Fixes WB-24306
Adds a conditionally available section to the ObjectView which displays full otel trace metadata when the field is available.

feat(ui): Conditionally add trace metadata to ObjectView

---

tests/trace/test_weave_client.py
tests/trace_server/test_calls_query_builder.py
weave/trace_server/calls_query_builder.py
weave/trace_server/sqlite_trace_server.py
weave/trace_server/trace_server_common.py

[WB-24092](https://wandb.atlassian.net/browse/WB-24092)
TODO:
- do we want to set this to log a warning instead of raising? It's technically possible users are using the app around its limits here and will be forced to change their workflow. We could track the errors? probably not necessary, there are very few use cases for spamming thousands of ids, other endpoints cap it at 1000 like delete. 
We can't handle more than a couple thousand parameters in the calls query filter because the clickhouse client passes parameters in the URL, instead of in a post body payload like a sane request...
This pr limit each of these hardcoded filters to 1000. 
- Add unit test
- add end to end client test
[WB-24092]: https://wandb.atlassian.net/browse/WB-24092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …

chore(weave): cap hardcoded filters to 1000

---

weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/AddToDatasetDrawer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/DatasetDrawerContext.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/__tests__/DatasetDrawerContext.test.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/schemaUtils.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/OverflowMenu.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooksCallRefExpansion.ts

Calls have refs in their inputs and outputs recursively resolved before being added to a dataset.
The calls table now passes selected calls by ID to the drawer. The drawer then queries for the calls by ID and then uses the `useClientSideCallRefExpansion` hook to expand the refs. This PR adds a `recursiveUnwrap` option to the hook which causes the provided paths for expansion to be recursively expanded, ie if a ref resolves to a value that contains a ref, the inner ref is also resolved.

fix(ui): expand refs in call objects when adding to dataset

---

weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableQuery.ts

[WB-24343](https://wandb.atlassian.net/browse/WB-24343)
Type fix from high level query to low level query, which affects the use of `parentId` in filters used to determine the default date range. 
prod:
branch:
[WB-24343]: https://wandb.atlassian.net/browse/WB-24343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(weave): convert filter for query used in default time windor

---

weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterRow.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterTagItem.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterTagStatus.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/SelectValue.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/ValueInputStatus.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/common.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableColumns.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/StatusChip.tsx

Wires up the UI to allow filtering by status, either through the filter popup form or Option+Click. Backend support for this was added in https://github.com/wandb/weave/pull/3797
Also makes Option+Click more useful. Currently doing Option+Click on the same value adds multiple duplicate filters. With this PR we change it so a second Option+Click will either toggle the filter off or replace it with an updated one (e.g. in the case where you have an `OR` of status values and want to filter to one.)

feat(ui): Add status filtering

---

weave-js/src/components/Panel2/PanelStepper/component.tsx
weave-js/src/components/Panel2/PanelStepper/configComponent.tsx
weave-js/src/components/Panel2/PanelStepper/index.tsx
weave-js/src/components/Panel2/PanelStepper/types.tsx

- Implements [WB-24236](https://wandb.atlassian.net/browse/WB-24236)
- Adds a selection to the stepper panel config to allow the user to select the step key.
- Valid step keys are those where the values are all integers, but can contain null values (e.g. in the case where a custom step key is logged for one run but not for another).
- We ignore monotonicity since the data could span across runs (e.g. `runs.history`), in which case the entire sequence may not be monotonic 
Local FE Invoker
https://github.com/user-attachments/assets/47de0543-7426-4b03-a619-fc9f1dbb718c
[WB-24236]: https://wandb.atlassian.net/browse/WB-24236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(app): Allow selection of custom step metric in stepper panel

---

tests/trace/test_client_trace.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/sqlite_trace_server.py

[WB-24344](https://wandb.atlassian.net/browse/WB-24344)
This pr adds additional columns to the calls query process when a user requests  a calls query that returns a `summary` but does not already have the required columns. This happens when a user explicitly sets columns to include `summary` (but not other columns) or sets the `include_costs` flag.
When a user requests a `summary` payload or `include_costs`, now we select the following additional columns:
- `ended_at`
- `display_name`
- `exception`
todo add unit
master:
branch:
[WB-24344]: https://wandb.atlassian.net/browse/WB-24344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(weave): add other required columns when `summary` requested

---

pyproject.toml

crewai release 0.114.0 is broken on Python 3.10. See:
https://github.com/crewAIInc/crewAI/issues/2543
https://github.com/crewAIInc/crewAI/pull/2553
This is temporarily pinning the version to be not greater than the previous release, 0.108.0 to fix CI.

chore(weave): crewai release broken on 3.10

---

tests/trace/test_server_file_storage.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/file_storage.py

This is a pure refactor of the file storage mechanics such that the trace server client only has instantiates a single connection to the bucket. As implemented today, a client connection is minted for each request which is not as performant as it could be. 
Furthermore, it correctly decouples the loading of an environment-configured client from something that could be generated at runtime. This is the first step to moving to the better auth system.

chore(weave): Create long-live storage clients per instance

---

docs/docs/guides/tools/otel.md
docs/sidebars.ts

- Fixes https://wandb.atlassian.net/browse/DOCS-1390
Documents the new OpenTelemetry functionality based on @zbirenbaum's PR and draft
Location in docs: Productionization > Tools & Utilities because:
- It’s a technical integration guide for configuring an external system to send data to Weave similar in spirit to other tools like serve or deploy.
- It supports production-level observability and monitoring workflows, which align with the broader goals of the Productionization section.
- It's not tied to a specific LLM or framework, so it doesn't make sense in the "Integrations" section.

docs(weave): OpenTelemetry docs

---

weave/trace/weave_init.py

Defer import of sqlite trace server until the very rare init_local case. 
Prod:
```python
>>> import weave
File "<stdin>", line 1, in <module>
File "/Users/griffin/Desktop/core/services/weave-python/weave-public/weave/__init__.py", line 4, in <module>
from weave.trace.api import *
File "/Users/griffin/Desktop/core/services/weave-python/weave-public/weave/trace/api.py", line 12, in <module>
from weave.trace import urls, weave_client, weave_init
File "/Users/griffin/Desktop/core/services/weave-python/weave-public/weave/trace/weave_init.py", line 12, in <module>
from weave.trace_server import sqlite_trace_server
File "/Users/griffin/Desktop/core/services/weave-python/weave-public/weave/trace_server/sqlite_trace_server.py", line 34, in <module>
from …
```

fix(weave): lazy import sqlite server for otel support

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableColumns.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableQuery.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClientTypes.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts
weave-js/src/util.ts

- Fixes WB-23748
Add storage size column to CallsTable
Changes:
- Added storage size column to display total storage usage for each call
- Implemented loading state handling with LoadingDots component
- Added proper null checking for storage size values
The storage size column shows human-readable byte sizes (e.g., "1.5 MB") and handles loading states appropriately.
Please also refer this [mini design doc(private)](https://www.notion.so/wandbai/Data-Size-display-1bde2f5c7ef38087bc03cb8accb95bfb?pvs=4#1cfe2f5c7ef3805e9f73f9ddc4575460) for greater context.
At the beginning of implementing this PR, I debated myself how to load the data for this additional column.
The `/calls/stream_query` API  is capable of either:
1: accepting a group (about 50) of call_ids, and do table joins to calculated …

feat(weave): Display trace storage size in Trace view

---

weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/sqlite_trace_server.py
weave/trace_server/token_costs.py
weave/trace_server/trace_server_interface_util.py

After removing some code in https://github.com/wandb/weave/pull/4091 that I happened to notice wasn't used anywhere, I remembered that there are tools like [vulture](https://github.com/jendrikseipp/vulture) that can help with finding unused code. This is removing just a few of its detections.

chore(weave): remove unused code

---

pyproject.toml

See https://github.com/wandb/weave/pull/4062 - latest release of transformers fixes the reason we had to have the version constraint.

chore(weave): unpin transformers library

---

weave/trace/weave_client.py

Consider the API call:
```
import weave
client = weave.init("jamie-rasmussen/2025-04-11_values")
calls = client.get_calls(
filter={"trace_roots_only": True},
query={"$expr":{"$gt":[{"$getField":"started_at"},{"$literal":1743780131.121}]}},
sort_by=[{"field":"started_at","direction":"desc"}],
limit=1000,
offset=0,
)
```
This returned 110 results. If I run the query with an offset greater than that, e.g.
```
import weave
client = weave.init("jamie-rasmussen/2025-04-11_values")
calls = client.get_calls(
filter={"trace_roots_only": True},
query={"$expr":{"$gt":[{"$getField":"started_at"},{"$literal":1743780131.121}]}},
sort_by=[{"field":"started_at","direction":"desc"}],
limit=1000,
offset=500,
)
```
I will get: `ValueError: __len__() should return >= 0`

fix(weave): length calculation when offset > available

---

weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterBar.tsx

[WB-24373](https://wandb.atlassian.net/browse/WB-24373)
Typing into the string filter leads to many more queries than necessary. Example:
- [11s query](https://us5.datadoghq.com/logs?query=trace_id%3A67f7fe1c00000000285d6f06728f0022&cols=host%2Cservice&event=AwAAAZYguMhY6jqs4AAAABhBWllndU02QUFBQ0xnOHI2S2E4dU9RQVkAAAAkMDE5NjIwYmMtZGU0Zi00N2YwLThmYzMtYzI0NWM2MGZkNDg1AAaBMQ&fromUser=true&index=&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&viz=stream&from_ts=1744304692493&to_ts=1744306703588&live=false) from user just bringing up the filter (before even typing)
- Then the actual[ full filter query](https://us5.datadoghq.com/logs?query=trace_id%3A67f7fe2f00000000e97a4c881cd8fa88&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AwAAAZYguPNQIyesygAAABh …

chore(weave): improve filter interactions, fewer refreshes

---

tests/trace_server/test_calls_query_builder.py
weave/trace_server/calls_query_builder.py

[WB-24386](https://wandb.atlassian.net/browse/WB-24386)
In this pr we handle the `op_name` separately from the other having conditions. So we can pull it before the group by. Because ALL call starts are guaranteed to have an `op_name` we can always filter by `op_name LIKE <> or op_name is NULL` to grab all possible rows that match. 
Example:
```sql
SELECT calls_merged.id AS id
FROM calls_merged
WHERE calls_merged.project_id = {pb_263_2:String}
-------------------------
AND ((calls_merged.op_name LIKE {pb_263_1:String}) OR (calls_merged.op_name IS NULL))
-------------------------
GROUP BY (calls_merged.project_id,
calls_merged.id)
HAVING (((any(calls_merged.started_at) > {pb_263_0:Float64}))
AND ((any(calls_merged.deleted_at) IS NULL))
AND ((NOT ((any(calls_merged.started_at) IS NULL))))) …
```

perf(weave): filter op_name pre group by 

---

tests/trace/test_weave_client.py
weave/trace/weave_client.py

[WB-24388](https://wandb.atlassian.net/browse/WB-24388)
We are doubling the offset when we fire the fetch func when we provide an offset override to PaginatedIterator. 
adds unit test
[WB-24388]: https://wandb.atlassian.net/browse/WB-24388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(weave): paginated iterator offset fix

---

weave-js/src/common/components/elements/NumberInput.tsx
weave-js/src/common/components/elements/SliderInput.tsx
weave-js/src/common/css/NumberInput.less

This updates the NumberInput to have an option for the newest designs with a +/- stepper. Since the wider width may not be compatible with older usages, I added an optional prop so that it's opt-in as older ones are migrated. 
See designs here: 
https://www.figma.com/design/BsoKhzDe7Q8OX08owa9DuM/Media-panel-improvements?node-id=5257-141396&m=dev
Tested in https://github.com/wandb/core/pull/28695. It should only be enabled in that one place, which is currently behind a ramp flag.

chore(app): Update NumberInput to new designs

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/llmMaxTokens.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/usePlaygroundState.ts
weave/trace_server/costs/cost_checkpoint.json
weave/trace_server/model_providers/model_providers.json

also reorgs dropdown to have newer models closer to the top
updates costs and model providers to have 4.1 models
https://github.com/user-attachments/assets/311bf432-0973-4c7e-90dc-2a0eade8366a

chore(weave): Add gpt4.1 models, makes 4.1-mini the default

---

weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterBar.tsx

[WB-24415](https://wandb.atlassian.net/browse/WB-24415)
This pr: 
- increases the debounce time from 700ms to 1s
- fixes an issue with the string filter where rapidly deleting the filter results in the last character reappearing
- Now we explicitly keep track of incomplete filters. We only submit filters that are complete, and keep in local state the rest. This is only when a filter row has been modified from complete to incomplete. Instead of removing the entire row, which causes a large UI change and the filter to disappear, we keep it around in local state and render it with the value field as empty (which is what you expect as a user). 
- This should feel exactly the same as the current flow, without the reappearing character bug, _and_ now when the filter is incomplete we query the …

chore(weave): increase filter bar debounce + fix character reappearing

---

weave/trace/weave_client.py

Internal Slack: https://weightsandbiases.slack.com/archives/C0880TX4U5V/p1744740337426419
We aren't recursing into tuples in the `map_to_refs` part of our serialization. The symptom was that a Pydantic object inside the tuple was getting rendered as a string.

fix(weave): serialization in map_to_refs wasn't recursing into tuples

---

weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/DatasetDrawerContext.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/SchemaMappingStep.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/__tests__/DatasetDrawerContext.test.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/schemaUtils.test.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/schemaUtils.ts

The add to dataset ui extracts schema for call data and datasets. This PR modifies the logic of schema extraction to treat all objects and arrays encountered during object traversal as a blanket object and array types.
This PR also adds separate methods in the schema utils for extracting the schema from call data and datasets. The logic is different we should have separate implementations with some common dependencies.
Here is an example trace with list of objects https://wandb.ai/bcanfieldsherman/hello/weave/traces?peekPath=%2Fbcanfieldsherman%2Fhello%2Fcalls%2F0196362e-b5a6-7380-bc6b-38f5fecc7a36
Here is a before and after of creating a new dataset from the call liked above:
Before
After

fix(ui): limit expansion of nested call data in add to dataset flow

---

weave-js/src/common/components/elements/NumberInput.tsx
weave-js/src/common/css/NumberInput.less

This centers the input so it looks nicer in between the plus and minus buttons. It also tries falling back to the placeholder value in case that's a number so that we can have an empty input but have the arrows work to get from placeholder '1' to value '2' for example.
https://github.com/user-attachments/assets/e70257b8-615b-49a3-a4c0-5a875817b942

chore(app): Center number input and handle empty values better

---

weave/trace/urls.py

`remote_project_weave_root_url` only used by `project_weave_root_url` which does the same thing.

chore(weave): remove unnecessary function

---

weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/AddToDatasetDrawer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/NewDatasetSchemaStep.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/SchemaMappingStep.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/schemaUtils.ts

This PR includes annotations in the set of call fields that can be mapped to dataset columns in the add to dataset flow. Annotations will appear in the schema mapping step for new and existing datasets, see below:
The column name can be changed for new datasets but will default to the name of the annotation:
This PR also includes handling for scorer output on a call, but the code disables these from appearing in the list of available fields. There may be a good use case for this now but it may also just clutter the options.

feat(weave): include annotations when adding calls to dataset

---

tests/trace/test_client_trace.py
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallSummary.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/cache.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClientTypes.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts
weave-js/src/util.ts
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/token_costs.py

This PR adds storage size information to the call summary page, providing users with visibility into the storage footprint of their calls and traces.
Here is [a mini design doc](https://www.notion.so/wandbai/Data-Size-display-1bde2f5c7ef38087bc03cb8accb95bfb) for the context.
- Added storage size display for individual calls, showing the sum of the size of inputs, outputs, attributes, and summary data
- Added total storage size display for root traces
- Included a tooltip explaining that the size doesn't include referenced objects (e.g., images or audio blob storage)
- Added storage size information to the trace server API and data model
Root trace call:
Non-root call:
- Frontend:
- Added new storage size display components with human-readable byte formatting
- Extended the call cache to …

feat(weave): Show storage size on call summary page

---

tests/trace/test_custom_objs.py
weave/trace/serialization/custom_objs.py

We were leaking a bunch of custom type loading events - not good

fix(weave): Do not trace custom type loading

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx

Only render the add to dataset drawer if the drawer is open. The drawer was rendering unnecessarily when the selected calls changed.

chore(ui): conditionally render add to dataset drawer only if open

---

tests/trace/test_client_trace.py
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/common.ts
weave/trace_server/calls_query_builder/calls_query_builder.py

- Fixes a bug that impacts production right now
1. Disables total_storage_size_bytes as a filterable column in the filter dropdown.
2. Add detection logic in the query builder which rejects unexpected filter conditions. 
Manually tested the UI,
Added a unit test for `#2`

fix(weave): fixes the case tha Trace Size becomes a filter condition

---

weave-js/src/components/PagePanelComponents/Home/Browse3/context.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/CompareEvaluationsPage.tsx

When you click the "Return to Evaluations" button on the Evaluation Compare page, it was taking you to the traces page with a filter, rather than to the evaluations URL.
Prod: Note the "Traces" in the breadcrumbs and nav sidebar.
PR:

fix(ui): evaluation compare goes back to evals

---

tests/trace_server/test_opentelemetry.py
weave/trace_server/opentelemetry/attributes.py
weave/trace_server/opentelemetry/constants.py
weave/trace_server/opentelemetry/python_spans.py

- Fixes WB-24499
creates new `wandb.display_name` check for otel attributes to allow setting `display_name` for call through traces
added unit tests

feat(weave): allow setting display name through weave attribute

---

tests/trace_server/test_opentelemetry.py
weave/trace_server/opentelemetry/attributes.py
weave/trace_server/opentelemetry/constants.py
weave/trace_server/opentelemetry/python_spans.py

- Fixes WB-24515
Required for #4143
Example for OpenInference (input.value and output.value are the attributes in the OTEL span)
Note: While it the key display is a bit wonky since input.value is parsed as two layers of headers, that's for the frontend to handle not the backend.

feat(weave): use otel attribute keys as input and output subfields

---

weave-js/src/components/ToggleButtonGroup.tsx
weave-js/src/components/Tooltip.tsx

https://wandb.atlassian.net/browse/WB-23072 
If the trigger of a tooltip is detached from the DOM for whatever reason, this prop detaches the Tooltip as well so that it's not just floating on nothing.
Tested in https://github.com/wandb/core/pull/28848

chore(app): Add hideWhenDetached prop to ToggleButtonGroup Tooltip

---

weave-js/src/components/PagePanelComponents/Home/Browse3/filters/common.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/tabularListViews/operators.ts

[WB-24546](https://wandb.atlassian.net/browse/WB-24546)
Add a "not equals" string operator selectable from the frontend filter bar.
[WB-24546]: https://wandb.atlassian.net/browse/WB-24546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(weave): add frontend not equal string operator

---

docs/docs/guides/core-types/prompts.md

Fix typo on prompts page
- Fixes https://wandb.atlassian.net/browse/DOCS-1427

docs(weave): typo in prompts.md

---

weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterTagItem.tsx

This is a little ugly. For context, night mode inverts everything with a CSS filter, and then an additional rule for images normally inverts that (not perfectly, but that's besides the point here). However, tags, including the Filters tag, use a `useTagClasses` hook which applies `night-aware` which overrides this. The solution in this PR is to apply night-aware to just the user filter tag contents to invert that yet again, making the profile picture look right.
A better solution would be to figure out why tags were set to be night aware not just for themselves but for their children as well. However, that would require a larger code audit than I think we want to take on right now.
Before:
After:

fix(ui): inverted photo in filter tag

---

tests/trace/test_client_trace.py
tests/trace/test_objects_query_builder.py
tests/trace/test_table_query.py
weave/trace_server/clickhouse_schema.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/external_to_internal_trace_server_adapter.py
weave/trace_server/objects_query_builder.py
weave/trace_server/sqlite_trace_server.py
weave/trace_server/table_query_builder.py
weave/trace_server/trace_server_interface.py
weave/trace_server_bindings/caching_middleware_trace_server.py
weave/trace_server_bindings/remote_http_trace_server.py

This PR adds support for displaying storage size information in the object details view and table statistics. It consists of mostly the backend changes, and minimum frontend changes to fit the interface changes related to object storage size only.
TLDR, I changed the following two APIs to include storage size information
```
/objs/query  ---> this will be used to retrieve each individual object version's storage size,
/table/query_stats_batch ---> this will be used to retrieve each table's storage size from all of its rows.
```
After this PR is merged. The internal PR https://github.com/wandb/core/pull/28783 should merge soon.
As a reference, the Frontend change that is going to utilize the API endpoint in this PR can be reviewed [here](https://github.com/wandb/weave/pull/4142).
1. …

feat(weave): Support emitting storage size in object details view (trace_server)

---

weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterRow.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/common.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/tabularListViews/operators.ts

[WB-24553](https://wandb.atlassian.net/browse/WB-24553)
Add a "does not contain" string filter operator. Increase the width of the operator dropdown. 
[WB-24553]: https://wandb.atlassian.net/browse/WB-24553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(weave): add "does not contain" string filter

---

weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/CellRenderers.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/DatasetEditorContext.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/EditPopover.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/EditableDatasetView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/editors/CodeEditor.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/editors/DiffEditor.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/editors/TextEditor.tsx

- We were using the datagrid api's edit mode control, which meant we were managing a piece of datagrid state and also adding separate components for rendering the cells in edit and non edit modes. This was not necessary and has been replaced with a single component.
- Moves some repeated logic for updating the editor state into a hook into the editor context called `updateCellValue`, which hides the details of the update logic from the components that accept new cell values from the user.
- Moves control of the editor mode and the assembly of the children editor components from the cell renderers file and into the edit popover component.

refactor(dev): simplify dataset cell renderers

---

weave-js/src/components/PagePanelComponents/Home/Browse3/filters/VariableChildrenDisplayer.tsx

Fixes this error:
This was also the root cause behind a Saved Views bug with filters.

fix(ui): react 18 createRoot warning

---

weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/CellRenderers.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/DatasetEditorContext.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/EditPopover.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/editors/CodeEditor.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/editors/DiffEditor.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/editors/TextEditor.tsx

Enable editing of list valued dataset cells in the UI. Prior to this PR list values are not editable and users see a tooltip saying the cell can't be edited.
Now list values can be edited as json in the same popout editor used for strings. Only code and diff mode can be used and json syntax highlighting is applied. The popover editor cannot be closed while the value is invalid json or not a list. Validation errors are shown in a footer at the bottom of the editor.

feat(ui): edit list valued dataset cells

---

tests/trace_server/test_opentelemetry.py
weave/trace_server/opentelemetry/attributes.py
weave/trace_server/opentelemetry/constants.py
weave/trace_server/opentelemetry/helpers.py
weave/trace_server/opentelemetry/python_spans.py

- Fixes WB-24513
- Fixes WB-24514
This adjusts the parsing logic to make it simple to generate and keep docs in line with the parser code. This adjusts the parser such that a set of standard fields are created for each of input, output, summary and attributes. Each field is assigned a list of keys which are checked until a valid entry is discovered or the possible key entries are exhausted.
Also includes cost calculation fix

feat(weave): Refactor otel parsing to standardize fields

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/ecpTypes.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ExampleCompareSection/ExampleCompareSection.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ExampleCompareSection/exampleCompareSectionUtil.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooksEvaluationComparison.ts

This addresses a part of the evaluation comparison performance issue. No the customer scenario will no longer crash. 
UI wise, there is no noticeable behavior change.
Here I attach [a video(internal)](https://www.loom.com/share/e07ee35dcd464094bc06aebf97fb8962?sid=691778a9-6156-4b2f-884a-095f3a78d29c) to explain the change.
This PR is manually tested against the customer scenario and locally.

perf(weave): address data loading perf issue on eval compare

---

weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/DatasetDrawerContext.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/schemaUtils.ts

https://wandb.atlassian.net/browse/WB-23507
Adds notes and feedback as includable call fields in the add to dataset flow. Both fields will be added as string lists containing the notes as separate strings and the reactions as separate strings.
The default name for the columns are `notes` and `reactions` respectively.
https://github.com/user-attachments/assets/c81ea128-1915-41cf-918d-154034f1a1ac

feat(ui): include notes and reactions when adding calls to datasets

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallSummary.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts

Currently, all unfinished calls fail to load, resulting in really bad user experience.
2 bugs:
1. When returning no call, we just show loader - this is fixed now to show "No call found"
2. When loading the call page, if a call is still running, AND we request costs, the backend incorrectly returns 0 calls. This is a bug!. I added a UI fix to load this in two steps (inefficient, but fixes for now)

fix(weave): Fixes call view loading hand for unfinished calls

---

.gitignore

Just prevents git from checking in pyrightconfig.json which is a very useful tool for configuring editor environment.

chore(weave): Add pyrightconfig.json to gitignore

---

tests/trace/test_client_trace.py
tests/trace_server/test_calls_query_builder.py
weave/trace_server/token_costs.py

Fixes issue where unfinished calls returned nulls in the cost query
2 errors
1. if we did default to the proper empty usage json, it was not properly escaped and the query would error returning null
fixed default usage not being properly escaped
2. we needed to account for the default usage being {}
https://github.com/user-attachments/assets/2a8eaa17-5a9b-4db0-a473-6b96a40f1452
updated test
check the fetching works for finished, unfinished and failed calls

chore(weave): Fix nulls returning from cost query

---

weave_query/tests/test_cache.py
weave_query/weave_query/cache.py

Update incorrect example in docstring and verify example behaviour in unit tests
--- 
<details>
<summary>PR was updated to only change the docstring and unit tests, here's the original PR description</summary>
This PR corrects the behaviour of our cache bucketing method to what I believe is the intended implementation.
---
Currently, timestamps starting at the current interval and up to the next interval will be assigned into the same bucket. Concretely, given an interval of 7 days and the days: [day 0, day 1, ..., day 6]. All 7 days will be assigned the "day 7" bucket. Consequently, the following unit test will fail: 
```
def test_bucket_should_advance_when_time_passes(self):
INTERVAL_DAYS = 7
INITIAL_TIME = 100
with mock.patch("time.time", return_value=100):
initial_bucket = …
```

chore(weave_query): clarify behaviour of cache bucketing

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallSummary.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/cache.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts

Sig:
```
const useCall = (
key: CacheableCallKey | null,
opts?: {includeCosts?: boolean; includeTotalStorageSize?: boolean}
):
```
Caller Code:
```
const call = useCall(
{
entity: props.entity,
project: props.project,
callId: descendentCallId,
withTotalStorageSize: true,
},
{
includeTotalStorageSize: true
}
);
```
We shouldn't ask the user to have the withTotalStorageSize in the first part of the param. the useCall should abstract that detail away and use the second param options as additional key values if appropriate
Manually re-validated the related UX, and saw no breakage.

chore(weave): Refactor the cache key usage

---

weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterRow.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx

[WB-24519](https://wandb.atlassian.net/browse/WB-24519)
"option click" filters use the raw value, which is fine for the initial filter, until you change the operator. Lets just cast to string, which should also always work (also tested for bool)
Prevents the weird class of errors highlighted in the ticket. It is still possible to create these errors through the API, not exactly sure how to deal with that...
Prod: 
Branch:
[WB-24519]: https://wandb.atlassian.net/browse/WB-24519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(weave): dump option click filter values to string

---

weave/trace_server/clickhouse_trace_server_batched.py

This pr: 
- logs error information (`table`, `data_len`, `data_bytes`, `example_data` (first row), `column_names`, `settings`) when an insert fails
- adds the count of stripped payloads to the dd trace in `_strip_large_values`
- really hard to test the error reporting, i'm not sure how to cause the error, thats why we need the additional logging.

chore(weave): add error and span logging for inserts

---

.github/workflows/test.yaml

Our trace tests are regularly timing out. E.g.
[Trace nox tests (3, 9, trace)](https://github.com/wandb/weave/actions/runs/14623990680/job/41030949100?pr=4243#logs)
succeeded 13 minutes ago in 14m 44s
[Trace nox tests (3, 10, trace)](https://github.com/wandb/weave/actions/runs/14623990680/job/41030975195?pr=4243#logs)
succeeded 14 minutes ago in 14m 44s
[Trace nox tests (3, 11, trace)](https://github.com/wandb/weave/actions/runs/14623990680/job/41030988008?pr=4243#logs)
succeeded 15 minutes ago in 13m 55s
[Trace nox tests (3, 12, trace)](https://github.com/wandb/weave/actions/runs/14623990680/job/41031002516?pr=4243#logs)
succeeded 14 minutes ago in 14m 50s
[Trace nox tests (3, 13, trace)](https://github.com/wandb/weave/actions/runs/14623990680/job/41031016003?pr=4243#logs)
failed 13 …

chore(dev): increase trace test timeout

---

pyproject.toml

[typos](https://crates.io/crates/typos-cli) is a very useful tool for finding spelling mistakes in source code. I often fix typos not just to be fussy but because it is helpful for testing CI, where I want to have confidence that I'm not getting some cached behavior and that the CI behavior isn't a result of what's in the PR.
Adding some minimal configuration to reduce the amount of output to make it easier to detect new errors.
`typos --color always | less -R`

chore(dev): add typos config

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallDetails.tsx

When grabbing the call details, we query for `childCalls` by setting the `parentIds` filter. We know this is only one call, and we know the `traceId` should be the same, so lets also set that in the filter. This should massively improve this query performance, as the trace id is handled pre-groupby and we usually have not so many calls in one trace when compared to the rest of the project. 
This is causing a huge number of errors in a well known instance:
Tested in an infamous project (5x faster, 20x less memory): 
| Environment | Elapsed Time | Rows Read           | Data Size | **Memory Usage**   |
|-------------|--------------|---------------------|-----------|----------------|
| prod        | 7.703s       | 81,199,925 rows     | 11.86 GB  | 26 GB          |
| branch      | 1.536s …

perf(weave): add trace id filter when only querying one parent

---

weave-js/src/components/PagePanelComponents/Home/Browse3/filters/common.ts

`"not equals"` -> `"does not equal"`
Branch:
prod:

chore(weave): fix not equals string filter copy

---

tests/trace_server/test_calls_query_builder.py
weave/trace_server/calls_query_builder/calls_query_builder.py

We explicitly add a `project_id` condition when joining on the feedback table, but this is not necessary.  As far as I can tell, it is impossible to generate a feedback join without the existing `project_id` condition, making this redundant and safe to remove. 
Introduced in [this pr](https://github.com/wandb/weave/pull/2865). 
Updated unit tests.

fix(weave): remove duplicate project_id condition

---

weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/sqlite_trace_server.py

- Fixes an issue that errors in `table_query_stats` used to trigger 400 (Bad request) error, now it will be 500.
manually tested

fix(weave) ensures that the failures in table_query_stats triggers 500 error

---

docs/docs/guides/core-types/evaluations.md
docs/docs/guides/integrations/langchain.md
docs/docs/guides/integrations/llamaindex.md

- Fixes https://wandb.atlassian.net/browse/DOCS-1450
Update all scorer code examples for latest version: use `output` instead of `models_output` 

docs(weave): Update all scorer code examples to use `output` instead of `models_output`

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectsPage/ObjectVersionsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/EmptyContent.tsx

When you delete all versions of an object, we show "No objects yet" messaging, which is confusing. This is a quick fix to display a more correct message, though we should probably think about what we actually want the UX to be. (E.g. return to objects list page?)
Before:
After:
wf versions example, deleted object versions.

fix(ui): show less confusing empty page for object versions

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx

re-do of https://github.com/wandb/weave/pull/4190, with special conditioning for strings. This time I actually tested it on more than just float/number types 🤦🏻 . 
All option clicked into the filter:

chore(weave): option click filter always uses strings, fixed

---

weave/flow/eval_imperative.py

Adds metadata to identify that the call is a score and comes from the imperative eval suite

chore(weave): Add scoring metadata for imperative evals

---

weave/trace_server/table_query_builder.py

- Fixes a SQL query syntax error in the `make_table_stats_query_with_storage_size` function
- Adds an explicit table alias "AS sub" to the subquery because the ClickHouse version 24.12.* demands it
Tested by verifying the corrected SQL query executes successfully against the database without syntax errors.

fix(weave): Add subquery alias 

---

tests/trace/test_dataset.py
weave/flow/dataset.py
weave/trace/vals.py
weave/trace/weave_client.py

https://wandb.atlassian.net/browse/WB-24473
Adds public `add_rows` method on the `Dataset` class. This method takes rows to be appended to the dataset as input and returns a new dataset derived from appending the provided rows to the existing dataset. The new dataset returned by the helper has already been published to the server.
To use:
```python
import weave
weave.init("bcanfieldsherman/tldr")
dataset = weave.ref(
"weave:///bcanfieldsherman/tldr/object/annotated_loops:33yoXWgOPrFNqhXhrDkiaoGMXPeaAjQEkocRmeRjCpk"
).get()
new_dataset = dataset.add_rows(
[
{
"output": "The pull request introduces a really mid method that does not work. Whoever wrote this should be fired.",
"reactions": ["👎", "😠", "💩"],
"notes": ["This is really mean", "Please never do this again", "Not cool"],
},
{ …
```

feat(weave): Dataset.add_rows helper for efficient append to an existing dataset

---

weave-js/src/util.ts

- Fixes a bug in the `convertBytes` function where byte conversion thresholds were incorrectly set
This PR corrects the byte conversion thresholds in the `convertBytes` utility function. The previous implementation used `10e9`, `10e6`, and `10e3` (which equal 10 billion, 10 million, and 10 thousand respectively) as thresholds. This has been fixed to use the correct values: `1e9` (1 billion), `1e6` (1 million), and `1000` for proper byte conversion to GB, MB, and KB.
Manually tested on the UI

fix(weave): fix incorrect bytes calculation

---

tests/trace/test_client_trace.py

faster dynamic batching test, by monkeypatching we get the same effect
test

chore(weave): slightly faster dynamic batching test

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectsPage/ObjectDeleteButtons.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectsPage/ObjectVersionsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectsPage/ObjectVersionsTable.tsx

Adds checkboxes and a delete button to the Object Versions page, allowing you to quickly delete an entire object (not just one version of it) or multiple selected objects.
This UI follows the current backend permissions checks, which allow anyone with write access to the project to delete, even if they are not an admin / not the original creator of the version.
@Yangyi-wandb @m-rgba - design consult, do we want more of a warning about this irreversible action?
Fixes some additional bugs:
* Delete button only getting shown for site admins on version list page
* Row selection state not getting cleared when object versions are deleted through peek drawer.
Manual through `wf` versions example.

feat(ui): add bulk object delete functionality

---

tests/trace/test_client_trace.py
tests/trace/type_handlers/Image/image_test.py

- reduces the sampling number of ops
- reduces image size and rows for image tests
test!

chore(weave): speed up image and sampling tests

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPage.tsx

Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1745603003227869?thread_ts=1745595688.279219&cid=C03BSTEBD7F
When you save a view (as opposed to just renaming it) we need to refetch the latest data to make sure clicking around in the switch view gets the latest definition.

fix(ui): Saved Views view switch panel not refreshing

---

tests/trace/test_trace_settings.py
tests/trace/test_weave_client.py

Save some CI time by reducing `time.sleep` where possible
test

chore(weave): reduce sleep times for many tests

---

weave/trace_server/clickhouse_trace_server_batched.py

- Uncomments the error check in `table_query_stats` to ensure exactly one result is returned. The commenting was an expedited measure to quickly put prod errors out.
- Modifies the SQL query in `table_query_stats_batch` to:
- Use `any(length(row_digests))` to pick one result instead of just `length(row_digests)`
- Add a `GROUP BY digest` clause to properly aggregate results
- I have validated that the advanced form query generated by `make_table_stats_query_with_storage_size` does not return duplicated results.
This change was tested by running the produced query against the impacted production data.

fix(weave): Uncomment validation check and fix table_query_stats query

---

docs/docs/guides/tracking/feedback.md

- Fixes https://wandb.atlassian.net/browse/DOCS-1441
Adds callouts about feedback note len limit to https://weave-docs.wandb.ai/guides/tracking/feedback/

docs(weave): Add callouts about feedback note len limit

---

weave-js/src/common/hooks/useStorageSizeCalculation.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/DatasetVersionPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/EditableDatasetView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/DataTableView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectsPage/ObjectVersionPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/StorageSizeSection.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerCachingClient.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClientTypes.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerDirectClient.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts

- Address [WB-23748](https://wandb.atlassian.net/browse/WB-23748)
This PR implements the frontend components and data flow for displaying storage size information in object and dataset detail views. It includes UI components, data fetching logic, and type updates to support the new storage size feature.
Preview:
1. Added `StorageSizeSection` component:
- Displays storage size for current version and all versions
- Handles loading states with LoadingDots
- Formats byte sizes using `convertBytes` utility
- Shows total size across all versions when applicable
1. Updated `DatasetVersionPage`:
- Added storage size display with version comparison
- Integrated table size calculations for datasets
- Added storage usage tracking for both metadata and table data
2. Enhanced `ObjectVersionPage`:
- …

feat(weave): Frontend Implementation for Storage Size Display

---

tests/integrations/bedrock/bedrock_guardrail_test.py
tests/integrations/bedrock/bedrock_test.py
tests/trace/test_op_decorator_behaviour.py
weave/flow/eval.py
weave/scorers/bedrock_guardrails.py
weave/scorers/classification_scorer.py
weave/scorers/coherence_scorer.py
weave/scorers/context_relevance_scorer.py
weave/scorers/fluency_scorer.py
weave/scorers/hallucination_scorer.py
weave/scorers/json_scorer.py
weave/scorers/moderation_scorer.py
weave/scorers/presidio_guardrail.py
weave/scorers/prompt_injection_guardrail.py
weave/scorers/pydantic_scorer.py
weave/scorers/ragas_scorer.py
weave/scorers/similarity_scorer.py
weave/scorers/string_scorer.py
weave/scorers/summarization_scorer.py
weave/scorers/trust_scorer.py
weave/scorers/xml_scorer.py
weave/trace/op.py

This adds better type hinting support for editors.
Resolves:
- https://github.com/wandb/weave/issues/3423
- https://github.com/wandb/weave/issues/3494
Before:
After:

chore(weave): Don't destroy type information when using op decorator

---

weave-js/src/components/FancyPage/useProjectSidebar.ts

In the case of an empty project or one that has both Models and Weave data we are showing the Overview page twice, once at the top of the nav bar and once in the Models overflow menu.
Before:
After:

fix(ui): don't show overview in nav sidebar twice

---

weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/schemaUtils.test.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/schemaUtils.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/smallRef/SmallRefLoaded.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/smallRef/SmallWeaveRef.tsx

https://wandb.atlassian.net/browse/WB-24372
This PR adds the option to include a ref to the original call in the add call to dataset flow. There is now a `trace` field which contains a ref to the source call of each row.
The PR also modifies the `SmallWeaveRef` component to support call refs. Calls must be fetched with a different query than objects, so the `SmallWeaveRef` now wraps two children `SmallWeave{Object,Call}Ref` which in turn handle the querying and rendering for their respective data.

feat(ui): include trace ref in add to dataset

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx

Fixes https://wandb.atlassian.net/browse/WB-24646 
UI crash caused by infinite loop. If you pass MUI data grid a sortModel that references columns that don't exist it invokes `onSortModelChange` with an updated list instead of just ignoring them. This was a problem for Saved Views where the sorting was on a column like "output" that gets added after data is loaded.

fix(ui): infinite loop when loading saved view

---

tests/trace_server/test_calls_query_builder.py
weave/trace_server/calls_query_builder/calls_query_builder.py

Fix for a small but damaging parenthesis bug introduced in https://github.com/wandb/weave/pull/4198. Because this is implemented as a query optimization, it should not be impacting correctness, but for mega large projects is causing performance issues. 
We need to add the extra set of parentheses for when we are filtering by only one inputs/output ref set! 
[Example error](https://us5.datadoghq.com/logs?query=span_id%3A2612604084348452742&agg_m=count&agg_m_source=base&agg_t=count&clustering_pattern_field_path=message&cols=host%2Cservice&event=AwAAAZZ99ZZofjFJMwAAABhBWlo5OWFtZkFBQ3ZjeE4taEo3OWh3QUEAAAAkMDE5NjdkZjUtYmU1ZC00NGI3LTliOTQtOGJiOTQ4OWMyMWIxAAAifg&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&viz=stream&from_ts=1745869956939&to_ts=174586997091 …

fix(weave): fix ref filter optimization query construction

---

.github/workflows/test.yaml

Run the sqlite tests first, they are faster to run so if there is an obvious issue that will catch and return faster.
Also name the sqlite tests from `Nox -> Nox (Sqlite Only)`
ci in this pr

chore(weave): run sqlite tests first

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ExampleCompareSection/ExampleCompareSection.tsx

Fix https://wandb.atlassian.net/browse/WB-24661
Before:
After:

fix(ui): mid-word breaks in evaluation compare example section

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableColumns.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableQuery.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/StatusChip.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerDirectClient.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts
weave-js/src/errors.ts

- Fixes [WB-24053](https://wandb.atlassian.net/browse/WB-24053)
Communicate trace endpoint errors to users
In case of a trace call loading error due to network or auth issues, user will see this:
Ok, based on [the latest feedback](https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1745524789840019?thread_ts=1745451631.673699&cid=C03BSTEBD7F): 
I have decided to show StatusChip in place of the costs/storage size errors, which would look like this:
when a user hovers it, we will see:
Manually tested with auth error and a forged bad server response
[WB-24053]: https://wandb.atlassian.net/browse/WB-24053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(weave): Communicate trace endpoint errors to users

---

weave_query/weave_query/weave_http.py

Allow for chunks of up to 8MB before we write to the file

chore(weave_query): increase chunk size on async file downloads

---

weave-js/src/common/components/WandbLoader.tsx

Noticed an identical block of code between `TrackedWandbLoader` and `TrackedWaveLoader` comps. I'm about to add a third loader type so I figured I'd refactor a bit instead of copying into a third component

refactor(ui): Create reusable helper for tracked loaders

---

weave-js/src/components/PagePanelComponents/Home/Browse3/components/TraceNavigator/TraceScrubber/components/scrubbers.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/components/TraceNavigator/TraceViews/TreeView.tsx

[WB-24729](https://wandb.atlassian.net/browse/WB-24729)
Trace tree crashes if call parents are nonexistent, probably a bigger issue but for now be more robust to errors. 
Prod:
Branch:
[WB-24729]: https://wandb.atlassian.net/browse/WB-24729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(weave): tree navigator robust to missing parents

---

weave-js/src/common/components/TraceCountDisplay.tsx

Trace count display component so we don't have to use the hook in the frontend.

chore(weave): break out trace count display

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/SavedViews/PanelView.tsx

Fixes https://wandb.atlassian.net/browse/WB-24715
Same problem and resolution as https://github.com/wandb/weave/pull/4204
Before:
After:

fix(ui): small night-mode fix for pill in PanelView

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts

[WB-24629](https://wandb.atlassian.net/browse/WB-24629)
This pr:
- adds a `refetchOnRename` opt to the `useCall` hook
- invalidates the cache to fetch the new `displayName` only on rename
Prod:
Branch:
[WB-24629]: https://wandb.atlassian.net/browse/WB-24629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(weave): display name updates in call details page

---

tests/trace/test_client_trace.py
weave/trace_server/calls_query_builder/calls_query_builder.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/sqlite_trace_server.py
weave/trace_server/trace_server_interface.py

- Adds support for retrieving total storage size in call query statistics
- Enhances `CallsQueryStatsReq` with an optional `include_total_storage_size` parameter
- Updates `CallsQueryStatsRes` to include an optional `total_storage_size_bytes` field
- Modifies the query construction to aggregate storage size data when requested
- In order to see the entire picture, please review the entire stack of PRs as suggested by Graphite comment below.
Added a test that:
- Creates calls with nested structure containing data
- Queries calls with the new `include_total_storage_size` flag
- Verifies the response includes the expected count and non-null storage size
- Handles ClickHouse-specific optimizations with materialized views
Also improved code formatting in an existing test by moving a multi-line …

feat(weave): backend change for including storage size in the stats query

---

weave-js/src/common/components/Tags.styles.ts
weave-js/src/common/components/Tags.tsx

- Fixes [WB-23977](https://wandb.atlassian.net/browse/WB-23977)
This PR updates the protected alias tag design in the (deprecated) tag component. While the component is deprecated, it is still used in various locations for artifacts. switching them out to the current component would require heavier work, so for now we're still updating this component & plan to switch to the current component later.
protected aliases design: 
- [notion link](https://www.notion.so/wandbai/Protected-alias-tag-1c8e2f5c7ef38078b75dfecdb5e80a9f)
- [figma link](https://www.figma.com/design/vXjdSVJ18xjU3T2pKnLuVd/QA-for-Workspaces?node-id=3033-26667&t=exnXegNXf7GUJyZ3-11)
the screenshots below also include tags since those icons were also affected by this PR
protected aliases in collection card:
deletable …

chore(ui): update styling for protected aliases

---

weave-js/src/components/PagePanelComponents/Home/Browse3/filters/common.ts

[WB-24755](https://wandb.atlassian.net/browse/WB-24755)
Restrict the name filter to just string operations. 
Prod:
Branch:
[WB-24755]: https://wandb.atlassian.net/browse/WB-24755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(weave): restrict name filter type to string

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClientTypes.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts

- Adds support for retrieving and displaying total storage size of all trace calls of a project
- Extends `TraceCallsQueryStatsRes` type to include optional `total_storage_size_bytes` field
- Adds `includeTotalStorageSize` option to `useCallsStats` hook to request storage size information
- In order to see the entire picture, please review the entire stack of PRs as suggested by Graphite comment below.
- The UI is surfaced up by this PR https://github.com/wandb/core/pull/29078
Tested by verifying that the trace server client correctly requests and receives the total storage size when the new option is enabled, and that the UI components correctly display this information when available.

feat(weave): display trace size from the entire project

---

tests/trace/test_weave_client.py
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClientTypes.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/external_to_internal_trace_server_adapter.py
weave/trace_server/sqlite_trace_server.py
weave/trace_server/trace_server_interface.py
weave/trace_server_bindings/caching_middleware_trace_server.py
weave/trace_server_bindings/remote_http_trace_server.py

- Adds a new `files_stats` API endpoint to the trace server interface
- Implements the endpoint in the ClickHouse trace server to return total file size statistics
- Adds appropriate adapter implementations in middleware servers
- Includes a test case to verify functionality
The new endpoint allows clients to query for aggregate statistics about files in a project, specifically the total size in bytes of all files.
- In order to see the entire picture, please review the entire stack of PRs as suggested by Graphite comment below.
- There is also a server endpoint change snippet here: https://github.com/wandb/core/pull/29079
Added a test case that creates a file of known size and verifies the `files_stats` endpoint returns the correct total size.

feat(weave): backend for getting all file size for a project

---

weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/CreateDatasetDrawerContext.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/__tests__/jsonUtils.test.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/jsonUtils.ts

Remove dependency of `jsonUtils.ts` for parsing json datasets on logic for csv files in `csvUtils.ts`. This led to a bad bug where list values were treated as strings. Now the json parsing logic has its own interfaces and is logically separate from the csv parser. And the bug is fixed.

fix(ui): treat json lists within uploaded dataset rows as lists, not strings

---

weave-js/package.json
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClientTypes.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerDirectClient.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
weave-js/yarn.lock

- Adds a new API endpoint for querying file statistics in projects
- Implements a React hook `useFilesStats` to fetch total file size for a project
- Introduced `react-use` library.
- In order to see the entire picture, please review the entire stack of PRs as suggested by Graphite comment below.
The actual UI is surfaced up by https://github.com/wandb/core/pull/29080 PR
Tested by verifying the new API endpoint returns the correct file statistics and the React hook properly fetches and displays the total file size for projects.

feat(weave): show project's total file size

---

tests/trace/test_client_trace.py
weave/trace_server/calls_query_builder/calls_query_builder.py
weave/trace_server/sqlite_trace_server.py

The Run and User id filters had an extra paren at the end of the query causing invalid query generation

fix(weave): Fixes User and Run ID filters

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/SavedViews/savedViewUtil.ts

Fix https://wandb.atlassian.net/browse/WB-24737
When a saved view had a filter with a "contains" operation the representation of that clause didn't match what was saved, causing freshly loaded views to appear to be in the "modified" state.
Tested with Adam's project

fix(ui): saved view modified state incorrect when contains filter in use

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPageLoadView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPageLoadViewWithUser.tsx

[WB-24769](https://wandb.atlassian.net/browse/WB-24769)
Allows users who are not logged in to view weave projects. 
Prod:
Branch:
[WB-24769]: https://wandb.atlassian.net/browse/WB-24769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(weave): allow anonymous users to view public projects

---

weave-js/src/core/suggest.ts

Also filter out `customRunNames` variable before showing weave suggestions. The variable defines the mapping from run ID to a custom run name (if one is set) and is causing [confusion with users](https://weightsandbiases.slack.com/archives/C02DQUT83SR/p1738324755752539) who are trying to use it to display their run's custom name inside the query panel. With this issue being fixed via https://github.com/wandb/weave/pull/4360, which defines a special path for the `run.name` op to account for custom run names, we should hide this variable, as it is otherwise only used internally within the query panel code.
The change in this PR will not break functionality for users that are currently using the variable. 
Local FE
https://github.com/user-attachments/assets/27e19baf-50dd-47c5-907b-874ce890d58 …

chore(app): hide customRunNames variable in weave suggestions

---

tests/trace/type_handlers/Audio/audio_test.py

`audio_test.py` currently has two tests doing the same thing and uses tempfile with the delete=False option. This PR removes the redundant test and revises all tests to use the built in temporary test directory fixture provided by pytest.

chore(weave): use tmp_path builtin and remove redundant test in audio_test.py

---

weave-js/src/components/PagePanelComponents/Home/useDrawerResize.tsx

[WB-24735](https://wandb.atlassian.net/browse/WB-24735)
Resizing the browser and/or opening up the console and/or connecting to external displays can cause the drawer width to get set less than the minimum allowed. Strictly enforce a minimum drawer width. 
Prod
Branch
[WB-24735]: https://wandb.atlassian.net/browse/WB-24735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(weave): force min width even if set incorrectly

---

tests/trace/test_weave_client.py
weave/trace_server/calls_query_builder/calls_query_builder.py
weave/trace_server/sqlite_trace_server.py

This pr:
- adds a better test for latency filtering/sorting
- cast the latency to float in sqlite
- updates test

chore(weave): add better test for latency filtering

---

weave-js/src/components/PagePanelComponents/Home/Browse3/components/TraceNavigator/TraceViews/CompositionView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimplePageLayout.tsx

[WB-24781](https://wandb.atlassian.net/browse/WB-24781)
Fixes TraceComposition rendering in small width drawers.
This pr:
- truncates very long op names
- adds better flex handling for the ms timings
- increases the minimum drawer size (old view was simpler, this one needs more space)
[WB-24781]: https://wandb.atlassian.net/browse/WB-24781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(weave): fix small width CompositionView in TraceNavigator

---

weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/AddToDatasetDrawer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/DatasetDrawerContext.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/__tests__/DatasetDrawerContext.test.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/schemaUtils.test.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/schemaUtils.ts

1. Don't flatten dataset columns if the nested data is a weave object, like an image. 
2. Include fields from the flattened objects in the resulting dataset if they have an included field as a prefix of their name.
3. Put a `CustomWeaveTypeProjectContext` in the add to dataset drawer scope so weave objects will render.
https://github.com/user-attachments/assets/037463d4-6ffa-4c8d-a7b0-76930de7ce59

fix(ui): do not expand weave objects when moving from schema mapping to confirm step

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTableButtons.tsx

The compare view is so great, it deserves some love. Lets try it as primary for a bit. Also add some tooltip text. 
Before: 
After:

chore(weave): make compare button primary + tooltip

---

weave-js/src/common/components/WeaveStatsSummarySection.tsx

Added a new `WeaveStatsSummarySection` component that displays statistics for Weave projects. The component shows:
- Total number of traces
- Total size of traces
- File storage size
The component fetches data using `useCallsStats` and `useFilesStats` hooks, and displays loading indicators while data is being retrieved.
This component is supposed to replace the \<TraceCountDisplay /> component created in https://github.com/wandb/weave/pull/4341/files
and will be consumed by \<ProjectOverview /> in https://github.com/wandb/core/pull/29080/files
Preview:
Before:
After:
Tested locally.

chore(weave): WeaveStatsSummarySection

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/PlaygroundChat.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundPage.tsx

- Switched to `WaveLoader` instead of CircularLoader (trying to deprecate usage across app).
- Tried this: `playgroundStates.length === 1 ? 'lg:min-w-[800px]' : ''` as a fix for the card collapsing in to ~740px on larger screens... pretty annoying visual OCD issue -- this is a bit of a hack, but it improves it.
- Used a single px border + `outline outline-[1.5px] outline-teal-400` for the setting active state (and the rounded the top corner of the card header)
- We do this somewhere else as a fix as well, it would be preferable to use Tailwind's `ring` but I think box-shadow is set to none in dark mode which is what it uses for the active ring border.
- Updated `Add chat` to `Add model` copy - my bad (since that's the actual unit we're adding - and `Add chat` could make the user think …

chore(ui): Minor nits - multi-chat playground update

---

weave-js/src/components/PagePanelComponents/Home/Browse3/OpCodeViewer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/OpDefCode.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/compare/CodeView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx

Continuing towards goal of eliminating Browse2, this just relocates and renames `Browse2OpDefCode` to `OpDefCode`.

refactor(ui): move OpDefCode out of Browse2

---

weave-js/src/components/PagePanelComponents/Home/Browse3/filters/CellFilterWrapper.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableColumns.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/tabularListViews/columnBuilder.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/tabularListViews/operators.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
weave/flow/saved_view.py

[WB-24782](https://wandb.atlassian.net/browse/WB-24782)
This pr:
- refactor the "onAddFilter" to "onUpdateFilter" (just a name change, per the TODO comment)
- Add support for "option+click" filtering by trace name. 
- Add support for "option+click" filtering for `latency_ms`. When option clicking latency, the default is "greater than or equal to". Because we are generating this field manually on the backend, it is actually a float, not a string stored in json, so we need to omit the conversion params from the filter. 
[WB-24782]: https://wandb.atlassian.net/browse/WB-24782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(weave): add option+click support to Name and Latency

---

tests/trace_server/test_opentelemetry.py
weave/trace_server/opentelemetry/attributes.py
weave/trace_server/opentelemetry/constants.py
weave/trace_server/opentelemetry/helpers.py
weave/trace_server/opentelemetry/python_spans.py

- Fixes WB-24778
OTEL spans from langfuse don't display latency correctly because the start and end time of the spans are not the actual start and end time. Instead, the real start and end time are under:
`langfuse.startTime`
`langfuse.endTime`
This PR checks for these values and parses them out.
Added test cases for datetime conversion handler and override fields parser.

fix(weave): Correct timestamps for langfuse OTEL

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallChat.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/PlaygroundChat.tsx

animation buffer looks like lag in playground
adds option to not use buffer
before
https://github.com/user-attachments/assets/278bff62-d58f-42df-a23c-9c7b59123652
after
https://github.com/user-attachments/assets/ee547968-15c2-4ec0-bc40-9513e1e6ed0d

style(weave): Fix playground add chat animation

---

weave/trace_server_bindings/remote_http_trace_server.py

Modifies the retry logic in `_flush_calls` to prevent infinite retries of non-retyable errors. Previously we requeued all batches that failed. Now we requeue batches that fail with a retryable exception (ie 4XX). If a batch failsfails with with 4XX, we `logger.error` the response code, text, and reason, the dropped start and end event ids that were dropped, and proceed.
Example script that would infinitely retry 400:
```python
import weave
weave.init("testing")
@weave.op()
def get_artifact_url() -> str:  # Malformed ref in output causes a 400 error on request validation
return "weave:///artifact/bcanfieldsherman/testing/toxic-extra-path/run-4cinli05-test.py:v0"
get_artifact_url()
```
Previously running this generated an infinite loop of:
```
Batch failed after max retries, requeueing …
```

fix(weave): do not retry call inserts that fail with a non retryable status code

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueViewMarkdown.tsx

Fixes https://wandb.atlassian.net/browse/WB-24852
Wrap long lines when displaying a `weave.Markdown` as an input in the object viewer.
Before:
After:
Added an example to `wf`.

fix(ui): wrap long markdown lines

---

.github/workflows/notify-wandb-core.yaml

- Fixes issue with npm publish failing when package already exists
Updates the npm publish commands in the notify-wandb-core workflow to handle E409 errors (package already exists) gracefully. The workflow now captures the output of npm publish and checks for E409 errors, preventing the job from failing when the package version already exists in the registry.
Example fail:
https://github.com/wandb/weave/actions/runs/14871415503/job/41760432377
Tested by verifying that the workflow continues successfully when npm publish returns an E409 error code.

chore(dev): make notify wandb core rerun-able on the same commit

---

tests/trace/test_client_trace.py
tests/trace/test_weave_client.py
weave/trace_server/refs_internal.py
weave/trace_server/trace_server_interface_util.py

https://wandb.atlassian.net/browse/WB-24747
If these are included in the `input_refs` and `output_refs` field for a `CHInsertable`, it will lead to a validation error on the pydantic class and then a 400 bad request back to the client. This PR modifies `extract_refs_from_values` to attempt a parse of each of our special uri prefixes before we construct the `CHInsertable` and perform the validation there:
- `weave:///`
- `weave-trace-internal:///`
- `wandb-artifact:///`
If the parse fails, we omit the value from the refs list, since this will lead to a downstream validation error and 400. The result is that our backend treats these malformed uris in call i/o and objects as strings and our queries will not attempt to resolve those refs.

chore(weave): trace server does not 400 for malformed refs in call inputs or output

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueViewMarkdown.tsx

Fixes https://wandb.atlassian.net/browse/WB-24881
The fix in https://github.com/wandb/weave/pull/4406 wasn't good. While it did wrap long lines in lists, our markdown renderer is inserting a large number of newlines at the start of HTML generated for a simple table. `break-spaces` would preserve these newlines, causing the table to not even be visible without scrolling. Setting `white-space` to `normal` collapses the whitespace. (It takes precedence over the `white-space: nowrap` on `.MuiDataGrid-cell` that was the cause of the original issue.)
Tested on customer reported trace.

fix(ui): extra newlines in markdown rendering

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/LLMDropdown.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/LLMDropdownOptions.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/PlaygroundChat.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/PlaygroundChatTopBar.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/useChatFunctions.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundSettings/PlaygroundSettings.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/types.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/usePlaygroundState.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/useSaveModelConfiguration.ts

Frontend for saved models
Main Changes
LLM Dropdown
- We fetch saved models
- Add them to the LLM Dropdown
- Add support within the playgrounds state to select and search for them
Playground Settings
- On selection we load the settings
- We can save or update a model
- Adds a text field, for model name, and button for publishing
https://github.com/user-attachments/assets/22ed9045-58d3-4dde-b2e5-2c0c0ad30608

feat(weave): Saved models frontend

---

weave/trace/grid.py

Fix for https://github.com/wandb/weave/issues/4444
I haven't been able to reproduce the problem on my machine when passing `''`. I can get the locale error if I do:
`import locale; locale.setlocale(locale.LC_ALL, 'invalid_locale')`
I thought it might be because I have `LANG=en_US.UTF-8` in my environment, but it doesn't error for me even if I unset that, so maybe this is OS or Python version specific? In any case, I believe this should resolve the error for the user.

fix(weave): Grid locale can error

---

.github/workflows/test.yaml

Node 18 is past its [EOL](https://github.com/nodejs/release#release-schedule) of 2025-04-30. Let's use v20 in our WeaveJS Lint and Compile check.

chore(dev): bump Node to v20 in WeaveJS Lint and Compile check

---

tests/trace/test_client_trace.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/external_to_internal_trace_server_adapter.py
weave/trace_server/project_query_builder.py
weave/trace_server/sqlite_trace_server.py
weave/trace_server/trace_server_interface.py
weave/trace_server_bindings/caching_middleware_trace_server.py
weave/trace_server_bindings/remote_http_trace_server.py

- Adds a new `project_stats` API endpoint to retrieve storage usage statistics for a project
- Implements the endpoint for ClickHouse trace server with statistics for trace, object, table, and file storage sizes
- Adds a test case to verify the functionality with direct ClickHouse data insertion
- This PR depends on [https://github.com/wandb/core/pull/29316](https://github.com/wandb/core/pull/29316)
The new `project_stats` endpoint provides a unified, accurate, and efficient way to retrieve all relevant storage statistics for a project—including trace, object, table, and file storage sizes—in a single atomic query. Unlike the previous approach, which required separate calls to endpoints like `calls_query_stats` (for traces) and `files_stats` (for files), and still lacked object and table …

feat(weave): backend for the project stats API

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts

Removes the temporary and now unused `useCall2` hook
lint/compilation is a pretty good test for this.

chore(weave): remove useCall2

---

weave/integrations/mistral/v1/mistral.py

Fix an issue when using streaming + tool calling, as Unset type was not treated as empty and concatenation.
This way you always end up with a real list before appending.

chore(weave): quick fix for tool calling with stream

---

weave/flow/scorer.py

Preserves summarize ordering by not using `set`

chore(weave): Preserve order of auto-summarize keys

---

tests/conftest.py

This helps resolves some CI issues where a straggling test that incorrectly cleaned up could cause a cascade of test failures.
We should still be on the look out for those stragglers

chore(weave): Zero out call stack before each test

---

weave/trace/grid.py

Fix for https://github.com/wandb/weave/issues/4459 
I unfortunately don't have a Windows machine available for testing. Cursor will gladly write the equivalent `get_key` for me that uses `msvcrt` but without a way to test it I thought it safer to just not support the interactive grid pagination feature on Windows for the time being.

fix(weave): grid using imports not available on Windows

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Links.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/util.tsx

Replace the UI for the parentId filter value, from one using a Material UI Chip to one using a W&B common component removable tag.
Besides a more consistent look with the rest of the UI, changes/improvements are:
* Use the display name of the parent call, which might have been changed
* Use the "trailing 4 char" form of id abbreviation instead of an older approach.
* The component automatically has a tooltip if the call name is truncated.
Before:
After:
@Yangyi-wandb @m-rgba - if we go with this we should also replace the Chips used for input/output filters but wanted to get your opinions on it first.
----
Update - have replace Chip component for the input/output object link too.

chore(ui): replace MUI Chip with RemovableTag

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Id.tsx

The quicker fix for https://wandb.atlassian.net/browse/WB-24855 - revert to using the older deprecated Tooltip component so the update-content-on-click interaction works again. We should probably replace with a toast but there are design considerations so just unbreaking things in the meantime.

fix(ui): use deprecated tooltip component until component can be updated

---

weave-js/src/components/CopyableText.tsx

Fixes https://wandb.atlassian.net/browse/WB-24950
Truncate text with ellipsis rather than having overflow be visible in CopyableText. (If the full text is needed it's just a click to copy away.)
Before: 
After:

fix(ui): ellipsis in copyable text

---

weave-js/src/components/PagePanelComponents/Home/Browse3/filters/common.ts

Override filter field label to hide the internal field name and make it match the column display.
Before:
After:

chore(ui): update Run filter label

---

weave-js/src/common/util/render_babylon.ts

https://wandb.atlassian.net/browse/WB-24590
BabylonJS defaults to a left handed axes system for some reason which isn't the standard https://forum.babylonjs.com/t/left-and-right-handed-shenanagins/17049. But since this has been our default so far, we're just going to add this as a media setting if someone wants to switch to right handed to avoid sudden user confusion with all axes mirrored.
Tested in https://github.com/wandb/core/pull/29413

chore(app): Add optional setting to use Right Handed System

---

weave-js/src/common/components/WeaveStatsSummarySection.tsx

Updates the WeaveStatsSummarySection component to use "ingestion size" terminology instead of "storage size" for better accuracy in the UI. This change affects the variable names and display labels throughout the component.
Also remove the artificial gap between the category name and its value.
This UI currently looks like this:
A newer design will be implemented later to revise this section. For now, as long as the information is accurate, styling issues can be deprioritized.
Manually tested locally

chore(weave): change wording and remove gap

---

sdks/node/package.json
sdks/node/src/__tests__/legacy/op.test.ts
sdks/node/src/__tests__/legacy/tsconfig.json
sdks/node/src/__tests__/modern/op.test.ts
sdks/node/src/__tests__/modern/tsconfig.json
sdks/node/src/__tests__/op.test.ts
sdks/node/src/__tests__/tsconfig.json
sdks/node/src/index.ts
sdks/node/src/media.ts
sdks/node/src/op.ts
sdks/node/src/types.ts
sdks/node/src/urls.ts
sdks/node/src/weaveClient.ts

This PR improves the Node SDK test infrastructure by:
1. Adding proper module path mapping for tests using the `moduleNameMapper` configuration in Jest
a. Updating imports in test files to use the cleaner new path aliases (`weave` and `weave/*`). It looks more like how client side is going to consume the packages.
b. Consolidating test TypeScript configuration files. "tsconfig.test.json" is ok to be used as base template, but my IDE doesn't seem to recognize it unless I renamed it to "tsconfig.json"
c. Fixing mock implementations in tests
2. Adding environment variable support for trace server URL configuration.
3. Exporting additional types from the media module. (WeaveAudio, and WeaveImage) users should have a use of them.
This is a follow up of the TS decorator PR: …

chore(weave): code cleanup for TS SDK test setup.

---

weave-js/src/components/UserLink.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-24992
Quick fix, we may want a more comprehensive design review of this component. If the viewer does not have permission to view a user's email we shouldn't show a blank row in the information table in the user popup.
Before:
After:

fix(ui): empty email in user popup

---

docs/docs/guides/evaluation/evaluation_logger.md

- Fixes https://wandb.atlassian.net/browse/DOCS-1492
In https://weave-docs.wandb.ai/guides/evaluation/evaluation_logger/#basic-example
1. Adds missing `weave.init`
2. Replaces `weave.flow.eval_imperative` with `from weave import EvaluationLogger` since we don't want to expose internal structures in user facing code 

docs(weave): update basic eval logger example

---

tests/integrations/langchain/cassettes/langchain_test/test_simple_chain_invoke_no_client.yaml
tests/integrations/langchain/langchain_test.py
weave/integrations/langchain/langchain.py
weave/integrations/openai_agents/openai_agents.py

Resolves: https://wandb.atlassian.net/browse/WB-25005
Previously, if `weave.init` was called in a submodule, patching would apply everywhere and could affect modules where `weave.init` was not called, causing a crash.
Now, patching still applies everywhere, but it simply no-ops if there is no client available.

fix(weave): Dont crash in langchain if client is not init'd

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/hooks.ts

- Fixes WB-25009
Currently normalizing the call trace into a Chat occurs on every keypress when the user types into the playground prompt box and multiple times every time the chat is rendered in playground and trace view.
With this change it is only re-parsed when the underlying data changes.
tested in playground

fix(weave): only perform trace to chat conversion when underlying data changes

---

weave-js/src/components/Form/TextField.tsx

Add `id` prop to `TextField` common comp, which will be assigned to the input element. This allows us to associate accessible labels to the input.
Used here: https://github.com/wandb/core/pull/29499

chore(ui): Add id prop to TextField

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ComparisonDefinitionSection/ComparisonDefinitionSection.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ComparisonDefinitionSection/ModelRefLabel.tsx

The first of some small refactors - the larger goal is extracting this evaluation selector component from the evaluation comparison page as part of allowing people to swap evaluations when viewing the predict_and_score traces.

refactor(ui): move ModelRefLabel into its own file

---

weave_query/weave_query/ops_domain/table.py

Ensure the utils for incremental table logging are imported. Unsure how I missed this, but no impact as the incremental logging write path isn't released.
local invoker.ini

fix(weave_query): ensure utils are imported

---

weave_query/weave_query/derive_op.py

Without this line, we call `mapped_file-table_with_increments` which means the `file-table_with_increments` op is never called individually and therefore not cached. This adds it to the list so it can be parallelized and cached.

fix(weave_query): Make mapped file-table_with_increments op parallel

---

wb_schema.gql
weave-js/src/components/PagePanelComponents/Home/Browse2/CellValueRun.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterBar.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterRow.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterTagItem.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/SelectValue.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/common.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableColumns.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableFilter.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableQuery.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/context.tsx
weave-js/src/components/RunLink.tsx
weave-js/src/components/RunState.tsx
weave-js/src/components/SelectRun.tsx

* When the user hovers over a value in the Run column we show a little popup summary.
* Option+Click to add a filter still works, but is less hacky because we can query for the project's internal ID.
* We don't have to show the confusing run name in the filter bar, we can show the display name and give it the same hover treatment as the cell value.
* Users can select Run as the field in the filter popup, and a new Select widget allows them to pick one.
A follow up PR in the core repo will link from the Run Overview to the filtered traces page using code in this PR.
I also copied the `RunState` component from the core repo so we could use it in Weave. Follow up PRs will point core uses at this location and then delete the core version to finish that migration.
Before:
After:
Hover over the …

feat(ui): Improve run links and filtering

---

wb_schema.gql

The weave_query unit tests were breaking because the directive wasn't defined. I used the definition from gorilla.

chore(ui): define @internal directive

---

weave_query/requirements.legacy.txt
weave_query/weave_query/ops_domain/table.py

`orjson` is faster at JSON parsing than the native `json` package and should help us shave another 2-3 seconds on the load time of large tables (e.g. [This 1.7GB table parse took ~7s](https://us5.datadoghq.com/apm/traces?query=%40duration%3A%3E5s%20-customer-ns%3Awandb-qa-%2A%20%40customer-ns%3Awandb-cohere%20service%3Aweave-python&agg_m=count&agg_m_source=base&agg_t=count&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=false&graphType=flamegraph&historicalData=true&messageDisplay=inline&shouldShowLegend=true&sort=time&sort_by=%40duration&sort_order=desc&spanID=11545485965206133566&spanType=all&storage=hot&timeHint=1747167777574&trace=AwAAAZbLUJMmVU2BMQAAABhBWmJMVUp6OEFBQnprVU0yWXRwWWprb1kAAAAkMDE5NmNiNTQtZjVkZS00MzNkLWFjYTItMTExZjZiM …

chore(weave_query): Add orjson package and use for JSON parsing of tables

---

sdks/node/src/__tests__/call.manipulation.test.ts
sdks/node/src/__tests__/call.test.ts
sdks/node/src/__tests__/legacy/op.test.ts
sdks/node/src/__tests__/modern/op.test.ts
sdks/node/src/__tests__/op.test.ts
sdks/node/src/call.ts
sdks/node/src/op.ts
sdks/node/src/opType.ts
sdks/node/src/weaveClient.ts

Adds a new `invoke` method to ops that returns both the result and a Call object, allowing users to update call metadata after execution. The Call object provides a `setDisplayName` method to change the display name of a call even after it has completed.
Tested by creating ops, calling them with the new `invoke` method, and verifying that the returned Call object can be used to update the display name both during and after execution.
Some unit tests scenarios are authored as well.

feat(weave): TS SDK: allows call handle to be returned

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/compositeMetricsUtil.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ExampleCompareSection/ExampleCompareSectionDetail.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ExampleCompareSection/ExampleCompareSectionTable.tsx

Adrian noticed that the new pivot view was crashing here: https://app.wandb.test/adrian2/support-model-eval2/weave/compare-evaluations?evaluationCallIds=%5B%220192f9d6-dc35-7673-87c2-411d9d46b23b%22%2C%220192f9d4-d736-7162-9b66-31c5ec16bd67%22%5D&metrics=%7B%22function_call_scorer.function_call_score%22%3Atrue%2C%22response_quality_scorer.tone_score%22%3Atrue%2C%22response_quality_scorer.conciseness_score%22%3Atrue%2C%22response_quality_scorer.clarity_score%22%3Atrue%2C%22response_quality_scorer.helpfulness_score%22%3Atrue%2C%22Latency%22%3Atrue%2C%22Total+Tokens%22%3Atrue%7D
There were 2 issues:
1. When there are dataset mismatches, the missing rows were causing access errors
2. (Not causing a crash, but fixed here): when there are scorer mismatches, I was not merging the columns …

fix(weave): Fix case where there are dataset and scorer mismatches with new pivot view

---

noxfile.py

- Fixes WB-25094
Temporarily moves DSPY to 3.9 incompatible shards. Their dependency `json_repair` pushed some changes yesterday which are 3.9 incompatible.
We can open a PR upstream to fix this but in the mean time CI shouldn't be broken over it.

fix(weave): fix breaking dspy test runner

---

docs/docs/guides/tracking/tracing.mdx
docs/docs/reference/python-sdk/weave/index.md
tests/trace/test_current_call.py
weave/trace/context/call_context.py
weave/trace/weave_client.py

- describe immutability of call attributes in docs and code comments
- allow user edits to call.summary and mention merge behavior
- test attribute immutability edge cases and summary merge
- `nox --no-install -e lint` *(fails: Failed to fetch packages)*
- `nox --no-install -e "tests-3.12(shard='trace')"` *(fails: pytest errors)*

feat(weave): document call attribute immutability and summary editing

---

bin/codex_setup.sh
noxfile.py

Ensures that we install the correct lint / precommit hooks before internet access is removed

chore(weave): Fixes bootstrap script for Codex (v3)

---

weave-js/src/components/Icon/Icon.tsx

Prevents icons from shrinking in flex containers. See https://wandb.ai/authorize for a reference to this problem.

fix(app): fixes icon shrinking problem

---

docs/docs/guides/core-types/evaluations.md

- Fixes https://wandb.atlassian.net/browse/DOCS-1545
https://weave-docs.wandb.ai/guides/core-types/evaluations needs some ❤️ 
- Distinguish between eval object and individual runs
- talk about the different ways to generate and name objects vs runs
- clean up language and headers overall
- pull out usage info and tips from the codebase
- Reorg sections more logically so it flows like a tutorial and covers all major parts of evals 
- Move complete code sample and screenshots to it’s own section
- Add more descriptions

docs(weave): Improve eval doc

---

tests/integrations/openai/test_openai_sdk.py

- add tests for new streaming behavior with non-OpenAI endpoints
- `nox --no-install -e lint`
- `nox --no-install -e "tests-3.12(shard='custom')" -- integrations/openai/test_openai_sdk.py`
- `nox --no-install -e "tests-3.12(shard='trace')" -- trace/test_client_trace.py::test_simple_op`

test(weave): cover stream options host check

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/CompareEvaluationsPage.tsx

- Callout area for eval compare page.
- Reduce moving-the-cheese effect for moving results to new page.

chore(ui): Added callout area to eval compare page

---

weave-js/src/components/PagePanelComponents/Home/Browse3/typeViews/moviepy.video.VideoClip/VideoPlayer.tsx

| ![image](https://github.com/user-attachments/assets/d5baa9c3-419d-40c1-8cef-3c4137c8ca33) | ![image](https://github.com/user-attachments/assets/e7fb22fe-ebe0-48a8-890f-f30e698f6d40) |
| ![image](https://github.com/user-attachments/assets/eacb9170-51fc-4448-b780-65b1187c32a3) | ![image](https://github.com/user-attachments/assets/ebaa7990-3981-4678-bc1c-4a9a79dee97f) |
- Loads video to 1s, removes controls, and adds a play button overlay if loaded in the peek drawer.
- Uses pill w/ MP4 extension if the video is referenced in the list view (emulates design of MP3 waveform).

chore(ui): Video thumbnail enhancement

---

tests/trace/test_call_behaviours.py
tests/trace_server_bindings/test_remote_http_trace_server_binding.py
weave/__init__.py
weave/trace/api.py

Now that the full weave code is in the server image, `configure_logger` affects any logger whose name starts with `"weave."`. By default these logger will propagate to the parent logger, which leads to double printing.
Moving `configure_logger()` to `init` ensures that the configuration only affects real SDK usage, not all imports of the `weave` module.
- Not yet tested in the scoring worker, but will do in the morning.

chore(weave): Move logger configuration to init so that it doesn't affect non-SDK usage

---

pyproject.toml
tests/integrations/smolagents/test_smolagents.py
weave/integrations/smolagents/smolagents_sdk.py

`smolagents` got a new version (1.17.0). Which changes its internal logic a bit so that we don't get exactly the same number of runs.

fix(weave): Updating smollagents test for new version

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts

The backend checks the filter against `None` to trigger a special performant stats query. In the frontend, we are actually passing an empty filter, which is not the same as `None`.
Prod:
Branch:

chore(weave): dont pass empty filter in stats query

---

tests/trace/test_weave_client.py
weave/trace/weave_client.py

- Fixes WB-25167
Rewrites the `sum_dict_leaves` function to properly handle lists of dictionaries with nested structures and mixed data types. The new implementation correctly aggregates numeric values while preserving non-numeric values in lists.
Most of its logic is already covered by existing tests.
However this PR added additional test cases that verify:
- Basic functionality with lists of dictionaries
- Handling of nested dictionaries
- Empty lists and dictionaries
- None values
- Mixed data types in the same key position
- Deeply nested dictionary structures (up to 2 levels)

fix(weave): Resolve mixture of value types in weave_client.sum_dict_leaves

---

tests/trace/test_objects_query_builder.py
weave/trace_server/objects_query_builder.py

Comments in queries get logged to dd which makes it ugly(er) and [bloated](t&cols=host%2Cservice&event=AwAAAZcY6gOY-FsCgAAAABhBWmNZNmhXZ0FBQ044NDVJZEJfQWdRQUoAAAAkMDE5NzE4ZWYtNWFiMy00MDA5LWJhZmEtNGRiNmZiMTU2MzdhAAP9Qw&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&viz=stream&from_ts=1748469677884&to_ts=1748469680926&live=false), lets just pull it out.

chore(weave): move comment out of query to remove from logs

---

tests/integrations/openai/test_openai_sdk.py
weave/integrations/openai/openai_sdk.py

Fix [WB-25044](https://wandb.atlassian.net/browse/WB-25044)
- Fixes issue with stream_options being set for non-OpenAI endpoints
`stream_options` currently only happen for Completion series API, because that's the only occasion we would attach {stream: true}
For non-OpenAI endpoints, eg mistral, the `stream_options` config is not supported and will be rejected. 
So we can't just add `stream_options` indiscriminately.
This PR modifies the `_add_stream_options` function to only set `stream_options` when the API endpoint is specifically targeting OpenAI's official API (`api.openai.com`). It checks the hostname from the client's base URL before applying the stream options, preventing these options from being incorrectly applied to other compatible APIs.
added tests in …

fix(weave): Streaming mode is broken for mistral endpoints

---

weave-js/src/components/Icon/Icon.tsx

Icons should by default appear next to elements rather than consume the block. For example: 
rather than

fix(weave): default Icon to inline block

---

weave/trace/env.py
weave_query/weave_query/environment.py

- Fixes 25242
Attempting to read an unavailable netrc file was reported to cause a large delay in execution.
This changes the code to just return the env key if found (which is prioritized anyways) which is how the node SDK already handles this.

fix(weave): Do not attempt to read .netrc when API key is set in env

---

docs/docs/guides/tracking/tracing.mdx
docs/docs/quickstart.md
sdks/node/README.md
sdks/node/package.json

- Updates TypeScript SDK documentation to reflect automatic instrumentation of OpenAI
- Removes references to `wrapOpenAI()` which is no longer needed
- Adds links to the TypeScript SDK integration guide for complete setup instructions
- Updates code examples in quickstart and tracing guides to use the simplified approach
- Bumps Node SDK version from 0.8.0 to 0.9.0
Verified all documentation examples are consistent with the current SDK behavior and that links to the TypeScript integration guide are correct.

chore(weave): Bump TS SDK version and update docs

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/CompareEvaluationsPage.tsx

Modifies default view to be table instead of split

chore(weave): Design - default eval compare view results to table instead of split view

---

tests/integrations/bedrock/bedrock_test.py
weave/integrations/bedrock/bedrock_sdk.py

Disable the application of the postprocessor when there is no outputs.
- Added a test for it.

chore(weave): Bedrock invoke postprocessor fix

---

weave-js/src/components/FancyPage/FancyPage.tsx

makes the fancy page's content a `main` element and applies the `main-content` id on it so the skip to content link can jump straight to it.
https://wandb.atlassian.net/browse/WB-25111

chore(weave): fancy page content as main with id

---

weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/ReactionsLoaded.tsx

Only show the popup when hovered or actually has existing reactions, not all feedback (which is now more broad). 
Prod
Branch

chore(weave): only show feedback hover with reactions

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallDetails.tsx

[WB-25314](https://wandb.atlassian.net/browse/WB-25314)
Make sure the predict and score table is visible before other children in the call display page. 
Branch
[WB-25314]: https://wandb.atlassian.net/browse/WB-25314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(weave): sort eval predict call table first

---

weave-js/src/components/PagePanelComponents/Home/Browse2/CellValueString.tsx

[WB-25400](https://wandb.atlassian.net/browse/WB-25400)
Limit the number of characters to display in the table and in the hover state. Update the "click" description to reference missing material. This improves loading time to first paint and performance of navigating around the table. 
prod
branch
[WB-25400]: https://wandb.atlassian.net/browse/WB-25400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

perf(weave): truncate strings in table display

---

tests/integrations/openai/test_openai_sdk.py
weave/integrations/openai/openai_sdk.py

- Captures the OpenAI API endpoint URL in call attributes when using the OpenAI SDK
- Extracts the base URL from the completion client and adds it to the call input parameter `self`.
Tested by verifying that the API endpoint is correctly captured in the call input when making OpenAI API calls through the SDK.
Preview:

feat(weave): OpenAI API endpoint tracking

---

weave-js/src/components/PagePanelComponents/Home/Browse3/inference/DetailTile.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/inference/ModelDetailsLoaded.tsx

This improves the layout of the model details page when you reduce the width of the browser window. Before, the code component wouldn't shrink, detail tiles wouldn't wrap, etc. causing content to be clipped in a bad way.
Before:
After:

fix(weave): better resizing of model details

---

tests/integrations/langchain/cassettes/langchain_test/test_langchain_google_genai_usage.yaml
tests/integrations/langchain/langchain_test.py

This PR updates the VCR configuration in the langchain test to filter out the Google API key from the recorded cassettes. It replaces a real API key with a fake one in the test cassette file.
This change was tested by running the langchain integration tests to ensure they still pass with the updated VCR configuration.

chore(weave): remove the exposed API key

---

weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterBar.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/SelectDatetimeDropdown.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/TextValue.tsx

[WB-25435](https://wandb.atlassian.net/browse/WB-25435)
[WB-25311](https://wandb.atlassian.net/browse/WB-25311)
Changes in this pr:
**debounce**
- Increases debounce delay from 500ms to 1000ms to give users more typing time for dates
- Remove the global filter state debounce, so now selecting from dropdown and calendar execute immediately.
- Adds 1000ms debounce to the TextValue component to maintain existing text input functionality.
- Adds Enter key support to immediately parse and confirm input
- Enhances blur behavior to immediately parse input when focus is lost
**input field**
- Removes automatic "1mo" default - component no longer forces a default value
- Prevents invalid input from updating filter state - invalid input shows red highlight but doesn't change the actual filter
- …

chore(weave): better datetime filter ergonomics

---

tests/trace/test_serialize.py
weave/trace/serialization/op_type.py

[WB-25498](https://wandb.atlassian.net/browse/WB-25498)
Turn changing memory addresses into stable `0x000000000` so multiple instantiations of the same function at different memory addresses doesn't create multiple versions of ops. This impacts all `litellm` calls! 
Turn `<Function object at 0x10c349010>`  --> `<Function object at 0x000000000>`
_We could also move these two regex operations into one:_ `_try_replace_memory_address` 
added test (fails without my change)
[WB-25498]: https://wandb.atlassian.net/browse/WB-25498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(weave): sanitize memory addresses to prevent dupe ops

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx

[WB-25503](https://wandb.atlassian.net/browse/WB-25503)
Loading a call details drawer with a child calls table causes a loader on the entire page! It should only be loading in the drawer.
regression introduced in this pr: https://github.com/wandb/weave/pull/4343
Prod
Branch
[WB-25503]: https://wandb.atlassian.net/browse/WB-25503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(weave): isolate call details loader to drawer

---

weave-js/src/components/PagePanelComponents/Home/Browse3/inference/ModelDetailsLoaded.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/inference/ModelTile.tsx

Previously added model ID copy button to model tile, design requested adding it to details page too.
Internal slack: https://weightsandbiases.slack.com/archives/C08RU04P36G/p1749746145399799?thread_ts=1749683637.172539&cid=C08RU04P36G
Recommend "Hide Whitespace". I also put in some better conditional rendering if `idPlayground` is missing, which is allowed by current type definitions but shouldn't come up in practice with our starting data.

chore(weave): add model id copy button to details page

---

tests/trace/test_top_level.py
weave/trace/api.py

This is helpful for users who do:
```py
weave.init(project)
```
but then need to retrieve the client later (perhaps in a different context).  Now they can:
```py
client = weave.get_client()
```

chore(weave): Add top level get_client function

---

weave/trace_server/clickhouse_trace_server_batched.py

By default, use the prod inference service endpoint. To make things work in QA (hopefully, needs testing) we will get the hostname and sneak it into the headers that get passed through to this layer.

chore(weave): use prod inference service hostname by default

---

weave-js/src/components/PagePanelComponents/Home/Browse3/inference/ModelDetailsLoaded.tsx

This is not the final icon either, updating per design's request until they can make us a new one.
Before:
After:

chore(ui): change icon for license field in model details page

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/llmMaxTokens.ts

When I updated our model data in https://github.com/wandb/weave/pull/4730 I forgot to update llmMaxTokens.ts which broke opening up the playground with the selected models.

fix(ui): update llmMaxTokens

---

weave-js/src/components/PagePanelComponents/Home/Browse3/inference/Explorer.tsx

(Recommend hide whitespace)
Don't attempt to render the model catalog UI until we know the available width. Before, on load the initial width of the component would be 0, causing the computed number of tile columns to be 1, leading to a distracting animation when the actual width was available if the number of computed columns was greater than 1 (which was likely for common desktop browser widths).

fix(ui): don't render model tiles until we know available width

---

weave/trace/weave_init.py

Resolves: https://wandb.atlassian.net/browse/WB-25497
This prevents calls from getting lost in case the first client gets cleaned up

chore(weave): When initializing client in a new project, flush the existing client first

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/LLMDropdownOptions.tsx

Internal Slack: https://weightsandbiases.slack.com/archives/C08RU04P36G/p1749683637172539
Add Preview pill in model select component.

chore(ui): add Preview pill to model selection menu

---

weave-js/src/components/PagePanelComponents/Home/Browse3/inference/ModelTile.tsx

There's intentionally a small area around the model tile buttons where clicks are ignored - it's too easy to miss the button and cause a confusing tile deselection. However, the div was stretching across the tile, which made it confusing why selection wasn't toggling when you clicked to the right of the buttons.
Internal Notion report: https://www.notion.so/wandbai/W-B-Inference-QA-Testing-210e2f5c7ef38051a7e8d9dd2ab01cd6?source=copy_link#211e2f5c7ef380f5978bda678d2b72bc

chore(ui): smaller ignored click zone on model tile

---

weave/trace/op.py

Error handling for ops only captures Exceptions, but we need to also handle KeyboardInterrupt, SystemExit which, like Exception, inherit from BaseException. Traces experiencing these would be left in a running state forever, and if the client context is re-used, eg in a notebook, all new calls will inherit the call stack from the point of failure.
Changing the blanket catch from `Exception` to `BaseException` will catch the things we want but will also catch `GeneratorExit`, which gets raised in healthy generator exits, kind of a weird implementation detail of python.

fix(weave): handle `KeyboardInterrupt`, `SystemExit` within ops

---

weave/trace_server/clickhouse_trace_server_batched.py

[WB-25559](https://wandb.atlassian.net/browse/WB-25559)
Fixes large call part insertion bug using new calls. We do not need these fields, in the `scoring_worker.py`, we only use `project_id` and `call_id`
manual: 
prod has no trace, while branch has:
[WB-25559]: https://wandb.atlassian.net/browse/WB-25559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(weave): strip large fields from queue push on call end

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/useChatCompletionFunctions.tsx

- Adds error handling to chat completion functions by displaying error messages as toasts
- Ensures users are notified when chat completion encounters an error
[Screen Recording 2025-06-17 at 12.17.55 PM.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/EP6WIPJt2CEmlVsvzEO5/2fbaec67-d008-423b-9756-9c443965970d.mov" />](https://app.graphite.dev/media/video/EP6WIPJt2CEmlVsvzEO5/2fbaec67-d008-423b-9756-9c443965970d.mov)
Tested by triggering error conditions in chat completion and verifying that error messages are properly displayed as toast notifications.

chore(weave): Add error toast for Playground stream errors

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/llmMaxTokens.ts

Fix https://wandb.atlassian.net/browse/WB-25632
Change the default model selection for the playground to be from our Inference Service. This should be safe even if the current account does not have access to the inference service (e.g. personal account, dedicated) because the `isValueAvailable` handling in the useEffect will fall back to the first value that is available. (And the previous default model selection happens to be the first model that was in OpenAI, which was the first provider.)

chore(ui): change playground default to use Inference Service

---

tests/trace/test_evaluate.py
weave/flow/eval.py

Fixes WB-25648
A customer is returning a custom object from their summary (in this case pydantic), which crashes on the json dump. We should never fail when all we are doing is logging some info to the user. This PR simply makes that a safe procedure

fix(weave): Ensure summary logging does not crash when custom summary includes non-primitives

---

weave-js/src/components/PagePanelComponents/Home/Browse3/compare/ComparePageCalls.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClientTypes.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts

- Adds support for retrieving storage size information for calls in the Compare Page
- Extends the trace server client types to include a new `include_storage_size` parameter
- Updates the data model hooks to pass this parameter to the API when requested
Tested by verifying that the Compare Page successfully retrieves and displays storage size information for calls when the `includeStorageSize` parameter is set to true.

feat(weave): include the ingestion size in call compare view

---

weave-js/src/components/Panel2/ImageWithOverlays.tsx

Fixes this warning in the console that caused an issue with the bounding boxes disappearing
Before:
https://github.com/user-attachments/assets/b700a323-8c30-44a4-8ddf-0e40c4a4e3df
After:
https://github.com/user-attachments/assets/3f6a7bbb-4ecf-49b1-b65a-e8efd55c7f59

fix(app): Fix bounding box outline disappearing on resize

---

weave/trace_server/migrations/016_add_thread_id_to_stats.down.sql
weave/trace_server/migrations/016_add_thread_id_to_stats.up.sql

Adds `thread_id` to the `calls_merged_stats` table and updates the `calls_merged_stats_view` materialized view to include this field. This change enables tracking thread information in call statistics, which will help with analyzing execution flow across threads.
This was missed in PR https://github.com/wandb/weave/pull/4805 
This PR was tested by:
- Applying the migration to a test database
- Verifying that the `thread_id` column was properly added to the `calls_merged_stats` table
- Confirming that the materialized view correctly includes the thread_id field

chore(weave): add thread_id to stats view and table

---

weave/trace_server/clickhouse_trace_server_migrator.py

This pull request updates the `_determine_migrations_to_apply` method in `weave/trace_server/clickhouse_trace_server_migrator.py` to improve clarity and enforce stricter migration behavior. The changes include refining warning messages and disabling automatic down migrations.
* Updated the warning message when the current version exceeds the known versions to provide clearer context about the situation.
* Disabled automatic down migrations by replacing the logic with a warning message, instructing users to handle down migrations manually. This ensures greater control and prevents unintended operations.

chore(weave): Disable automatic down migrations to prevent un-intended behavior

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTableButtons.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-25727
Internal Slack: https://weightsandbiases.slack.com/archives/C01T8BLDHKP/p1750792719999149
We should scope with the entity when doing a `weave.init` in the Python export code sample - if your default entity is not the one you are looking at, the code sample could confusingly create a different project with the same name and the query would return 0 results.
Note that the curl code sample does already include the entity.

fix(weave): Include entity in weave.init in Python code sample

---

tests/trace/test_server_file_storage.py
weave/trace_server/file_storage.py

[WB-25670](https://wandb.atlassian.net/browse/WB-25670)
I believe the issue was that the gcp client automatically retries "retryable" exceptions, per [this](https://cloud.google.com/python/docs/reference/storage/latest/retry_timeout) doc. So we were actually retrying like 5 x 3 times! Disable the auto retries, rely on our own handling.
This probably also explains why the timeouts were longer, and there are no logs for the retries! 
Adds test
[WB-25670]: https://wandb.atlassian.net/browse/WB-25670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(weave): disable auto retries in gcs boto causing long busy waits

---

weave-js/src/components/PagePanelComponents/Home/Browse3/filters/filterUtils.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx

[WB-25753](https://wandb.atlassian.net/browse/WB-25753)
Okay kinda wild, but use a global constant to never ever assign the same id when creating a filter. This should prevent collisions, even when filters are in a un-saved state. Also, use the `getNextFilterId` when option clicking! 
Prod
Branch
[WB-25753]: https://wandb.atlassian.net/browse/WB-25753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(weave): fix option click filter then delete

---

weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/CreateDatasetDrawer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/CreateDatasetDrawerContext.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/datasetOperations.test.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/datasetOperations.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/useDatasetSaving.tsx

I am using the dataset editor in the Eval Playground and need to refactor some dataset code. This PR extracts the non-functional changes for easier review.
Specifically:
1. Extracts `DatasetFilePicker` for external use in `weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/CreateDatasetDrawer.tsx`. This will allow me to directly embed this in another part of the app.
2. Exposes `initializeDataset` as part of the CreateDatasetDrawerContext in `weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/CreateDatasetDrawerContext.tsx`. This allows me to directly bootstrap a new dataset with raw data
3. Correctly types `createNewDataset` and allows me to get the ref back out `weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/datasetOperations.ts`
4. …

chore(weave): Code Refactor: Datasets 1

---

weave-js/src/components/PagePanelComponents/Home/Browse3/OpCodeViewer.tsx

- Fixes WB-25598
Added a parent container for the code viewer with some styling for overflow handling
Bug was reproduced: In the view accessible by clicking on the op+version from the summary tab the code tab is opened by default and does not reach the bottom.
After this change, even when first opened the code will scroll to the bottom

fix(weave): fix scroll not reaching bottom of code

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/ChatFormats/openai.ts

Fixes https://wandb.atlassian.net/browse/WB-25767
If an exception was thrown during op execution, call.output will be null. Our checking for whether the call matches the OpenAI responses format was not handling this case.
```
TypeError: Cannot use 'in' operator to search for 'object' in null
at isTraceCallChatFormatOAIResponsesResult
```

fix(ui): Page crash in chat view for OpenAI responses when exception was thrown

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/ChatFormats/anthropic.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/ChatFormats/langchain.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/ChatFormats/types.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ChatView/hooks.ts

- Fixes WB-25805
Enables ChatView for langchain when used with Anthropic, Gemini, and OpenAI providers. Also adds error handling which hides the chat view if an error is encountered while processing a detected format.
Tested with various scripts and forced an error to be thrown which resulted in the chat view being hidden.

feat(weave): LangChain ChatView

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/MonitorsPage/MonitorFormDrawer.tsx

Before this PR, the monitor form would always fetch the latest object named after the scorer object. Those names are not unique across object types.
In the case where the user names the scorer the same as the monitor, the fetched scorer would actually be the monitor object, resulting in the form not showing the scorer sub-form. Then upon saving, the scorer is removed from the monitor.
This PR uses the exact scorer version key to fetch it from the server.

fix(weave): Fetch correct scorer in monitor form

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts

[WB-25669](https://wandb.atlassian.net/browse/WB-25669)
After a successful subsequent request, reset the error state. 
prod
branch
[WB-25669]: https://wandb.atlassian.net/browse/WB-25669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(weave): clear error on subsequent request

---

tests/trace/test_call_object.py
tests/trace/test_client_trace.py
tests/trace_server/test_threads_query_builder.py
weave/__init__.py
weave/trace/api.py
weave/trace/context/call_context.py
weave/trace/weave_client.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/external_to_internal_trace_server_adapter.py
weave/trace_server/sqlite_trace_server.py
weave/trace_server/threads_query_builder.py
weave/trace_server/trace_server_interface.py
weave/trace_server_bindings/caching_middleware_trace_server.py
weave/trace_server_bindings/remote_http_trace_server.py

- Adds thread context support to Weave, allowing users to group related operations under a common thread ID
- Implements `weave.thread()` context manager for setting thread IDs on calls
- Adds turn_id tracking to identify top-level operations within a thread
- Introduces ThreadContext class that provides access to thread_id and turn_id
- Adds thread_id and turn_id fields to Call objects and ensures proper inheritance
Please review this doc for the overall plan
https://www.notion.so/wandbai/Threads-API-Design-Document-PRD-21ee2f5c7ef3806f93ecfdb38b8982fb
Added comprehensive test cases that verify:
- Thread context management with the weave.thread() API
- Thread ID capture in call records
- Thread ID inheritance by child calls
- Error handling within thread contexts
- Turn ID functionality …

feat(weave): SDK support for using threads

---

tests/trace/test_client_trace.py

- Adds tests for thread ID query filtering functionality
- Adds comprehensive tests for the threads_query endpoint
This PR adds two new test functions to validate thread-related functionality:
1. `test_thread_id_query_filtering`: Tests that calls can be properly filtered by thread_id, verifying that the correct thread IDs are returned in query results.
2. `test_threads_query_endpoint`: Tests the threads_query endpoint (/threads/query) with various parameters including:
- Basic thread querying
- Limit and offset parameters
- Sorting by thread_id, trace_count, and last_updated
- Datetime filtering
- Combination of multiple parameters
- Validation of ThreadSchema field types and values
The PR is the test for [PR 4808](https://github.com/wandb/weave/pull/4808)

chore(weave): Unit tests for the /threads/query API

---

weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterBar.tsx

I forgot to remove the feature gate around the "Monitored by" filter option.

chore(weave): Remove omitted admin-only feature gate for online evals

---

docs/notebooks/Multi_turn_chat_evaluation.ipynb

This PR adds a detailed tutorial on evaluating multi-turn conversations using LLM as a judge. It shows how to define custom metrics in Weave and I have explained the reasoning behind their design. I’ve explained the steps in a very detailed way. Feel free to trim it down to better match your guidelines if needed.
I’m currently using a sample/dummy dataset.
- Do you have a HuggingFace Hub account where such datasets are usually stored?
- Or is there a preferred place for uploading example files?
No

docs(weave): add multi-turn conversation evaluation with custom metrics using Gemini APIs and Weave

---

weave/flow/eval_imperative.py

Resolves: https://wandb.atlassian.net/browse/WB-25510
This PR prevents instances from stomping on each other when logging in parallel by explicitly not using the global stack
This snippet will generate the following topology:
```py
def log_evals():
ev = weave.EvaluationLogger()
for x in range(3):
pred = ev.log_prediction(inputs={"a": x, "b": x+1}, output=x+2)
pred.log_score(scorer="scorer1", score=x+2)
pred.log_score(scorer="scorer2", score=x+3)
for x in range(3):
log_evals()
```
Before:
After:

fix(weave): Don't cause EvaluationLogger instances to stomp on each other when logging in parallel

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectsPage/ObjectVersionPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectsPage/Tabs/TabUseModel.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectsPage/Tabs/TabUseObject.tsx

Same change as in https://github.com/wandb/weave/pull/4944 but for models and other Weave objects. Adds an example to the Use tabs showing how to access with a name and version index instead of complete URI.
Checked copied code samples in ipython

chore(ui): add alternate get example for models and other objects

---

.github/workflows/test.yaml
noxfile.py
pyproject.toml

Parallelize trace tests by splitting them into shards.  Speeds up tests from ~17 min to ~6.5min (62%)

chore(weave): Parallelize trace tests

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx

Wrap the Trace navigator in an ErrorBoundary to avoid a whole page crash on error. (Hide whitespace)
Tried with the issue in https://github.com/wandb/weave/pull/4983 before that fix.

chore(ui): add error boundary around trace navigator

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallSummary.tsx

[WB-25950](https://wandb.atlassian.net/browse/WB-25950)
Move the expensive loading of trace size to when a user opens the summary page, rather than delaying the main call details tab from loading. 
Prod
Branch
[WB-25950]: https://wandb.atlassian.net/browse/WB-25950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

perf(weave): defer call stats to summary component

---

weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/context.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ThreadDetailPage/ThreadDetailPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ThreadDetailPage/ThreadMetadata.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ThreadDetailPage/ThreadTurnDetails.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ThreadDetailPage/ThreadTurnsList.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ThreadsPage/ThreadsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts

- Adds a new Thread Detail Page to view individual thread information
- Implements navigation from Threads list to Thread Detail view
- Creates components for displaying thread metadata, turns list, and turn details
- Adds routing support for thread detail pages
The PR introduces a Thread Detail Page that displays information about a specific thread, including its metadata, a list of turns within the thread, and detailed information about each turn. Users can navigate between turns and view performance thread-level metrics like p50 and p90 latency.
The chatlog view is intentionally left blank and will be implemented in the next PR.
Manually tested by:
- Navigating from the Threads list to a Thread Detail page
- Verifying thread metadata display
- Testing turn navigation and selection
- …

feat(weave): Show the thread detail drawer view

---

tests/integrations/anthropic/anthropic_test.py
tests/integrations/anthropic/cassettes/anthropic_test/test_beta_anthropic.yaml
tests/integrations/anthropic/cassettes/anthropic_test/test_beta_anthropic_stream.yaml
tests/integrations/anthropic/cassettes/anthropic_test/test_beta_async_anthropic.yaml
tests/integrations/anthropic/cassettes/anthropic_test/test_beta_async_anthropic_stream.yaml
weave/integrations/anthropic/anthropic_sdk.py

User reported that they had stopped getting traces logged when using newer versions of PydanticAI. We were able to reproduce - it worked in pydantic 0.2.6, didn't work >= 0.2.7. From the [Pydantic AI Changelog](https://github.com/pydantic/pydantic-ai/compare/v0.2.6...v0.2.7) we noticed [this PR](https://github.com/pydantic/pydantic-ai/pull/1818) where PydanticAI switched to using the beta methods of the Anthropic client. Weave's Anthropic integration wasn't autopatching those beta methods. 
This PR adds patching for the beta methods. It also updates a few imports to use preferred aliases, see e.g. https://github.com/anthropics/anthropic-sdk-python/blob/main/src/anthropic/types/message_delta_event.py#L8
Internal Slack: https://weightsandbiases.slack.com/archives/C0880TX4U5V/p174920708234888 …

feat(weave): Add support for auto-patching Anthropic beta model

---

weave-js/src/core/model/helpers.ts
weave-js/src/core/model/typeHelpers.test.ts
weave_query/tests/test_weave_types.py
weave_query/weave_query/weave_types.py

Improves the performance of the `union()` function when deduplicating typedDict types from O(n²) to O(n) complexity.
The previous implementation used `_.uniqWith()` which compared every type against every other type, resulting in quadratic time complexity. This became a bottleneck when processing unions with many typedDict members. The new implementation uses a hash-based approach with a `getTypedDictKey()` function that creates canonical string representations of typedDict types for fast deduplication via a Set.
The optimization maintains the original behavior including order preservation of union members. Non-typedDict types continue to use the original comparison logic to ensure correct assignability checking. Also includes a fix for notRequiredKeys assignability to ensure that …

perf(weave_query): optimize union type deduplication from O(n²) to O(n) for typedDicts

---

weave-js/src/components/PagePanelComponents/Home/Browse3/filters/SelectDatetimeDropdown.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ThreadsPage/ThreadsPageSavedViewControl.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ThreadsPage/ThreadsTable.tsx

- Fixes a race condition in the datetime dropdown component
- Improves default filter handling in the ThreadsPage
- Removes the onFilterModelChange handler from ThreadsTable which complicates the procedure of what FilterPanel does.
This PR addresses two issues:
1. Fixes a race condition in the SelectDatetimeDropdown component by adding a flag to prevent the blur handler from reverting values when a suggestion is clicked.
2. Improves the default filter handling in ThreadsPage by tracking when the default filter has been adopted, preventing it from being repeatedly applied. This fixes a bug that clearing all the datetime filters using the following UI would still revert to the default filter (Past 1wk).
Manually tested the datetime dropdown to ensure selecting suggestions works correctly …

fix(weave): datetime filter reliability on threads list page

---

sdks/node/src/__tests__/live/prompt.test.ts
sdks/node/src/__tests__/live/publish.test.ts
sdks/node/src/__tests__/live/weaveObject.test.ts
sdks/node/src/dataset.ts
sdks/node/src/evaluation.ts
sdks/node/src/weaveClient.ts
sdks/node/src/weaveObject.ts

The current serialization payload for TS objects looks like this:
```
{
...
val: {
"_type": "<Type>",
"_class_name": "<ClassName>",
"_bases": [...],
"_baseParameters": {
"id": "<id>",
"description": "<description>"
}
}
}
```
This is misaligned with payloads for Python objects. This PR changes it to match as such:
```
{
...
val: {
"_type": "<Type>",
"_class_name": "<ClassName>",
"_bases": [...],
"name": "<name>",
"description": "<description>"
}
}
```
- Fixes WB-26068
- unit tests

fix(weave): Align serialization payloads between Typescript and Python

---

weave/trace_server_bindings/async_batch_processor.py

[WB-26078](https://wandb.atlassian.net/browse/WB-26078)
Don't naively sleep, wait on shutdown condition with timeout. 
manual testing, appears to be fixed
[WB-26078]: https://wandb.atlassian.net/browse/WB-26078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(weave): shutdown health check thread immediately on exit

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ExampleCompareSection/ExampleCompareSectionTable.tsx

| <img width="1470" alt="image" src="https://github.com/user-attachments/assets/a12d33af-db3e-4028-92af-b41245b71047" /> | <img width="1470" alt="image" src="https://github.com/user-attachments/assets/d6ac39c7-b694-467c-9597-4bec11b1b060" /> |
Small change, updated header height to make it more compressed (`40px`, same as CallsTable).

chore(ui): Eval compare: Updated compare table header height

---

weave-js/src/common/components/elements/NumberInput.tsx
weave-js/src/common/components/elements/SliderInput.tsx
weave-js/src/common/util/shiftInputByValue.test.ts
weave-js/src/common/util/shiftInputByValue.ts

https://wandb.atlassian.net/browse/WB-25770
The ticks can be floats, so we can't just add one or subtract one. This extracts the same logic as the NumberInput to determine what the shift should be when the user presses the arrow keys to increment/decrement.
Before:
https://github.com/user-attachments/assets/c74bf4e6-ee68-4c76-bddc-10d2fe667c07
After:
https://github.com/user-attachments/assets/c014da95-2b23-4c88-b625-a20c179bc35d

fix(app): Fix slider input keyboard controls assuming integer ticks

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/SavedViews/savedViewUtil.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ThreadsPage/ThreadsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ThreadsPage/ThreadsPageSavedViewControl.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ThreadsPage/ThreadsTable.tsx

This PR supplements https://github.com/wandb/weave/pull/4889 which didn't support saved views properly.
- Enhances the Threads view with improved saved view functionality
This PR adds proper saved view functionality to the Threads page, matching the capabilities already available in Calls, Evaluations, and Traces views. It includes:
- Default configuration for Threads views with a 1-week filter and sorting by last_updated
- Support for saving column visibility and pin settings in Threads views
- Implementation of view renaming, saving, and deletion for Threads
- Refactored common configuration for Calls, Evaluations, and Traces into shared constants
Tested by:
- Creating, saving, and loading Thread views with different configurations
- Verifying that column visibility, pin settings, …

feat(weave): Saved view support for Threads page

---

.github/workflows/test.yaml
noxfile.py

Splits out non-server tests into their own shard, reducing CI time by ~1min (14%)

chore(weave): Split out non-server tests

---

weave/trace/api.py

py39 will be EOL in Oct 2025 (https://devguide.python.org/versions/)

chore(weave): Add warning that we will drop support for python 3.9

---

weave/trace/weave_client.py

While implemented backend evals, I noticed that our mixed project check was not checking for entity equality. This is equally as important! Adding this for safety

chore(weave): Fixes small bug with mixed project protection

---

weave/trace_server_bindings/remote_http_trace_server.py

Prep work for remote evals:
Allows the auth and extra_headers properties to be set by the constructor. Small refactor to make this nicer in terms of calling

chore(weave): Adds the ability for remote_http_trace_server to accept additional headers

---

tests/trace/test_evaluation_ref_get.py
weave/flow/eval.py
weave/trace/serialization/serialize.py

Our serialization/deserialization strategy is sorely in need of a re-write. I attempted it here, but it is a big change with wide-spread blast radius. Instead, I just made a very pointed hack to make sure we can deserialize things correctly. I learned a lot though, and am tempted to fix it once and for all soon.

chore(weave): Ensure that LLM-based evaluations can be serialized and deserialized correctly

---

pyproject.toml

Temporarily adding the wandb dependency back in (removed in https://github.com/wandb/weave/pull/4982) because there are a few cases we're not handling right without it yet.

fix(weave): add wandb dependency back in

---

weave-js/src/components/PagePanelComponents/Home/Browse3/charts/CallsCharts.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/charts/Chart.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/charts/ChartModal.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/charts/types.ts

https://wandb.atlassian.net/browse/WB-26065
- Adds custom naming capability for charts in the trace table chart section
- Implements a utility function `generateChartAutoName` to create automatic chart names based on axis fields and plot type
- Adds a text field in the ChartModal to allow users to set custom names for charts
- Using auto-generated names when custom names aren't provided
Tested by creating various chart types (scatter, line, bar) and verifying that:
- Default auto-generated names are created correctly based on chart configuration
- Custom names can be entered and are properly displayed
- Names persist when charts are saved and reopened for editing
https://github.com/user-attachments/assets/ff6705f9-fd69-414d-b0cd-d826badc6f47

feat(weave): customize chart names in trace table

---

weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/context.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ThreadDetailPage/ThreadTurnsList.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ThreadDetailPage/TurnAnchor.tsx

This PR enhances navigation between thread and call views by:
1. Adding back navigation capability in peek views with a new back button
2. Implementing a "previous URL" tracking system to enable proper navigation history
3. Making "View trace" links clickable in the TurnAnchor component
4. Adding a "Trace" button to each turn in the ThreadTurnsList for quick access to trace details
These changes improve the user experience by:
- Preserving navigation context when moving between related views
- Providing intuitive ways to navigate back to previous screens
- Adding convenient access points to trace information from thread views
The implementation uses React Router for navigation and maintains state about previous URLs to enable proper back navigation, especially within peek views.
The video …

feat(weave): Add link to go to trace detail view

---

tests/conftest.py
tests/trace_server/conftest_lib/trace_server_external_adapter.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/external_to_internal_trace_server_adapter.py
weave/trace_server/sqlite_trace_server.py
weave/trace_server/trace_server_interface.py
weave/trace_server_bindings/caching_middleware_trace_server.py
weave/trace_server_bindings/remote_http_trace_server.py

Simple PR that adds the scaffolding for:
* `evaluate_model`
* `evaluation_status`
These are not implemented currently and will not have user impact. I am on my 3rd iteration of the underlying implementation now and I just want to get the stubs landed to make incremental delivery easier

chore(weave): Adds backend evaluation stubs

---

weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterBar.tsx

[WB-26056](https://wandb.atlassian.net/browse/WB-26056)
Fix for double popovers causing contention and call stack exceeded runtime errors. 
prod
branch
[WB-26056]: https://wandb.atlassian.net/browse/WB-26056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(weave): remove datetime filter callstack exceeded error

---

tests/trace_server/test_trace_server_evaluation_apis.py

Skip [broken test](https://github.com/wandb/weave/actions/runs/16228542054/job/45826073140?pr=5069) in sqlite
test

chore(weave): skip sqlite on test with db lock

---

weave-js/src/components/PagePanelComponents/Home/Browse3/inference/types.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/InferenceBanner.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/PlaygroundPage/PlaygroundChat/InferenceBannerAdvertise.tsx

Fixes https://wandb.atlassian.net/browse/WB-26164 
Note: banner won't appear until a [small core PR](https://github.com/wandb/core/pull/31583) that passes in `inferenceFreeLimit` lands.
Expected banner on Personal, Enterprise (wandb), Free accounts.

chore(ui): add inference service advertisement banner to playground

---

tests/trace/test_weave_client.py

Test flakes: https://github.com/wandb/weave/actions/runs/16226956842/job/45821009761?pr=5066
I think this is because the client queues up calls in unexpected batches. In theory this test should never flake already, but it does.... This change ensures the client waits until the previous call is uploaded before proceeding, further reducing chance of flake. 
test

chore(weave): fix test flake sort by latency

---

sdks/node/package.json
sdks/node/src/integrations/openai.ts

- Fixes a bug in the OpenAI integration proxy implementation in TypeScript SDK
- Bumps Node SDK version from 0.9.1 to 0.9.2
Around May 29, OpenAI has released 5.0.0 with significant changes https://github.com/openai/openai-node/commit/7a857b3a609eaa471292bf8337ae5ae69dd74ac2
One impacting change is that it changes from emitting a Class object into a Function object. In javascript, one can modify a property of a class, but not a property of a function. 
So doing `exports.OpenAI = {} ` no longer works if `exports` is a Function. 
However `Object.defineProperty` can set a property of a Function. Luckily it so happens that `Object.defineProperty` works universally on Class object as well. That means it is a backward compatible approach for 4.X versions as well. 
What gets more complicated is …

feat(weave): Adapt to new export format for OpenAI integration

---

weave-js/src/common/components/elements/SliderInput.tsx

https://wandb.atlassian.net/browse/WB-26214
Based on feedback from Cécile, adds support for cmd / ctrl + left/ right arrow keys when incrementing and decrementing media panel steps. 
The commands will be:
> and < to change panel in panel full screen
> and < to change run in media full screen
And Ctrl > and Ctrl < to change steps.
corresponding core change: https://github.com/wandb/core/pull/31665

chore(weave): adding modifiers to SliderInput key bindings

---

weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/datasetNameValidation.ts

Relax dataset name validation in the create dataset drawer to match the actual backend constraints on object id.

chore(weave): relax dataset name validation

---

tests/flow/test_evaluation_imperative.py
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/LeaderboardPage/leaderboardConfigEditorHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/views/Leaderboard/query/leaderboardQuery.ts
weave/flow/eval_imperative.py

Modifies the leaderboard UI code to support `EvaluationLogger` (imperative-style) evals
See example code where we only log summary data:
```py
import weave
import random
weave.init('testing1009')
for k in range(2):
ev = weave.EvaluationLogger(model=f"abc{k}", dataset="def")
ev.log_summary({f"metric{i}": random.random() for i in range(4)})
```

fix(weave): Make EvaluationLogger work with Leaderboards

---

tests/trace/test_client_trace.py
tests/trace/test_publish_round_trip.py
tests/trace/test_weave_client.py
weave/trace_server/interface/query.py
weave/trace_server/trace_server_interface.py

Partially solves: [WB-25859](https://wandb.atlassian.net/browse/WB-25859)
Currently we allow extra keys in both the `CallsFilter`, `SortBy`, and `Query` portions of the `client.get_calls` query, which basically renders the existing validation worthless! Lets be stricter, and tell users if they have typed in something wrong...
This predictably also exposes a few unrelated errors for incorrect usages of these types!
- add explicit tests
- fix broken tests that weren't being validated
[WB-25859]: https://wandb.atlassian.net/browse/WB-25859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(weave): actually do validation on client side call queries

---

.pre-commit-config.yaml

This PR:
1. Moves the Fixit command first as it is a codemod and will affect all downstream checks
2. Moves pyright up before mypy because it's faster
3. Moves mypy up before the other checks which are not specifically code related

chore(weave): Reorder pre-commits to have most relevant checks run first

---

tests/trace/test_client_trace.py
weave/trace_server/clickhouse_trace_server_batched.py

[WB-26077](https://wandb.atlassian.net/browse/WB-26077)
The solution is to always order by `started_at, id` instead of just `started_at`. 
Actually, we should probably be adding order by id after ALL non-null sorts. The user should not be responsible for figuring that out...
- adds `test_trace_call_query_timings` which fails in prod
[WB-26077]: https://wandb.atlassian.net/browse/WB-26077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(weave): indeterminate ordering in callsquery w/ identical started_at

---

tests/trace_server/test_calls_query_builder.py
weave/trace_server/calls_query_builder/calls_query_builder.py

Filtering calls by feedback is crazy slow, this pr filters feedback first in a subquery, both forcing the use of the primary index and pre-filtering. 
Update unit tests
Manual testing in cloud console: 
| Env    | Elapsed   | Rows Read         | Data Read | Peak Memory   |
|--------|-----------|-------------------|-----------|---------------|
| prod   | 3.028s    | 28,424,000 rows   | 15.54 GB  | 12 GB         |
| branch | 0.114s    | 283,865 rows      | 43.70 MB  | 197.57 MiB    |

perf(weave): massively improve filter calls by forcing index

---

tests/trace/test_client_trace.py
tests/trace_server/test_threads_query_builder.py
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClientTypes.ts
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/sqlite_trace_server.py
weave/trace_server/threads_query_builder.py
weave/trace_server/trace_server_interface.py

- Adds thread_id filtering capability to the threads_query API
- Implements thread_id filtering in both ClickHouse and SQLite query builders
- Updates the ThreadsQueryFilter model to include the new thread_id field
- Adds comprehensive tests for thread_id filtering, including combinations with other filters
This changed is needed for refactoring of the Thread details page in https://github.com/wandb/weave/pull/5064
- Added unit tests for thread_id filtering in both ClickHouse and SQLite query builders
- Added integration tests that verify thread_id filtering works correctly in the API
- Tested combinations of thread_id with other filters (date ranges, sorting, pagination)

feat(weave): Let Thread API to support filter by thread id

---

docs/scripts/generate_service_api_spec.py

Problem
The make docs command was failing with a Docusaurus error:
Error: Docusaurus error: the <Tabs> component requires at least one <TabItem> children component
The build was failing specifically on the /reference/service-api/inference-chat-completions-inference-v-1-chat-completions-post page due to empty <SchemaTabs>
components being generated without any <TabItem> children.
Root Cause
The issue was in the OpenAPI specification processing pipeline. The API spec contained anyOf arrays with problematic combinations:
1. Empty objects: Some anyOf arrays contained empty objects {} alongside valid type definitions
2. Object-null combinations: Fields like response_format had anyOf arrays with only {"type": "object"} and {"type": "null"}
When the Docusaurus API docs generator processed these …

fix(weave): Fix docs build failure caused by empty SchemaTabs components

---

weave/trace_server/interface/builtin_object_classes/builtin_object_registry.py
weave/trace_server/interface/builtin_object_classes/generated/generated_builtin_object_class_schemas.json
weave/trace_server/interface/builtin_object_classes/saved_view.py

Adds chart configs for trace plots to the builtin types and saved view object definitions. Most of the diff is generated json. The main change is to `saved_view.py`.

chore(dev): add chart config to saved view type

---

docs/docs/guides/integrations/inference.md

- Fixes https://wandb.atlassian.net/browse/DOCS-1671
Addresses feedback here https://weightsandbiases.slack.com/archives/C08RU04P36G/p1753316192306759?thread_ts=1753311721.674809&cid=C08RU04P36G
- direct unpaid users to https://wandb.ai/subscriptions to upgrade and access pay-as-you-go inference if they run out of free credits
- Note that this doesn’t apply to enterprise users—they'll need to contact their account executive. 
- Clarify the 429 error code and what users should do
- Cosmetics, nits and a few typos
- Reorg page a bit so it's easier to parse and nav. Group content under new subsections for linkability

docs(weave): Update inference docs usage and limits

---

.github/workflows/notify-wandb-core.yaml

- Removes the `publish-package` job from the `notify-wandb-core.yaml` workflow
- Weave-js moved to core, so there's no point in publishing it from here

chore(dev) remove weave js package publish

---

weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/model_providers/model_providers.json
weave/trace_server/model_providers/model_providers.py
weave/trace_server/model_providers/modelsFinal.json

Updates our script that creates the `models_providers.json` file to also pull in information about CoreWeave hosted models.
This gives us a way to know which model strings should result in delegation to the Inference Service without having to prefix the model strings with `coreweave/`
The `gemini/` changes are unrelated update from re-running `make update_model_providers`

feat(weave): allow omitting coreweave/ prefix on hosted model strings

---

docs/docs/guides/evaluation/guardrails_and_monitors.md
docs/docs/guides/evaluation/scorers.md
docs/docs/guides/integrations/js.md
docs/docs/guides/platform/weave-self-managed.md
docs/docs/guides/tools/playground.md
docs/docs/guides/tracking/threads.md
docs/docs/introduction.md
docs/docs/reference/gen_notebooks/pii.md

This PR fixes all broken anchor links in the Weave documentation that were causing build warnings.
Fixed broken anchors in the following files:
- `docs/guides/evaluation/guardrails_and_monitors.md` - Updated data access guide link
- `docs/guides/evaluation/scorers.md` - Fixed tracing guide and evaluations guide links
- `docs/guides/integrations/js.md` - Corrected advanced usage section link
- `docs/guides/platform/weave-self-managed.md` - Updated cluster name configuration reference
- `docs/guides/tools/playground.md` - Fixed message controls section link
- `docs/guides/tracking/threads.md` - Updated basic and advanced examples links
- `docs/reference/gen_notebooks/pii.md` - Fixed prerequisites and method 1 links
- `docs/introduction.md` - Corrected pre-built scorers link
- ✅ Ran `npm run …

docs(weave): Fix broken anchors in documentation

---

docs/docs/guides/tracking/threads.md

1. The previous example of OpenAI and Anthropic provider example uses  `weave.thread()` context manager in the leaf weave.op functions, but when there is no weave ops underneath a thread, nothing will be grouped. This doc fixe lifts the location of `weave.thread()` usage 1 level up. This ensures thread context is established at the appropriate boundary.
2. Adds a new section on resuming previous sessions with examples of how to properly handle thread IDs when implementing optional thread resumption. The new documentation emphasizes the importance of always providing a valid thread ID rather than using `None`.

docs(weave): Rework thread handling in OpenAI and Anthropic API calls; Add session resumption example

---

weave/trace_server/calls_query_builder/calls_query_builder.py

Fixes: [WB-26607](https://wandb.atlassian.net/browse/WB-26607)
Error: `Error streaming response: can only join an iterable`
Master
Branch
[WB-26607]: https://wandb.atlassian.net/browse/WB-26607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(weave): sort by output when string

---

tests/trace_server/test_opentelemetry.py
weave/trace_server/opentelemetry/constants.py
weave/trace_server/opentelemetry/python_spans.py

- Fixes WB-26584
Add parsing and handling for these two attributes:
wandb.thread_id
wandb.is_turn
When wandb.is_turn is set to true, sets turn_id to the span.id (which is used for call.id)
When wandb.is_turn is set but thread_id is unset, ignore, is_turn is ignored
Added detailed test cases for the different scenarios

feat(weave): add OTEL parsing for thread_id and handling for is_turn

---

weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/NewDatasetSchemaStep.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/SchemaMappingStep.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/datasets/schemaUtils.ts

Allow for the inclusion of otel spans into datasets when importing calls into a dataset in the UI.

feat(ui): import otel spans into datasets

---

noxfile.py

Starts testing for py313 now that this version is officially supported by these packages

chore(weave): Start testing py313 for anthropic and crewai

---

docs/sidebars.ts

This PR fixes the sidebar configuration after the inference page was moved to the W&B docs site in PR #5222.
After merging PR #5222, the sidebar still contained a reference to the deleted `guides/integrations/inference` page, causing a build error:
```
[ERROR] Error: Invalid sidebar file at "sidebars.ts".
These sidebar document ids do not exist:
- guides/integrations/inference
```
- Removed the reference to `guides/integrations/inference` from the LLM Providers section in `sidebars.ts`
This ensures the documentation builds successfully without referencing the non-existent page.

docs(weave): Fix sidebar - remove inference page reference

---

docs/docs/guides/evaluation/guardrails_and_monitors.md
docs/docs/guides/integrations/index.md
docs/docs/guides/tools/playground.md
docs/docs/introduction.md
docs/docs/quickstart.md

This PR fixes broken links to the inference documentation that was moved to the W&B docs site in PR #5222.
After moving the inference page to https://docs.wandb.ai/guides/inference/, several documentation pages still contained broken links to the old location:
```
Exhaustive list of all broken links found:
- Broken link on source page path = /guides/evaluation/guardrails_and_monitors:
-> linking to ../integrations/inference.md (resolved as: /guides/integrations/inference.md)
- Broken link on source page path = /guides/integrations/:
-> linking to /guides/integrations/inference
- Broken link on source page path = /guides/tools/playground:
-> linking to ../integrations/inference.md (resolved as: /guides/integrations/inference.md)
- Broken link on source page path = /quickstart:
-> linking …
```

docs(weave): Fix broken links to inference documentation

---

weave/trace_server/clickhouse_trace_server_batched.py

Accumulator of reasoning_content for completions_create_stream so thinking tokens are saved on call

fix(weave): Add accumulator for reasoning-content to completions_create

---

weave/trace_server/reference/generate.py

Adds routes added in the last few months, notably `project_stats`, `threads_query_stream`, `completions_create_stream`, and `export_trace` (otel)

chore(weave): Update reference trace server to include new routes

---

pyproject.toml
tools/codegen/openapi.json
tools/codegen/openapi.stainless.yml
weave/trace_server/reference/generate.py

Adds OTEL, completions, and threads endpoints.
Additionally exposes the `completions` endpoint which was previously hidden

chore(weave): Update codegen to include new endpoints

---

docs/docs/guides/core-types/media.md

- Fixes https://wandb.atlassian.net/browse/DOCS-1520
Updates the docs from https://github.com/wandb/weave/pull/4528 to represent the current state of the API and moves the Content docs to the top of the media page since it is the preferred way to handle all media now.

docs(weave): document Content API

---

weave/compat/wandb/wandb_thin/internal_api.py

Re-adds support for gql>=4.0.0 which was previously added then accidentally removed in https://github.com/wandb/weave/commit/e70cfe4af2eb0e3371ee48608c918d2595e67738#diff-a106ba8e7cd28ff9ea9bd95a182b7397daa2c2fa24394faf35cca07202be9953

chore(weave): Add support for gql>=4.0.0 (pt2)

---

pyproject.toml

This is only used in the trace server, so moving the dep there

chore(weave): Remove jsonschema dep from client

---

tests/trace/test_client_trace.py
tests/trace/test_op_decorator_behaviour.py
tests/trace/testutil.py
tests/trace_server/test_refs.py
weave/flow/saved_view.py
weave/integrations/integration_utilities.py
weave/trace/api.py
weave/trace/display/rich/refs.py
weave/trace/feedback.py
weave/trace/refs.py
weave/trace/serialization/custom_objs.py
weave/trace/serialization/serialize.py
weave/trace/weave_client.py
weave/trace_server/workers/evaluate_model_worker/evaluate_model_worker.py
weave/trace_server_bindings/caching_middleware_trace_server.py

Moves ref methods on to the Ref objects themselves, which is more descriptive in some cases

chore(weave): Move ref methods to the Ref objects themselves

---

tests/trace/type_handlers/Content/content_test.py
weave/type_wrappers/Content/utils.py

- Fixes [WB-27106](https://wandb.atlassian.net/browse/WB-27106)
Attempting the `_from_guess` method used for annotations would cause the text to attempt to be encoded to ascii, which raised an uncaught error during the check if a string is valid base64. This allows HTML and Markdown or any other text with unicode characters like emojis to work with Content.
Adds regression test
[WB-27106]: https://wandb.atlassian.net/browse/WB-27106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(weave): Ascii encode error for content

---

.github/workflows/release.yaml

Update `weave` reference in wandb/core for integration tests when the weave sdk is released.
Sending half of https://github.com/wandb/core/pull/33810

test(weave): update weave SDK version in wandb/core for tests on release

---

noxfile.py

Adds a flag to only run the fast checks

chore(weave): Add --ruff-only flag to lint to run just the fast ruff checks

---

weave/flow/leaderboard.py

https://wandb.atlassian.net/browse/WB-25790
In some cases the `call.output` could be `None`, resulting in an Exception

fix(weave): Dont crash if leaderboard call output is None

---

.github/workflows/test.yaml

https://wandb.atlassian.net/browse/WB-27281
In future, we'll add a nightly shard to run all versions
https://github.com/wandb/weave/pull/5395

chore(weave): Only run CI on min and max supported python versions

---

docs/docs/guides/tracking/tracing.mdx

Resolves [DOCS-1275](https://wandb.atlassian.net/browse/DOCS-1275). This update adds information about how `op.call` manages exception handling. It also clarifies the existing documentation to be more explicit.
[DOCS-1275]: https://wandb.atlassian.net/browse/DOCS-1275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(weave): Updates tracking doc to explain exception handling

---

tests/flow/test_evaluation_imperative.py
weave/evaluation/eval_imperative.py

See https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1756247631879479
Passing a string as the "model" parameter to EvaluationLogger that was not a valid class name would raise a ValidationError.
```
File "/Users/jamie/source/jcr/suprot_2025-08-25/infdoc.py", line 112, in <module>
evaluate_model(model, dataset)
File "/Users/jamie/source/jcr/suprot_2025-08-25/infdoc.py", line 70, in evaluate_model
eval_logger = EvaluationLogger(
^^^^^^^^^^^^^^^^^
File "/Users/jamie/source/jcr/suprot_2025-08-25/.venv/lib/python3.12/site-packages/pydantic/main.py", line 214, in __init__
validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```

fix(weave): sanitize string passed as model name to EvaluationLogger

---

weave/trace_server/calls_query_builder/calls_query_builder.py

[WB-27450](https://wandb.atlassian.net/browse/WB-27450)
New clickhouse version: `25.8.2.29` breaks the weave data existence check special query! All projects with both wandb and weave data will not show _any_ weave data if this ch version hits prod without a change. 
Currently, all dev environments testing with the most recent clickhouse version will suffer the above issue. 
This pr re-writes the stats query to not use `multiIf` and `Exists`, the later of which has had pretty extensive work done on it in the most recent ch release, possibly causing this issues. 
[WB-27450]: https://wandb.atlassian.net/browse/WB-27450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(weave): calls stats existence query works w/ new ch version

---

tests/trace_server/test_environment.py
weave/trace_server/environment.py
weave/trace_server/kafka.py

[WB-27534](https://wandb.atlassian.net/browse/WB-27534)
Max buffer size on the trace server kafka queue. Warn if at 50%. Drop call from queue push at 100%. Call will still be inserted, but not eligible for online scoring. 
how do we test scoring worker stuff? 
[WB-27534]: https://wandb.atlassian.net/browse/WB-27534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(weave): drop calls from bufstream produce after max (10k)

---

weave/trace_server/interface/builtin_object_classes/saved_view.py

This is a required change by PR https://github.com/wandb/core/pull/34330

chore(weave): Adds a missing field in the saved view schema

---

docs/docs/guides/tools/evaluation_playground.md

This clarifies that you can only use "models" created using the playground feature in the playground.

docs(weave): Updates Eval Playground doc to mention model limitation

---

pyproject.toml

- Fixes #NNNN
Our CI started failing when llama-index==0.12.50 introduced a breaking change. As a stopgap, this PR initially pinned llama-index to <0.12.50. The upstream maintainers have since shipped a patch release that resolves the issue introduced in 0.12.50. This PR updates the dependency to the fixed version and removes the temporary <0.12.50 constraint.

fix(weave): unpin LlamaIndex dependency

---

tests/trace_server/test_custom_provider.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/llm_completion.py

Allows the usage of '/' and ':' in provider and custom model names unblocking ollama and openrotuer custom model usage
Changes to accept a custom:: prefix from the frontend on custom provider requests instead of just guessing at it
created and hit local ollama models and sent reqeusts to openrouter

fix(weave): use delimiter and custom:: prefix for custom providers

---

weave/trace_server/model_providers/model_providers.py

Python declarations and small data loading function for the JSON file that powers the Inference model catalog. 
These will be used in a core PR that implements the OpenRouter model listing API.

chore(weave): add model JSON type declaration

---

.github/workflows/nightly-tests.yaml
noxfile.py

This minimizes spurious CI failures where memray causes a segfault

chore(weave): Move memray profiling to nightly tests

---

pyproject.toml

Latest version `0.1.4` breaks CI

chore(weave): Temporarily pin verifiers to unblock CI

---

weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/opentelemetry/python_spans.py

- Fixes WB-27757
Passes user id to call conversion for span so that it is associated with the call
manually

fix(weave): OTEL traces missing user id

---

weave/trace/settings.py

This has been opt in, but has been soaking for a while, we should make it default on. 
A month of testing in prod with the flag.

chore(weave): parallel table uploads by default

---

tests/trace/test_feedback.py
weave/trace_server/orm.py
weave/trace_server/token_costs.py

[WB-27642](https://wandb.atlassian.net/browse/WB-27642)
Fixes bug in field validation logic that was allowing any param with a column substring to hit the db. 
To do so we needed to add a way of bypassing the `_transform_external_field_to_internal_field` which gets called on more than just external fields it turns out. All of the cost/token query fields are hitting this function, which really makes zero sense!
add test 
and tested locally, costs appear fine:
[WB-27642]: https://wandb.atlassian.net/browse/WB-27642?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(weave): better feedback field validation

---

tests/flow/test_evaluation_imperative.py
tests/trace/test_current_call.py
weave/__init__.py
weave/evaluation/eval_imperative.py
weave/trace/api.py
weave/trace/view_utils.py

Adds `weave.set_view` to the primary api. Adds `EvaluationLogger.set_view` to the imperative eval logger api.
The parameter and return signature is the same for both. They accept a view `name` and `weave.Content` to display.
Content is persisted to the file backend and the json manifest is dumped into `summary.weave.views.<view_name>`.
This frontend PR adds rendering for these custom views to a new default tab for the call page: https://github.com/wandb/core/pull/34732
Added unit tests to verify the summary is populated with the `Content` json dump when called in an op or the imperative eval method, passed either by a `Content` object or a string with an extension or mimetype specified.

feat(weave): user code can define custom content to display on a call page

---

docs/docs/guides/core-types/env-vars.md

Resolves [DOCS-1474](https://wandb.atlassian.net/browse/DOCS-1474). Updates the environment variables page with information about how to disable link printing using the equivalent `weave.init(settings)` argument.
[DOCS-1474]: https://wandb.atlassian.net/browse/DOCS-1474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(weave): How to silence link printing using `.init()`

---

docs/docs/guides/integrations/index.md
docs/docs/guides/integrations/openrouter.md

The proper name for this company is "OpenRouter" without a space.
https://openrouter.ai/about
yarn start

docs(weave): fix OpenRouter name

---

pyproject.toml

Pins `pydantic<2.12.0` as the latest version seems to break a lot of things

chore(weave): Pin pydantic to unblock CI
