wandb/weave

.github/workflows/test.yaml

- actions/checkout@v2 is used with fetch-depth: 0 and token: ${{ secrets.GITHUB_TOKEN }} to get all history and allow push operations respectively
- run command is broken down into new lines
- actual implementation in 68-71

Fix lint issues using prettier, commit them back to branch

---

Dockerfile

Alpine 3.9.6 is no longer supported by the Alpine maintainers, so upgrading to the most recent version of this image.
Additionally, resolves the following:
- https://security.snyk.io/vuln/SNYK-ALPINE39-OPENSSL-1089235
- https://security.snyk.io/vuln/SNYK-ALPINE39-OPENSSL-1089232
- https://security.snyk.io/vuln/SNYK-ALPINE39-OPENSSL-1089234
- https://security.snyk.io/vuln/SNYK-ALPINE39-OPENSSL-1089233
- https://security.snyk.io/vuln/SNYK-ALPINE39-OPENSSL-1089231
- https://security.snyk.io/vuln/SNYK-ALPINE39-MUSL-1042761
- https://security.snyk.io/vuln/SNYK-ALPINE39-OPENSSL-1089236

chore: bump Dockerfile to alpine-3.17_glibc-2.34

---

weave/ecosystem/test_notebook_ecosystem_executions.py
weave/server.py
weave/tests/test_execution_graphs.py
weave/util.py
weave/value_or_error.py
weave/weave_server.py

About 2 weeks ago, I implemented node-level error handling. Well, that was really nice, but hid a bunch of node errors from getting captured in DD and Sentry. This PR logs out the errors to Sentry and DD before returning the response to the caller.

Re-enable capturing of error logs

---

weave/ops_domain/run_ops.py

If parquet history was empty we would return before calling `process_run_dict_item` on the live data. That would lead to dicts getting passed to ops that expected objects. This fixes that issue.

ensure all history entries are processed with process_run_dict_item

---

weave-js/src/common/components/Monaco/schemas/sweep-config-schema.json

These are just suggestions when creating a launch sweep for the frontend UI. They are not actually pushed to Anaconda2, as they get picked out of the sweep config and placed into the run config overrides.

chore(sweeps): add scheduler params for launch sweeps to suggestions

---

weave-js/src/common/components/JupyterViewer.tsx
weave-js/src/common/util/markdown.test.ts
weave-js/src/common/util/markdown.ts
weave-js/src/components/Panel2/PanelFileJupyter/Component.tsx
weave-js/src/components/Panel2/panellib/libpanel.ts
weave-js/src/context.tsx

In order to allow Markdown => HTML rules to be relaxed depending on the security of the outside environment we need a way to trigger changes in the sanitization schema from outside Weave. 
The usage of WeaveFeaturesContext is explained here: https://github.com/wandb/weave/pull/28#pullrequestreview-1475643423
Original slack thread: https://weightsandbiases.slack.com/archives/C01T8BLDHKP/p1686328384196249
ticket: https://wandb.atlassian.net/browse/WB-12729
wand PR that is blocked by this PR: https://github.com/wandb/core/pull/15416

feat: Allowing UI configuration to be passed in from outside

---

weave-js/src/components/Panel2/ChildPanel.tsx
weave-js/src/components/Panel2/PanelGroup.tsx
weave-js/src/components/Panel2/PanelPlot/PanelPlot.tsx
weave-js/src/core/hl.ts
weave-js/src/react.tsx
weave/execute_fast.py

This fixes issues where plots synchronized on zoom ranges would make additional unnecessary queries. And should generally improve app performance given the fixes to ref equality and resolve_static_values.
Perf:
- Fix ChildPanel and PanelGroup callback construction. We were always create non-ref-equal stack variables for all components, so the entire tree would generally rerender all the time.
- Adds client side mutations. If we're mutating a const node with a set of known ops (pick, getattr, index) we can perform the mutation on the client immediately.
- Fixes a python issue where resolve_static_values over-executed ops.
Debugging:
- adds an optional callSite parameter to useNodeValue, that can be used for debug logging

Perf fixes, including for zoom synchronized plots.

---

requirements.txt
weave/artifact_wandb.py
weave/ops_domain/history.py
weave/ops_domain/wb_util.py
weave/runfiles_wandb.py
weave/show.py
weave/storage.py
weave/tests/test_artifact_metadata.py
weave/tests/test_wb_stream_tables.py
weave/wandb_interface/wandb_artifact_pusher.py
weave/wandb_interface/wandb_lite_run.py
weave/wandb_interface/wandb_stream_table.py

Double Revert!
https://github.com/wandb/weave/pull/59 got merged too early... this is the re-do of that
----
This PR introduced a new top-level class: StreamTable which has a very simple API:
```python
st = StreamTable("entity/project/table_name")
st.log(row_or_list_of_rows)
```
Currently we only support sequential multi-writers (meaning you can stop and start over and over and keep logging to the same table). Soon we will have gorilla support for parallel writers (which should be only a few lines to uptake).
This data can be accessed by viewing the history of the run. Soon (my remaining TODO), we will also have top-level ops: opProjectStreams and opProjectStream which will give direct access to the underlying table. This will ensure we can swap out a first-class table API without users …

Revert "Revert "WIP: Stream Tables""

---

weave-js/src/components/Panel2/PanelPlot/versions/index.ts
weave-js/src/components/Panel2/PanelPlot/versions/v12.ts
weave-js/src/components/Panel2/PanelPlot/versions/v13.ts

https://wandb.atlassian.net/browse/WB-14186
Fixes https://weights-biases.sentry.io/issues/4022125791/?project=6620563&referrer=jira_integration
Fixes an issue that caused a full page panelplot crash with weave1 enabled. The issue was due to the fact that v12 of the panelplot config typed `LazyAxisSelection`s as `maybe(list(any))`. Weave python does not know how to deserialize const nodes of this type, so any stored panelplot configs with nonnull domains would cause a weave1 crash. 
This fixes this by adding a new config version migrated to have narrower types.

fix: narrow domain types  in panelplot

---

weave-js/src/components/Panel2/PanelGroup.tsx
weave-js/src/components/Panel2/toWeaveType.tsx

moves `panelIdAlternativeMapping` to `toWeaveType.tsx` to avoid a circular import in v13.ts.

refactor: refactor panelIdAlternativeMapping

---

weave-js/src/components/Panel2/PanelPlot/PanelPlot.tsx

Fixes https://weights-biases.sentry.io/issues/4167873076/?project=6620563&referrer=jira_integration
https://wandb.atlassian.net/browse/WB-14188
Ensures that we use the correct value types for our line tooltip nodes. These were sometimes typed as tagged values before, but they were never tagged values since we never called tag getter ops on them in the panelplot weave query. This ensures we always strip the tags from the types.

fix: fix Float object not subscriptable

---

weave-js/src/components/Panel2/useAssetFromArtifact.ts
weave-js/src/core/model/types.ts
weave/wandb_util.py

Fixes https://app.datadoghq.com/rum/replay/sessions/c5ed94d1-0d66-45bf-9966-9c711c32718e?highlightedEventId=AgAAAYj-aJxW2SBhiwAAAAAAAAAYAAAAAEFZai1hS05XQUFDN3dHX0xXZUtrU2dBQgAAACQAAAAAMDE4OGZlNmItYzBjOS00MGU3LTk1YjgtMmVkNmE2YWVmMWZj&p_devtools_tab=performance&seed=62c6b482-a313-45da-bf69-102c758f69bb&ts=1687895448662&from=1687895448274
We were not handling the wb_trace_tree type in `_convert_type`. This fixes that and also makes `wb_trace_tree` a media type so its properties are not transformed into columns in tables.

fix: fix full page crash in trace tree viewer

---

weave/ops_domain/history.py
weave/ops_domain/wb_util.py

Supports images/separated in history, fixing this full page crash 
https://app.datadoghq.com/rum/replay/sessions/04539f46-014f-4b65-8e51-6c90d89c9228?seed=2e0629b8-f92a-496b-9876-af1a4385577d&ts=1687907305412&from=1687907305305

feat: support Images/separated in history

---

DEVELOPMENT.md
weave-js/src/components/Panel2/PanelComp.styles.ts
weave-js/src/components/Panel2/PanelTable/PanelTable.tsx

Problem: When there are no rows to display in a table the table header is appearing beneath the "no rows" message.
Longer term we may consider additional improvements to the zero rows condition, but for now just trying to restore previous behavior.
Note: the solution here is reverting a previous change that was intended to fix a problem with the "remove filter" button not being clickable. I haven't been able to reproduce that problem, if it reoccurs will try to fix it another way.
Internal Jira: https://wandb.atlassian.net/browse/WB-14244
Internal Slack: 
https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1687892535814509?thread_ts=1687892494.958909&cid=C03BSTEBD7F
https://weightsandbiases.slack.com/archives/C05DURZNT41/p1687890163378049
Before:
After:

fix: table headers appear at bottom when no rows

---

weave/ops_domain/history.py

https://wandb.atlassian.net/browse/WB-14287
Fixes a regression in our handling of summary and history objects. We would raise anytime we didn't have an explicit history keytype for a summary or history entry (like a number or typeddict). This was due to the new streamtable section of the `history_key_type_count_to_weave_type` switch statement. `maybe_history_type_to_weave_type` would raise if `tc_type` was `None`. Now it correctly returns `types.UnknownType()` as before.

fix: 'NoneType' object has no attribute 'startswith'

---

weave/ops_domain/trace_tree.py

https://wandb.atlassian.net/browse/WB-14302
Fixes https://weights-biases.sentry.io/issues/4281416895/?referrer=jira_integration
We had incorrectly typed `Span.results` as `typing.Optional[typing.List[Result]]` when in fact it should have been `typing.Optional[typing.List[typing.Optional[Result]]]`. This was causing a full page crash on the second panel of `wandb.ai/morg/trace-example` with w1 enabled. This fixes the type and updates the sites downstream where it is consumed. Verified that it matches the w0 output on that workspace.

fix: refine type of results in Span class

---

weave-js/src/components/Panel2/PanelPlot/PanelPlot.tsx
weave-js/src/core/mutate.ts
weave-js/src/core/ops/primitives/list.ts
weave-js/src/react.tsx

- avoid unnecessary rerendering and fetching by ignoring types for useNodeValue, useNodeWithServerType
- don't do unnecessary & expensive PanelPlot defaultPlot computation

Perf improvements: 

---

weave-js/src/components/PagePanel.tsx
weave-js/src/components/Panel2/PanelCard.tsx
weave-js/src/components/Panel2/PanelEachColumn.tsx
weave-js/src/components/Panel2/PanelGroup.tsx
weave-js/src/components/Panel2/PanelPanel.tsx
weave-js/src/components/Panel2/PanelProjectionConverter/component.tsx
weave-js/src/components/Panel2/PanelTable/tableState.ts
weave-js/src/components/Panel2/libchildpanel.ts
weave-js/src/components/Panel2/panelTree.ts
weave-js/src/components/Sidebar/OutlineItemPopupMenu.tsx
weave-js/src/components/Sidebar/VarBar.tsx
weave-js/src/components/WeavePanelBank/PBSection.tsx
weave-js/src/components/WeavePanelBank/PanelBankFlowSection.tsx
weave-js/src/components/WeavePanelBank/PanelBankGridSection.tsx

I'm working on an [upgrade to Vite 4 in core](https://github.com/wandb/core/pull/15611), which itself will require building core with Immer v10, which removed the default export for `produce` and now requires a named import instead. This change will make weave's code work with both versions, then we can upgrade in weave itself later.

chore: immer 10 compatibility

---

weave/ops_domain/trace_tree.py
weave/tests/fixture_fakewandb.py

https://wandb.atlassian.net/browse/WB-14364
Fixes https://weights-biases.sentry.io/issues/4284886999/?project=6620563&referrer=slack&rule_id=12726589
`Result.inputs` can sometimes be a list of strings, but we were expecting it to be a dict. This adds handling for the list of strings case to reproduce the output in weave0. 
Testing: tested locally.

fix: update type results type handling in trace tree

---

weave-js/src/components/Panel2/PanelProjectOverview.tsx
weave-js/src/components/Panel2/PanelRegistry.tsx
weave/ecosystem/wandb/wandb_objs.py
weave/language_features/tagging/process_opdef_resolve_fn.py

Problem: Runs and Artifacts tabs of Project Overview panel are empty.
Internal Jira: https://wandb.atlassian.net/browse/WB-14326
Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1687987478104619
Before:
After:

fix: empty Runs and Artifacts tabs of project overview

---

.pre-commit-config.yaml
pyproject.toml
requirements.dev.txt

ruff is an extremely fast Python linter, written in Rust. It can do many of the same checks as flake8/pylint and other tools. The W&B SDK started using it recently.
See https://beta.ruff.rs/docs/rules/ for the rules we can choose to enable. Lots of possibilities to improve consistency, readability, and performance.
After installation you can run `ruff check .` to manually check for issues. I have also added it to pre-commit.
This PR intentionally enables almost no rules. We can turn them on one-by-one to incrementally ratchet up quality. 
I enabled two rules, mostly as an placeholder showing how to do it. These disallow `FIXME` and `XXX` annotations, none of which exist in the repo today. (We have very many TODO comments.) This is handy, as you can annotate something with FIXME to make …

chore: add ruff for fast linting

---

weave-js/src/components/Panel2/PanelFileTextDiff/Component.tsx

https://wandb.atlassian.net/browse/WB-14115
Ensures that the python prism language grammar is imported when serving via PagePanel.
Related to https://github.com/wandb/core/pull/15816 which fixes this in app.

fix: load python grammar in notebooks

---

weave-js/src/core/ops/primitives/list.test.ts
weave-js/src/core/ops/primitives/list.ts

https://wandb.atlassian.net/browse/WB-14394
there is a bug in opDropna in weaveJS. the bug is if you call opDropna on a node with this type:
```json
{
"type": "tagged",
"tag": {...},
"value": {
"type": "list",
"objectType": {
"type": "union",
"members": [
"none",
{
"type": "list",
"objectType": {
"type": "tagged",
"tag": {...},
"value": {
"type": "typedDict",
"propertyTypes": {}
}
}
}
]
},
"maxLength": 50
}
}
```
then the output type you get back is the same as the input type, despite the fact that the none should be removed from the union by the weaveJS `opDropna` returnType function. this is incorrect - the none should be stripped from the output type.
`opDropna` is a standardConfigurableOp , which means its `returnType` function is called by the `mntTypeApply` hook. there is an issue …

fix: update dropna optype

---

weave-js/src/panel/WeaveExpression/hooks.ts

Entering a space character into a panel expression editor and then clicking away would throw an uncaught exception.
Problem: `domRange.startContainer` can be a text node that doesn't have a `getBoundingClientRect` method. This was masked by a cast.
Internal Jira: https://wandb.atlassian.net/browse/WB-14369
Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1688159224967539

fix: entering a whitespace-only expression and clicking away would crash

---

weave/derive_op.py
weave/language_features/tagging/tag_store.py
weave/ops_primitives/pandas_.py

https://wandb.atlassian.net/browse/WB-14201
This PR is a workaround for a performance regression in the model registry described in the above JIRA ticket. We understand the source of the regression, but the correct fix will involve implementing a new plugin type. This quick fix improves the performance by parallelizing the refinement and resolution of mapped ops, which is the hot spot. There are other ways to improve this but @tssweeney and I decided this was the best immediate course of action. 
This has the potential to improve the performance of all mapped ops by our parallelism factor if they are IO bound.

feat: add parllelism to derived op resolver

---

weave/ops_domain/table.py

Fix https://wandb.atlassian.net/browse/WB-14409
When reading partitioned tables, we were sampling `1000 / num_partitions` rows from each partition and using those rows to determine the object type for each partition. When `num_partitions` was large, this could lead to sampling only a few rows to get the row type, leading to incorrect type inference. This manifested as an `invalid null error` in the ticket above. We sampled some rows from a partition that happened to be null to determine the type, but the rest of the data was not null. 
The fix here is to sample 1000 / num_partitions rows from each partition, and then take the `union` of the types from each partition to get the final type. Then we use that global type when converting the read data to an AWL. 
Related to #41, which …

fix: update partition table type inference to use all sampled data

---

weave-js/src/components/Panel2/PanelPlot/PanelPlot.tsx
weave-js/src/components/Panel2/PanelPlot/versions/index.ts
weave-js/src/components/Panel2/PanelPlot/versions/v14.ts
weave/panels/panel_plot.py
weave/tests/test_plot.py

https://wandb.atlassian.net/browse/WB-14410
Fixes two issues related to scales in panelplot. 
1. Calling `type_of(panel_plot.Scale(...)).to_dict()` did not produce the correct serialized type because `Scale` has a `type` attribute that collides with weave's `ObjectType` `type` attribute. I renamed this attribute `scaleType` so that it doesn't collide and the type can be correctly deserialized from its serialized version. Added a migration to enforce this and a unit test. 
2. The serialized version of `Scale` constructed from python code includes all keys, with values of `None` if a value is unset or null. This caused an error to be raised in Vega because the corresponding javascript object contained entries like `{scale: {..., range: None}}` instead of just omitting the `range` key. This …

fix: make AxisScale serializable in python, make scale configurable from python code

---

weave-js/package.json

Gets error messages from jest to show up on the correct lines.

fix busted line numbers in tests: remove esbuild jest

---

weave-js/src/components/Panel2/PanelProjectionConverter/util.ts
weave/ops_arrow/dict.py

https://wandb.atlassian.net/browse/WB-14436
```
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
(3 additional frame(s) were not displayed)
...
File "weave/execute.py", line 410, in execute_sync_op
return op_def.resolve_fn(**inputs)
File "weave/op_def.py", line 359, in resolve_fn
return process_opdef_resolve_fn.process_opdef_resolve_fn(
File "weave/language_features/tagging/process_opdef_resolve_fn.py", line 123, in process_opdef_resolve_fn
res = propagate_arrow_tags(op_def, resolve_fn, args, kwargs)
File "weave/language_features/tagging/process_opdef_resolve_fn.py", line 78, in propagate_arrow_tags
res = resolve_fn(*tag_stripped_args, **tag_stripped_kwargs)
File "weave/ops_arrow/dict.py", line 252, in awl_2d_projection
:, ~(np_array_of_embeddings.sum(axis=0) == 0) …
```

fix inference of valid embedding columns in panel projection converter

---

weave/tests/test_numpy.py
weave/tests/test_wb_data_types.py
weave/wandb_util.py

https://wandb.atlassian.net/browse/WB-14433
Fixes an error in the file-table read path that was improperly typing unserialized (i.e., raw pylist) numpy arrays as `None`. This happens whenever the SDK logs a table where a numpy array is not a top level key. Now numpy arrays of this type are typed as `List(Unknown())`. The unknown is filled in later in the path, which fixes the arrow mapping error we see above.

fix: Handle unserialized numpy arrays in table read path 

---

.gitignore

git should ignore .DS_Store files.

chore: git ignore macOS Desktop Services Store files

---

weave-js/src/contextProviders.tsx

This is AMAZING! our old polling logic works out of the box! In W&B main app, until we are fully moved over to Weave1, then our polling logic will cause issues by invalidating the shared Apollo cache. But here we are totally in the clear!

chore: Enable polling on weave pages

---

weave/engine_trace.py
weave/language_features/tagging/tag_store.py
weave/weave_server.py

Adds logging and monitoring of the number of entries of our tag store at the beginning of each weave_server.execute call.

stats: monitor size of tag store at beginning of each request

---

weave-js/package.json
weave-js/src/panel/WeaveExpression/OpDoc.styles.ts
weave-js/src/panel/WeaveExpression/OpDoc.tsx
weave-js/src/panel/WeaveExpression/SuggestionRow.tsx
weave-js/src/panel/WeaveExpression/hooks.ts
weave-js/src/panel/WeaveExpression/index.tsx
weave-js/src/panel/WeaveExpression/styles.ts
weave-js/src/panel/WeaveExpression/suggestions.tsx
weave-js/src/panel/WeaveExpression/types.ts
weave-js/yarn.lock

Internal Jira: WB-14130
Updated suggestion panel to obscure less of the expression editor in use:
* Suggestions are suppressed on first focus
* OpDoc panel is hidden by default, hover over info icon to show or click it to persist.
* Suggestions panel is now positioned at bottom left of editor instead of at cursor. Uses [Floating UI](https://floating-ui.com/) to reposition within viewport.
* Styling updates
Before:
After:

feat: suggestion popup restyled and less invasive

---

weave-js/src/components/PagePanelComponents/Home/HomeCenterEntityBrowser.tsx
weave-js/src/components/Panel2/pyBoardGen.tsx
weave-js/src/core/hl.ts
weave/panels_py/__init__.py
weave/panels_py/panel_autoboard.py
weave/panels_py/panel_seedboard.py

This is a small PoC of how we can quickly add python-defined board generation to the UI. This is not quite the long term design, but will work for upcoming customer demos.

chore: Enable in-app board generation

---

weave/wandb_interface/wandb_lite_run.py

`urllib3` emits a bunch of nasty `WARNING:urllib3.connectionpool:Connection pool is full, discarding connection` warnings when we open up more than 10 connections. This PR changes the logger to not emit warnings. These warnings do not indicate data loss and is more informational than useful.

chore: Hide `urllib3` warnings

---

weave-js/src/common/components/elements/LegacyWBIcon.tsx

LegacyWBIcon required a ref but we dont pass one in most times

Fix innerref warning

---

weave-js/src/components/PagePanelComponents/Home/HomePreviewSidebar.tsx

When viewing preview, was getting this console warning:

chore: prevent 'Functions are not valid as a React child' warning

---

weave/signal_handlers.py
weave/weave_server.py

* Fixes an issue where the trace dumper was writing the traceback for the signal handler and not the main thread from when the signal was called
* Refactors signal handler installation to make it more modular
* Fixes an issue where memory dump handlers and traceback dump handlers were not being properly interleaved

chore: refine signal handlers

---

weave/signal_handlers.py
weave/weave_server.py

* Fixes a bug where the default signal handling dump path was not being set properly
* Does not install debugging signal handlers by default
* Preserves existing signal handling paths if they exist

chore: dont intercept other signal handling paths, fix path setting bug

---

weave/ops_arrow/vectorize.py
weave/ops_primitives/projection_utils.py
weave/server.py

Internal JIRA: https://wandb.atlassian.net/browse/WB-14631
Silences error logs in notebooks/colab by default, like those shown above. Enables forcing them on with a flag.

fix: silence error logs in notebook

---

weave-js/src/components/PagePanelComponents/Home/HomeCenterEntityBrowser.tsx
weave/compile.py

Basically anytime we do `callOpVeryUnsafe` without a type, we run the risk of making un-compilable graphs. Here I fix it for StreamTable.rows when seeding a table.
Fixes https://wandb.atlassian.net/browse/WB-14622

chore (weave): Fix seed board from StreamTable

---

weave-js/src/components/PagePanelComponents/PersistenceManager.tsx
weave-js/src/components/PagePanelComponents/PublishModal.tsx
weave-js/src/components/PagePanelComponents/persistenceStateMachine.ts
weave-js/src/components/PagePanelComponents/util.ts
weave/ops_primitives/weave_api.py
weave/storage.py
weave/tests/test_artifact_metadata.py
weave/tests/test_mutation2.py
weave/tests/test_publish_flow.py

When publishing a new board, allow the user to select entity and project.
Internal Jira: https://wandb.atlassian.net/browse/WB-14207 (partial)

feat: select entity/project on publish new

---

weave/environment.py

Quick fix for self hosted weave, we always expose it under `/weave` in self hosted.

chore(sdk): Append weave to server weave urls

---

weave/execute.py

Reduce the amount of bytes logged, these details don't seem needed in production when we have execution summary.

chore(server): Move op logging to info

---

weave-js/src/components/Panel2/useAssetFromArtifact.ts

https://wandb.atlassian.net/browse/WB-14116
Add the `content-disposition=inline` parameter when fetching direct URL from gorilla. This new QS param will be handled properly once [the change to support it](https://github.com/wandb/core/pull/16215) is deployed.

fix(weave): fix html panels not rendering in weave1

---

weave/environment.py
weave/signal_handlers.py

I'm working on running the core integration tests as Kubernetes Jobs, and I need all the support containers to exit 0 when they receive a SIGTERM -- otherwise, Kubernetes interprets the shutdown as a failure and cancels the rest of the tests. Since SIGTERM isn't mentioned anywhere else in the repo, I'm guessing there's no graceful shutdown behavior to preserve -- if so, then it should be safe to add this handler to immediately exit 0 when SIGTERM is sent.

chore: make weave exit 0 on SIGTERM

---

weave-js/src/components/Panel2/PanelObject.tsx

Internal JIRA ticket: https://wandb.atlassian.net/browse/WB-14782
Fixes an issue in the artifacts files page where users would get a full page crash if they tried to view a directory with PanelObject. The problem was that PanelObject was not equipped to render dict{str, directory}, but that type was assignable to the Panel's input type, typedDict({}). The files page would sometimes supply that type as input to a nested PanelObject. 
I updated the type system to allow typedDicts to be declared as not allowing dicts to be assigned to them.

fix: dont crash artifact files page if users choose panelobject

---

weave-js/src/core/model/graph/editing/hash.ts

Internal JIRA ticket: https://wandb.atlassian.net/browse/WB-14781
Fixes a bug in `hash.ts` where we were getting collisions due to only hashing values instead of entire nodes (values and types). 
The particular collision we were getting here was:
```
{
"nodeType": "const",
"value": [],
"type": {"type": "list", "objectType": "string"}
}
```
was colliding with
```
{
"nodeType": "const",
"value": [],
"type": {"type": "list", "objectType": {"type": "typedDict", "propertyTypes": {}}}
}
``` 
leading the latter type to be used in both instances, causing the wrong type to be propagated in the type system in weave python, manifesting downstream as a dispatch error.
This fixes the issue by hashing the entire node instead of just the value, leading nodes with the same value but different types to be …

fix: Fix panel crash (unable to dispatch projection2d) due to bug in hash.ts

---

requirements.txt

Sentry 1.29.0 has this PR (https://github.com/getsentry/sentry-python/pull/2243) which broke GQL response handling in our Python unit tests. GQL requests would be sent and returned correctly with data, except our SDK receives empty data because of Sentry monkeypatching.

fix(weave): Pin sentry version to exclude release which breaks Python unit tests

---

weave-js/package.json
weave-js/yarn.lock

Fix the warning being output by yarn lint, as it instructs:

chore: fix lint warning message

---

weave-js/package.json
weave-js/yarn.lock

Adds [react-select](https://react-select.com/) as a dependency - this is a flexible select/autocomplete widget that is used in the W&B app, which will allow us to have shared components for things like selecting a project within an entity.

chore: add react-select dependency

---

weave-js/src/components/Button/Button.tsx
weave-js/src/components/Button/index.ts
weave-js/src/components/Button/types.ts
weave-js/src/components/Tooltip.tsx

Step 1 of moving the Button common component from the app into Weave, allowing us to use it in both places.
Commit 1 is the exact files from app master.
Commit 2 is small import changes necessary to make Storybook continue to work after we update it to point here in a subsequent PR.

chore: copy app button into Weave

---

weave/ecosystem/all.py
weave/weave_server.py

Internal Jira: https://wandb.atlassian.net/browse/WB-14865
Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1690921044929769?thread_ts=1690905026.878269&cid=C03BSTEBD7F
Load ecosystem modules one at a time, catching import errors, and reporting out status at end.
Previously, any import error would cause the ecosystem loading to stop, and the error was silent. 
Example output when a dependency, e.g. one newly added, is not in the virtualenv:
Example output when all dependencies are available:

feat: more robust and transparent loading of ecosystem

---

.github/workflows/test.yaml

Decreases CI unit test timeout to 10 minutes. Anything longer indicates an issue with the underlying tests and will fail anyway. This makes failures happen faster.

ci: decrease CI unit test timeout to 10 minutes

---

.github/workflows/test.yaml

Timeout unit tests in CI at 90 seconds. cc @vwrj

ci: add timeouts to unit tests

---

weave/wandb_interface/wandb_stream_table.py

Fixes flake affecting  tests/test_wb_stream_table.py::test_stream_logging_image, where temporary files were being reaped before the file pusher had a chance to upload them.

ci: fix streamtable flake

---

.github/workflows/test.yaml
.pre-commit-config.yaml

Increase mypy timeout so we dont fail linting checks waiting for mypy to finish running after containers take longer than normal to come up. We can put this back down when we replace mypy with pyright.

ci: increase mypy timeout in ci

---

weave/ops_domain/wbmedia.py

https://wandb.atlassian.net/browse/WB-14784
the path variable below would come back as null, we could also just do a null check in the frontend
now instead of returning  mask: { loadedFrom, path: null}, it returns mask: null which doesnt call this SegmentationMaskFromCG
``` 
const SegmentationMaskFromCG: FC<SegmentationMaskFromCGProps> = props => {
const {filePath, classSet, maskControls} = props;
const {loadedFrom, path} = filePath;
const fileNode = useMemo(
() =>
opArtifactVersionFile({
artifactVersion: loadedFrom as any,
path: constString(path),
}) as
| Node<{
type: 'file';
extension: string;
}>
| VoidNode,
[loadedFrom, path]
);
```

chore(weave): Fix null image path

---

weave-js/src/components/Panel2/PanelTable/PanelTable.tsx

Fixes a regression in Prompts (W0) which I introduced with https://github.com/wandb/weave/pull/223. Will need to circle back and fix this for OpenAI dashboard the correct way.

chore(weave): Fix broken indexes in Weave0

---

weave-js/src/components/Panel2/availablePanels.test.ts
weave-js/src/core/model/helpers.ts

Internal JIRA ticket: https://wandb.atlassian.net/browse/WB-14924
Fixes an issue where PanelWBObject was being marked available to handle `union[null, file]`, due to `isFileLike()` returning true for unions of files with none. This narrows the types the converter can handle to non-null assignable types, fixing a downstream panel crash in prompts. Adds a unit test for this case.

fix: fix panel crash in prompts custom column due to incorrect panel for table type

---

weave-js/src/components/PagePanelComponents/Home/HomeCenterBrowser.tsx
weave-js/src/components/PagePanelComponents/Home/HomeCenterEntityBrowser.tsx
weave-js/src/components/PagePanelComponents/Home/HomeCenterLocalBrowser.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-14944
Right now the "Delete board" action is only available when viewing that board. This adds that action to the overflow menu in the browser.

feat: allow deleting boards without opening them first

---

weave-js/src/components/PagePanelComponents/DeleteActionModal.tsx
weave-js/src/components/PagePanelComponents/Home/HomeTopBar.tsx
weave-js/src/components/Panel2/ChildPanel.tsx
weave-js/src/components/Panel2/PanelPanel.tsx
weave-js/src/components/Sidebar/VarBar.tsx
weave-js/src/components/WeavePanelBank/PBSection.tsx
weave-js/src/panel/WeaveExpression/OpDoc.tsx

Update parts of Weave to use the common component Button. This makes e.g. the background highlighting for the pencil button the same as the new panel button next to it.
Before:
After:

chore: update some places to use new common component Button

---

weave-js/src/components/Alert.styles.ts
weave-js/src/components/Alert.tsx
weave-js/src/components/WeavePanelBank/PanelBankEmptySectionWatermark.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-14551
Copies the Alert component originally built for Launch into Weave, uses it as a short-term fix for the empty board state styling. (Commented out code indicates we eventually want to do something more sophisticated here.)
@Cecile0112358 there are now a few different alert/banner components around, it might be good to unify as part of the overall common components effort.
Before:
After:

chore: improve empty board styling

---

weave-js/src/components/Panel2/PanelTable/tableState.ts

Generating tables with > 1000 columns from the client can force exhaustion on the ability of weave to generate new column IDs. This is a temporary patch that allows columns of known size to declare the numeric ID range in advance, saving both compute time in Weave and avoiding errors where the `newColumnId` fn cannot generate a unique ID.
Note: this is a patch to fix an immediate customer issue and should be followed by a better/more stable method for ID generation.

fix(weave): Avoiding expensive/brittle ID generation

---

weave/environment.py
weave/ops_domain/wbgqlquery_op.py
weave/wandb_client_api.py

Internal JIRA ticket: https://wandb.atlassian.net/browse/WB-14961
Occasionally, the odd GQL request will hit a 30s read timeout and lead to a random page crash. This adds configurable timeout retry logic like we have for auth. In production, we should set this to 1 to mimic our auth retry logic. That way we wont overwhelm gorilla but will drastically reduce our chances of having a read timeout crash a page.

fix: Add configurable retry of wandb GQL timeouts

---

weave/compile.py
weave/compile_domain.py
weave/graph.py
weave/stitch.py
weave/tests/test_compile.py
weave/tests/test_wb_stream_table.py

This is a pretty tricky PR. It is useful to define a "static lambda". A "static lambda" is a const node of type function with no inputs. This is used in our system to represent a constant value which is a node. Useful for generating boards or any sort of op that operates on nodes themselves.
Moreover, it is also useful to remind ourselves that our compile pass will automatically "quote" inputs to ops that expect node inputs - effectively making static lambdas when called for. 
Furthermore, it is important to know that stream table rows (and many other ops) now support expansion (meaning they get expanded into a chain of new nodes in the compile pass).
Conceptually, this created an issue: Compile passes that mutate nodes (eg node expansion or gql compile) would modify the quoted node. But, …

chore(weave): Fix stitch for StreamTable

---

weave-js/src/components/Panel2/PanelComp.tsx
weave-js/src/components/Panel2/PanelContext.tsx
weave-js/src/components/Panel2/PanelMaybe.tsx
weave-js/src/react.tsx

Fixes cases where nested null responses trigger PanelMaybe's null detection incorrectly.
Say you have Maybe.Table
Prior to this PR, if any descendent query in the tree returned a None response, we would trigger the Maybe error boundary and render None for the whole table.
This makes it so we only throw NullResult if the NullResult happens on the exact Node PanelMaybe is monitoring...
- This is still not quite right, since Weave propagates nulls, now we may be too conservative

fix: Fixed over-aggressive PanelMaybe

---

weave/conftest.py

#336 introduced a bug that affects local testing, it tries to call int() on None. This fixes it

fix: fix typeerror when invoking pytest locally

---

weave-js/src/components/PagePanelComponents/PersistenceManager.tsx
weave-js/src/components/PagePanelComponents/PublishModal.tsx
weave-js/src/components/PagePanelComponents/util.ts

When loading a board, there are a handful of data requests that are not used in many cases. This removes these queries which has 2 benefits:
1. There is less data requested
2. The cache key for gql requests can be shared across more requests which are not co-mingled with these extra data requests
Basically all this does is delay loading information needed for modals until they popup
This reduces the empty board load time from 500-700ms to 30-70ms!

chore(weave): Remove unneeded data fetching in board hot path

---

weave/registry_mem.py
weave/weave_server.py

This one is a small perf improvement, but we hit `/ops` on initial page load which can take 80-100ms to execute and blocks all other executions.
With this change, we cache the serialized op results, resulting in 50-70ms load. 
Small, but every full page load is blocked by this.

chore(weave): Cache Ops endpoint

---

weave/ops_domain/artifact_version_ops.py

Internal JIRA: https://wandb.atlassian.net/browse/WB-15084
Handles `historyStep == null` in `_get_history_metrics()`, fixing a page crash in the model registry.

fix: fix model registry page crash when historyStep == null

---

weave/artifact_wandb.py
weave/memo.py

2 things:
1. we can use our per-execution `@memo` to memoize the uri resolution of artifacts. This means that for each graph, we will only attempt to resolve a URI once, rather than for each time the artifact is constructed (typically once per opGet and opGetRefine)
2. this didn't work right away because the memoization is reset each time we enter another execution hander. I don't see a reason why these can't be shared, so this PR also only sets up a fresh memo cache if one does not already exist.
Practically, shaves off another 100ms from the OpenAI board.

chore(weave): Share memo context across nested execution and memoize artifact URI calls

---

weave-js/src/react.tsx

Internal JIRA: https://wandb.atlassian.net/browse/WB-15092
Fixes an issue where `PanelMaybe` did not work properly for graphs with vars, causing page crashes.

fix: compare node/panelMaybeNode with dereferenced vars in useNodeValue

---

weave/frontend/build.sh

Currently, the sha1sum is computed over the file list that includes the path:
```
139b8d024c433f23555bef3b65229f41b69ab637  /Users/jzhao/code/weave/weave/frontend/../../weave-js/tailwind.config.cjs
```
This is unstable since the file path differs depending on where it is called while the content hash is stable. The fix just takes the first column to hash which only include the content hashes.

chore(dev): remove file path from sha1 calculation

---

weave-js/src/components/PagePanelComponents/Home/Home.tsx
weave-js/src/components/PagePanelComponents/Home/HomeLeftNav.tsx
weave-js/src/components/PagePanelComponents/Home/HomePreviewSidebar.tsx
weave-js/src/components/PagePanelComponents/Home/HomeTopBar.tsx
weave-js/src/components/PagePanelComponents/Home/LayoutElements.tsx

updates the headers in left nav and sidebar
moves the new board button
adds expand and copy action to sidebar
new
old

chore(weave): Update homepage headers and move new board button

---

weave/ops_arrow/list_ops.py

Implements unnest in arrow following https://github.com/apache/arrow/issues/27923#issuecomment-1378008415. 
Allows us to avoid breaking out to pandas in unnest.

perf: implement unnest in arrow

---

weave/ops_arrow/list_ops.py
weave/tests/test_arrow.py

Fixes an issue where multiple list columns were unnested individually in `awl.unnest()`. As an illustration of this bug, calling unnest on 
```
[
{"a": [1, 2, 3], "b": "c", "c": ["a", "b", "c"]},
{"a": [4, 5, 6], "b": "d", "c": ["d", "e", "f"]},
]
```
would yield
```
[
{'a': 1, 'b': 'c', 'c': 'a'},
{'a': 1, 'b': 'c', 'c': 'b'},
{'a': 1, 'b': 'c', 'c': 'c'},
{'a': 2, 'b': 'c', 'c': 'a'},
{'a': 2, 'b': 'c', 'c': 'b'},
{'a': 2, 'b': 'c', 'c': 'c'},
{'a': 3, 'b': 'c', 'c': 'a'},
{'a': 3, 'b': 'c', 'c': 'b'},
{'a': 3, 'b': 'c', 'c': 'c'},
{'a': 4, 'b': 'd', 'c': 'd'},
{'a': 4, 'b': 'd', 'c': 'e'},
{'a': 4, 'b': 'd', 'c': 'f'},
{'a': 5, 'b': 'd', 'c': 'd'},
{'a': 5, 'b': 'd', 'c': 'e'},
{'a': 5, 'b': 'd', 'c': 'f'},
{'a': 6, 'b': 'd', 'c': 'd'},
{'a': 6, 'b': 'd', 'c': 'e'},
{'a': 6, 'b': 'd', …
```

fix: fix handling of multiple list columns in awl.unnest()

---

weave-js/src/components/PagePanel.tsx
weave-js/src/components/Panel2/PanelPanel.tsx

This has bothered me for a while. When you make any edit to a published board (basically any interaction)... there is a slight delay, then a full page reload. It is super jarring. This fixes that 👍 .
This also fixes back buttons as well when making such edits.
To be honest, i am not proud of this solution... the way saved panel updates hare handled between PagePanel & PanelPanel & ChildPanel is a spaghetti of indirection and this PR just patches on top of that. We really should audit this entire code path and refactor it to be more understandable and maintainable. 
**Before:**
**After:**

chore(weave): Stop published board editing from harsh reloading

---

examples/monitoring/dev/openai_monitoring_board_demo.ipynb
weave-js/src/components/Panel2/PanelDropdown.tsx
weave-js/src/components/Panel2/PanelFilterEditor.tsx
weave/panels/panel_filter_editor.py

FilterEditor component now has a visual mode, we use it in the openai monitoring board.
Features:
- Let's you visually construct an AND of filters for string, number and boolean keys in the input list.
- Switch between visual editing and expression editing (for more complex queries)
- Suggestions for keys and string values
- Supports string in filters.
Underlying state is stored as a Weave node.
Will need a design pass, but not blocking, let me get the rest of the board cleanup/features in first.

feat: Visual filter editor

---

weave/compile.py
weave/ops_arrow/dict.py
weave/ops_domain/run_ops.py
weave/ops_domain/wandb_domain_gql.py
weave/tests/test_arrow.py
weave/tests/test_wb_end_to_end.py

This pattern is used in the OpenAI dash and causes us to bail out of weave. Building off of https://github.com/wandb/weave/pull/381 we add an optimization to compile this op chain to an efficient representation
When loading an OAI dash of 50k rows, this one step typically costs 5 seconds. With this change it is down to 126 nanoseconds!!

chore(weave): AWL.keys.flatten.unique optimization

---

weave-js/src/components/Panel2/ChildPanel.tsx
weave-js/src/components/Panel2/PanelFilterEditor.tsx
weave-js/src/components/Panel2/PanelGroup.tsx
weave/panels/panel_board.py
weave/panels_py/panel_openai_monitor.py

- Render variable name as a bold title when editable=False for varbar
- Remove edit and ... menu controls from varbar when editable=False
- Remove new panel button from varbar when editable=False
- Fix overflow for vertical/horizontal group layout child panels, so controls can correct expand out of parent (like Dropdown)

feat: Clean varbar

---

weave-js/src/common/css/color.styles.ts
weave-js/src/components/Panel2/ChildPanel.tsx
weave-js/src/components/Panel2/KeyValTable.tsx
weave-js/src/components/Panel2/PanelPlot/PanelPlot.tsx
weave-js/src/components/Sidebar/Inspector.tsx
weave-js/src/components/WeavePanelBank/PBSection.tsx
weave-js/src/core/hl.ts
weave/panels_py/panel_autoboard.py
weave/panels_py/panel_openai_monitor.py

Now we only show the variable name converted to a title format on panels by default. When you mouse over, you get the whole editor bar as it was.
Also shrunk the height of the metric panels in the openai board from 5 to 3, which looks nicer.
Other changes:
- 13px font size for KeyValTable so PanelObject matches PanelTable
- Modified simpleOpString to produce a much simpler string when we are using binning operations, improving PanelPlot legend
- Removed the edit button next to "New Panel", it was always present onscreen, and opens to the outline editor which seems confusing.
- Made sure there are no underscores in variables names in the openai board
- Background color for main section of board is now a very light gray
- Use W&B run color scheme for PanelPlot colors
- Don't show …

feat: Cleaner board UX

---

weave-js/src/components/PagePanelComponents/Home/HomeCenterEntityBrowser.tsx

passing in the destructured props, vs props stops it

chore(weave): Stop browser actions from rerendering everytime

---

examples/monitoring/dev/openai_monitoring_board_demo.ipynb
perf_notebooks/case_when v if_then_else.ipynb
weave-js/src/core/ops/domain/local.ts
weave/compile.py
weave/decorator_op.py
weave/ops_arrow/boolean.py
weave/ops_arrow/dict.py
weave/ops_arrow/list_.py
weave/ops_arrow/vectorize.py
weave/ops_primitives/boolean.py
weave/panels_py/panel_openai_monitor.py
weave/tests/test_cond.py
weave/tests/test_with_columns.py
weave/weavejs_fixes.py

This gives us the ability to derive the correct OpenAI API cost. Everything is vectorized.
To do this, I added two new ops, which are both major pieces of new functionality.
One is "cond". Here's an example of it's usage:
```
def cost(row: dispatch.RuntimeOutputNode) -> dispatch.RuntimeOutputNode:
return weave.ops.cond(
weave.ops.dict_(
a=row["output.model"] == "gpt-3.5-turbo-0613",
b=row["output.model"] == "gpt-4-0613",
),
weave.ops.make_list(
a=row["summary.prompt_tokens"] * 0.0015e-3
+ row["summary.completion_tokens"] * 0.002e-3,
b=row["summary.prompt_tokens"] * 0.03e-3
+ row["summary.completion_tokens"] * 0.06e-3,
),
)
```
This formulation matches arrow's case_when. I don't love this because you have to write the cases in the first argument, and the resulting values in the second …

feat: cond op, with_columns op, openai cost calculation

---

weave-js/src/components/Panel2/ConfigPanel/index.tsx
weave-js/src/components/Panel2/PanelFilterEditor.tsx

- better sort order for filter keys
- all ConfigFieldModifiedDropdown use cursor pointer on whole element
- default to IN for string filter
- don't allow empty IN filters

feat: Small UX improvements

---

weave/panels/panel_table.py
weave/panels/table_state.py
weave/panels_py/panel_openai_monitor.py

- Add the ability to specify sorting when add a table column
LLM board
- Sorts the table by timestamp (most recent first)
- Changes a couple column names to make it more clear that we've captured all of the data but are only showing the last input and output messages.

feat: LLM board: Sort the table by timestamp (most recent first)

---

weave/panels/panel_table.py

Fixes the issue illustrated below, where pinning a row on a sorted table caused the wrong row to be shown in a connected active_row panel:

fix: fix active_row returning the wrong row on sorted table

---

weave/wandb_interface/wandb_stream_table.py

Printed link should have browse after changing URL structure in https://github.com/wandb/weave/pull/353

chore: include browse in printed URL

---

weave-js/src/assets/icons/icon-overflow-vertical.svg

the fill of each individual dot in `icon-overflow-vertical` was hard-coded instead of using `currentColor`

fix(ui): Fix overflow-vertical icon fill

---

weave-js/src/components/Panel2/PanelFilterEditor.tsx

Follow up to comment here
https://github.com/wandb/weave/pull/425#discussion_r1302306233
Just tightens up a type from Array<string | boolean |number> -> string[]

chore(weave): Fix panel filter type

---

weave-js/src/components/Panel2/ChildPanel.tsx
weave-js/src/components/WeavePanelBank/PBSection.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-15202
I recommend turning on "Hide whitespace" in the diff view.
A recent change toggles between a title-only view and an editor bar when you mouse enter/leave a panel. It was taking the editor bar out of the component tree entirely when not over the panel, which causes the expression editor to lose any unsubmitted state. This PR changes it to just `display: none` the contents instead.

fix: hide panel editor bar rather than omitting it on mouseleave

---

.github/workflows/upload-assets.yaml

the default token cannot bypass branch protections so I need to use this specific user.

chore(dev): use wandbmachine github user to push to master

---

weave-js/src/components/IconButton.tsx
weave-js/src/components/Sidebar/Outline.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-15246
Add an icon explaining that root/sidebar/main are not editable. Update button styling to match design.

chore: update IconButton styling, add locked panel indicator

---

weave/panels/panel_table.py

pinnedColumns did not exist on the config, so pinned columns did not work
https://wandb.atlassian.net/browse/WB-15228
https://wandb.atlassian.net/browse/WB-15043
before
https://github.com/wandb/weave/assets/25037002/1c8d50d4-9ef2-4a8e-82e3-796ab1c55db1
after
https://github.com/wandb/weave/assets/25037002/7d24ca42-a3c6-4694-900d-2dce2af599c0

fix(weave): Enable pinning columns

---

weave-js/src/components/PagePanelComponents/DeleteActionModal.tsx

Button size large to align with design spec.
Before:
After:

chore: use destructive variant for board deletion button

---

.github/workflows/test.yaml
.pre-commit-config.yaml
requirements.dev.txt

Updates our pre-commit hooks to run before pushing to github instead of on commit, following a discussion from office hours on Wednesday.

chore: replace pre-commit hooks with pre-push hooks

---

weave-js/src/components/ErrorBoundary.tsx
weave-js/src/components/ErrorPanel.tsx
weave-js/src/components/Panel2/PanelComp.tsx
weave-js/src/components/Panel2/WeaveMessage.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-14135
The current error indicator doesn't adapt to its available space, which can lead to the message appearing cropped or other visual problems. This PR adds an ErrorPanel that determines whether it has space to display a full size message, and if not, instead shows just an icon with a tooltip.
Before:
After:

chore: update error boundary and display

---

weave/ops_domain/wb_schema.gql

Fixes internal sentry issue https://weights-biases.sentry.io/issues/4431714471/?referrer=slack&alert_rule_id=12726589&alert_type=issue

fix: add ttlDurationSeconds to schema

---

weave/mappers_gql.py

Fixes internal sentry issue https://weights-biases.sentry.io/issues/4431472757
Handles deserialization of TimeDeltas in mappers_gql. Allows representation of `computeSeconds`.

fix: handle duration in mappers_gql

---

weave/compile.py
weave/execute_fast.py
weave/graph.py
weave/ops_arrow/vectorize.py
weave/ops_domain/run_history/history_op_common.py
weave/ops_primitives/type.py
weave/serialize.py
weave/tests/test_arrow.py
weave/tests/test_compile.py
weave/weave_server.py

This also improves node_id performance by a lot, which is used in deserialize, by not calculating hashes of types on all nodes which can be quite large. So deserialize performance improves a lot here too.
The node_ops compile pass expands nodes, potentially producing a bunch more ops, that can be duplicates of others that we already have in the graph. This was causing a lot of extra execution on the LLM monitoring board. On the dev board using 100 as the argument to random_predictions, this takes the execution time of the largest query from 2.3s to 1.3s.

perf: Dedupe rendundant ops after expansion.

---

weave-js/src/components/Panel2/PanelFileText/Component.tsx

Internal Slack thread: https://weightsandbiases.slack.com/archives/C04MNBGJDBN/p1693319020965789?thread_ts=1693265406.551939&cid=C04MNBGJDBN

fix: variables to determine which warning to show are swapped in artifact file viewer

---

weave-js/src/components/Panel2/PanelFileText/Component.tsx

Fixes file extension extraction, which in turn makes syntax highlighting and JSON re-indentation etc. work.
Before:
After:

fix: unwrap tagged type to get artifact file extension

---

weave-js/src/common/css/SemanticOverride.less
weave-js/src/components/ErrorPanel.tsx

* Corners more rounded in modals
* Use circular instead of triangular warning icon
* Tighten error panel subtitle line height

chore: styling tweaks from design

---

weave-js/src/components/PagePanel.tsx
weave-js/src/components/Panel2/ChildPanel.tsx
weave-js/src/components/Panel2/PanelGroup.tsx
weave-js/src/components/WeavePanelBank/PBSection.tsx
weave-js/src/components/WeavePanelBank/PanelBank.less

- Fix default blank board to have actual working VarBar again! We always render expressions below the title row in VarBar now
- Clean up how panel configuration is used in PanelGroup and ChildPanel (see new comments in PanelGroup)
- Remove "=" in ControlBar (var = Panel expr)
- Factor Add panel buttons out of PanelBank and into PanelGroup, so if you add a Flow/Grid section to within another panel, we do something reasonable.

chore: UI updates

---

weave-js/src/common/util/hooks.ts
weave-js/src/components/PagePanelComponents/Home/HomePreviewSidebar.tsx
weave-js/src/components/PagePanelComponents/util.ts
weave-js/src/components/Panel2/PanelPanel.tsx
weave-js/src/components/Panel2/PanelPlot/PanelPlot.tsx
weave-js/src/panel/WeaveExpression/hooks.ts

When using the weave app, there are numerous interactions that result in mem leak errors from react. This is caused by attempting to update a component state after it is unmounted. This PR address a number of issues I found while using the app (making dashboards, templates, navigating back and forth, etc...):
1. Fixes `HomePreviewSidebar` to put the state update before the page change
2. Fixes `useIsAuthenticated` to respect mount state
3. Fixes `PanelPanel` refinement dispatch to respect mount state
4. Fixes `PanelPlot`'s `handleTooltip` to respect mount state.
5. Fixes `WeaveExpression/hooks.ts::useWeaveExpressionState` to respect mount state

chore(weave): Cleanup various memory leaks

---

weave/gql_to_weave.py
weave/mappers_arrow.py
weave/mappers_gql.py
weave/ops_domain/run_ops.py
weave/tests/test_arrow_vectorizer.py

Fixes these internal sentry issues 
https://weights-biases.sentry.io/issues/4435792101
https://weights-biases.sentry.io/issues/4435792046
The GQL type of run-computeSeconds is Duration, which maps to a python type of `datetime.TimeDelta()`. Our gql_prop_op `run-runtime` had this typed as `types.Number()`, which was correct before #478 but not anymore. Here we explicitly rewrite the op to convert the duration to integer seconds, add arrow mappers to convert the timedelta to the correct arrow type, and add a vectorized special op to do the conversion to number using arrow compute functions. 
Adds a unit test.

fix: Return correct type for run-runtime (number instead of timedelta)

---

weave/stitch.py
weave/tests/test_join.py

we weren't stitching through join2. Tricky because join2 returns an array of dictionaries where each dictionary has a key for each of two input tables. So we use a LiteralDictObjectRecorder that contains the input tables... Seems to work but needs tests.

fix: join_2 stitching

---

weave/conftest.py

Fixes an issue where calls to logging.error in tests would raise an error due to the logger not being configured, obscuring the actual exception that was raised

chore: configure logs in test

---

weave/ops_arrow/dict.py
weave/ops_arrow/vectorize.py
weave/ops_primitives/_dict_utils.py
weave/tests/test_arrow_vectorizer.py

This PR introduces the capability to perform vectorized scalar,vector and vector,scalar merges in weave. Before only vector,vector merges were supported. The scalar,vector case is often hit in the PanelPlot path. 
1. Added `_ensure_awl_for_merge` in `weave/ops_arrow/dict.py` to convert scalar dicts to ArrowWeaveLists before merging.
2. Introduced `preprocess_merge` op to ensure that inputs for merge are ArrowWeaveLists.
3. Added `_vectorize_merge_special_case` in `weave/ops_arrow/vectorize.py` to use the `preprocess_merge`.
4. Updated type handling logic in `weave/ops_primitives/_dict_utils.py`.
5. Added relevant tests for new merge behaviors in `weave/tests/test_arrow_vectorizer.py`.
New unit tests have been added to validate the functionality. 
This PR should improve the robustness of …

feat: vectorize merge in panelplot path

---

weave/ops_domain/trace_tree.py

Fixes this internal sentry issue https://weights-biases.sentry.io/issues/4443133957/?environment=prod&project=6620563&query=!error.type:WeaveReponsesDifferException+!error.type:WeaveTypescriptServiceError+!error.type:WeavePerformanceRegressionException+release:latest+stack.stack_level:0&referrer=issue-stream&sort=freq&statsPeriod=7d&stream_index=8.
We were catching the wrong error type in our new trace tree `_setattr_with_typeguard()`. This catches the correct one.

fix: properly catch typeguard error in trace tree

---

weave/serialize.py
weave/tests/test_compile.py

Related to #247. Fixes internal JIRA ticket https://wandb.atlassian.net/browse/WB-15389.
This is the python analog of the above bug #247. We were hashing parsed constnodes by value instead of by type and value, leading to collisions between nodes of different types that could affect dispatch. This PR fixes deserialize to hash constnodes by type and by value instead of just by value.

fix: hash constnode type to avoid collisions in deserialize in python

---

weave/tests/test_js_compat.py
weave/weavejs_fixes.py

This PR fixes an issue where nested `PartialObject` types sent from python to JS in response to queries like `refine_summary_type` were not properly converted to the forms that JS expected, instead retaining their internal python representation. The reason for this was that the py -> js conversion was only going 1 level deep, so nested PartialObjects were being missed. Here we fix it by updating the function to recurse correctly. This fixes an issue where run colors were not working in panel plot. 
Before:
After:

fix: properly strip partialobject type from response payload before sending to JS

---

.github/workflows/release.yaml

This checks that only the `sha1.txt` value is unchanged, if we check the entire git tree, the `index.html` file is currently not stable so it will change even if there is no material change in the code. This check makes it more stable.

chore(dev): fix publish script sha check

---

weave-js/src/components/Panel2/ChildPanel.tsx
weave-js/src/components/Panel2/PanelGroup.tsx

updates the titlebar check to include that if the panel is an expression(eg in the varbar) allow the name to be edited
https://github.com/wandb/weave/assets/25037002/70a14858-3d23-4514-8a15-602f5c3cb939

chore(weave): Allows editing of varbar names

---

weave/engine_trace.py
weave/environment.py

This reverts commit 8b663dc8b721590f276e9d09a7f03d32090639d6.
I moved the logic to middleware -- it's not needed in the open source package.

revert: "feat: support weave streamtable trace sampling, allow specification of API key in sendproc (#535)"

---

weave/dispatch.py
weave/errors.py
weave/util.py

JIRA: https://wandb.atlassian.net/browse/WB-14243
We set the fingerprint on the error if possible in `raise_exception_with_sentry_if_available`. The error will get bubbled up to `capture_exception_with_sentry_if_available` which will use the fingerprint from the error if it exists. 
You can see the stack trace and custom fingerprint being set below when I test it locally by calling `[].throwError()`.

analytics(weave): Make Sentry respect fingerprint & stack trace

---

.github/workflows/test.yaml
weave/dispatch.py
weave/util.py

Since #472, linting checks have not been running in CI. This PR fixes that, and runs them locally to ensure that they pass on this commit.

chore: make sure linting runs in CI and run it locally 

---

weave-js/src/components/PagePanelComponents/Home/Home.tsx

Wrap main browser panel in ErrorBoundary so you can attempt to navigate after an error.
Before:
After:

chore: add an error boundary

---

weave-js/src/components/PagePanel.tsx
weave-js/src/components/Panel2/ChildPanel.tsx
weave-js/src/components/Panel2/PanelInteractContext.tsx
weave-js/src/components/Panel2/PanelPanel.tsx
weave-js/src/components/Sidebar/PanelInteractDrawer.tsx

https://wandb.atlassian.net/browse/WB-15451
No user-facing changes, just renames a bunch of things and updates `editorIsOpen: boolean` to `panelInteractMode: enum` in `PanelInteractContext`
Regression spot checks for "edit panel" experience:
https://github.com/wandb/weave/assets/17016170/fd6a4638-01be-4daf-8463-6949d23e08ed

refactor(wir): Allow more modes in PanelInteractContext

---

weave-js/src/components/PagePanel.tsx

https://wandb.atlassian.net/browse/WB-15502
URL is not present as a property in the analytics whitelist. Even if it was, it would be anonymized to hide PII (`entity` and `project` are examples of PII properties in the whitelist). 
PageName does exist and it's not anonymized. So we use it as a tag on page view events from enterprise customers. It currently holds one of two values: `WeaveBrowser` or `WeaveBoardOrTable` (or the empty string for all other URLs).

analytics(weave): Tagging pageview analytics with pageName

---

weave/ops_domain/artifact_version_ops.py

Implements artifactVersion-historyStep in weave1. Fixes internal sentry issue https://weights-biases.sentry.io/issues/4473302674/?referrer=slack&notification_uuid=616b934f-fb93-424c-90fd-5ed4b60a1946&alert_rule_id=12726589&alert_type=issue

feat: implement artifactVersion-historyStep

---

weave/op_policy.py

Implements a comment from @tssweeney, tracks table-rows in `bytes_read_to_arrow`.

chore: track table rows in bytes read to arrow

---

weave/execute.py

Fixes internal sentry issue https://weights-biases.sentry.io/issues/4473321899/?referrer=slack&notification_uuid=c9637b87-cf47-454e-ba30-d6f76e134df6&alert_rule_id=12726589&alert_type=issue

fix: Move setting bytes_read_to_arrow out of finally block

---

weave-js/src/components/Panel2/KeyValTable.tsx
weave-js/src/components/Panel2/PanelObject.tsx

Fixes this development mode warning by using divs styled to match existing table instead of an actual table element.

chore: fix dev mode validateDOMNesting warning

---

weave-js/src/components/PagePanelComponents/Home/HomeCenterEntityBrowser.tsx

The goal here is to make the expression structure for logged tables more closely match the expression structure for stream tables, which in turn will let us simplify the UI logic for fetching the artifacts (boards) depending on the table.

chore: change logged table expression to use get op

---

weave-js/src/components/PagePanelComponents/Home/HomeCenterEntityBrowser.tsx
weave-js/src/components/PagePanelComponents/Home/query.tsx

Add a new column for number of rows for stream tables:
Note: this does not work for logged tables so I display a `-` to indicate the information does not exist

feat(weave): add number of rows for ST in home page table

---

weave/ops_domain/run_ops.py

Fixing typo in https://github.com/wandb/weave/pull/564

fix(artifacts): Typo in run history limit - change 5 to 100

---

weave/util.py

Fixes suppression of sentry issues by commenting out calls to init_sentry(), which overwrites sentry configuration from other sources

chore: disable init_sentry()

---

weave/artifact_wandb.py
weave/mappers_publisher.py

Part of internal Jira: https://wandb.atlassian.net/browse/WB-14546
When publishing boards we traverse them looking for tables being used and add a reference entry to the underlying artifact. This will power the UI feature for showing boards that are using a table.

chore: when publishing boards, add cross-references to other artifacts

---

weave/ops_domain/artifact_version_ops.py

Related to #563. Handles the user case and fixes one of our top sentry issues, https://weights-biases.sentry.io/issues/4488342603.

fix: handle null initiator in artifact version created by user

---

weave/panels/panel_plot.py

Adds defaults for some panel plot object types. Fixes this internal jira/sentry issue. https://wandb.atlassian.net/browse/WB-15608 https://weights-biases.sentry.io/issues/4308896418/

fix: add defaults for panel plot objects

---

weave/ops_domain/wb_util.py

Internal Jira: https://wandb.atlassian.net/browse/WB-15607
Fixes an issue where we were not properly handling float values (e.g., 64.0) in our histogram deserialization path.  Solution: coerce to ints.

fix: coerce bin count to int in histogram

---

weave/ops_arrow/util.py
weave/tests/test_arrow_vectorizer.py

Fixes an issue where we were not unboxing nones properly in util.equal, util.not_equal, and adds a test. 
Internal JIRA: https://wandb.atlassian.net/browse/WB-15609
Internal Sentry: https://weights-biases.sentry.io/issues/4490051920

fix: Unbox nones in pyarrow util.equal, util.not_equal

---

weave-js/src/components/Panel2/ChildPanelExportReport/ReportOption.tsx
weave-js/src/components/Panel2/ChildPanelExportReport/ReportSelection.tsx

before:
1. report select is disabled if there's only 1 report in the selected entity
2. "New report" option text slightly misaligned
3. awkward state for unpublished boards (because entity name is not in url)
after:

fix(wir): Fix minor report select issues

---

weave-js/src/components/Panel2/ChildPanelExportReport/ChildPanelExportReport.tsx
weave-js/src/components/Panel2/ChildPanelExportReport/computeReportSlateNode.ts

https://wandb.atlassian.net/browse/WB-15492
testing: copy the computed slate node config and manually add it into a report. with [this change](https://github.com/wandb/core/pull/17121) merged, the panel at least gets rendered, even if not yet editable
https://github.com/wandb/weave/assets/17016170/3d451414-bc81-49e2-9ab5-19cc853757fe

feat(wir): Compute slate node for report export

---

weave/artifact_wandb.py
weave/wandb_client_api.py

Uses GQL retry logic in wbroot_gqlquery op in our artifact path. Should reduce incidence of artifact queries timing out due to GQL. 
Internal Sentry: https://weights-biases.sentry.io/issues/3913896763
Internal JIRA: https://wandb.atlassian.net/browse/WB-15640

fix: Use gql retry in artifact path

---

weave/artifact_wandb.py

Handles artifacts that were never uploaded the same way that deleted artifacts are handled, addressing internal sentry issue https://weights-biases.sentry.io/issues/3933057442/?referrer=slack.

fix: handle artifacts that were never uploaded

---

weave-js/src/components/Panel2/ChildPanel.tsx
weave-js/src/components/Panel2/ChildPanelExportReport/computeReportSlateNode.ts
weave-js/src/components/Panel2/PanelPanel.tsx

https://wandb.atlassian.net/browse/WB-15547
before - if there multiple weave panels are added to the same report, their state is synced
https://github.com/wandb/weave/assets/17016170/62120e75-c610-404c-8f7a-82c588124438
after - each panel displays own state & can be edited individually
https://github.com/wandb/weave/assets/17016170/6433b190-4246-49eb-a803-ede1ee7820d5
(tested with [this branch](https://github.com/wandb/core/compare/master...connie/report-child-panel-edit?expand=1&w=1) in core - not quite ready for review yet but will be soon)

fix(wir): Allow multiple panels on one report

---

weave-js/src/components/Panel2/ChildPanel.tsx
weave-js/src/components/Panel2/PanelInteractContext.tsx

Internal Jira: 
https://wandb.atlassian.net/browse/WB-15644
https://wandb.atlassian.net/browse/WB-14310
Selects panel on click, keeping the expression editor and other buttons shown while panel is selected. Can click on background or elsewhere to clear selection.
This is a usability fix, as it was too easy for minor mouse movements to hide the expression editor while people were using it.

feat: improve panel selection

---

weave-js/src/components/Panel2/ChildPanel.tsx
weave-js/src/components/Panel2/ChildPanelExportReport/computeReportSlateNode.ts
weave-js/src/components/Panel2/PanelPlot/PanelPlot.tsx
weave-js/src/components/Panel2/toWeaveType.tsx
weave-js/src/core/model/graph/typeHelpers.ts
weave-js/src/core/model/types.ts
weave-js/src/core/weave.ts

Figuring out this issue was quite an adventure, and I'm not 100% confident I landed on the correct solution. Made a couple of looms to walk through what I did - let me know what you think! (PS sorry about the poor video quality)
Initial issue with input type:
https://www.loom.com/share/63150218dd71484e9eeec431c9c4efbe
Follow-up issue with update handler:
https://www.loom.com/share/c6b228f522f34471b0ba28ccc9ae0da7
--> after discussing with Tim, we've decided on a different approach. Instead of updating the "exp to string" logic, we're modifying the "is expression unchanged" check with additional logic that handles `_is_object` const nodes

fix(wir): Allow updates on panels exported to reports

---

weave/weave_server.py

Makes trying to access a local file with no user set return 403 instead of 500.

chore(weave): 403 on send_local_file with no user, not 500

---

weave/weave_server.py

A `~/_netrc` file existing can cause auth problems in the same way a `~/.netrc` file existing can, since the requests library will check both locations.
https://github.com/psf/requests/blob/main/src/requests/utils.py#L61
This PR adds a little extra logging to help developers better notice this potential issue.

chore: better logging for _netrc

---

weave/ops_arrow/dict.py

Merge was borking with null incoming arg. The rest of the op (and typing) supports nones, but not the first loop. This fixes it and properly declares the incoming type.

chore(weave): Fixes nullability on first arg on merge

---

weave/graph.py
weave/graph_debug.py
weave/ops_arrow/vectorize.py

This PR makes some changes to graph expression strings in Weave:
* It imports the partial_object module in graph.py and graph_debug.py. This is used for handling partial object types in graph node expressions.
* It adds better handling for gqlroot-querytoobj nodes in node_expr_str() and node_expr_str_full(). These expressions now show the narrow object type for the query if it is available, otherwise they show "?".
* In the vectorize module, it saves the node expression to a variable before logging it. This avoids calling node_expr_str_full() multiple times.
The main changes are adding support for printing gqlroot-querytoobj nodes with more detail about the narrow object type for the GraphQL query. The other changes improve logging and avoid duplicate work generating the node expression …

chore: Clean up debug strings (node_expr_str) in weave python 

---

weave-js/src/components/PagePanelComponents/Home/Home.tsx
weave-js/src/components/PagePanelComponents/Home/HomeCenterTemplates.tsx
weave-js/src/components/PagePanelComponents/Home/HomeFeaturedTemplates.tsx
weave-js/src/components/PagePanelComponents/Home/HomeLeftNav.tsx
weave-js/src/entrypoint.tsx
weave-js/src/urls.ts
weave-js/src/util/localStorage.test.ts
weave-js/src/util/localStorage.ts
weave-js/src/util/useLocalStorage.ts
weave/panels_py/panel_llm_monitor.py
weave/panels_py/panel_trace_monitor.py

Update of https://github.com/wandb/weave/pull/617 with some additional feedback from @joecloughley 
Internal Notion: https://www.notion.so/wandbai/Weave-Board-Templates-Design-3babd954cc514e4b8df951243249025b?pvs=4#b901fe23256c46f09dc6294d1598754f
Note that the local storage code in util was borrowed from core.

feat(weave): Templates re-design

---

weave-js/src/components/PagePanelComponents/Home/HomeCenterEntityBrowser.tsx
weave-js/src/components/PagePanelComponents/Home/query.tsx

In this step, I introduce a new type that can be navigated to in the Weave Browser: `Legacy Trace` which maps the the data structure we see in W&B Workspaces. This simply makes the data available, but does not do the work to convert it to our new LLM board - that will be a followup.

chore(weave): Expose current WB TraceTree Data in Weave1 (Part 1)

---

weave-js/src/components/Panel2/ChildPanel.tsx
weave-js/src/components/Panel2/PanelInteractContext.tsx
weave-js/src/components/Panel2/PanelPanel.tsx
weave-js/src/components/Panel2/PanelPanelContextProvider.tsx

Multiple PanelPanel documents may share 1 PanelInteractContext in a report. When a ChildPanel is selected for interaction, we need to track its root document ID so the report knows which panel is being interacted with.
Required to support [this change](https://github.com/wandb/core/commit/550f33f4817f52372abf78ab8222ab039252ef4c#diff-1fbc6ee517b197cc9f11b39e62c031feef371075f4cd4a95d298291318b650cfL136) so that the selected panel is set only when the "edit" button is clicked (rather than on click anywhere on the panel)

feat(wir): Track selected documentId in PanelInteractContext

---

weave-js/src/components/Panel2/PanelPlot/PanelPlot.tsx

Fixes an issue where setting labelLimit on the x axis if x axis was disabled would cause a page crash.
Internal JIRA: https://wandb.atlassian.net/browse/WB-15751

fix: only set labelLimit on x axis if x axis is not false

---

weave/tests/test_wb_stream_table.py
weave/wandb_api.py
weave/wandb_interface/wandb_stream_table.py

This PR adds support for initializing streamtables with just project/tablename, instead of requiring entity/project/tablename. The entity is calculated using the default entity from the current WB api context. 
Adds a test for this behavior.
Internal JIRA: https://wandb.atlassian.net/browse/WB-15768

feat: use default entity in streamtable construction when no entity specified

---

weave/monitoring/openai.py

Example table for Completion both with and without stream:
https://weave.wandb.ai/?exp=get%28%0A++++%22wandb-artifact%3A%2F%2F%2Fjzhao%2Fllmon-test%2Fopenai_completion_logs%3Alatest%2Fobj%22%29%0A++.rows
Example table for the original Chat completion:
https://weave.wandb.ai/?exp=get%28%0A++++%22wandb-artifact%3A%2F%2F%2Fjzhao%2Fllmon-test%2Fopenai_chat_completion_logs%3Alatest%2Fobj%22%29%0A++.rows
One follow up is the monitoring board template does not work with the fields from the completion API by default. We discussed this offline and decided to ship the SDK changes first and fix the boards separately.

feat(weave): add openai completion api to monitoring sdk

---

weave-js/src/components/Panel2/PanelDateRange.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-15777
The DateRange control was using `toLocaleString`. This does not make it clear to the user what time zone is being used. Worse, it varies from browser to browser what date input formats can be parsed, and a non-US user was seeing parsing fail, without good UI feedback, for an input format it might seem was supported because we used it for output.
A longer term fix might involve fancier controls for date and timezone selection, but for now we display the timestamp in a format that can be parsed back (in tested browsers), is not ambiguous about timezone, and is less confusing about MM/DD vs. DD/MM ordering.
Before:
After:

fix: Use UTC ISO-ish format for timestamp display

---

weave-js/src/panel/WeaveExpression/styles.ts

Fix for long expressions overlapping content in ugly way.
This solution does introduce some issues:
1. The suggestion panel not being positioned properly.
2. No visible indication when expression has been truncated (if browser is like Chrome and hides the scrollbar)
3. Scroll position isn't always properly updating as you edit or move keyboard focus around with arrows.
See loom for demonstration:
https://www.loom.com/share/6e490c6c6e7c4db3a0b45fa2002f5b38?sid=d2a8647f-9b44-4dac-b4e3-95fde6b2c0f2

fix: scroll expression editor

---

weave-js/src/components/Panel2/ChildPanelExportReport/computeReportSlateNode.ts
weave-js/src/components/Panel2/PanelInteractContext.tsx

Adds a documents registry to `PanelInteractContext` so that all documents sharing a single `PanelInteractDrawer` are tracked in the context.
Required for https://github.com/wandb/core/pull/17251. Enables [this specific change](https://github.com/wandb/core/pull/17251/commits/7aa31e5b6c03fbea0ca70ea82cc6ac262b59edff) to better decouple the responsibilities of report page vs panel interact context

feat(wir): Create root documents registry in PanelInteractContext

---

weave/ops_domain/trace_tree.py
weave/stream_data_interfaces.py

Some old legacy traces don't have span ids and we were generating random ones. This PR stabilizes the ID so polling does not generate new ones, and by extension cause reloads

chore(weave): Stabilize span id

---

weave/environment.py

Internal Jira: https://wandb.atlassian.net/browse/WB-15694 (partial)
A `_netrc` file can also cause problems. (It's the filename used on Windows.)
See https://github.com/psf/requests/blob/main/src/requests/utils.py

chore: check for _netrc too

---

weave/compile.py
weave/mappers_python_def.py

Internal JIRA: https://wandb.atlassian.net/browse/WB-15623
Adds fingerprinting to two errors that currently have multiple types of sub events merged.

chore: Add sentry disambiguation to two paths

---

weave-js/src/components/PagePanelComponents/Home/HomeCenterEntityBrowser.tsx
weave-js/src/components/PagePanelComponents/Home/HomePreviewSidebar.tsx

* Removes Preview: this was deemed not useful by most folks
* Puts templates at the top
* Code Clean

chore(weave): Simplify Sidebar

---

weave-js/src/components/Panel2/PanelDateRange.test.ts
weave-js/src/components/Panel2/PanelDateRange.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-15815
Use system time instead of UTC in PanelDateRange to keep it in sync with plots.
* deltaStringToSeconds was actually returning milliseconds
* It was not handling negative values as comment implied, will now
* Add unit tests

fix: PanelDateRange use system time

---

weave-js/src/errors.ts
weave-js/src/react.tsx

We need to be able to distinguish when a client-side error is due to the engine, or react code - this will help us to do that

chore(weave): Propagate if errors are server errors

---

weave/monitoring/monitor.py

Allows initializing monitor streamtable with default entity, following #652.

fix: update _init_monitor_streamtable to allow default entity initialization

---

weave-js/src/components/Panel2/PanelPanel.tsx

Problem: panel editor outline view doesn't work in report page
https://github.com/wandb/weave/assets/17016170/acb49614-26a9-4f47-afae-6d7652cd5c92
Solution: need to set selected doc id in `PanelInteractContext` when navigating to outline view
https://github.com/wandb/weave/assets/17016170/9a43e4c3-71e8-4144-92f6-e17e4363260a
Still works in boards too
https://github.com/wandb/weave/assets/17016170/6dbdb2a7-4fbf-4082-a6af-92cabf92fd53

fix(wir): Set documentId for PanelPanelConfig outline view

---

weave-js/src/components/PagePanelComponents/Home/query.tsx
weave-js/src/components/Panel2/PanelTraceTree/util.ts
weave/panels/panel_trace.py

Working with customer example, I realized that we fail to recommend the if there are no parent_ids in the schema! This fixes that issue

chore(weave): Fix LLM Board to work for root-only-spans

---

weave-js/src/components/Sidebar/PanelInteractDrawer.tsx

https://wandb.atlassian.net/browse/WB-15857
Problem: if `PanelInteractDrawer` is used with page contents that are long and scrollable (e.g. reports), the drawer contents may scroll out of view.
https://github.com/wandb/weave/assets/17016170/7c0d390c-7427-482a-86dc-a3ea2585d8e4
Solution: accept sticky prop to make drawer stick to the top as user scrolls (need to update core to use this prop: https://github.com/wandb/core/pull/17419)
https://github.com/wandb/weave/assets/17016170/37010d18-5b52-4f7a-8a00-2580b512f925
Drawer still works as expected in boards
https://github.com/wandb/weave/assets/17016170/e7806a11-e17b-4dbf-89bc-bc3ff3ca3a95

feat(wir): Support sticky PanelInteractDrawer

---

weave/compile.py
weave/panels/panel_facet.py

Fixes an issue where projection pushdown on the output of facet-selected was not being propagated to the facet input node in the resolver of facet-selected. Accomplishes this by transitioning facet-selected to a new style autocall op

fix: migrate facet-selected to new-style autocall op

---

weave-js/src/components/Panel2/ChildPanelExportReport/computeReportSlateNode.ts

Related to: https://github.com/wandb/core/pull/17490/files
No functional impact to end users.
I noticed that core app actually doesn't have `uuid` as a dependency; it mostly uses the `ID` util from weave instead. Decided to update the logic for generating exported panel `documentId` for consistency.

refactor(wir): Use weave ID util instead of uuid

---

weave/ops_domain/wandb_domain_gql.py
weave/tests/test_arrow_vectorizer.py

This PR removes the requirement that the input `ArrowWeaveListType(PartialObjectType())` to a vectorized GQL prop op have a specific key in order to dispatch the vectorized (instead of mapped) version. This prevents us breaking out to python in cases where we have a lambda function that does not have propagated GQL types. 
I dont think this requirement was ever needed in the first place, since if GQL domain compilation is working correctly we should always have the requisite keys available.

perf: dont require key for vectorization

---

weave/wandb_api.py

When we query for a default entity to initialize a streamtable, if `result` is `None` and we call `.get()` on it, it will raise an `AttributeError`. Here we return `None` in that case to fix.

fix: fix attributeerror on default_entity_name

---

weave/ops_domain/artifact_version_ops.py

The `artifact.created_by` field is allowed to be null, but we were not handling that correctly.

chore(weave): Fixes nullable created_by field on artifacts

---

weave-js/src/components/PagePanelComponents/Home/HomeCenterBrowser.tsx

- https://wandb.atlassian.net/browse/WB-15986
- https://www.notion.so/wandbai/Fix-spacing-on-the-data-browser-add965ca327d4b9e8709ec0993f8b2da?pvs=4

fix(weave): Fix spacing in data browser

---

weave-js/src/panel/WeaveExpression/index.tsx

https://github.com/wandb/weave/pull/616 suppresses suggestions after you run an expression.
If you type a key, it stops suppression of suggestions. However, we have a check for printable characters, so just hitting shift etc won't stop the suppression. However, delete/backspace is a non-printable character that changes the expression, and should make it so you see suggestions again.

fix: delete key should unsuppress suggestions

---

weave-js/src/components/Panel2/ChildPanelExportReport/computeReportSlateNode.ts

No functional change. Just found `makePanel` and `makeGroup` utils and figured I should use those instead of manually constructing those objects.

refactor(wir): Use make panel utils for exported panel

---

weave-js/src/components/Panel2/ChildPanel.tsx

Problem: if a report has multiple weave panels and you try to edit one of them, all panels show the hover controls as though they're the one selected
https://github.com/wandb/weave/assets/17016170/7a0c94a9-c673-455a-9cb4-45a3d701b886
Root cause: currently we only check the ChildPanel's path to determine if it's the selected one. For panels exported to reports, we always add the target panel at path `root.panel`.
Solution: check document ID in addition to path

fix(wir): Check docid when determining if ChildPanel is selected

---

weave-js/src/components/Sidebar/PanelInteractDrawer.tsx

https://wandb.atlassian.net/browse/WB-15856
before:
https://github.com/wandb/weave/assets/17016170/1bdd65ac-add3-453b-99ff-2b7890169a7d
after:
https://github.com/wandb/weave/assets/17016170/547b30cb-ea13-440a-8e1f-80b49002b6dc
made sure it still looks right in boards:
https://github.com/wandb/weave/assets/17016170/29285cd9-9fb7-43a8-bfeb-d1e71f1bc8d4

fix(wir): Update PanelInteractDrawer styles for smaller screens

---

weave/environment.py
weave/wandb_api.py

Adds support for specifying custom HTTP headers to be included with GQL requests as environment variables.

feat: allow specifying weave_wandb_gql_headers

---

weave/weave_server.py

Follow on to #749. Logs the headers specified in that PR on startup.

chore: log weave wandb gql headers

---

weave/compile.py
weave/tests/test_compile.py
weave/tests/test_list_arrow_compat.py

There was a query this week consistently hitting our 2min timeout. After this change, the query resolves in < 2 seconds locally (after data is cached)! The key insight is that:
* a `flatten` op called on a `List<AWL>` is exactly functionally equivalent to calling `AWL-concat` on the same object! 
* a `concat` op called on a `AWL<list>` is exactly functionally equivalent to calling `AWL-flatten` on the same object! 
This PR adds a compile step to do this work.

chore(weave): Compile `List<AWL>.flatten` to `List<AWL>.AWL-concat`

---

weave/ops_arrow/constructors.py
weave/tests/test_arrow.py

Before this would fail with "must pass at least one array." This explicitly handles the length 0 case and fixes the failure.

fix: Make arrow.constructors.repeat handle repeat request size of 0

---

weave-js/src/components/Panel2/ChildPanelExportReport/computeReportSlateNode.ts

JIRA: https://wandb.atlassian.net/browse/WB-15933
Related PR: https://github.com/wandb/core/pull/17777
If group panel config `equalSize` is set to true, `flex: 1` CSS rule is applied to each group item within. This is required when exporting panels to reports because table panels need it to have height and display its contents.
Before:
After:

fix(wir): Set equalSize so table panel exported to reports have height

---

weave-js/src/components/Button/Button.tsx
weave-js/src/components/Checkbox/Checkbox.tsx
weave-js/src/components/Radio/index.tsx
weave-js/src/components/Slider/index.tsx
weave-js/src/components/Switch/index.tsx

A recent change applied focus outlines to common components (e.g. button, checkbox, etc): https://github.com/wandb/weave/pull/764
This means a focus outline will be applied on both keyboard and mouse interactions. We should definitely have focus outlines for keyboard interactions, but I'm not sure about mouse interactions. Is it visually distracting? I'd love some design team input on this. **Update: [synced with design team](https://weightsandbiases.slack.com/archives/C01QMPF38PQ/p1698115091476279?thread_ts=1698092402.588549&cid=C01QMPF38PQ)**
Examples:
https://github.com/wandb/weave/assets/17016170/762d00f8-c753-4ae1-b797-367bb5fe7428
https://github.com/wandb/weave/assets/17016170/7a22d62f-3c94-4933-910f-41c1ec396794
--
We can use the …

feat(ui): Apply focus outline only for keyboard interactions

---

weave-js/src/common/css/breakpoints.styles.ts
weave-js/src/common/css/globals.styles.ts
weave-js/src/common/css/globals_deprecated.styles.ts
weave-js/src/common/hooks/useWindowSize.ts

Change summary:
1. Added breakpoint constants from design team ([see figma](https://www.figma.com/file/01KWBdMZg5QM9SRS1pQq0z/Design-System----Robot-Styles?type=design&node-id=96-1210&mode=design&t=e8gsezGHcqe627pt-0))
2. Marked old breakpoint constants as deprecated
3. Copied `useWindowSize` hook from core
4. The primary use case for `useWindowSize` is to check the current viewport width against responsive breakpoints, so I added a `responsiveSize` property to the return value
Testing: call `useWindowSize` in report page and log `responsiveSize` value  (I chose reports just cuz it's what I've been working on lately). On report page, resize window and verify the logged values.
https://github.com/wandb/weave/assets/17016170/cd407f19-e7d8-47d3-ae01-21ae6362f959
Next step: remove …

feat(ui): Copy useWindowSize from core; add responsive sizes

---

weave-js/src/components/Tag/Tag.tsx

context: want to use this common component but cannot because it only allows me to use "tag" icon, but I want to be able to use "pin" icon

chore: pass optional iconname to tag to override the default tag icon

---

integration_test/cypress.config.js
integration_test/cypress/e2e/interactive/boardTemplateNotebookLinks.cy.ts
integration_test/cypress/e2e/testlib.ts
integration_test/yarn.lock
weave-js/src/components/PagePanelComponents/Home/HomeCenterTemplates.tsx

Adds an integration test that goes through the board template user flow on the weave homepage, ensuring that the links to the tutorial colabs to generate boards work and point to actual colab links. 
https://www.loom.com/share/11959932dc3044f889acee72888b0c8a?sid=7a31d8a2-8fc5-4fd2-8300-4659fdd7e9a7

ci: Add integration test to ensure that links to board template colabs work

---

weave-js/src/components/Panel2/PanelNumber.tsx
weave-js/src/core/util/number.test.ts
weave-js/src/core/util/number.ts
weave-js/src/core/util/string.test.ts
weave-js/src/core/util/string.ts

Internal Jira: https://wandb.atlassian.net/browse/WB-15980
Adds flexible number panel formatting. For ease of use numbers can be formatted with some predefined formats like "Percent"; for flexibility we allow specifying a custom format that supports a subset of  [Python's format specifier mini-language](https://docs.python.org/3/library/string.html#format-specification-mini-language).
This has not been reviewed by design and is not meant to be a final solution (FYI - @joecloughley) but in the short term will allow us to make some of the templates more usable.
Before:
After:
Specifying:

feat: allow formatting PanelNumber output

---

weave-js/package.json
weave-js/src/components/DropdownMenu/DropdownMenu.tsx
weave-js/src/components/DropdownMenu/index.tsx
weave-js/src/components/Sidebar/OutlineItemPopupMenu.tsx
weave-js/src/components/Sidebar/PopupMenu.tsx
weave-js/vite-plugin-block-cjs.ts
weave-js/yarn.lock

Something that's been bothering me for a while is the panel overflow menu. It doesn't close on select, and doesn't reposition if the trigger has moved.
https://github.com/wandb/weave/assets/17016170/3aa5c2c6-9a78-4417-9a32-73e937c95290
The component is currently built on semantic-ui's Popup + Menu, which doesn't work that well. I decided to bring over the DropdownMenu from core (built on radix + tailwind), which works much better.
https://github.com/wandb/weave/assets/17016170/9a06439b-f9b0-402a-ac3a-5b4f89ea5466
There will be a follow-up PR in core to remove the copy of `DropdownMenu` there and update import paths.

feat(ui): Move radix dropdown to weave; Use for outline item menu

---

weave-js/src/components/DropdownMenu/DropdownMenu.tsx
weave-js/src/components/Panel2/ChildPanelExportReport/ChildPanelExportReport.tsx
weave-js/src/components/Panel2/ChildPanelExportReport/utils.ts

https://wandb.atlassian.net/browse/WB-15976
problem: if a new report draft is created when you export a panel, the report draft doesn't show up on the reports table. however, the draft clearly exists because if you click into the report and try to edit, you'll get the "continue draft?" dialog
https://github.com/wandb/weave/assets/17016170/7f9de075-f0ac-4f84-bfc8-511bdd01e11e
solution: I compared the upsert request made by core vs weave and found that core includes `entityName` and `projectName` while weave does not. after adding those properties the reports table correctly detects the drafts created by weave
https://github.com/wandb/weave/assets/17016170/9d944707-b509-474c-93e2-c264c8b1b3bd

fix(wir): Set entity and project names on create report draft

---

weave-js/src/components/Panel2/ChildPanelExportReport/computeReportSlateNode.ts
weave-js/src/components/Panel2/PanelGroup.tsx
weave-js/src/components/Panel2/panelTree.ts
weave-js/src/components/Sidebar/Outline.tsx
weave-js/src/components/WeavePanelBank/PanelBankFlowSection.tsx
weave-js/src/components/WeavePanelBank/panelbank.ts

- Convert plain comments to doc comments -- this means when you hover a property you'll get more helpful details
- Better typing for `makeGroup` util so you can't just throw on whatever config values you want
- Better typing for `Outline` component (similar to last bullet)
- Misc changes required to resolve type errors

chore(weave): Improve PanelGroup types

---

weave-js/src/components/Button/Button.tsx

Button component currently doesn't expose any way to apply style overrides to the Tailwind wrapper. This can be quite problematic. My current issue is I need to set `display: block` on the wrapper div. I'm sure there's other use cases. Best to allow flexibility.

feat(ui): Allow tw wrapper style overrides for Button

---

weave-js/src/components/Panel2/ChildPanelExportReport/ChildPanelExportReport.tsx

https://wandb.atlassian.net/browse/WB-15912
Won't really do anything until https://github.com/wandb/core/pull/17913 is merged to core, but it's not blocking. This change can safely be merged either way.
Updates report URL on panel export to point at the specific panel we just added
https://github.com/wandb/weave/assets/17016170/7e3a2cfb-3512-4101-a5a0-e701b96d0514
(note that we link to prod core by default, but the change is still only in localhost so I had to manually update that for the demo above)

feat(wir): Link to specific report section on panel export

---

weave-js/src/common/css/Base.less
weave-js/src/common/css/globals.less

Currently we have a 2s transition when you go from light mode to dark mode, while going in the other direction happens instantly. Per feedback from design, this makes the transition instant in both directions.
See also https://github.com/wandb/weave/pull/774 which was an option considered to do a 0.4s duration transition in both directions.

chore: remove animated transition on night mode toggle

---

weave-js/src/components/Panel2/ChildPanelExportReport/ChildPanelExportReport.tsx

https://wandb.atlassian.net/browse/WB-16092
before: while "export" drawer is open...
- if user clicks in main area but not on a specific panel, the target panel becomes the whole of main, which should not be allowed
- if user clicks on another panel in main, the target panel changes but it's not obvious to the user
https://github.com/wandb/weave/assets/17016170/fbd11c6c-3d7d-4b70-a94a-0040d05970cb
after:
- drawer closes if target panel is not valid for export (which includes main)
- target panel name is highlighted if changed
https://github.com/wandb/weave/assets/17016170/46ebbd18-a9a6-4ee1-b906-19230e8ddbf9

feat(wir): Highlight selected panel change for report export

---

weave-js/src/components/Panel2/ChildPanel.tsx
weave-js/src/components/Panel2/ChildPanelExportReport/ChildPanelExportReport.tsx
weave-js/src/components/Panel2/panelTree.ts
weave-js/src/components/Sidebar/OutlineItemPopupMenu.tsx

Inspired by this comment: https://github.com/wandb/weave/pull/809#discussion_r1379231648
Testing (these are all regression checks):
- Open overflow menu for a panel in main -> split/add to report options are displayed
- Open overflow menu for a panel in varbar -> split/add to report options are **not** displayed
- Open panel editor, then click to main area background (not on a specific panel) -> drawer updates to show outline view
- Open panel editor, then click to another panel in main -> drawer updates to editor for new panel
- Open panel editor, then click to another panel in main, specifically a **group** panel -> drawer updates to editor for whole group (not specific child item that was clicked on)
- Open panel exporter, then click to main area background (not a specific panel) -> …

refactor: Create utils for checking path against main

---

weave-js/src/components/Panel2/ChildPanelExportReport/ReportSelection.tsx

https://wandb.atlassian.net/browse/WB-15936
before: when exporting a panel to a report, the entity field auto-populates based on the entity of the board. however, the project field does not. the UX is inconsistent and the extra clicks are slightly tedious.
https://github.com/wandb/weave/assets/17016170/a3ab8f36-33df-4043-90be-9337fd4f9491
after:
- if board is published to a project, project will be auto-selected when user chooses "new report"
- if it's a new board that doesn't belong to any entity/project, user still needs to manually select each of those
https://github.com/wandb/weave/assets/17016170/ea6f9957-25cf-44a7-acdb-edb3bd8f6308

feat(wir): Select default project on export to new report

---

weave-js/src/components/PagePanelComponents/Home/HomeCenterEntityBrowser.tsx
weave-js/src/components/PagePanelComponents/Home/HomePreviewSidebar.tsx

If you have a logged table and delete the artifact version but leave the sequence, attempting to preview it in the UI will crash the page. Wrapping the component in an error boundary helps, though a more comprehensive fix is desirable.
Before:
After:

fix: safer preview when artifact version deleted

---

weave-js/src/components/Panel2/ChildPanelExportReport/ChildPanelExportReport.tsx
weave-js/src/components/Panel2/ChildPanelExportReport/ReportSelection.tsx

removes the alert that says WIR is in development

chore(wir): Remove in-development alert for report export

---

weave-js/src/components/Panel2/ConfigPanel/index.tsx

We add a 2px border to config fields when they have focus. This change in size causes other UI elements to move around in distracting ways. Fixed by having an invisible border when not focused so size stays the same.

fix: plot config jitter

---

weave-js/src/components/Panel2/PanelPlot/PanelPlot.tsx

"Advanced properties" in PanelPlot allows you to specify linear vs. log scale for X and Y axes. It is collapsed by default. The onClick handler to hide the section was attached to the wrong div, so it would hide as you were trying to edit.

fix: advanced properties was toggling when click on input

---

weave-js/src/components/Panel2/PanelTable/PanelTable.tsx

Fix this warning in the developer console:

chore: fix react unique key warning in row height controls

---

weave-js/src/components/Sidebar/OutlineItemPopupMenu.tsx

When you delete a panel, some times another panel would get resized. An easy way to reproduce this is to create a board from a logged table. The table panel will stretch across the main panel. Add a new panel and immediately delete it. The table will get resized.

fix: other panel getting resized when you delete a panel

---

weave-js/src/components/Panel2/ChildPanelExportReport/computeReportSlateNode.ts

bug bash feedback from Yangyi
https://www.notion.so/wandbai/Panel-name-is-not-carried-over-68b647a972e0408c89e7a3eb8e185fa4?pvs=4

fix(wir): Keep panel name on report export

---

weave/derive_op.py

Internal JIRA ticket: https://wandb.atlassian.net/browse/WB-16272
Fixes an issue where missing artifact collections could trigger full page crashes in the weave1 engine. This matches the weave0 behavior, which fails more gracefully and loads any artifacts that can be found, and returns none for artifacts that cannot be found.

fix: make weave1 missing artifact behavior match weave0

---

weave-js/src/components/Panel2/PanelGroup.tsx

The "New panel" button at the bottom of the board fades in and out. Clicking on it before it has faded in still adds a panel, which can be confusing for the user. This PR replaces it with a standard common components Button, so it is always visible and matches the styling of the "New panel" button that is at the top of the board.
Before:
After:

chore: use common component for bottom New Panel button

---

weave-js/src/components/Panel2/PanelPlot/RadioButtons.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-16296
Use common component buttons for Zoom/Select and add tooltips.
Before:
After:

chore: update and add tooltips to plot zoom/select buttons

---

weave-js/src/common/css/TableEditor.less
weave-js/src/components/Panel2/PanelTable.styles.ts
weave-js/src/components/Panel2/PanelTable/ColumnSelector.tsx
weave-js/src/components/Panel2/PanelTable/PanelTable.tsx
weave-js/src/globalStyleImports.ts

Internal Jira: https://wandb.atlassian.net/browse/WB-16311
Bring over missing styling from app and update to use new button component.
(A short term improvement while we work on bigger table design updates.)
Before: 
After:

fix: bring over app styles for table column selector

---

weave/mappers_arrow.py
weave/ops_arrow/arrow.py
weave/ops_arrow/date.py
weave/ops_arrow/list_.py
weave/tests/test_arrow_vectorizer.py

This PR introduces a new duration type to handle time deltas and adds vectorization to the `totalSeconds` operation for time deltas.
- Two new mapper classes `TimeDeltaToArrowTimeDelta` and `ArrowTimeDeltaToTimeDelta` for converting between Python timedelta objects and Arrow time delta types.
- An operation `timedelta_total_seconds` is added in `weave/ops_arrow/date.py` that calculates the total seconds from a timedelta object, casting it to a float64 for precision.
- The `_object_type_is_basic` function in `weave/ops_arrow/arrow.py` now considers `TimeDelta` as a basic type.
- Unit tests are added to ensure the correct operation of the new duration type conversion and the `totalSeconds` function.

feat: Add Duration Type and Vectorize TotalSeconds Function

---

weave-js/src/core/client/cachePolicy.ts

This PR enahances impure identification to more than just latest, including all non-hash aliases.

chore(weave): Correctly identify all non-digest aliases as impure

---

weave-js/src/components/Panel2/PanelPlot/PanelPlot.tsx

This PR fixes a support issue in which image tooltips were not working in panelplot in weave0 due to the lack of a file tag on cached image refs. The issue was introduced by #680. The fix is to not cache the image tooltips, and instead execute the full tooltip graph each time an image tooltip is needed. This does not result in a performance degradation because in all cases, an op must be executed to get the signedURL for each tooltip. 
Note: the bug described here only affects weave0, not weave1.

fix(panelplot): circumvent cached tooltip path for images to fix image tooltips in weave0

---

integration_test/cypress/e2e/notebooks/experimental/app/RunChain.cy.ts

The Runchain test is failing due to an issue occurring early in the Python code execution within the notebook. This failure is not critical. We're temporarily disabling this test until we resolve the issue, after which it will be re-enabled.

chore(weave): temporarily disable runchain test 

---

weave-js/src/components/Panel2/PanelPanel.tsx
weave-js/src/components/Sidebar/Config.tsx

The "back to Outline" button is a non-standard component. Because of this, hovering over the back arrow will highlight the background, hovering over the "Outline" text will not, even though clicking either does the same thing.
Before:
After:

chore: use common component for back to outline button

---

weave-js/src/components/Panel2/PanelPlot/PanelPlot2Inner.tsx

Fixes an issue where circumventing the panelplot tooltip cache for image files did not work properly for columns that had dots in the names, causing tooltips to appear as `PanelNone`. This reinstates the code from the pre-cache tooltip path, using the proper logic for `escapeDots` to handle those cases and select the right column names.

fix(panelplot): escape dots correctly in panelplot tooltip pick op

---

weave-js/src/entrypoint.tsx

Internal slack thread: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1700594468967239
When not authenticated, useViewerUserInfo query was always staying in a "loading" state, which prevented the page from displaying. As a follow up, we should decide if we want to change `useNodeValue`'s behavior with respect to `skip` and `loading`.

fix: local integration tests broken by night mode

---

integration_test/cypress/e2e/testlib.ts
weave-js/src/components/WeavePanelBank/panelbankGrid.ts

Make new panels span the entire board width instead of being sized to half of it.
This was a design team request.
The new size requires a small integration test change. Now, adding the two additional panels (with the automatic scrolling on new panel that we have) causes the top table panel to scroll partly out of view, making the test fail. Updated the test to scroll tables into view before checking their contents.

feat: new panels now span entire board width

---

weave-js/src/components/PagePanelContext.tsx
weave-js/src/components/Panel2/PanelGroup.tsx
weave-js/src/components/Sidebar/OutlineItemPopupMenu.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-16367
When a panel was deleted through its overflow dropdown, we were navigating back to the outline, even if a different panel was being configured.
This also adds the automatic selection for configuration of a panel added with one of the "New panel" buttons.

fix: select panel on add and don't deselect if deleting other

---

weave-js/src/components/Panel2/PanelPlot/PanelPlot2Inner.tsx

Update the default tooltip code to ignore const nodes, i.e. mark shape and size are default const values.
Before:
After:

fix: don't show const values in default tooltips

---

weave/artifact_fs.py
weave/registry_mem.py
weave/weaveflow/__init__.py
weave/weaveflow/faiss.py

Two bug fixes for handling nested published object/op saving and loading.
Also adds a weave type for FAISS indexes.

chore: Fix RAG example relocatability

---

weave/weave_server.py

This PR ensures that eager execution mode is disabled whenever we run the server as a flask application. This ensures the standalone server always operates in lazy execution mode. This fixes an exception in the parquet history path that is raised by the server when this function is executed: 
```python
def concat_awls(awls: list[ArrowWeaveList]):
list = make_list(**{str(i): table for i, table in enumerate(awls)})
with compile.disable_compile():
return use(concat(list))
```

fix: ensure eager mode is disabled in server

---

weave/weaveflow/evaluate.py

Makes LLM evals much faster by eliminating redundant publishing of eval output type. This shaved off ~5 minutes from each of my eval runs.

perf: make eval faster by only publishing output type once

---

weave-js/src/components/Panel2/PanelPlot/ConfigDimComponent.tsx

Use standard button as trigger
Before:
After:

chore: update color config overflow menu to use new button

---

weave-js/src/components/Panel2/PanelString.styles.ts
weave-js/src/components/Panel2/PanelString.tsx

Prefix the `spacing` prop in PanelString's styled components with a `$` - this prevents the prop from being passed through to the DOM and fixes the following dev console warning:

chore: fix dev warning by prefixing styled component prop

---

weave-js/src/components/Button/Button.tsx
weave-js/src/components/Button/types.ts
weave-js/src/components/Panel2/PanelTable/PanelTable.tsx
weave-js/tailwind.config.cjs

Adds a new button variant, "quiet" which is kind of like "ghost secondary" - for use where we don't want even as much visual prominence as a ghost button.
Internal Figma: https://www.figma.com/file/01KWBdMZg5QM9SRS1pQq0z/Design-System----Robot-Styles?type=design&node-id=482-6745&mode=design&t=tQ229Vsx1axqFrOR-0
Internal Slack: https://weightsandbiases.slack.com/archives/C01QMPF38PQ/p1701375856855049?thread_ts=1701370967.808779&cid=C01QMPF38PQ
Internal Jira: https://wandb.atlassian.net/browse/WB-16512
This PR includes use of the quiet variant in the table panel as an example. Per @Cecile0112358 this represents the "selected" row height button by switching it to the active ghost variant.
Before: 
After:
Per @Cecile0112358 I have also dropped the opacity of disabled buttons from 40% to 35%. …

feat: add quiet variant to button component

---

weave-js/src/components/Panel2/ChildPanel.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-16482
Internal slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1701182330468479
The condition for when not to show panel configuration was incorrect e.g. `main.panel` is a prefix of `main.panel0` but `panel` would not be an ancestor of `panel0`.

fix: sometimes showing wrong panel config

---

weave-js/src/core/ops/primitives/list.ts

Fixes an issue where unnest output types were not properly unnested when columns were tagged lists. This led to panelplot crashes for certain grouping configurations.

fix: Fix unnest output type for tagged lists

---

weave-js/src/components/Panel2/PanelPlot/util.ts
weave/panels_py/panel_observability.py

Allows configuration of panelplot color dimension independently of label dimension in code (JS API, python API, but not in EE). Not doing this messes up custom colors in the launch observability dashboard.

feat: Enhanced Color Functionality in PanelPlot and Observability Panel

---

weave-js/src/core/suggest.ts
weave-js/src/core/util/string.test.ts
weave-js/src/core/util/string.ts

In expression editor, when user has entered a partial string, we sort matching results to the top. This was case-sensitive and the leading period in the query meant only matches at the start of the string would get sorted to the top, which did not seem to be the intent of the code.
Before:
No reordering
After:
Case-insensitive matches have been sorted to top

fix: case-insensitive suggestion reordering

---

weave-js/src/components/Panel2/PanelTable/PanelTable.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-16407
Update table pagination buttons to use new common button/icon components. This improves consistency, makes it easy to give them tooltips, etc.
Before:
After:

chore: update table pagination controls to use new button and icons

---

weave-js/src/components/Panel2/ChildPanel.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-16505
This is the same kind of bug that was fixed in https://github.com/wandb/weave/pull/892
In this example, the mouse is not over panel0, but we are rendering the expression editor as if it was, because the selection check for ancestry was using the incorrect "startsWith" and the top panel (named "panel") is a prefix of "panel0".
After:

fix: incorrectly showing EE when other panel selected

---

weave-js/src/common/components/elements/PanelError.tsx

This would enable more stable and readable tests to test the `PanelError` component in future.

test(app): Add data-test for PanelError

---

weave/ops_arrow/vectorize.py

Short circuits vectorized function application to length-0 AWLs. This prevents errors from being thrown when trying to do aggregations on empty AWLs, and improves performance.

fix: Short circuit list ops

---

weave-js/src/components/Panel2/PanelExpr.tsx

Internal Figma: https://www.figma.com/file/7FDRLfBXsEDyGWhH2IJ8Kn/Weave-plot-UX-improvements?type=design&node-id=2%3A3391&mode=dev
Internal Notion: https://www.notion.so/wandbai/RFC-Plot-UX-improvements-61b5f5c537ac444992b2736ae9a138cf?pvs=4#5f53e29a17d94c209e78b3eceae215d4
Internal Jira: https://wandb.atlassian.net/browse/WB-16488
(I have a slight concern about the term "inspector" since we don't use that elsewhere but matching what's in Figma for now.)

feat: Empty expression panels tell user to configure

---

weave-js/src/components/Panel2/panelTree.ts
weave-js/src/components/Sidebar/OutlineItemPopupMenu.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-16493
When we duplicate a panel, make the new one the same size, and position it near the original instead of at the end.
Before:  Duplicating top left "latency over time" panel adds big panel to the bottom. This is below the fold and we don't autoscroll, so it's not obvious the operation even succeeded.
After: Duplicating the same panel keeps its size and positions it near the original. There's still room for improvement on layout, but this seems better.

feat: duplicating a panel preserves its size

---

weave-js/package.json

Reduce verbosity of prettier so lint warnings are easier to notice. This is keeping consistency with a change I made to core.
See internal PR https://github.com/wandb/core/pull/18445 for more info.

chore: less verbose prettier output

---

weave-js/src/components/Panel2/panelTree.ts
weave-js/src/components/Sidebar/OutlineItemPopupMenu.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-16492
Today, when you duplicate a panel, that source panel is selected. The config panel will not be automatically opened if it is closed.
This change makes it so the newly created panel is selected and its configuration is opened. This reduces the steps a user needs to take for common cases like creating a plot from the same data as a table.

feat: duplicated panel automatically selected for config

---

weave-js/src/components/Slider/index.tsx

Updates styling of `Slider.Display` so it's more consistent with other input interfaces (e.g. Select, TextField)
Before: a bit too tall, no hover styles, incorrect focus color
https://github.com/wandb/weave/assets/17016170/91927530-8b0f-4d1b-adfb-2339c76894b4
After: height, hover, and focus styles match other inputs (second example shows it side-by-side with a select menu)
https://github.com/wandb/weave/assets/17016170/04f976e6-abf2-49d8-8619-6795c944e231
https://github.com/wandb/weave/assets/17016170/19fe814a-189c-4696-b750-11e6c4dd7a4b

feat(ui): Update slider display styles

---

weave-js/src/components/Form/Select.tsx
weave-js/src/components/Panel2/PanelPlot/ConfigDimComponent.tsx
weave-js/src/components/Panel2/PanelPlot/ConfigSelect.tsx
weave-js/src/components/Panel2/PanelPlot/plotState.ts

Update mark and point shape to use react-select component.
(Waiting on design for some more icons for the mark selector - it will get them soon.)
Before: 
After:

chore: update config to use common select component

---

weave-js/src/components/Form/Select.tsx
weave-js/src/components/Panel2/ChildPanel.tsx
weave-js/src/components/Panel2/PanelBarChart/index.ts
weave-js/src/components/Panel2/PanelBoolean/index.ts
weave-js/src/components/Panel2/PanelColor.tsx
weave-js/src/components/Panel2/PanelDate/index.ts
weave-js/src/components/Panel2/PanelDateRange.tsx
weave-js/src/components/Panel2/PanelExpr.tsx
weave-js/src/components/Panel2/PanelFilterEditor.tsx
weave-js/src/components/Panel2/PanelGroup.tsx
weave-js/src/components/Panel2/PanelHexColor.tsx
weave-js/src/components/Panel2/PanelHistogram/index.ts
weave-js/src/components/Panel2/PanelNumber.tsx
weave-js/src/components/Panel2/PanelObject.tsx
weave-js/src/components/Panel2/PanelPlot/PanelPlot.tsx
weave-js/src/components/Panel2/PanelRegistry.tsx
weave-js/src/components/Panel2/PanelString.tsx
weave-js/src/components/Panel2/PanelStringEditor.tsx
weave-js/src/components/Panel2/PanelStringHistogram.tsx
weave-js/src/components/Panel2/PanelTable/PanelTable.tsx
weave-js/src/components/Panel2/SelectPanelType.tsx
weave-js/src/components/Panel2/availablePanels.tsx
weave-js/src/components/Panel2/panellib/libpanel.ts
weave-js/src/components/Panel2/panellib/stackinfo.ts
weave-js/src/components/Panel2/panellib/types.ts
weave-js/src/components/Sidebar/Outline.tsx

Create a new select widget for panel type that supports icons and grouping. Icon association is now part of the panel spec; the outline is updated to pull the information from there.
Internal Jira: https://wandb.atlassian.net/browse/WB-16556
Internal design RFC: https://www.notion.so/wandbai/RFC-Plot-UX-improvements-61b5f5c537ac444992b2736ae9a138cf?pvs=4#97503190d2c34c7a8e59abe135334601
Before:
After:

feat: new panel type selector

---

weave/artifact_base.py
weave/artifact_fs.py
weave/artifact_wandb.py
weave/context_state.py
weave/decorator_op.py
weave/execute.py
weave/graph_client.py
weave/op_def.py
weave/ops_arrow/arrow.py
weave/ops_arrow/list_.py
weave/ops_domain/run_history/history_op_common.py
weave/ref_base.py
weave/tests/test_op.py
weave/tests/test_weaveflow.py

This makes it so we can look up calls that consumed the value of a given object. In particular this is useful so we can show all the calls that consumed a specific row of a dataset in the UI. So if for example I'm looking at the 5th question in my QA dataset, I can see any calls that have been made with that question.
```
dataset_ref = weave.publish(weave.Dataset([...]), ...)
dataset = dataset_ref.get()
@weave.op()
def my_op(v):
return v['val'] + 5
my_op(dataset.rows[0])
dataset.rows[0].input_to() # -> returns the call that we just did
dataset_ref = weave.publish(weave.Dataset([...]), ...)
dataset = dataset_ref.get()
dataset.rows[0].input_to() # -> returns nothing because the dataset[0] ref is a row in the new version
dataset.rows[0].value_input_to() # -> returns the same call as above …
```

feat: enable finding consuming calls for any table row

---

weave/op_def_type.py

Simply returning None when loading ops in production allows operating on the opdef references successfully.

chore(weave): Fixes op def references in production

---

.github/workflows/test.yaml

Our k8s CI cluster is having a networking issue. Switching CI back over to GHA runners.

chore: switch to GHA runners

---

weave/ops_arrow/arraylist_ops.py

When a NullArray is used in dimdown resolver (totally valid) we were crashing. This fixes that.

chore(weave): Don't crash when NullArray is sent to dim down resolver

---

weave-js/package.json
weave-js/yarn.lock

See https://react-select.com/advanced#sortable-multiselect - an upcoming PR will use this library in conjunction with our react-select based component, e.g. to allow changing the order of fields selected for the plot tooltip.

chore: add react-sortable-hoc dependency

---

DEVELOPMENT.md
weave-js/src/components/PagePanelComponents/Home/Browse2/SmallRef.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/context.tsx
weave/artifact_wandb.py
weave/execute.py
weave/execute_fast.py
weave/graph_client.py
weave/monitoring/monitor.py
weave/op_def.py
weave/ops_arrow/concat.py
weave/ops_arrow/list_ops.py
weave/ops_domain/run_history/history_op_common.py
weave/parallelism.py
weave/run.py
weave/run_context.py
weave/run_streamtable_span.py
weave/storage.py
weave/tests/test_weaveflow.py
weave/weaveflow/__init__.py

This PR moves the write APIs that Weave uses into GraphClient, which prior to this was just the read API (except for add_feedback)
Think of graph_client as the "weave server interface", it should contain all the API surface that the Weave engine and user APIs make use of.
This paves the way for creating other GraphClient implementations (after a little more refactoring), so that we can:
- unit test Weaveflow
- remove the old trace_local interface
- speed up all the Weave unit tests by a lot (by making them use a Memory implementation instead of the local artifacts implementation which is slow)
- enable logging to local artifacts, and later selectively synchronizing to wandb ("offline mode")
- experimenting with other implementations, like using a table for non-custom objects, or using a …

chore: Graph interface

---

weave-js/src/components/Panel2/PanelPlot/ScaleConfigOption.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-16646
Updates the scale selector to use react-select. This will make styling more consistent with the rest of the config panel. Also disabled the option filtering, which just seemed confusing given there are only two options. 
Before:
After:

chore: update scale select to common component

---

weave-js/src/components/Panel2/ChildPanel.tsx
weave-js/src/components/Sidebar/OutlineItemPopupMenu.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-16368
Reduces number of clicks to create a plot panel with the same input as a table from four to one.
Before: 
1. Click overflow menu
2. Click "Duplicate" option
3. In panel config, click "Panel type" dropdown
4. Select "Plot" option
After:
1. Click plot icon button in table header
It uses the same logic as panel duplication in terms of inserting the new panel.

feat: button to quickly create plot from table

---

weave-js/src/components/Panel2/ChildPanel.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-15746
Clicking on the main panel group (board background) sets that as the selected panel. To the user this looks like clearing the selection and displaying the outline. This PR keeps track of where the mouse down event occurred, so we can distinguish between clicking on the background and the user dragging the corner of a panel to resize it, which will also generate an onClick event. i.e. This PR makes it so we preserve the panel selection when resizing.

fix: keep panel selection on panel resize

---

weave-js/src/components/Panel2/PanelTable.styles.ts
weave-js/src/components/Panel2/PanelTable/ColumnHeader.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-16406
As a user edited the expression or column name in the table column popup, the changes were immediately reflected in the displayed column header. However, the changes would not be reverted if the popup was canceled.
This change keeps the displayed column header at its starting value, which is consistent with the displayed cell values.
This PR also updates the close button on this panel to use new common components and have a tooltip.
Before:
After:

fix: don't show column name changes if canceled

---

weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/Browse3SideNav.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimpleFilterableDataTable.tsx

Implements a quick and dirty collapsing navbar. This will certainly change with design, but it helps give more real-estate to the primary area in prep for a peek view.

chore(weave): Quick and dirty Condensed Navbar

---

weave-js/src/components/Form/Select.tsx

This adds a mode for the select widget where its height is variable. This will be used with multiple selection mode, allowing the widget to grow as more options are selected.

feat: create a variable size variant of the select widget

---

weave-js/src/components/Panel2/PanelPlot/ConfigDimLabel.tsx
weave-js/src/components/Panel2/PanelPlot/DimensionLike.ts
weave-js/src/components/Panel2/PanelPlot/plotState.ts
weave-js/src/components/Panel2/PanelPlot/types.ts

Just a refactoring, moving DimensionLike out of plotState.ts - would like to do more to bring the size of that down further.

refactor: move DimensionLike into its own file

---

weave/api.py
weave/conftest.py
weave/context_state.py
weave/graph.py
weave/graph_client_local.py
weave/mappers_publisher.py
weave/mappers_python_def.py
weave/ops_arrow/convert.py
weave/ops_arrow/list_.py
weave/ops_primitives/weave_api.py
weave/ref_base.py
weave/storage.py
weave/tests/test_ref_tracking.py
weave/tests/test_reffed_obj.py
weave/tests/test_weaveflow.py
weave/weave_init.py
weave/weave_types.py

This PR improves "ref tracking" in Weave.
One of Weave's goals is to keep track of the lineage of data at the function and value level.
Weave has the concept of a "Ref", which is a pointer to a saved object or a sub-part of a saved object, that looks like a URI.
In particular this PR
- improves ref tracking so that it works through vector operations.
- ensures that any container objects that have objects for which we already have references are saved with references instead of copies
Here's an example
```
weave.init_local_client()
items = weave.WeaveList([1, 2, 3])
weave.save(items)
@weave.op
def add5(v):
return v + 10
result = items.apply(add5)
run = weave.output_of(result[0])
```
run is a run object that represents the first call to add5. 
Issues:
- this implementation doesn't play …

feat: Better ref tracking

---

weave/ops_arrow/util.py

pa.not_equal errors when comparing `null` and `null` types, handle this case explicitly
https://wandb.atlassian.net/browse/WB-16723

fix: short circuit pa.not_equal when null

---

weave/panels/panel_plot.py

when the data being selected has been operated on by binning function, we can't naively assume `target` is temporal. Lets hack-ily handle the case where our temporal data is defined by bin `start`

fix: allow selection of grouped temporal bin data

---

weave-js/src/components/Panel2/PanelPlot/PanelPlot2Inner.tsx

We were using the type before unnesting as the tooltip node type in cached-value, non-line tooltips. This updates the tooltip cache to use the correct (unnested) type.

fix(plot): use type after unnest for tooltip nodes

---

weave-js/src/components/Panel2/PanelPlot/PanelPlot2Inner.tsx

Follow-on to #1002. 
* Uses correct (non-vega escaped) column names to access `rowType.propertyTypes` object, fixing crashes
* Adds fallback (non-caching) behavior for missing keys
* Refactors tooltip cache path

fix: Tooltip type improvements

---

weave-js/src/components/Panel2/PanelAudio/index.ts
weave-js/src/components/Panel2/PanelImage.tsx

In outline view, use less generic icons for image and audio panels.
Before:
After:

chore: use less generic icon for image/audio panels

---

weave/ops_primitives/weave_api.py

Allow for resolving graphs in the weave api mutation path with nodes that have no input, like `datetime-now`. 
https://wandb.atlassian.net/browse/WB-16740

fix: allow mutations on ops with no inputs

---

weave/api.py
weave/graph_client.py
weave/graph_client_local.py
weave/graph_client_wandb_art_st.py

`weave.ref('dataset').get()` was failing, because we were not using the 'obj' path.

chore: Fix weaveflow ref loading issue

---

weave-js/src/components/Form/Select.tsx
weave-js/src/components/Form/SelectMultiple.tsx
weave-js/src/components/Panel2/PanelPlot/PanelPlot.tsx
weave-js/src/components/Panel2/PanelPlot/SelectGroupBy.tsx

Adds a generic select component that optionally allows dragging the selected options to rearrange them. This code is based on a react-select example: https://react-select.com/advanced#sortable-multiselect
The second part of this PR replaces the current panel plot "Group by" selector with the new component. This does not take advantage of the sorting, but a later PR for specifying the tooltip dimension will.
The main advantage is more consistent styling. We also add placeholder text.
Before:
After:

chore: update plot group by to new component

---

weave/context_state.py
weave/execute.py
weave/graph_client_local.py
weave/graph_client_wandb_art_st.py
weave/io_service.py
weave/monitoring/monitor.py
weave/op_def.py
weave/storage.py
weave/tests/test_weaveflow.py
weave/wandb_interface/wandb_stream_table.py
weave/weave_init.py

This PR cleans up everything I needed to get fast weaveflow evaluation working:
- adds async op support (just decorate an async function with weave.op and use it as usual)
- adds a perf improvement to the wandb graph client to avoid repeatedly trying to publish the same objets
- fixes a super gnarly shutdown hang due to not being able to use the IO service in atexit handlers
- fixes openai patching to work with weaveflow init

fix: Async ops, fix openai patching, gnarly shutdown bugfix, perf

---

weave/engine_trace.py

when remove pii was true, internal _dd.metrics/tags were removed, and caused the spans to not be indexed

chore(weave): Fix dd traces, when DISABLE_WEAVE_PII was true

---

weave/execute.py
weave/graph_client.py
weave/graph_client_local.py
weave/graph_client_wandb_art_st.py

BaseException is broader than Exception, it includes KeyboardInterrupt. This PR ensures we log run spans for all BaseException. This is especially important right now given runs are only created when they are finished as opposed to when they are started. This ensures that for infinitely running agents that can only be stopped by ctrl-c, we still log the top level run span.

chore: Ensure runs are logged after ctrl-c

---

weave-js/src/components/PagePanelComponents/Home/Browse2/SpanDetails.tsx

- Order inputs/outputs
- Don't overlap object view grid
- Remove "_" attributes

fix: Weaveflow UI tweaks 

---

weave-js/src/components/Panel2/PanelPlot/PanelPlot2Inner.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-16641
`xScaleAndDomain` is defined like this:
```
concreteConfig.signals.domain.x
? {scale: {domain: concreteConfig.signals.domain.x}}
: {},
```
That empty object when there is no zoom seems to cause Vega to use the domain [0, max] and not [min, max]. In the screenshots below, the x values are timestamps that are close together, but far from zero, causing all of the points to overlap in a misleading way, and the user to have to zoom in a lot to see a more useful visualization. The change here is to reference the data field, which makes Vega use its min/max.
Before:
After:

fix: default range for x

---

weave-js/src/components/PagePanelComponents/Home/Browse2/CallViewSmall.tsx
weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse2/SmallRef.tsx
weave-js/src/components/PagePanelComponents/Home/Browse2/callTree.ts
weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/Browse3SideNav.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Links.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimpleFilterableDataTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfInterface/naive.ts
weave-js/src/time.ts

In response to our design discussion today, this PR removes a bunch of features that are viewed as distractions for MVP. I kept everything in code, just commented out for now. Changes:
* Sidebar simplified to just Operations, Objects, and Calls
* Default page is now "Operations"
* OpVersions:
* Op Versions page renamed to "Operations"
* Columns are minimal: Op, Category, Created, Versions
* Note: "Op" is now the name of the op + version
* Clicking Op brings you to the Op Version page
* Clicking on "Versions" lists all the versions for the op which it belongs to.
* OpVersion Page
* Defaults to "Calls Tab" - metadata tab moved to the right
* Removed useless action menu
* Made "Execute" an under-construction tab.
* ObjectVersions Page:
* Renamed to "Objects"
* Columns are just Object, …

chore(weave): Dramatic simplification of Weaveflow UI pre internal release

---

weave/cli.py
weave/conftest.py
weave/context_state.py
weave/decorator_op.py
weave/derive_op.py
weave/errors.py
weave/op_def.py
weave/op_def_type.py
weave/serve_fastapi.py
weave/tests/op_versioning_importfrom.py
weave/tests/op_versioning_inlineimport.py
weave/tests/op_versioning_obj.py
weave/tests/op_versioning_solo.py
weave/tests/test_op_versioning.py
weave/weaveflow/util.py

- Fix cases where ops that were methods on classes didn't capture dependencies
- Much better error messages/warnings: walk the AST of op function bodies, ensuring that we can capture any variables that are external references to the function
- Improve module import generation, handles more cases
- Capture closure variables that are json-able correctly.
- Add unit tests for all these cases
Bonus:
- fix "weave serve" for async ops
- add async_foreach util

feat: Hugely improved op saving/loading support

---

weave/artifact_base.py
weave/artifact_fs.py
weave/ecosystem/all.py
weave/errors.py
weave/execute.py
weave/graph_client_context.py
weave/graph_client_local.py
weave/op_def_type.py
weave/storage.py
weave/tests/test_op_versioning.py

Example
```
@weave.op()
def cat(v: int):
print("hello from cat()")
return v + 1
@weave.op()
def dog(v: int):
print("hello from dog()")
return v - 1
x = {"a": cat, "b": np.array([1, 2, 3])}
@weave.op()
def pony(v: int):
v = dog(v)
v = x["a"](v) + x["b"].mean()
v = np.array([v, v, v]).mean()
print("hello from pony()")
return v + 99
pony(...)
```
serializes to
```
import typing
import weave
dog = weave.ref('local-artifact:///op-dog:5b1dba2d0802ab99a3c9/obj').get()
x = {
"a": weave.ref('local-artifact:///op-cat:7dfb9a69dc75d47fa618/obj').get(),
"b": weave.storage.artifact_path_ref('x/b#0').get()
}
import numpy as np
import weave.api as weave
@weave.op()
def pony(v: int):
v = dog(v)
v = x["a"](v) + x["b"].mean()
v = np.array([v, v, v]).mean()
print("hello from pony()")
return v + 99
```

feat: Full Weave serialization of op closures including other op calls

---

weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionsPage.tsx
weave-js/src/components/Timestamp.tsx

Bringing over the common Timestamp component from core, updating it to add relative time display features. Updated weaveflow UI to use it. The main advantages over using moment.fromNow are that it will do live updating and also shows the absolute time in a tooltip.

feat: common component timestamp

---

weave/op_def_type.py
weave/tests/test_op_versioning.py

- imports on top
- no more "import weave as weave"
- dedupe imports
Original
```
import typing
import weave
dog = weave.ref('local-artifact:///op-dog:5b1dba2d0802ab99a3c9/obj').get()
x = {
"a": weave.ref('local-artifact:///op-cat:7dfb9a69dc75d47fa618/obj').get(),
"b": weave.storage.artifact_path_ref('x/b#0').get()
}
import numpy as np
import weave.api as weave
@weave.op()
def pony(v: int):
v = dog(v)
v = x["a"](v) + x["b"].mean()
v = np.array([v, v, v]).mean()
print("hello from pony()")
return v + 99
```
New
```
import weave
import numpy as np
dog = weave.ref('local-artifact:///op-dog:b8e5d369eea85c8d0852/obj').get()
x = {
"a": weave.ref('local-artifact:///op-cat:5588512188219faae386/obj').get(),
"b": weave.storage.artifact_path_ref('x/b#0').get()
}
@weave.op()
def pony(v: int):
v = …
```

feat: Clean up how op code is rendered

---

weave/execute.py
weave/op_def_type.py
weave/pyfunc_type_util.py
weave/storage.py
weave/tests/test_op.py
weave/tests/test_weaveflow.py
weave/weave_types.py

The prime example of an object which doesn't have a Weave type is openai.Client
We will still print warnings in these cases for now.
- Fixed case where object with unknown type is passed as argument to op with undeclared type
- Fixed case where object with unknown type is passed as argument to op with declared type
- Fixed where object with unknown type is captured by op closure.

fix: Fix cases where objects that don't have a Weave type are passed to ops.

---

weave/graph_client_local.py
weave/monitoring/openai/__init__.py
weave/monitoring/openai/openai.py
weave/monitoring/openai/util.py
weave/tests/test_monitoring_openai.py

- use graph_client instead of the older monitor context. This makes local logging (as opposed to streamtable) work as well
- fix async calling. async calls were using shared state and getting wires crossed
- remove Callbacks mechanism to simplify control flow

fix: Fix openai patched async calls, simplify, use graph client

---

weave/context_state.py
weave/op_def_type.py
weave/registry_mem.py
weave/tests/test_op_versioning.py

- Ensure we correctly locate async ops during op loading.
- Handle case where an import causes other ops to be loaded

fix: Fix op loading issues.

---

weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/SideNav.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/Sidebar.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/SidebarSection.tsx
weave-js/src/components/nightMode.ts

Some commented out code while we decide things like whether we want separate Models/Datasets entries, whether we want section headers, etc. We should be able to remove the Browse3SideNav code once we're happy with this.

feat: update navigation sidebar to better match app

---

weave/ops_domain/run_history/run_history_v3_parquet_stream_optimized.py

Fast path for case when history table only contains the following types:
```
types.TypedDict,
types.ListType,
types.UnionType,
types.RefType,
types.NoneType,
types.Number,
types.String,
types.Boolean,
types.Timestamp,
```
This reduces load time on one of my hooman projects from like 1m+ to a few seconds.
Note this does not include ObjectType. I think we'd need to change the write path a little bit to get that working. But we're not saving ObjectType directly in the calls table in Weaveflow use cases so far.

perf: Fast path for loading streamtable data

---

weave/ops_domain/run_history/run_history_v3_parquet_stream_optimized.py

The new fast path type safety check was too specific.

fix: Fix overly aggressive type check

---

weave/panels_py/panel_observability.py

changed my mind, better to have this not in the type, 2 reasons: 
1. priority has only been logged for a couple weeks, anyone visiting the dashboard page in that new time without launching a job might see an error. 
2. we might actually want to play games with the type, seeing as it was causing grief...

chore(launch): remove priority from qob type

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage.tsx

Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1705604211776789
This may be a bit better than before in that if the row element exists, it will scroll it to the top - but often the row element won't exist because of virtualization. Still room for improvement.

fix: try to scroll to top

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionsPage.tsx

Internal Notion: https://www.notion.so/wandbai/Weaveflow-Jan-2024-Tasks-e4f3a053bc8243738ba1dad3c4cff6d4?pvs=4#338afecd952044da949820bc32985548
Clicking the "Latest Only" or "Roots Only" buttons should do the same toggle as clicking on the checkbox itself.

fix: toggle Latest filter on button click

---

weave-js/src/common/css/utils.test.ts
weave-js/src/common/css/utils.ts
weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/StyledDataGrid.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimpleFilterableDataTable.tsx

Internal Notion: https://www.notion.so/wandbai/Weaveflow-Jan-2024-Tasks-e4f3a053bc8243738ba1dad3c4cff6d4?pvs=4#4ad31d2f2c764ef49b195f983ec82970
Centralizes custom datagrid styling. Adds row selection to various grids, sync'ing it with what's shown in the peek drawer.

feat: highlight table row corresponding to open peek drawer

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/StatusChip.tsx

Internal Notion: https://www.notion.so/wandbai/Weaveflow-Jan-2024-Tasks-e4f3a053bc8243738ba1dad3c4cff6d4?pvs=4#c1b2e1b7cd8a494580952055afa51bbb
Make it clearer what the status icons mean.

chore: weaveflow status chips have tooltips

---

requirements.txt

The evaluate framework added a dependency on the [rich](https://rich.readthedocs.io/en/latest/) library.
https://github.com/wandb/weave/blob/master/weave/weaveflow/evaluate.py#L12

fix: add rich to requirements.txt

---

weave-js/src/components/PagePanelComponents/Home/Browse2/WeaveEditors.tsx

feat: autosize dataset values columns

---

weave/autopatch.py

E.g. https://wandb.github.io/weave/tutorial-eval#upload-a-dataset - nothing is obviously using OpenAI here, so the message being output is confusing.

chore: don't print openai message

---

weave/ops_domain/run_history/run_history_v3_parquet_stream_optimized.py
weave/wandb_interface/wandb_stream_table.py

- unbox in streamtable write path, we were saving boxed booleans as {_type, _val} dicts in streamtable instead of as the raw values
- handle empty calls case in history3 read fast path

fix: two little crashes, handle zero case in history3 read path

---

weave-js/src/components/PagePanelComponents/Home/Browse2/SmallRef.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionPage.tsx
weave-js/src/react.tsx

// TEMP HACK (Tim): This is a temporary hack to ensure that SmallRef renders
// the Evaluation rows with the correct label and link. There is a more full
// featured solution here: https://github.com/wandb/weave/pull/1080 that needs
// to be finished asap. This is just to fix the demo / first internal release.

chore(weave): Quick fix to enable correct ref links for eval use case

---

weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx

Feedback from design team.
Before:
After:

chore: Swap status and id columns, set status column header and size

---

weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx

Was doing a string sort instead of sorting numerically.
Before:
After:

fix: sorting of latency column

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx

Makes the code tab available when viewing a call, not just an op version. Saw in user testing that people are looking for this and having trouble finding it.

feat: add code tab to call

---

.pre-commit-config.yaml
mypy.ini
requirements.txt
weave/api.py
weave/decorator_arrow_op.py
weave/decorator_op.py
weave/language_features/tagging/make_tag_getter_op.py
weave/panel_util.py
weave/show.py
weave/wandb_util.py

Before
After
This change breaks type checking for lazy weave (where calling an op returns a Node instead of eagerly evaluating it), which is used in ops* and panels* subdirs, but is not the user-facing API exposed by the weaveflow work (which is eager).
So for expediency, I have disabled type checking in all weave/op* subdirs, and all weave/panel* subdirs.
But pyright in vscode will still happily show you all the type errors in those files, so the development experience does not change, we are just allowing type errors in our pre-commit checks within non-weaveflow parts of weave for now.

fix: @weave.op() decorator passes through user type and docstrings

---

weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionsPage.tsx

By default you can show/hide any column. This PR disables that for the first column in the table. One motivation for doing this is that the user can get stuck if they click the "Hide All" button in the "Manage columns" dialog, as we don't have a GridToolbar to provide them another way to access that.
Before:
After:

fix: disallow hiding first col

---

weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse2/tableStats.ts

Makes the input and output columns more available, including across ops.

feat: loosen restrictions on showing call input & output

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx

Make object name filter options unique and sorted.
Before:
After:

fix: uniquify and sort name filter for objects

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/TypeVersionCategoryChip.tsx

Internal Figma:
https://www.figma.com/file/27JVuBYWHbcAYc8WPb4HqA/Weaveflow-hifi?type=design&node-id=2051-104821&mode=design&t=PXxHLY0uc1XxES1x-4
Before:
After:

chore: use common component for object type chip

---

weave-js/src/components/CopyableText.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseDataset.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseModel.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseObject.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseOp.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Links.tsx

Adds click-to-copy usage examples for ops and objects.
Note: some of the suggested code may not be quite right since I haven't gotten e.g. weave deploy working myself, but I figure it will be quick to fix after this goes in.

feat: add Use tabs to Object and Op pages

---

weave-js/src/components/Panel2/panellib/libcolors.ts
weave-js/src/core/model/helpers.ts
weave-js/src/core/model/typeHelpers.test.ts

Chart colors were broken here https://github.com/wandb/weave/pull/865/files 
Properly unnest tagged list types for the mapeach so that run colors are properly mapped
before
after

fix(weave): fix run colors

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx

Just trims off the "op-" prefix to make the op name at the top of the call peek drawer match the value we show in the grid.

chore: use nice name in drawer

---

weave-js/src/core/ops/domain/artifactVersion.ts
weave-js/src/core/ops/domain/gql.ts
weave/ops_domain/artifact_version_ops.py

[WB-17216](https://wandb.atlassian.net/browse/WB-17216)
[Gong is facing slow load times](https://weightsandbiases.slack.com/archives/C01KQ5KTDC3/p1706797103944949) for the artifact version overview page, possible because they have an artifact consisting of 100k files, 400GB. 
The artifact overview page calculates the file count by counting the files in the fileTree returned by `opArtifactVersionFiles`. This PR adds an op to fetch the file count directly from the GQL endpoint `fileCount` from the Artifact type.
[WB-17216]: https://wandb.atlassian.net/browse/WB-17216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(artifacts): add fileCount ops for artifact version

---

weave-js/src/components/PagePanelComponents/Home/Browse3/OpCodeViewer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/OpCodeViewerDiff.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/SelectOpVersion.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionPage.tsx

Button to enter diff mode if there is more than one version:
Diff mode shows you what changed. Arrows let you step through changes incrementally.
Can select specific version to compare:

feat: add code version diff

---

.gitignore
weave-js/src/components/Panel2/PanelString.styles.ts
weave-js/src/components/Panel2/PanelString.tsx
weave/conftest.py
weave/ops_domain/table.py
weave/tests/test_execution_graphs.py

Please see the code comments:
```
```

chore(weave): Fix full page crash on very complicated legacy weave tables

---

weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Links.tsx
weave-js/src/core/util/string.ts

Tweaks from design team to calls table:
* Make first column show op name instead of just the abbreviated call id.
* Remove the op column.
* Move latency column to right
Also makes the "Producing calls" rendering more like the "Consuming calls". It's still a little weird because we don't have an autocomplete widget for the outputs the way we do the inputs.
Before:
After:

chore: merge call and op columns, other grid tweaks

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseDataset.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseModel.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseObject.tsx

Was generating code like:
`notion-dataset = weave.ref("...").get()` but `notion-dataset` is not a valid Python variable name.

fix: use Python-safe var name

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallOverview.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/constants.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/interface.ts

In order to improve query-side performance, we need to move away from the naive-ORM style loading pattern. Instead, implementing a lazy-loading approach that takes advantage of the weave query engine characteristics.
This will be done in 6 parts: 1 for each of the main 6 pages. 
This is part 1. I implement the new model for the ObjectVersionPage and most of the initial interface under weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/interface.ts
Note: for this page alone, using the hooman example, we move from a ~4.3MB data transfer to load the page to ~15kb! As a very practical result - MUCH MUCH more client side caching will take place over time! 
More to come

chore(weave): UI-Side Query Migration Page 1/6: ObjectVersionPage

---

weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Links.tsx

Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1707419506214469
Render call links in a more efficient & readable way. Clicking on link, id, or in-between will navigate.
Note: We'll want to make other call references currently using truncateID match, but I want to see if we have agreement on this truncating to four chars before doing that work.
Before:
After:

chore: Update call link styling

---

weave/environment.py
weave/file_util.py
weave/path_util.py

changes get allowed dir to use filesystem.get_filesystem_dir instead of using the env var 
needed for the cache prefix to apply everywhere

fix(weave): change a file util to use correct path

---

weave-js/src/components/PagePanelComponents/Home/Browse2/WeaveEditors.tsx

Use CSS grid with autosizing of first column instead of MUI grid with column sizing based on percent of space. This prevents labels from overlapping values when the grid is narrow or wasting space when the grid is wide.
Before:
After:

fix: keys overlapping values in grid

---

weave-js/src/components/WeavePanelBank/PanelBankFlowSection.tsx

for some reason PBSection in flow mode would grow infinitely
https://github.com/wandb/weave/assets/17016170/e8b1c0c4-2032-44ab-a125-a59336e7dba1
honestly still don't know why this happens. i tracked it down to [this](https://github.com/wandb/weave/blob/57542fc68a6176f9525b0a65c2a53f46b8a90718/weave-js/src/components/WeavePanelBank/PBSection.tsx#L70) `onResize` handler, which kept getting triggered with a slightly larger height value each time. however if I set the inner container height to a fixed valued then the issue goes away.
https://github.com/wandb/weave/assets/17016170/a5d0d1f8-0d80-49e0-94cb-7e8d70768de1
I don't know if there's a problem with how we're using `react-measure`, or if it's a bug with `react-measure` itself, but I genuinely could not figure this one out 😅 
I did some …

fix(app): Stop infinite grow on PanelBankFlowSection

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx

The animation of the drawer couldnt handle the full trace tree, thats why the jumpiness only happens when we render the trace tree.
I tried a couple things before landing on this "solution"
- limiting the height of the trace tree on load so that not as many rows load
- fiddling with different position settings like absolute and fixed ("fixed works but then we dont get the correct overscroll behavior and waiting on load till after felt more gross than this)
this seemed like the cleanest, but open to suggestions
before
https://github.com/wandb/weave/assets/25037002/880fc817-e1cb-4720-b527-f45fe8abee89
after
https://github.com/wandb/weave/assets/25037002/257c530d-56ab-40c6-918a-9b5e60789930

fix(weave): fix jumpiness with drawer on trace view

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx

Styling change suggested by @Yangyi-wandb in Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1707778615974629?thread_ts=1707761474.511599&cid=C03BSTEBD7F
Before:
After:

chore: update trace tree styling

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallOverview.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallSummary.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Links.tsx

Moves some of the information currently shown in the call overview to a new Summary tab.
Needs more work to match internal figma. (Which is also a little outdated w.r.t category chip, call id rendering)
https://www.figma.com/file/27JVuBYWHbcAYc8WPb4HqA/Weaveflow-hifi?type=design&node-id=2656-68308&mode=design

chore: move some call information from overview to new summary tab

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimplePageLayout.tsx

We were trying to preserve the selected tab when you switch calls. However, the available tabs might differ from call to call.  E.g. with the quickstart, `extract_fruit` has a Code tab, `openai.chat.completions.create` does not.
The state we were storing was tab index rather than tab label, leading to two problems:
* You might switch to a different tab than you were on.
* The UI might crash if the tab index you were on was out of range for the new set of tabs.
This PR updates the code to use the label for the selected state, with a fallback to the first tab if the previous selection can't be found.
Datadog: https://app.datadoghq.com/rum/replay/sessions/a5163743-b8ca-4207-8ff6-4a09ba15a664?highlightedEventId=AgAAAY2kLgZZRpMbHgAAAAAAAAAYAAAAAEFZMmtMZ2EwQUFBVl9QY0VhVm11S2dBRwAAACQAAAAAMDE4ZGE …

fix: crashing related to preserving tab selection

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ButtonOverlay.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallDetails.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/OpVersionText.tsx

@shawnlewis asked for this in an internal [slack thread](https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1708533033919989?thread_ts=1708105790.878939&cid=C03BSTEBD7F).
See also [internal figma](https://www.figma.com/file/27JVuBYWHbcAYc8WPb4HqA/Weaveflow-hifi?type=design&node-id=2456%3A29152&mode=design&t=BFVpX6CBNrhEUDzm-1).
Before:
After:
If you mouse over the table you get this:

feat: multiple child call table acts like a button

---

weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/context.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Links.tsx

Hide trace tree by default for evaluation calls.
Internal notion: https://www.notion.so/wandbai/Default-trace-tree-state-should-be-collapsed-based-on-heurisitics-816a79c376f64b59bdf2bcab8491fc0c?pvs=4

feat: hide trace tree for evaluate

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallSummary.tsx

We're displaying similar information on the main call tab already, don't need it on the summary tab.

chore: remove child calls from call summary tab

---

weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse2/tableStats.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/BoringColumnInfo.tsx

Internal notion: https://www.notion.so/wandbai/Factor-common-inputs-out-of-calls-table-1e1823c4de6c4a1986b791e76a33a747?pvs=4
Identify columns that have the same value for all rows and instead render those values above the table. This makes it easier to see the interesting information in the grid.
Before:
After:

feat: hide boring columns, instead show values at top of table

---

weave-js/src/components/PagePanelComponents/Home/Browse2/WeaveEditors.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/StyledDataGrid.tsx

sets the max width of the columns to .75 browser when not in peek, and .5 browser in peek
https://www.notion.so/wandbai/Object-Version-View-Max-column-width-too-wide-for-Dataset-rows-table-10c654dda7944f29aabc7127f8ca9b6a?pvs=4
check out
https://beta.wandb.ai/llm-play/ticktock/weaveflow/object-versions?betaVersion=c85db4ce737e0d2fbebf6400ea8c0a6884f722c8

chore(weave): limit object table column size, and change to styled datagrid

---

.github/workflows/test.yaml
weave/tests/test_client_trace.py
weave/tests/trace_server_clickhouse_conftest.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/environment.py
weave/trace_server/graph_client_trace.py
weave/trace_server/remote_http_trace_server.py
weave/weave_init.py

While working on productionization and UI integration, I needed to fix a handful of little things and it would be good to isolate the land these changes:
* Refactor all environment variable accessing to a single, documented file and share that in all relevant areas. Not only good practice, but also important to inject such variables for different environments (dev, prod, etc...)
* All Clickhouse client to support username/password (allowing connections to secure CH servers like CH Cloud)
* Fix bug in DB aggregation logic regarding the aggregation of null values
* Fix table creation logic in bootstrap SQL to not re-create views/tables
* Move project creation into trace graph client
* Important: created `GraphClientTraceWithArtifactStorage` as a subclass of `GraphClientTrace` which uses …

chore(weave): Various CH Cleanups

---

weave-js/src/components/ErrorPanel.tsx

Instead of "please check the panel configuration for errors." it now says "An unexpected error occurred."

chore: update error message

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallDetails.tsx

As discussed in meeting this morning - for now skip rendering of singular child calls, but leave code in place while we decide if this is actually our preference.

chore: hide singular child details

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallOverview.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimplePageLayout.tsx

Don't show call title at the top of drawer, make it more prominent above tabs.
@Yangyi-wandb with this styling the title can get a little squished when you have the trace tree open.
Internal Figma: https://www.figma.com/file/27JVuBYWHbcAYc8WPb4HqA/Weaveflow-hifi?type=design&node-id=2544-113114&mode=design&t=DVq1XHahBd87zaBG-0
Before:
After:

chore: change drawer heading

---

weave-js/src/components/PagePanelComponents/Home/Browse2/tableStats.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/BoringColumnInfo.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/BoringStringValue.tsx

Internal slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1708959561574009
Improvements to the display of "Common values".
* Long string values are now truncated, can be clicked to expand.
* Doesn't show common values when there is a single row
* When there are many values, scroll horizontally instead of wrapping.
* Leave status code indicator in the table if it is the only common value we would display.

fix: improvements to display of common values

---

weave-js/src/components/CodeEditor.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallDetails.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CursorBox.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewerGroupingCell.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewerSection.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueViewNumber.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueViewString.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/traverse.test.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/traverse.ts

Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1709147066569379
New features:
* Use material tree grid to render, allowing expanding/collapsing sections and resizing the path/value columns.
* Fetch ref values so they can be displayed.
* JSON view
* Show/hide section
* First pass at rendering primitive values like numbers, null, boolean to better indicate type.
Before:
After:

feat: fancier input/output tables with ref expansion

---

weave/tests/test_client_trace.py
weave/trace_server/clickhouse_trace_server_batched.py

chore(weave): Fix datetimes coming out of trace server

---

weave-js/src/components/CopyableText.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseDataset.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseModel.tsx

* Remove "ref" from header because it appears in Use tab.
* Don't shrink copy-to-clipboard icon when panel is narrow
* Use tab now handles subpaths within parent objects better.

chore: improve object version page and Use tab

---

weave/api.py
weave/trace_server/environment.py

With this change, we now leverage the new trace server for call logging.

chore(weave): Makes trace server the new default logger

---

weave-js/src/components/PagePanelComponents/Home/Browse3/SideNav.tsx

Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1709239253561709
Move traces to top, hide evaluations for now.

chore: reorder navigation bar

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPage.tsx

Fix this developer console warning:
This is coming from the multiple child calls table. `CallsTable` is getting `hideControls={true}`, but that does just hide the filters, they are still there.
The op autocomplete filter gets its options from `useOpVersionOptions` which does two queries. This warning happens because we are specifying the autocomplete value based on the selection, but the query for the selected op versions may not have completed at the time we get the partial list of options back from the other query finishing.

chore: fix dev console Autocomplete warning

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallTraceView.tsx

The CallTraceView supported displaying additional input/output columns as an experiment, but that code path was disabled. 
It turns out I introduced a crash when I added the "hidden siblings" indicator if you turned it on. Fixing the crash would be trivial, but it seemed better just to remove the experimental code since I don't think we're going to use this UX.

chore: remove unused experimental code

---

weave-js/src/components/PagePanelComponents/Home/Browse2/WeaveEditors.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueViewPrimitive.tsx

We should do a more comprehensive alignment of how we display values, but wanted to get in a quick fix for null values appearing as disabled checkboxes.
Before:
After:

fix: null values in object viewer

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseOp.tsx

Missed this when fixed it for other Use tabs in https://github.com/wandb/weave/pull/1191

fix: check for legal Python identifier in op code sample

---

weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/FullPageButton.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/context.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Links.tsx

FYI @jlzhao27 
Internal slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1709568959470889
If you clicked the "Open full page for this object" button you would get an "Object not found" error.
Also made the button a link, which allows you to right click and open the page in a new tab/window.

fix: broken full page button

---

weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/cgDataModelHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClient.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts
weave/tests/test_client_trace.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/graph_client_trace.py
weave/trace_server/migrations/003_add_call_meta.down.sql
weave/trace_server/migrations/003_add_call_meta.up.sql
weave/trace_server/trace_server_interface.py

This PR adds tracking of the logging user and current WB run to weave calls. Specifically:
1. Adds these fields to the data model and various apis
2. Adds the logging of the run to the graph client
3. Adds filter functionality
4. Adds tests
5. Uses compatible migration so we don't need to blow away data
Uptake here: https://github.com/wandb/core/pull/19951

chore(weave): Add User and Run to Calls

---

weave-js/src/components/CopyableText.tsx

fix: minor styling issue with copyable text in use tab

---

weave-js/src/components/PagePanelComponents/Home/Browse2/CustomGroupedColumnHeader.tsx
weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx

Internal Notion: https://www.notion.so/wandbai/Show-full-path-when-configuring-columns-3fe1209223934a509ff98d88e441ba65?pvs=4
Column visibility configuration uses headerName (defaults to field) which doesn't work well with grouped columns. This PR makes the headerName the full dotted path but then uses a custom header renderer to strip off everything but the last segment.
Before:
After:

fix: show full path in column visibility dialog

---

weave/ops_domain/project_ops.py
weave/tests/test_wb_domain_ops.py

fixes an obscure error that happens in onprem.
basically instance { project {} } has no limit field

fix(weave): fix project limit error

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/BoringColumnInfo.tsx

before
https://github.com/wandb/weave/assets/25037002/68f2eec5-5664-4ae6-b0e7-302eb978a63f
after

chore(weave): add max width to boring tags

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx

This PR disables the path selection feature, allowing us to render the selected call without needing to load the entire trace.

chore(weave): Disable call subpath to make call loading near instant

---

weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse2/tableStats.ts

the previous pr here https://github.com/wandb/weave/pull/1248/files
had a bunch of  changes to keyvalue table and calldetails which was then promptly refactored.
so pulling out the runstable part
before
after

chore(weave): hide _result in runstable

---

weave-js/src/components/PagePanelComponents/Home/Browse2/SmallRef.tsx

chore(weave): fix boring refs overflow

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClient.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts

Recent PR here: https://github.com/wandb/weave/commit/a89107a53d1fd97b24226047ac538867b8cea243 implemented client-side batching for large data payloads. There was a bug that the hook would not reset when diff params were provided. I refactored the code to move the paging logic out of a hook and into a helper function. And reverted the hook to it's previous state

chore(weave): Fixes hook useCall staleness with pagination

---

weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx

See comment in coded. This makes it so you can navigate to new rows without losing the current data table state.

chore(weave): Fix loss of state (ex. Pinned Columns / Sort) when clicking runs

---

weave-js/src/components/PagePanelComponents/Home/Browse2/CellValue.tsx
weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse2/SmallRef.tsx

before example is closed, and ref column has string still
https://github.com/wandb/weave/assets/25037002/756c09e7-f415-4d19-b047-9ac99b3fe742
after
https://github.com/wandb/weave/assets/25037002/e31a8548-b37a-4260-88f1-d4c6a378edeb

chore(weave): auto expand input.example, hide ref string when expanded

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx

Fix sorting / filtering in object versions page, either making it work or disabling for the column.

fix: sorting and filtering in obj versions grid

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionsPage.tsx

Fix sorting / filtering in op versions page, either making it work or disabling for the column.

fix: sorting and filtering in op versions grid

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallTraceView.tsx

We were losing the path when you clicked on the close button that's in the trace tree header. Also added a tooltip to it.

fix: was losing path when closing trace tree with other button

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPage.tsx

On the Calls list page, if you selected an Op (all versions) instead of a single Op version, it would correctly filter the grid and list the specific versions available in the autocomplete, but when you clicked away from the filter the value would disappear and you could not clear it.

fix: autocomplete value not shown when showing all versions

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPage.tsx

Just hiding for now; post launch we should decide if we want to finish this feature or remove it from the code.

chore: hide pivot button on calls list view

---

weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx

After some recent changes the peek path may include query parameters like `?tracetree=1` - this broke the row selection highlighting in the calls grid which wasn't expecting that.

fix: call grid row selection was broken

---

weave-js/src/components/PagePanelComponents/Home/Browse3/StyledDataGrid.tsx

The custom expand/collapse headers will be addressed separately.
Internal Figma: https://www.figma.com/file/27JVuBYWHbcAYc8WPb4HqA/Weaveflow-hifi?type=design&node-id=3562%3A5105&mode=design&t=sLHcN487gXQPAgXZ-1
Before:
After:

chore: update grid column header color/weight styles

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseDataset.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseModel.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseObject.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseOp.tsx

Internal Notion: https://www.notion.so/wandbai/Replace-Material-design-components-dbb5f747b86d44efa5c55ecea2474810?pvs=4#bf7cec9f38044d3a9c0c24336153aab4
Before:
After:

chore: use common Alert component instead of Material's on Use tabs

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallOverview.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallSummary.tsx

Internal Notion: https://www.notion.so/wandbai/Highlight-exceptions-and-show-the-message-64f33fb8708d49f7b2a37be6b12de868?pvs=4
The padding looks weird but that will be addressed separately.
Before:
After:

chore: show exception information in header instead of summary tab

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/BoringColumnInfo.tsx

Boring columns are those where the value is the same for every row. Some columns are _super boring_ and have null for every value. We don't even bother to show the key/value pair for super boring columns. However, we were still counting them when determining whether to show the panel at all, which led to this unfortunate UI, which this PR fixes:

fix: don't show boring info if everything is super boring

---

weave/flow/eval.py
weave/trace/errors.py
weave/trace/op.py

Fix error messages in these scenarios
**Genera: op is called with invalid inputs**
```
weave.trace.errors.OpCallError: Error calling ExtractFinancialDetailsModel.predict: missing a required argument: 'marticle'
```
**Evaluation: model predict function does not have correct arguments**
```
weave.trace.errors.OpCallError: 
Call error: Error calling ExtractFinancialDetailsModel.predict: missing a required argument: 'marticle'
Options for resolving:
a. change ExtractFinancialDetailsModel.predict argument names to match a subset of dataset column names: id, article, extracted
b. change dataset column names to match expected ExtractFinancialDetailsModel.predict argument names: ['marticle']
c. construct Evaluation with a preprocess_model_input function that accepts a dataset example and returns …
```

feat: actionable error messages for Evaluation construction issues

---

weave/flow/eval.py
weave/trace/env.py

This is a quick fix to help make progress when client calls hit rate limit errors in the Weave client. For example, when calling the Anthropic API with default rate limits, more than 1 parallelism results in failing requests.
We're going to want changes to how parallelism works. This is just a quick fix to give an out for users to work around the problem manually.

fix: Control eval parallelism from env var

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueViewString.tsx

Internal Slack: https://weightsandbiases.slack.com/archives/C01T8BLDHKP/p1711576851862249?thread_ts=1711575233.181359&cid=C01T8BLDHKP
If user asks to render as string value as JSON, but it isn't valid JSON, indicate that.

feat: warn user if value is not valid JSON

---

weave/init_message.py
weave/wandb_api.py
weave/weave_client.py
weave/weave_init.py

**Before: Not Logged In:**
Note: you must execute a shell command or import `wandb` (a non-weave lib) to fix:
** Before: Successful Init:**
Not helpful for users:
**After**
Follows the same pattern as `wandb.init`
* (IF NEEDED): Prompt user to login with link to auth page - never need to import wandb
* (IF NEEDED): Warn user to upgrade `wandb` if the version is too low
* (IF NEEDED): Inform user of new weave package available (uses same mechanism as wandb)
* (Always) Informs user of their auth state and target project & link to weave home for logs
All 4 parts shown:
Normal base case:

chore(weave): Improve default init experience

---

weave/monitoring/openai/openai.py
weave/weave_client.py

This PR makes it such that our OpenAI integration logging creates an Op for the OpenAI trace - allowing for viewing all OpenAI calls in a list and code saving.

chore(weave): Make OpenAI calls their own ops

---

weave/tests/test_op_versioning.py
weave/tests/test_trace_server.py
weave/tests/test_vals.py
weave/tests/test_weave_client.py
weave/trace/op.py
weave/trace/op_type.py
weave/trace/refs.py
weave/trace/serialize.py
weave/trace/vals.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/migrations/004_new_objects.up.sql
weave/trace_server/refs_internal.py
weave/trace_server/sqlite_trace_server.py
weave/trace_server/tests/test_refs.py
weave/trace_server/trace_server_interface.py
weave/trace_server/trace_server_interface_util.py
weave/weave_client.py

This PR makes a fairly substantial change to the data model and ref structure. In particular, we make the following changes:
1. All trace server interfaces now accept a `project_id` rather than an `entity/project` tuple. Under no circumstances should the trace server implementation make the assumption that the project_id has any format whatsoever - it is just a string ID. This was already the case for calls, but now is true for objects, ops, and refs.
2. Refs are now stored with the following format: `weave-trace-internal:///PROJECT_ID/...` rather than `weave:///entity/project/...`. This sister representation is implemented in `refs_internal` and also gives us the benefit of moving `refs.py` out of the trace_server dependencies completely. With this change, and the change above, the trace …

chore(weave): Refactor: Replace all cases of plaintext entity/project with internal project ids

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueViewStringFormatMenu.tsx

Use our common component for the string value format dropdown instead of Material's menu. This will make it more consistent with our style guidelines, e.g. using Source Sans Pro, no ripple animation on click.
I suspect this will also fix a problem reported in Slack where the CSS rules were sometimes getting applied in an unexpected order, but I need to double check that.
https://weightsandbiases.slack.com/archives/C01T8BLDHKP/p1711575233181359
Before:
After:

chore: update dropdown to use common component instead of Material

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts

if im trying to do something like the function the skip wont be applied until after we try to fetch the trace client which causes the fetch to throw an error if no client. 
this pr moves the getTsClient after the skip is honored
```
export const useProjectHasTraceServerData = (
entity: string,
project: string
) => {
const hasTraceServer = useHasTraceServerClientContext();
const objs = tsWFDataModelHooks.useRootObjectVersions(
entity,
project,
{},
1,
{
skip: !hasTraceServer,
}
);
const calls = tsWFDataModelHooks.useCalls(entity, project, {}, 1, {
skip: !hasTraceServer,
});
const loading = objs.loading || calls.loading;
return {
loading,
result: (objs.result ?? []).length > 0 || (calls.result ?? []).length > 0,
};
};
```

chore(weave): Skip before fetching client

---

weave-js/src/components/PagePanelComponents/Home/Browse2/RefValue.tsx
weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse2/WeaveEditors.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/context.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseDataset.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/cgDataModelHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/constants.ts
weave/arrow/list_.py
weave/artifact_fs.py
weave/box.py
weave/object_type_ref_util.py
weave/ref_util.py
weave/tests/test_refs.py
weave/tests/test_vals.py
weave/tests/test_weave_client.py
weave/trace/refs.py
weave/trace/vals.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/refs_internal.py
weave/trace_server/sqlite_trace_server.py

1. Unifies all declarations of edge names to singles files across both python and typescript
2. Standardizes naming everywhere
3. Changes `atr` to `attr`
4. Changes `ndx` to `index`

chore(weave): Unify Edge Names Across Applciation

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Empty.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/EmptyContent.tsx

Internal Notion: https://www.notion.so/wandbai/Empty-states-for-Objects-Models-Datasets-pages-b748c0d705fb46e8ab93b5a90595c5ee?pvs=4
I will follow up with design re: the TODOs around loading indicators and color palette. The others TODOs are pending more confidence about the state of filters on these pages.
Before: 
After:

feat: empty pages

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx

We don't want the empty page to appear while the query is still loading.

fix: empty page showing during loading

---

weave-js/src/components/PagePanelComponents/Home/Browse2/tableStats.ts

Stringify objects when computing table stats. Without this, they are converted to `[object Object]` when used as a key of the valueCounts object. This would both incorrectly merge counts for different objects and appear in the boring value display instead of a usable string representation.
Would be interested in an opinion on the use of json-stable-stringify which will more correctly count objects according to JSON semantics vs. just JSON.stringify since in practice people often intend object key order to be meaningful.
Before:
After: (I turned on the input column so you could see the values)

fix: serialize objects when counting them for boring calculation

---

weave-js/src/components/PagePanelComponents/Home/Browse2/tableStats.ts

Fix bug I just introduced in https://github.com/wandb/weave/pull/1391 - limit stringify serialization to just arrays and objects.
Before:
After:

fix: don't stringify ref objects in boring stats

---

weave-js/src/components/Loading.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionsPage.tsx

Add (yet another) loading indicator.
Internal Notion: https://www.notion.so/wandbai/Replace-Material-design-components-dbb5f747b86d44efa5c55ecea2474810?pvs=4#1f656d27947346f3852d4684deeedb54
Before:
After:

feat: loading indicators on pages

---

weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx

We allow expansion of output fields, but didn't do grouping at all, resulting in broken expansions

chore(weave): Correct output expansion

---

weave/trace_server/clickhouse_trace_server_batched.py

chore(weave): Fixes wildcard name matching

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/traverse.ts

We were previously skipping past `_ref` and `_type` fields but we want to actually filter out all keys that are underscore prefixed, for example `_class_name` and `_bases` in the screenshots below.
Before:
After:

fix: hide underscore prefixed keys in object viewer

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseDataset.tsx

Seems that we should be using `id` instead of `index` to determine if we are viewing a row ref. Note that even with this fix I think row refs are broken.
Before:
After:

fix: dataset row use tab

---

weave-js/src/components/PagePanelComponents/Home/Browse2/CellValueString.tsx

Companion to https://github.com/wandb/weave/pull/1425 - make URLs hyperlinks in grid.
Before: 
After:

feat: url string values become hyperlinks in grid

---

weave/init_message.py
weave/urls.py
weave/weave_client.py

Shorten the links printed by the SDK by using new redirect page.
Before:
https://wandb.ai/jamie-rasmussen/2024-04-02_quickstart/weave/calls/f5676217-5279-4b47-b8c3-91456a79aef8?convertToPeek=true
After:
https://wandb.ai/jamie-rasmussen/2024-04-02_quickstart/r/call/e833f509-72a0-4abb-b74a-f26d60d16ece
The redirect takes you to a slightly different place than convertToPeek did too, with all versions of the op selected as the filter instead of the current version.

feat: shorter links output

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts

Fixes issue when swapping between Code views of different ops

chore(weave): Fix tsDataModelHooks to correctly revert to loading

---

weave/api.py
weave/trace/op.py
weave/trace/refs.py
weave/trace_sentry.py
weave/weave_init.py

https://weights-biases.sentry.io/issues/?project=4507019311251456
* Create a new global `global_trace_sentry` object that follows the same pattern as the `wandb` Sentry module
* Watches the major top level functions:
* weave.publish()
* weave.ref()
* Ref.get()
* Op.__call__()
* weave.init()
* After calling Weave.init we also configure the current context.
Caveats:
* Does not generally track everything - we have to manually wrap any function we want to "watch"

chore(weave): Implement Weave Client Sentry Tracking

---

weave-js/src/components/Alert.styles.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallDetails.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewerSection.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueView.tsx

Internal notion docs:
https://www.notion.so/wandbai/Trace-Detail-View-Handle-Ops-that-return-only-1-object-7f3b0c0c3bfa4bf4b00d4eab29061a1d?pvs=4
https://www.notion.so/wandbai/inputs-output-not-tracked-in-Nicholas-calls-possible-show-nones-in-UI-e33e491fcc9841448feeb3a5b914a5f5?pvs=4
Fixes a few issues:
- We were hiding input/output sections when values were null.
- When the output was a ref or list it was not expandable. 
- Declutter by not showing visibility icons when viewing a single simple value
- Better handling of some special cases like empty array output.
Before - inputs and output sections not shown because of nulls:
Before - can't expand output ref:
Before - empty array shown as empty string:
After - shows inputs and outputs even if null:
After - can expand output ref:
After - …

feat: improved handling of single value results

---

weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx

A short term change switching this column visibility alert from material components to our own Alert. Ran design by @adamwdraper  
Before: 
After:

chore: update visibility alert to use common alert component

---

weave-js/src/components/PagePanelComponents/Home/Browse3/OpCodeViewer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionPage.tsx

The intention is for the select widget to list versions in descending order (newest first) with the navigation showing the previous version on the left and subsequent version on the right by default. This presumably got broken when we switched out the backend APIs.
Internal notion: https://www.notion.so/wandbai/Version-sort-order-got-switched-in-diff-0170f9a22d7c4a3dbfaef32d7316c359?pvs=4

fix: op sort order got reversed

---

weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/context.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Links.tsx

Internal notion: https://www.notion.so/wandbai/Following-link-should-respect-trace-pane-open-heuristics-d3f2dd1fac24439a92a2fe4a60c1eb77?pvs=4
Don't attempt to preserve the shown/hidden state of the tracetree across calls, drive it by whether it is an evaluation or not. This also addresses the problem of the trace tree not being shown for a non-evaluation call when someone is coming from the SDK redirect link.

fix: simplify trace tree default open state

---

weave/api.py
weave/trace/op.py
weave/trace/refs.py
weave/weave_client.py
weave/weave_init.py

In the first iteration of sentry tracking, I instrumented a handful of user-facing APIs. However, this had the primary problem that user code defined in Ops were also getting tracked. Moreover, real errors thrown be the library to help users were getting caught too. Instead of getting fancy, I just moved the tracking to the weave_client layer. This is low-enough where we won't get effected by user-code and still likely captures the majority of true errors we should respond to.

chore(weave): Move all sentry tracking to just the weave client

---

weave-js/src/components/FancyPage/FancyPage.tsx
weave-js/src/components/FancyPage/FancyPageSidebar.tsx
weave-js/src/components/FancyPage/FancyPageSidebarSection.tsx
weave-js/src/components/FancyPage/index.tsx

Moving fancy sidebar code from App into Weave. Minor changes to fix deprecated imports and address the lack of a night mode beta feature hook.
This is part of unified side nav work.

chore: move FancyPage from app to Weave

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallTraceView.tsx

Internal Notion: https://www.notion.so/wandbai/Notes-on-Weaveflow-UX-674af4e66c6847248aeff7b93d87dc5c?pvs=4#a38299331f674872913c6ab7b5629d0f
Before - two call tree:
Before - single call tree:
After - two call tree:
After - single call tree:

chore: remove trace tree header

---

weave-js/src/components/Alert.tsx
weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx

before
After
i wonder if putting the boring cols above alert would look better

chore(weave): add border radius to table and alert

---

weave-js/src/components/PagePanelComponents/Home/Browse2/RefValue.tsx
weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx

Move the input grouping logic into a func addColGroup
Moves nested expansion logic into a func getGroupChildren
this cleanup and moving the logic into functions will help when we want to be able to infinitely drill down into refs
This uses the same logic for both inputs and outputs.
This fixes grouping being broken for expanding output refs, while still maintaining proper nesting
before 
after
maintains proper nesting

chore(weave): correctly expand output refs

---

weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse2/tableStats.ts

We had previously decided that when we are showing a single op version (either through filtering or there only is one) we would disable the automated column hiding.
However, we were in fact only hiding the UI that indicated columns had been hidden, and were still hiding the columns.

fix: incorrectly hiding columns for single op

---

weave-js/src/components/LoadingDots.tsx
weave-js/src/components/PagePanelComponents/Home/Browse2/RefValue.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx

Adds a more subtle animated loading indicator for use in table cells. PR uses this to fix the problem of version count column showing "O versions" while loading, which is misleading.
Internal notion: https://www.notion.so/wandbai/Versions-column-shouldn-t-show-0-versions-while-loading-7207cf774b0f4403818da853684eddc1?pvs=4

chore: better loading indicator for cells

---

weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionsPage.tsx

Use new dots loading indicator on op versions page and traces op version column.

chore: add loading indicators to op versions page

---

weave-js/src/components/PagePanelComponents/Home/Browse2/Browse2OpDefCode.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx

Remove a use of Semantic UI, show loading indicator instead of blank Monaco while loading.

chore: minor loader improvements

---

weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse2/WeaveEditors.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/traverse.ts

before 
after
shows description if exists

chore(weave): Hide name and description for CallDetails and ObjectViewer

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClient.ts

for responses > ~ 150MB the stream breaks, creating invalid JSON. Instead of failing, or returning partial results, we can continue the stream from the previous offset.

chore(weave): Fix streaming calls part 2: Huge responses

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueViewNumberTimestamp.tsx

Internal notion: https://www.notion.so/wandbai/int-value-timestamps-should-get-better-rendering-c2d6e171d6b24826806bc4eb630c6fca?pvs=4
Before:
After:

fix: don't commify created timestamp

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPage.tsx

Consolidates op filter and trace roots into a single selection. Removes all calls view

chore(weave): Remove trace roots only

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallDetails.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallOverview.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/Exceptions.tsx
weave/exception.py
weave/weave_client.py

Internal notion: https://www.notion.so/wandbai/Enable-full-stack-trace-logging-and-improve-UI-treatment-c514a45d530b442c916796a19358e223?pvs=4
Changes the Python client to log JSON structured exception information, serialized as a string value. The frontend will use this structured information to show a colorized traceback information instead of an Outputs section on the call tab.
For compatibility with previous releases, if the exception information is not JSON it will just display the string in the alert.
Before:
After:
After (dark mode):

feat: log and display error details

---

weave-js/src/core/ops/domain/run.ts

We are in the process of deprecating keySets in the HistoryKeyInfo data - they are no longer needed, so we are trying to remove them fully from core. I noticed that weave is also using history, so this removes the definition from the JS API. The sets data does not appear to be used in the JS code. 
Related question: should I be removing this from any python code as well?

chore(app): remove sets from historyKeyInfo definition

---

weave/flow/eval.py
weave/flow/obj.py
weave/flow/scorer.py
weave/flow/util.py
weave/table.py
weave/tests/test_evaluate.py
weave/trace/op_type.py

Evaluation updates
- add "trials" argument to Evaluation, to run over the same dataset multiple times
- automatically show model latencies
- show stderr for boolean scores
- change argument ordering of predict_and_score to self, model, example
- print progress
- add run_in_process_with_timeout
Breaking change:
- Changes the name of scorer columns when there are boolean outputs. This makes new evaluation calls incomparable with calls prior to this PR.

feat: eval updates

---

weave-js/src/components/PagePanelComponents/Home/Browse3/StyledAutocomplete.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/StyledTextField.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPage.tsx

Update op filter styling to better match our palette. Still things that could be improved like the button styling on clear / dropdown.
Part of internal Notion: https://www.notion.so/wandbai/Replace-Material-design-components-dbb5f747b86d44efa5c55ecea2474810?pvs=4
Before:
After:

chore: update styling of op filter

---

docs/docs/quickstart.md

Internal notion: https://www.notion.so/wandbai/Docs-clarify-python-version-req-a612f654efc74ead9d830ac09c070acf?pvs=4

chore: note Python version requirements in quickstart

---

weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimplePageLayout.tsx

Update the styling of the vertical resizer widget for the peek drawer.
Internal Notion: https://www.notion.so/wandbai/Replace-Material-design-components-dbb5f747b86d44efa5c55ecea2474810?pvs=4#033651ea931b4188be668eee45963186
Internal Figma: https://www.figma.com/file/27JVuBYWHbcAYc8WPb4HqA/Weaveflow-hifi?type=design&node-id=2911%3A305278&mode=design&t=JsjE0RCKScpAOud7-1
Before:
After:

chore: update styling of peek drawer resize widget

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClient.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts

Currently we fetch all versions of an object then let the client filter it down to the digest of interest. This is slower because it requires:
a) more data transmission
b) more data to scan.
With this approach we use a full-primary key lookup and directly fetch the data. My manual testing shows about a 2x speedup for these cases.

chore(weave): Use direct object version lookup

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx

With auto expanding objects, we don't want to do that for refs since it could be forever recursive.

chore(weave): Fix auto expansion with refs

---

weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/DataTableView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionsPage.tsx

We have been using the vanilla MUIDataGrid in many contexts and allowing the default options to persist. This has created 3 classes of snags:
1. UI "abilities" that don't make sense - for example, it is not necessary to manage columns for the object versions viewer
2. UI "abilities" that are purely broken: for example: sorting on ref expanded fields
3. UI "abilities" that are broken & hard to maintain moving forward: eg. filtering in the run table.
The point of this PR is to be a little bit aggressive in _disabling_ features. Cleaning this up leaves just the well-supported features so that we can intentionally enable features if/when we want to.
The only real "loss" here is I disable filtering on the Runs Table. I know we will want to bring this back, but i would prefer to do it in a …

chore(weave): Cleanup MUIDataGrid Options

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts

Some cleanup of old code that loaded everything into memory

chore(weave): Removes the last .find in favor of direct object lookups

---

wb_schema.gql
weave-js/src/components/DraggablePopups.tsx
weave-js/src/components/PagePanelComponents/Home/Browse2/CellValueString.tsx
weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse2/tableStats.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallSummary.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Links.tsx
weave-js/src/components/UserLink.tsx

Adds a User column to traces table. The widget works similarly to CellValueString, where you can hover over the in-page representation to get more information in a tooltip and you can click on the cell value to get a popup that can be repositioned, can have interactive links, etc.
@Yangyi-wandb @adamwdraper - could use design review.
In table cell shows avatar image (if available) and name.
Hovering over either image or name will show the link with hover color (this screenshot also showing night mode)
A tooltip appears when you hover with a larger photo and more information about the user.
Clicking makes the user info panel larger still, and the user properties become links you can interact with, e.g. to go to the profile page for that user or send them an email.
Commonly, all calls will …

feat: add User column with tooltip and popup

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueViewString.tsx

Fix Markdown rendering problem reported by @ash0ts in internal Slack: https://weightsandbiases.slack.com/archives/C01T8BLDHKP/p1712945416423219
We should only apply the CSS rule `white-space: break-spaces;` when format is Text and we are not collapsed.
Before:
After:

fix: markdown CSS

---

weave-js/src/components/PagePanelComponents/Home/Browse2/tableStats.ts

I introduced a bug in https://github.com/wandb/weave/pull/1518
RegExp.test will match the pattern anywhere in the string. I added `^` and `$` to only match the complete string because I didn't want e.g. `/opCategory/` to match a column like "mopCategory".
However, there was already a bug in the regular expression to begin with, i.e. `/input\.*/` - the intention was to match an "input." prefix, but this would actually match 0 or more literal periods because it was missing a period before the Kleene star.

fix: incorrect regexp in table stats computation

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionPage.tsx

Fixes data expansion in the viewer panels when the ref is a primitive

chore(weave): Fixes primitive expansion in object viewer / call viewer

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts

When toggling between ObjectVersion views (for example) the stale data was getting cached under the last key - resulting in incorrect data being shown to the user.

chore(weave): Fix incorrect cache storage

---

weave-js/src/components/PagePanelComponents/Home/Browse2/tableStats.ts

Internal slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1713202274928129
The "boring columns" feature didn't combine well with the "show all columns" feature. This makes them more independent, where "Show all" really just impacts the autohiding of mostly blank columns.

fix: show all doesn't show boring columns

---

weave-js/src/components/DraggablePopups.tsx

Internal slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1713306383328969
Material 4 was apparently more forgiving than v5, just putting a warning in dev console instead of throwing.
```
utils.js:1 Uncaught TypeError: Cannot read properties of null (reading 'scrollTop')
at reflow (utils.js:1:36)
at Grow.js:77:5
at Object.onEnter (Grow.js:71:9)
at Transition2.performEnter (Transition.js:271:16)
at Transition2.updateStatus (Transition.js:237:14)
at Transition2.componentDidMount (Transition.js:173:10)
at commitLifeCycles (react-dom.development.js:20663:24)
at commitLayoutEffects (react-dom.development.js:23426:7)
at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
```
```
Warning: …
```

fix: crash when clicking on cell

---

weave-js/src/components/DraggablePopups.tsx

chore: fix ref forwarding warning

---

weave-js/src/components/PagePanelComponents/Home/Browse3.tsx

Remove this little line - FYI @adamwdraper

chore: remove top border on peek drawer dragger

---

weave-js/src/components/PagePanelComponents/Home/Browse2/CellValueString.tsx

We trim whitespace before displaying a string value in the cell. This also trims it from the tooltip shown on hover. We should have a broader conversation about where to show less useful but sometimes important raw characters.
Before:
After:

chore: show trimmed instead of raw string in tooltip

---

weave-js/src/components/PagePanelComponents/Home/Browse3/SelectOpVersion.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPage.tsx

Use custom styling for code diff version select widget. Also fixes dropdown styling for op version select on traces page.
Before:
After:

chore: diff version select styling

---

weave-js/src/components/UserLink.tsx

Fix `Warning: validateDOMNesting(...): <th> cannot appear as a child of <div>.`

fix: dev console dom nesting warning

---

weave-js/src/components/LoadingDots.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionPage.tsx

Before, while loading version count ops would display nothing, objects would display a misleading `[0 versions]`.
This makes them consistent with each other and show the small "dots" loading indicator.

chore: show loading dots while counting versions

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Links.tsx

This makes those first grid columns consistent with the calls table and makes it easier to open the peek drawer.

chore: Op and Obj clickable area expands across grid cell

---

weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse2/tableStats.ts

Internal Notion: https://www.notion.so/wandbai/Expanding-calls-table-ref-brings-back-hidden-columns-f00c7b210f934d9a9a8fdc0fa28cdc07
Change visibility model to be controlled rather than setting initial state. This prevents us from losing user's changes when they manually hide a column but then expand a ref column.

fix: don't reset column visibility state on ref expansion

---

weave-js/src/components/PagePanelComponents/Home/Browse3/OpCodeViewerDiff.tsx

When one side of diff loads before the other it momentarily compares an empty string to actual contents making it look like the entire definition has changed. This shows the loading indicator until both sides are ready.

chore: show loading indicator until both sides load

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewerSection.tsx

Internal Notion: https://www.notion.so/wandbai/Expanded-view-resets-after-a-few-seconds-clicking-to-expand-particular-fields-8fc4e993dd934bc68cf8279dd074c3e4?pvs=4
When you have the auto-refresh option enabled it causes the object viewer component to lose its expanded state.

fix: ObjectViewer collapsing when autorefresh enabled

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClient.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts

Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1714067557396989
`callRead` can return a 403 with `{"detail":"Project not found"}`. Displaying an error is better than a crash. This doesn't address the related problem of why we are generating a bad link.
Before:
After:

fix: show error instead of crash on invalid project

---

weave-js/package.json
weave-js/yarn.lock

We don't need to declare @mui/x-data-grid if we have @mui/x-data-grid-pro

chore: remove @mui/x-data-grid

---

weave-js/src/components/CodeEditor.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewerSection.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-18500
When rendering inputs/outputs as JSON, allow the user to use the mouse wheel to scroll horizontally.
Also fixes the height calculation - the 2px for top & bottom border were not being taken into account when setting the height in CSS, but should be as we are using `box-sizing: border-box`. This was causing the unwanted display of a vertical scrollbar to move up and down 2px.

fix: using mouse wheel with code editor

---

.github/workflows/cla.yaml

Not sure why cla / CLAAssistant is still failing for Morgan after he commented in the PR. Trying this instead.

chore: add Morgan to CLA allow list

---

weave-js/src/components/PagePanelComponents/Home/Browse2/RunsTable.tsx

A user is experiencing a total crash of the calls page coming from errors in SmallRef. (We believe that problem is due to bad ref parsing when delimiters are used as part of the object name - will be handled separately.)
This PR adds an error boundary around more cells (some already had it), keeping the page a bit useful.

chore: wrap more calls grid cells in error boundaries

---

weave-js/src/components/PagePanelComponents/Home/Browse2/CellValueImage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueViewImage.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-18661
Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1715084757272079?thread_ts=1715016670.672359&cid=C03BSTEBD7F
Seems convenient / expected to close the image viewing lightbox when you click on the backdrop.

chore: close lightbox on backdrop click

---

weave-js/src/common/components/elements/ModifiedDropdown.tsx

The component `ModifiedDropdown` takes in prop `search` of type `boolean | ((options: DropdownItemProps[], value: string) => DropdownItemProps[])`. But `ModifiedDropdown` didn't handle passing in `search={false}` like the `semantic-ui-react` `Dropdown`, so all components using `ModifiedDropdown` had to be searchable. This fixes it so that `false` is correctly passed through to the `Dropdown` component.
Tested locally with the organization roles dropdown - it is no longer unnecessarily searchable.

chore(ui): Allow disabling search in ModifiedDropdown

---

weave-js/src/common/components/elements/ModifiedDropdown.tsx

We should avoid wasting time searching if the component isn't even searchable. This comes up because `doSearch` seems to be triggered onChange.
Tested locally with a `console.log` to verify that `doSearch` is no longer triggered when changing options if `search={false}`

chore(ui): Avoid searching if search is false in ModifiedDropdown

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseDataset.tsx

We used to use the row index as part of the generated variable name. After it got switched to a digest it is no longer nice to append that.
Before:
After:

chore: fix generated variable name for table row ref use

---

weave/trace_server/clickhouse_trace_server_migrator.py

Off by 1 error, resulting in `curr_version` always being behind by 1.  
credit @jamie-rasmussen with the fix
This branch:

chore(weave): fix migration down

---

weave/trace_server/migrations/001_init.down.sql

Literally of zero practical value but the 001 initial down migration is broken.

chore(weave): fix initial down migration

---

weave/trace_server/clickhouse_trace_server_batched.py

Introduces a new streaming method off of the batched server: `calls_query_stream` which is consumed in https://github.com/wandb/core/pull/21428. This method returns calls as an iterator, and importantly, fetches rows from clickhouse using a chunked stream. This means that we no longer need to load the entire results in memory to serve it to the user!

chore(weave): Implement end-to-end streaming of calls (weave)

---

weave/tests/test_pydantic.py
weave/trace/tests/test_vals.py
weave/trace/vals.py

Fixes 2 of the issues reported in: https://github.com/wandb/weave/issues/1584
1. Fixes error caused by using a PydanticV1 object as a property
2. Fixes the error caused by having no graph client, but retaining a reference to a trace object
Does not fix:
* This is almost certainly always going to break until google updates their ipython kernel to > 5.x.x. Workarounds: call weave.init after any cell that uses `await`. Or manually upgrade the kernel (which might have unintended consequences with google colab)
* This will need to be a followup

chore(weave): Fixes issue where graph client is closed but trace object still in memory

---

Dockerfile.test
requirements.test.txt
requirements.txt

Addresses the following CVEs:
```
tqdm>=4.66.3  # CVE 2024-34062
cryptography>=42.0.7  # CVE 2023-23931
Werkzeug>=3.0.3 # CVE 2024-34069
```

security(dev): upgrade python packages

---

.github/workflows/test.yaml
weave/conftest.py
weave/integrations/README.md
weave/integrations/litellm/litellm_test.py
weave/integrations/llamaindex/llamaindex_test.py
weave/integrations/mistral/mistral_test.py
weave/tests/test_client_trace.py
weave/tests/test_evaluate.py
weave/tests/test_weave_client.py
weave/trace_server/refs_internal.py

This adds ~30s to what is already a 6.5-7min test suite. I think it is worth it to keep clickhouse performing well.

chore(weave): Make Clickhouse Tests Always Run

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/utilities.ts
weave-js/src/react.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-18860
This one is a little confusing. The problem addressed here is that my change in https://github.com/wandb/weave/pull/1625 broke dataset rendering in the UI.
We have multiple functions that parse ref strings into objects. 
A table ref looks like: `weave:///entity/project/table/b8dfcb84974c481fd98fd9878e56be02ebef3e2da44becb59d1863cd643b83fe`
My understanding from Shawn is that the long identifier is its "digest" - a checksum of its rows.
The `parseRef` function puts that value in the `artifactVersion` field and sets `artifactName` to ''. When I rewrote parseRef to fix the user problems of slashes in artifact names I preserved that behavior.
The `refStringToRefDict` function was putting that value in the `artifactName` field and …

fix: table ref parsing

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/OpVersionsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/cgDataModelHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts

When we have a network error, the Operations and Objects pages show our "No objects yet" UI instead of indicating that there was an error. Network errors are common in development (fix-gov issue), and it can be confusing what has happened given that you are possibly switching between a prod and local datastore.
The traces page also has this issue, but saving that for a different PR (need to think about export button in header for example).  Also, @tssweeney could we get rid of cgDataModelHooks.ts entirely?
Misleading current behavior:
After this PR:

fix: when there is a network error, display error panel instead of no results

---

weave/tests/test_client_trace.py
weave/tests/test_weave_client.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/migrations/002_add_deleted_at.down.sql
weave/trace_server/migrations/002_add_deleted_at.up.sql
weave/trace_server/remote_http_trace_server.py
weave/trace_server/sqlite_trace_server.py
weave/trace_server/trace_server_interface.py
weave/weave_client.py

https://wandb.atlassian.net/browse/WB-18625
https://wandb.atlassian.net/browse/WB-18626
https://wandb.atlassian.net/browse/WB-18628
Adds: 
- `calls_delete` on the client
- `call.delete()` on the call object
- `calls_delete()` server method 
depends on https://github.com/wandb/core/pull/21555 for `wb_user_id` to appear on deletion rows.
(old pr: https://github.com/wandb/weave/pull/1655)

feat(weave): backend for deletion of calls

---

weave/tests/test_anonymous_ops.py
weave/tests/test_client_trace.py
weave/tests/test_op_versioning.py
weave/tests/test_weave_client.py
weave/trace/custom_objs.py
weave/trace/op.py
weave/trace/op_type.py
weave/trace/serialize.py
weave/trace/serializer.py
weave/weave_client.py

This enables users to register Serializers with Weave, like so:
```python
import faiss
from weave.trace import serializer
def save_instance(obj: faiss.Index, artifact, name: str) -> None:
with artifact.writeable_file_path(f"{name}.faissindex") as write_path:
faiss.write_index(obj, write_path)
def load_instance(
artifact,
name: str,
) -> faiss.Index:
return faiss.read_index(artifact.path(f"{name}.faissindex"))
serializer.register_serializer(faiss.Index, save_instance, load_instance)
```
After the `register_serializer` call, if the user tries to save an object that has a `faiss.Index` attribute, Weave will store the full FAISS index instead of just a __repr__ string.
This replaces the prior mechanism that relied on the older weave.Type. We were only relying on that for Op saving. The new …

feat: Pluggable object serialization

---

weave/integrations/llamaindex/llamaindex.py

Adds an extra catch on import, so that users with outdated llama_index packages or weird amalgamations of packages, dont get errored out, when we try to autopatch
I added a cta to update llama, since i figured thats better than silently failing, but down to silently fail if we dont want to bug users each time they to run something that doesnt relate to llama

chore(weave): Add another exception catch to the llama integration

---

weave-js/src/components/PagePanelComponents/Home/Browse3/context.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallOverview.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/OverflowMenu.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableQuery.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/cache.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/cgDataModelHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/context.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClient.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts

Single call deletion path. Also works for evaluations.
https://wandb.atlassian.net/browse/WB-18627
depends on: 
- https://github.com/wandb/core/pull/21555
- https://github.com/wandb/weave/pull/1673

feat(weave): frontend to allow deletion of single call

---

weave-js/package.json
weave-js/yarn.lock

Add MIT licensed emoji picker dependency. Will be used to select emojis in upcoming feedback PRs.
See 
https://github.com/ealush/emoji-picker-react
https://ealush.com/emoji-picker-react/

chore: add emoji picker library

---

weave-js/src/components/Form/TextField.tsx

This is a copy of the TextField component that is in core. Bringing it into the Weave repo so we can use it in the notes popup. Need to update core to use this copy in a separate PR so they don't get out of sync.

chore: bring TextField component over from core

---

weave-js/src/common/components/elements/ModifiedDropdown.tsx

Jira: https://wandb.atlassian.net/browse/WB-18777
Updates the `ModifiedDropdown` component to support hiding the input text prop so that we can display a JSX label as a dropdown option on its own. This will be used in the clone/ create report modal in an upcoming PR, https://github.com/wandb/core/pull/21754.
Before: 
After:
https://github.com/wandb/core/assets/126013019/e5c35eed-c45f-4e93-bbe1-05f18f15ede6

chore(app): add hide text option to ModifiedDropdown

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableColumns.tsx

The CallsTable defaults to sorting by CreatedAt DESC, however the MUI Data grid defaults to cycling through ASC -> DESC -> Null when clicking the sort arrow. So, then in the "DESC" (default) state, clicking the arrow changes to Null, which then reverts to DESC, which feels like nothing happens. This change removes NULL from the cycle for this column, making it work again

chore(weave): Fix sorting by created at column

---

weave/trace_server/clickhouse_trace_server_batched.py

We were scanning the whole clickhouse tables for object, file, and table reads, all the time.
Fix so that we only scan the subset of those tables that we need for the specific project referenced in the user query.
This should speed up W&B production reads from about 3s for object_versions, down to just 20ms in many cases (2 orders of magnitude faster). We should get similar improvements for files and table reads. as well. 
```
#
#
#
#
```

perf: Fix full table scans for objects, files, tables

---

weave-js/src/components/CopyableText.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseDataset.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseModel.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseObject.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseOp.tsx
weave-js/src/util/refs.ts

Internal Jira: https://wandb.atlassian.net/browse/WB-19087
Multiple people have reported not realizing that the `<ref_uri>` placeholder  in code examples is replaced with the full ref string in the copied text.
This updates replaces that placeholder with an abridged version of the ref string and updates the tooltip content to indicate that the unabridged string is copied.
Before:
After:

chore: make it clearer that unabridged text is copied in use tabs

---

weave/trace_server/clickhouse_trace_server_batched.py

This PR implements predicate pushdown for the primary filter clause (not yet implemented for the dynamic mongo queries). It was raised that our filter conditions are being applied after grouping, which is certainly not as efficient as applying the filter pre-grouped (since applying after grouping requires operating on far more rows than needed). In this PR we do the following:
1. Refactor many symbols/params from `conditions` to `having_conditions` to specifically mean the conditions applied after the group by (in the `having` clause of the query)
2. Modify the query builder functions to accept `start_event_conditions` and `end_event_conditions` which can be used to apply filters _before_ the aggregation. If these conditions are supplied, an inner query is executed which generates an `id …

chore(weave): Implement Predicate Pushdown for Calls

---

weave/trace_server/clickhouse_trace_server_batched.py

I just made some changes to push predicates down to an inner id clause. However, after analyzing real traffic, I realized that adding the project filter deeper down is a pretty big improvement

chore(weave): Add project clause to inner ID filter

---

weave/trace_server/clickhouse_trace_server_batched.py

Builds off of https://github.com/wandb/weave/pull/1715 ... another step in making queries faster! In this PR, we take advantage of the case where there are no group-by conditions. In such cases we can push the sort/limit down into an inner-clause.
This PR does 1 thing:
1. Under the condition that there are 0 `having_conditions` and we only need to sort based on data in 1 event type or the other (start or end), then we can use a fast path that pushes the sort condition down to the inner clause, avoiding extra aggregations!

chore(weave): Add a fast path for simple queries

---

requirements.test.txt
weave/tests/test_client_feedback.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/emoji_util.py
weave/trace_server/errors.py
weave/trace_server/feedback.py
weave/trace_server/orm.py
weave/trace_server/remote_http_trace_server.py
weave/trace_server/sqlite_trace_server.py
weave/trace_server/tests/test_emoji_util.py
weave/trace_server/tests/test_orm.py
weave/trace_server/trace_server_interface.py

Internal Jira: https://wandb.atlassian.net/browse/WB-18697
Adds Trace Server APIs for create / query / purge. These APIs are based on a new "ORM" layer that helps us have more similar code between ClickHouse and SQLite.
Emoji utilities were previously reviewed in core, bringing them over to this repo to correspond to change in where validation logic lives.
@tssweeney - there is obviously a bunch of code duplication here with the mongo processing in Calls that we should figure out what to do about.

feat: add feedback trace server APIs

---

weave-js/src/react.test.ts
weave-js/src/react.tsx

hotfix for url encoding differences between safari and chrome. spaces are allowed in ref names and get set to `%20` in safari, which then breaks ref parsing...
https://wandb.atlassian.net/browse/WB-19213

fix(weave): decode url before parsing weave ref 

---

requirements.txt

I moved the emoji shortcode augmentation from the HTTP layer to the storage layer. It is no longer only used for ClickHouse, but also for our sqlite backend implementation. Although the sqlite implementation is only used in tests today, it gets imported and so the dependency needs to be there.
Traceback from @davidwallacejackson 
```
File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 111, in get_config_from_filename
spec.loader.exec_module(mod)
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/weave-root/gunicorn_config.py", line 1, in <module>
from middleware import patch_tracer_to_send_traces_to_streamtable
File …
```

chore: add emoji to requirements.txt

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableColumns.tsx

https://wandb.atlassian.net/browse/WB-19203
This pr: 
- adds getter methods to datagrid for csv export. we use renderCell methods that prevent clean export. 
- dump objects and lists to string using `JSON.stringify`, otherwise lists mess up the columns of export, and objects just show up as `[object Object]`
Before:
After:

fix(weave): format values for csv export in datagrid

---

weave/trace_server/orm.py
weave/trace_server/tests/test_orm.py

This is an updated version of the ORM code that previously went in as part of reverted PR https://github.com/wandb/weave/pull/1718
The previous version of this class used ClickHouse classes like QuerySummary and Client. This created an unfortunate dependency chain:
* SqliteTraceServer depended on the TABLE_FEEDBACK definition for table create/drop/query.
* TABLE_FEEDBACK was implemented using this ORM layer
* This ORM layer depended on the ClickHouse library.
This is already undesirable as we don't want to introduce a dependency on the ClickHouse library to the Weave client library.
But there was a bigger problem, which is that the WBAuthMiddleware depends on importing weave, which in turn depends on SqliteTraceServer. So through this unfortunate dependency chain (which we should probably …

chore: add ORM with no clickhouse dependency

---

weave-js/src/components/UserLink.tsx

Tiny CSS adjustment to user link to make it align with small ref better and be less crowded.
Before:
After:

chore: add small margin in UserLink

---

weave/tests/test_client_feedback.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/feedback.py
weave/trace_server/remote_http_trace_server.py
weave/trace_server/sqlite_trace_server.py
weave/trace_server/trace_server_interface.py

This is an updated version of the trace server APIs code that previously went in as part of reverted PR https://github.com/wandb/weave/pull/1718
The changes are mostly just to use the new ORM library methods.

feat: Adding trace server feedback APIs using updated ORM

---

weave/tests/test_client_feedback.py
weave/tests/test_weave_client.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/feedback.py
weave/trace_server/sqlite_trace_server.py
weave/trace_server/trace_server_interface.py
weave/trace_server/trace_server_interface_util.py

We introduced a violation of inheritance rules with `TraceServerInterfacePostAuth`. We added this because the interface definition for the HTTP server differs slightly from that of the internal trace storage layers (namely the inclusion of wb_user_id which is populated by the server - and therefore not required).
This was problematic for a few reasons:
1. Most importantly: it made it so that `RemoteHTTPTraceServer` was no longer compatible with the other servers. This is not a good place to be in.
2. It violates inheritance rules
3. It introduces additional complexity (not that big of a deal
To remedy this, I:
1. Removed the `TraceServerInterfacePostAuth`
2. Added runtime checks to assert the presence of the required field in the implementations which require it.

chore(weave): Simplify TraceServerInterface definition and fix inheritance 

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallSummary.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallTraceView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CostTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CustomGridTreeDataGroupingCell.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/TraceUsageStats.tsx
weave-js/src/util/llmTokenCosts.ts

chore(weave): Add cost table to summary tab

---

weave/tests/test_weave_client.py
weave/trace/op.py

calls can be "named" with: 
```
weave.weave_client.set_call_display_name(call, "new name")
call = weave.weave_client.calls()[0]
call.set_display_name("new name")
```

chore(weave): remove call naming from op kwarg

---

weave/tests/test_client_trace.py
weave/trace_server/remote_http_trace_server.py
weave/trace_server/sqlite_trace_server.py
weave/trace_server/trace_server_interface.py

Currently, only the `ClickhouseTraceServerBatched` implements the call query stream method. However, in my crusade to align `RemoteHTTPTraceServer` and `SQLiteTraceServer` these both need to properly implement this API.
As an added bonus, we now get call streaming at the python client level!
And more practically, this is one step closer to being able to generalize and extract the converter components

chore(weave): Add Call Query Stream to the Interface

---

weave/tests/test_client_feedback.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/orm.py
weave/trace_server/sqlite_trace_server.py

The ORM layer is supposed to handle the dump/load of json columns from a dict to a string column in the db. I had added a separate JSON dump to string when I added a size limit check on the payload, but I should have still been passing in the payload as a dict. Added a test for this.

chore: fix double json encoding of feedback payload

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableColumnsUtil.ts

Internal Jira: https://wandb.atlassian.net/browse/WB-19326
We weren't creating an output column for ops that just return e.g. a string.
Before:
After:

fix: output column was missing for single values

---

weave-js/src/common/util/time.ts

Jira Reference:
https://wandb.atlassian.net/browse/WB-19359
Support team will be reducing support hours for non paying users to Tuesday, Wednesday, Thursday
This PR enhances the getTimeSegmentsInTimeZone function by including the day of the week in its return value to use as part of conditional logic in core
Change:
Definition of New Types:
WeekTimeSegments: An extended type of TimeSegments that also includes the day property.
Function Update:
The getTimeSegmentsInTimeZone function is updated to return an object of type WeekTimeSegments, which includes the time segments (hour, minute, second) and now the day of the week.

chore(app): Enhance getTimeSegmentsInTimeZone Function to Include Day Property

---

weave-js/src/components/PagePanelComponents/Home/Browse3.tsx

Internal Jira: https://wandb.atlassian.net/issues/WB-18752
In Safari if you horizontally overscroll our pages you get into a bad state where the entire page is positioned off screen.
Setting the peek drawer to display: none when closed seems to fix it in FeatureBee. (Local debugging in Safari has challenges we should address at some point, same kind of thing the authtool helps with in Chrome I'm guessing.)
Example:

fix: safari scrolling issue

---

weave/feedback.py
weave/tests/test_feedback.py

When doing the RefFeedbackQuery refactor I accidentally dropped the method that allows you to add custom key/value JSON as feedback. Added it in with a test.

chore: custom feedback API got lost in refactor

---

weave/tests/test_weave_client.py

This test seems to flake periodically in CI.  I haven't been able to reproduce, but based on the error message I think this might be a case where the object doesn't de-ref as expected.

chore(weave): Mark test as flaky

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/context.tsx

This method was removed in https://github.com/wandb/weave/pull/1694/files because it was unused at the time. Adding it back in because we will need it for upcoming core UI changes where we conditionalize things like the default quickstart choice based on whether the project has published Weave data.

chore: add useProjectHasTraceServerData method back

---

weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/FeedbackGrid.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/FeedbackGridInner.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/FeedbackTypeChip.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClient.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts

Add a tab to the Call details page for displaying feedback.
Feedback:
No feedback case:

feat: add feedback tab to call details page

---

pyproject.toml

Enables support for preview rules, see https://docs.astral.sh/ruff/preview/
Also turns on a specific rule that is not currently violated: https://docs.astral.sh/ruff/rules/too-many-newlines-at-end-of-file/

chore: enable Ruff W391 too-many-newlines-at-end-of-file

---

weave-js/src/core/util/constants.ts

In reports, we can and should support runsets with more than 50 runs selected.  This is important for leaderboard-style reports such as [this](https://api.wandb.ai/links/wandb-japan/xm2pju5m)

feat(weave): Increase maximum number of runs to resolve from 50 to 100

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/TraceUsageStats.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableColumns.tsx

Internal Slack: https://weightsandbiases.slack.com/archives/C01T8BLDHKP/p1718913564028869
Internal Jira: https://wandb.atlassian.net/browse/WB-19396
Exports the raw numeric values for token count and cost columns.

fix: include token counts and costs in CSV export

---

weave-js/src/components/CopyableText.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/TabUseCall.tsx

Adds a "Use" tab with copyable examples to calls, making them more consistent with ops and objects.
We should hold off deploying this until we've released a Weave Python SDK with feedback APIs.
The CopyableText component was updated to top align the copy icon (instead of center align) for multi-line text which looked better to me.

chore: add Use tab to call details

---

weave-js/src/components/PagePanelComponents/Home/Browse3/OpCodeViewerDiff.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-19432
Before, could get into this state:

fix: diff editor version selector header could overlap

---

weave-js/src/components/PagePanelComponents/Home/Browse3.tsx

In our recent sidebar refactor we accidentally introduced a regression where the "X Versions" link on objects no longer worked - resulting in the all objects view. This PR puts back functionality that was accidentally removed.
https://github.com/wandb/weave/assets/2142768/6b060626-e153-4e42-aa03-253c7f5a8ee4

chore(weave): Fix Object Versions Link

---

weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/ReactionsLoaded.tsx

Internal Slack: https://weightsandbiases.slack.com/archives/C05DURZNT41/p1719439840146599
Before: 
After:

chore: hide scrollbars in feedback cell

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/objectViewerUtilities.ts

Internal Jira: https://wandb.atlassian.net/browse/WB-19507
Before:
After:

feat: render anthropic input images as thumbnails

---

docs/docs/guides/integrations/index.md
docs/sidebars.ts

docs(weave): Add llama docs to sidebar

---

weave/weave_init.py

Fix an issue where reseting client caused a crash. This would occur in streamlit for example:
```
2024-07-01 21:46:39.095 Uncaught app exception
File "/Users/adamdraper/.pyenv/versions/weave-starter/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 567, in _run_script
self._session_state.on_script_will_rerun(
File "/Users/adamdraper/.pyenv/versions/weave-starter/lib/python3.11/site-packages/streamlit/runtime/state/safe_session_state.py", line 66, in on_script_will_rerun
self._state.on_script_will_rerun(latest_widget_states)
File "/Users/adamdraper/.pyenv/versions/weave-starter/lib/python3.11/site-packages/streamlit/runtime/state/session_state.py", line 514, in on_script_will_rerun
self._call_callbacks()
File …
```

fix: deinit crash

---

weave/trace/ipython.py
weave/trace/op_type.py

Resolves:
- https://wandb.atlassian.net/browse/WB-19574
This PR adds support for saving classes that are created inside an interactive environment.  
Previously, we would raise an error like:
```
TypeError: Source for <class '__main__.MyClass'> not found
```
This seems to be a common issue raised in ipython:
- https://github.com/ipython/ipython/issues/11249
- https://bugs.python.org/issue33826
- https://stackoverflow.com/questions/51566497/getting-the-source-of-an-object-defined-in-a-jupyter-notebook/65806216#65806216
The solution suggested in the threads above will not work with classes that don't have methods.  The approach here works for all classes, which is helpful because `BaseModel`s can be used like plain structs (with no methods)
TODO: This PR needs a nb test

fix(weave): Add support for class saving in ipython

---

weave-js/src/util/llmTokenCosts.ts

we were not properly checking if the model was valid, and defaulting for all strings

chore(weave): Fix cost calc model compare

---

weave/flow/dataset.py
weave/flow/obj.py
weave/refs.py
weave/serve_fastapi.py
weave/tests/test_client_trace.py
weave/trace/isinstance.py
weave/trace/tests/test_vals.py
weave/trace/vals.py
weave/weave_client.py

This PR updates naming:
- `TraceObject` -> `WeaveObject`
- `TraceTable` -> `WeaveTable`
- `TraceList` -> `WeaveList`
- `TraceDict` -> `WeaveDict`
And corrects spelling:
- `Tracable` -> `Traceable`

chore(weave): Rename Trace* objs to Weave* (e.g. TraceList -> WeaveList)

---

weave-js/src/react.test.ts
weave-js/src/react.tsx

See internal Notion doc: https://www.notion.so/wandbai/Team-naming-issue-792e4ae4d0014a178a9369a6137f365d?pvs=4

fix: allow spaces and other chars in entity names

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Links.tsx

chore: fixes call link spacing

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ExampleCompareSection/ExampleCompareSection.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ScorecardSection/ScorecardSection.tsx

Example: https://app.wandb.test/l2k2/hellaswag/weave/compare-evaluations?evaluationCallIds=%5B%22ff014327-f0b8-4959-a828-2a617b2969a4%22%2C%22403b9bd6-eda4-4908-b79d-06b68cac33c0%22%5D
When comparisons share the same model version, the scorecard was not showing different values

chore(weave): EvalCompare: Fixes issues when models are same version in scorecard section

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallOverview.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/OverflowMenu.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/EditableCallName.tsx

https://wandb.atlassian.net/browse/WB-19669
Allow a button in the overflow menu to control the editable field in the call overview page.

chore(weave): add rename button to overflow menu

---

docs/docs/guides/integrations/google-gemini.md
docs/docs/guides/integrations/local_models.md
docs/docs/guides/integrations/openrouter.md
docs/docs/guides/integrations/together_ai.md
docs/sidebars.ts

Given our native support of OpenAI SDK and many companies supporting that format by default, as per slack discussion, added a few pages that outline how Weave can be utilized with those companies even before we have a native integration with their pytho clients.
Also added a local models category, with links to the most popular local model runners with support for OpenAI SDK
(Attempt number 2, PR #1909 failed on CLA because I had a misconfigured git email on my machine) 
Signed-off-by: Alex Volkov <altryne@gmail.com>

chore(docs): Added gemini, together, openrouter and local models integrations to docs

---

weave-js/src/components/DraggablePopups.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsCustomColumnMenu.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/ManageColumnsButton.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/types.ts

For the Calls grid, replace the built-in column management popup with our own. This addresses several issues:
* Action to open dialog was buried in the column overflow menu, hard to discover
* State is not kept in the URL, which is a pain for sharing with others or if you spent a lot of time customizing to get the view you want
* Popup is not movable and obscures the grid content underneath
* Does not use W&B styling so inconsistent with rest of app.
Before:
After:

feat: new column management popup

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx

* Limits evaluation selection to 5 evaluations
* Shows help tooltip when disabled

chore: EvalCompare: Limit comparison to 5 and show help tooltip

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/CompareEvaluationsPage.tsx

Bug fix: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1720626468726109
Fixes issue where the filter condition was on evals, not models

fix: Show filters when there are 2 evals, not just two models

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallTraceView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooksEvaluationComparison.ts

Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1720659743682469

fix: UI crash when example is not a ref string

---

requirements.dev.txt

Currently, when trying to fix the lint using `ruff`, we get the following error:
```
error: TOML parse error at line 66, column 12
|
66 | [tool.ruff.lint]
|            ^^^^
unknown field `lint`, expected one of `allowed-confusables`, `builtins`, `cache-dir`, `dummy-variable-rgx`, `exclude`, `extend`, `extend-exclude`, `extend-include`, `extend-ignore`, `extend-select`, `extend-fixable`, `extend-unfixable`, `external`, `fix`, `fix-only`, `fixable`, `format`, `force-exclude`, `ignore`, `ignore-init-module-imports`, `include`, `line-length`, `tab-size`, `required-version`, `respect-gitignore`, `select`, `show-source`, `show-fixes`, `src`, `namespace-packages`, `target-version`, `task-tags`, `typing-modules`, `unfixable`, `flake8-annotations`, `flake8-bandit`, `flake8-bugbear`, …
```

chore: update Ruff version

---

weave-js/src/components/DraggablePopups.tsx
weave-js/src/components/PagePanelComponents/Home/Browse2/CellValueString.tsx
weave-js/src/components/UserLink.tsx

For the user and string popups, it was not obvious that the header could be grabbed and dragged to reposition the popup. This adds the same cursor treatment that was added for the column management popup in https://github.com/wandb/weave/pull/1881
Recommend viewing diff with "Hide whitespace"
Before:
After:

chore: add grab cursor to more popups

---

weave-js/src/components/PagePanelComponents/Home/Browse3.tsx

If filters are not specified, `query.filter` will be undefined and JSON parsing will fail, logging an error.

fix: error in console on objects page

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx

Internal slack thread: https://weightsandbiases.slack.com/archives/C01T8BLDHKP/p1720725155135389
Having multiple header rows doesn't work well with some external tools.
Before:
After:

fix: use single row for exported CSV header

---

weave/environment.py
weave/legacy/wandb_api.py
weave/trace_server/environment.py
weave/trace_server/remote_http_trace_server.py
weave/weave_init.py

feat(weave): Improved ergonomics for interacting with private weave instances

---

weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/grid/sort.test.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/grid/sort.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-19839
Store the calls grid column sort state in the URL rather than in local component state. This is another step towards having URLs that a user can bookmark or share and not have to spend a lot of time re-configuring.

feat: store calls grid sort state in URL

---

weave/flow/eval.py
weave/flow/obj.py
weave/flow/scorer.py
weave/integrations/anthropic/anthropic_test.py
weave/integrations/litellm/litellm_test.py
weave/storage.py
weave/tests/test_client_trace.py
weave/tests/test_pydantic.py
weave/tests/test_refs.py
weave/tests/test_weave_client.py
weave/trace/box.py
weave/trace/custom_objs.py
weave/trace/op.py
weave/trace/serialize.py
weave/trace/tests/test_op_return_forms.py
weave/trace/vals.py
weave/weave_client.py

resolves:
- https://wandb.atlassian.net/browse/WB-19587

fix(weave): Update box impl to use python None and bool instead of BoxedNone and BoxedBool

---

weave/__init__.py
weave/tests/test_client_trace.py
weave/trace/util.py

Resolves:
- https://wandb.atlassian.net/browse/WB-19692
This PR adds `concurrent.futures.ThreadPoolExecutor` and `threading.Thread` variants that behave like the original and also copy context to each of the threads.  This should resolve issues users have where the context is not copied by default.

feat(weave): Add threading helpers to simplify thread usage

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/OverflowMenu.tsx

Internal Jira:
https://wandb.atlassian.net/browse/WB-19877
https://wandb.atlassian.net/browse/WB-19878
Fix two problems with call deletion. Bad project_id getting sent to API and dev console key warning.
Before:

fix: call deletion

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/ecpTypes.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ComparisonDefinitionSection/EvaluationDefinition.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooksEvaluationComparison.ts

This PR implements some simple improvements to the loading order and grouping of the eval compare page to squeeze out some low-hanging fruit.
Current Waterfall:
1. `/calls/stream_query`: for N evaluation calls
2. N Parallel Requests:
* N x `/obj/read`: for unique Evaluation Objects
3. N Parallel Requests:
* N x `/obj/read`: for unique Model Objects
4. `/obj/read`: for Baseline dataset table digest
5. `/table/query/`: for table rows data
6. `/calls/stream_query`: for all calls within the N traces
New Waterfall:
1. `/calls/stream_query`: for N evaluation calls
2. (Non Blocking) `/calls/stream_query`: for all calls within the N traces
3. `/refs/read_batch`: for N unique Evaluation Objects AND N unique Model Objects
4. `/refs/read_batch`: for Baseline dataset table digest
5. `/table/query/`: …

chore: Implement a more parallel loading scheme for the eval page

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/sections/ExampleFilterSection/ExampleFilterSection.tsx

chore: Fix Compare Page "Dimension" Label Overflowing

---

weave/integrations/anthropic/anthropic_sdk.py
weave/integrations/openai/openai_sdk.py
weave/tests/test_op_call_method.py
weave/tests/test_op_decorator_behaviour.py
weave/trace/op.py

- https://wandb.atlassian.net/browse/WB-19805
- https://wandb.atlassian.net/browse/WB-19853
This PR changes the `call` special func to:
1. Return both the result and call
2. Never raise -- any exceptions are captured in the `call` and the result is `None`.
NB:
1. I'm slightly concerned about the "return async wrapper" pattern we have because it may introduce complexity when we try to cover other types of funcs like generators, async generators, etc.
2. For now, this is OK.

fix(weave): Don't raise when calling `call` special func, and return both res and `Call` obj

---

weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/grid/pagination.test.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/grid/pagination.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-19879
This is the same type of change as https://github.com/wandb/weave/pull/1956 but for the call grid's pagination state. This is another step towards having URLs that a user can bookmark or share.
Since the state in question is just two integers (one of which we don't let users customize today) I just store each of them in their own query parameter rather than storing a single parameter with a serialized JSON object. This makes the URL a little friendlier.

feat: store pagination model in URL

---

weave/tests/test_weave_client.py
weave/trace_server/clickhouse_trace_server_batched.py

This PR:
- fixes a bug that uses an unbound reference to `ref` which prevents cross project resolution [@tssweeney]
TODO:

fix: multi-ref and project-mismatch trace server

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallTraceView.tsx

Fixes this warning seen on startup
```
│[app.wandb] 1:33:58 PM [vite] warning: The "??" operator here will always return the left operand                                                                                             
│[app.wandb] 334|      }                                                                                                                                                                       
│[app.wandb] 335|      if (parentCall) {                                                                                                                                                       
│[app.wandb] 336|        const siblingCount = childCallLookup[parentCall.callId]?.length - 1 ?? 0; …
```

fix: incorrect use of ?? in call tree

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableQuery.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts

https://wandb.atlassian.net/browse/WB-19881
This pr: 
- registers the `useCallsStats` hook as a listener to the delete function
TODO(?): this shows the splash page but also the column headers...

fix: refetch call query stats on deletion

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/OverflowMenu.tsx
weave-js/src/integrations/analytics/userEvents.ts

https://wandb.atlassian.net/browse/WB-19880
This PR: 
- simplifies the error message
- only set the error when catching from `Promise.all`
- only close the modal on successful deletion, otherwise display error

fix: simplify delete error and show in modal

---

weave/flow/eval.py
weave/tests/test_evaluations.py

At some point in our past we auto-oped the model passed to Evaluation.evaluate. However, probably for good reason, we stopped such a practice. This PR implements a check to verify such cases and inform the user on how to proceed. A test is provided as well. In the case we want to loosen this requirement, the test for that is available too.

chore: Raise on Evaluation Non-Op Models

---

weave-js/src/core/ops/domain/artifactVersion.ts
weave-js/src/core/ops/domain/gql.ts
weave/legacy/ops_domain/artifact_version_ops.py

[WB-19874](https://wandb.atlassian.net/browse/WB-19874)
[WB-19874]: https://wandb.atlassian.net/browse/WB-19874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Should only be merged after this is deployed: https://github.com/wandb/core/pull/22735
Exposes the artifact attribute that tells us whether it is linked to a collection in the org registry. This is needed to add additional warnings which deleting artifacts in a run or via the artifacts UI
Tested the op by temporarily adding it to the `PanelArtifactMembershipOverview/index.tsx` file and logging the value in the console:
```
artifactIsLinkedToRegistry: opArtifactVersionIsLinkedToGlobalRegistry({
artifactVersion: artifactVersionNode,
}),
```

chore(artifacts): new op to check if artifact is linked to a collection in the global registry

---

weave/trace_server/external_to_internal_trace_server_adapter.py

I am working on uptaking the generalized converter in the prod server and my testing highlighted these issues.
Fixes: query_stream and query_stats user conversion

chore: Fixes  int/ext conversion logic before pickup in prod

---

weave/flow/eval.py
weave/tests/test_evaluations.py

For some reason op serialization was not happy with the custom exception. Should solve correctly, but for now this works

chore: Fix evaluation serialization in notebooks

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableColumns.tsx

We recently added system info to the call payload - but it was taking up the most important real-estate!
Before:
After:

chore: Hides `attributes.weave` from the calls table

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts

depends on: https://github.com/wandb/weave/pull/1991
brings back this beauty:

chore: callres.call can now be none

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
weave/tests/test_client_trace.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/external_to_internal_trace_server_adapter.py
weave/trace_server/sqlite_trace_server.py
weave/trace_server/trace_server_interface.py

https://wandb.atlassian.net/browse/WB-19932
This pr: 
- now allows for returning an empty Call in `CallReadRes`
- catch `StopIteration` to prevent returning 500s when the call ID doesn't exist
Test w/o change:

fix: catch stopIteration when call doesn't exist in CallRead

---

weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableColumns.tsx

Alternate approach to https://github.com/wandb/weave/pull/1988 - instead of removing the columns we make them available but hidden by default.

chore: make attributes hidden but available

---

weave/api.py

https://wandb.atlassian.net/browse/WB-19852
This pr: 
- inspects `objectRef` on publish, if `OpRef`, uses the Op link. 
Before: 
```bash
📦 Published to https://wandb.ai/griffin_wb/project1/weave/objects/func/versions/dEqDuj2UrumkzuLVUyYbE40jWRvwjLJ28v9KbRXYWok
```
This PR:
```bash
📦 Published to https://wandb.ai/griffin_wb/project1/weave/ops/func/versions/dEqDuj2UrumkzuLVUyYbE40jWRvwjLJ28v9KbRXYWok
```

chore: print out op url instead of object when OpRef

---

weave/tests/test_cli.py

Adds a basic test for the Weave CLI (to catch the issue seen in https://github.com/wandb/weave/pull/2001)

chore: add a basic test for CLI

---

weave/trace_server/remote_http_trace_server.py
weave/trace_server/requests.py
weave/trace_server/tests/test_remote_http_trace_server.py

Adds support for logging HTTP requests/responses with a small amount of metadata. This is enabled with  `WEAVE_DEBUG_HTTP=1` 
Here we see a multipart form request and formatting of JSON request/response bodies.
A Gateway timeout with a retry.

feat: an environment variable turns on HTTP logging for debugging

---

weave/tests/test_weave_client.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/external_to_internal_trace_server_adapter.py
weave/trace_server/remote_http_trace_server.py
weave/trace_server/sqlite_trace_server.py
weave/trace_server/trace_server_interface.py

This PR introduces a new method / endpoint to our universal interface that allows users to update Table rows via the API: `table_update(self, req: TableUpdateReq) -> TableUpdateRes`.
I was originally motivated for performance / bug reasons (see discussion below), but this is actually an important API for some other features on the horizon, namely:
1. Python SDK Dataset Mutations
2. UI Client Dataset Mutations (think "Add to Dataset")
Ok, now onto the original motivating factor:
Evaluations with large datasets / model predictions fail when getting to the summary step. This is because the input to summary is some multiple of the dataset size, often blowing the limit we have set for our servers. As a practical workaround, we can represent the summary input as a table …

chore: Add table update methods

---

weave/legacy/wandb_api.py
weave/weave_init.py

This makes `default_entity_name` in `WandbApi` have the same logic as the version of it in `WandbApiAsync`, where a `gql.transport.exceptions.TransportQueryError` will result in None being returned rather than an `AttributeError` being raised.
You will still get a `WeaveWandbAuthenticationException` stack trace which isn't the prettiest, but it will at least not also log the `AttributeError` stack trace.
I encountered this while manually putting an incorrect value in `.netrc` as part of other debugging.

fix: slightly better auth error

---

weave-js/src/components/Tag/Pill.tsx
weave-js/src/components/Tag/Tag.tsx

https://wandb.atlassian.net/browse/WB-19989
Currently our Tags all have hover state styles (darker on hover). Meanwhile Pills never have hover styles.
I got feedback from design that Tags and Pills should both have hover states, but only if the element is interactive (e.g. is removable or triggers a tooltip). I added an `isInteractive` prop to `Tag` and `Pill` components so that hover styles are only applied if the element is explicitly marked as interactive.
Testing: in storybook
- RemovableTag always has hover styles
- Tag has hover styles only if `isInteractive`
- Pill has hover styles only if `isInteractive`
https://github.com/user-attachments/assets/4735489b-b367-47f2-a5de-5eaba1e19d9f

feat(ui): Add isInteractive prop for Tags and Pills

---

weave/conftest.py
weave/tests/test_weave_client.py
weave/trace_server/remote_http_trace_server.py

In our server layer, we have a number of endpoints which we would expect to have large request or response payloads. In most cases we have solved that with streaming, batching, or pagination. However, with `table/create` it is still all-or-nothing. This means we have a practical limit (the network configured limit or the memory limit of the container) on the size of tables (which is the underlying data structure for Datasets). This PR augments the writer flow such that we create a binary partition of the dataset rows when they exceed some configurable limit, breaking the creation into a create + log_2(N) updates. This is possible thanks to the new Update api and the fact that a updates can be serialized!

fix: Allow > 32MB datasets

---

weave/legacy/ops_domain/wb_util.py

It seems that in the last 24 hours, we started getting a failing integration test (example: https://app.circleci.com/pipelines/github/wandb/core/144110/workflows/f2b58f88-78bd-40a4-b565-9968904b302e/jobs/3671133/tests) constantly in core. Looking at the details, it appears that the run summary endpoint is returning a flattened `_wandb` subkey payload, resulting in keys like `_wandb.runtime`. In the integration tests we test a related feature that checks summary keys, and we are now failing due to this new key being in the list. However, it is not happening with local-integration-tests, so that makes me think it might have to do with some RunsV2 stuff that doesn't run in local? Honestly, i don't quite know, but this should fix the issue to unblock CI.

chore: Fix Core CI relating to summary keys

---

weave/legacy/ops_domain/wb_util.py

We discovered the root cause of the issue and are pinning wandb until fixed. See https://github.com/wandb/core/pull/22966

chore(dev): "Revert Fix Core CI relating to summary keys"

---

weave/environment.py

To simulate what a Windows user might see, I moved my `~/.netrc` file to `~/_netrc`.
The resulting output was unexpected, outputting a "Please login" prompt but then continuing as if the user was authenticated. The resulting `WeaveClient` would throw a `401 Unauthorized` error on subsequent actions.
```
Please login to Weights & Biases (https://wandb.ai/) to continue:
wandb: Currently logged in as: jamie-rasmussen. Use `wandb login --relogin` to force relogin
Logged in as Weights & Biases user: jamie-rasmussen.
View Weave data at https://wandb.ai/jamie-rasmussen/2024-07-29_authtest/weave
Out[2]: <weave.weave_client.WeaveClient at 0x16afa5d90>
```

fix: netrc authentication for windows

---

weave-js/src/components/Dialog/Dialog.tsx

https://wandb.atlassian.net/browse/WB-20140
Noticed the "delete run" experience is really broken in reports
https://github.com/user-attachments/assets/562dac41-991e-454d-a2e6-4336cf2f5388
Looks like we [recently updated that modal](https://github.com/wandb/core/pull/22777) from semantic to the radix one, which is great! Unfortunately I guess a lot of reports page elements have weird z-indices. The semantic modal had `z-index: 1001` applied but our radix one doesn't set z-index at all.
Honestly I'm not sure of the best way to handle this, but it seems like the safest option is to use that same z-index on our radix dialogs so when devs convert semantic ones to the radix one, we won't be hit with unexpected styling issues like this in the future.

fix(ui): Center dialog, add z-index

---

weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/grid/pin.test.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/grid/pin.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableColumns.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-20138
Same kind of change as in https://github.com/wandb/weave/pull/1976 and https://github.com/wandb/weave/pull/1956
The Material UI grid allows you to pin columns to the left or right. This state was previously just kept in the component but is now stored in the URL. This is another step towards having URLs that a user can bookmark or share.

feat: store pinned column state in URL

---

weave/integrations/langchain/langchain.py

Internal Jira: https://wandb.atlassian.net/browse/WB-20199
Because the `-` in the regular expression was not escaped it matched any characters between `.` (46) and `_` (95) in the ascii codes, including `:` (58). The `^` inverts the match, meaning those characters were not substituted. (We're also lacking proper validation of the op name at other layers, which will be addressed separately.)

fix: langchain integration regex bug

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewerSection.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-20207
When we have the peek drawer open, the ObjectViewer for the inputs/outputs may stay mounted but with a changing `data` prop. When the data being rendered changes we need to recompute the default expansion mode, clear out the state for manually expanded nodes, etc.

fix: object viewer autoexpand

---

weave/flow/scorer.py
weave/tests/test_evaluations.py

This can happen when the model or scorer is non deterministic (ie. uses LLM to generate JSON) or when there are conditional keys in the output. A user recently had all "Nones" for an "error" key.

fix: Evaluations are robust to empty / null key entries

---

weave-js/src/components/Form/TextField.tsx

There are a few issues with our TextFields component so I wanted to clean it up a bit.
- Hover outline was wrong shade. Before/after:
https://github.com/user-attachments/assets/0b457df6-a215-461a-a582-3db13869a4c9
- Focus outline was not showing up
https://github.com/user-attachments/assets/9703fbe7-c7b9-4f3d-9ad8-182f8592ad39
- Icon did not have correct opacity in disabled state
https://github.com/user-attachments/assets/e7724396-c835-4548-b264-db8b1e8f52e6
- Icon was not triggering hover outline
https://github.com/user-attachments/assets/7b134da6-7f58-41fd-a5b3-5de82e6a61fb
- Icon and prefix elements clash if both are present
https://github.com/user-attachments/assets/e7108b4b-ee36-4130-b9b0-d67ef9a26d1d
- Extra polish: input should have right padding so extra long texts don't bump …

style(ui): Update TextField styles

---

.pre-commit-config.yaml

Our mypy step in pre-commit depends on types-all.  types-all depends on types-pkg-resources. All of the versions of types-pkg-resources were yanked: https://pypi.org/project/types-pkg-resources/#history
This is a temporary hack to unblock us while we wait for types-all to be updated.

chore: fix CI by pinning yanked types-pkg-resources

---

weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/FeedbackGrid.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/FeedbackGridActions.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/FeedbackGridInner.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/Reactions.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClient.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts

Internal Jira: https://wandb.atlassian.net/browse/WB-20018
Adds a button to the feedback grid, allowing you to delete feedback items. A future improvement would be to let people delete their notes from the notes popup.
This PR also adds listeners for feedback create and purge events. This keeps the various places that show feedback in sync as you make changes.

feat: feedback deletion in UI

---

weave/trace_server/trace_server_interface.py

Typing prep for upcoming prs. 
This will allow: 
- call_stream_query to filter out non-requested columns when exporting
- eventually will be passed on to `calls_query_stream` in `clickhouse_trace_server_batched` to only fetch requested columns from the db 
^^^ performance testing TODO on the query perf impact (speculation: there should be a tradeoff where most small queries get marginally slower, while larger queries might even get faster because we arent reading as much data into the db reader? All queries will have smaller payloads over the wire.)

chore: add no-op optional column spec to call query

---

weave-js/src/components/Form/TextField.tsx

Add night-aware dark styles to `TextField` so it matches design team's specifications. This also means the dark mode side won't be broken in storybook anymore :tada:
[figma](https://www.figma.com/design/01KWBdMZg5QM9SRS1pQq0z/Design-System----Robot-Styles?node-id=14657-39606&t=t5GVnW8JvSPGSVgv-0)
before/after:
https://github.com/user-attachments/assets/b5da36cb-763c-4ee7-b1a4-27e8fe48aae2
in app:
https://github.com/user-attachments/assets/a8fa53cd-80bd-47d7-95da-fca3595eb0d0

style(ui): Add dark styles for TextField

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableQuery.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/tabularListViews/operators.ts

Internal Jira: https://wandb.atlassian.net/browse/WB-20281
Our filter conversion was excluding filters with no value, but it is expected for filters using the `isEmpty` and `isNotEmpty` operator to not have a value.

fix: isEmpty and isNotEmpty filter

---

weave/trace/vals.py

Resolves:
- https://wandb.atlassian.net/browse/WB-20297
This PR resolves an issue in `WeaveList` where the `parent` attribute, intended for `Traceable`, was passed into `List` which accepts no kwargs.
The PR resolves this by changing clearly separating Traceable config from the regular list args.  We also do this for dict for consistency.

fix(weave): Fix kwargs init issue for WeaveList and WeaveDict

---

docs/docs/reference/python-sdk/weave/index.md
docs/docs/reference/python-sdk/weave/trace/weave.trace.util.md
docs/docs/reference/python-sdk/weave/trace_server/interface/weave.trace_server.interface.query.md
docs/docs/reference/python-sdk/weave/trace_server/weave.trace_server.remote_http_trace_server.md
docs/docs/reference/python-sdk/weave/trace_server/weave.trace_server.trace_server_interface.md
docs/docs/reference/python-sdk/weave/weave.feedback.md
docs/docs/reference/python-sdk/weave/weave.weave_client.md
docs/scripts/generate_python_sdk_docs.py

Adds:
* Link to source code
* Better support for objects inheriting from BaseModel

chore: Python Docs: Link to source, better pydantic objects

---

docs/docs/reference/python-sdk/weave/trace_server/weave.trace_server.trace_server_interface.md
docs/docs/reference/python-sdk/weave/weave.weave_client.md
docs/docs/reference/service-api/calls-query-calls-query-post.api.mdx
docs/docs/reference/service-api/calls-query-stats-calls-query-stats-post.api.mdx
docs/docs/reference/service-api/calls-query-stream-calls-stream-query-post.api.mdx
docs/docs/reference/service-api/objs-query-objs-query-post.api.mdx
docs/docs/reference/service-api/table-query-table-query-post.api.mdx
weave/tests/test_client_trace.py
weave/tests/test_evaluations.py
weave/tests/test_weave_client.py
weave/trace/tests/test_op_argument_forms.py
weave/trace/vals.py
weave/trace_server/calls_query_builder.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/orm.py
weave/trace_server/sqlite_trace_server.py
weave/trace_server/tests/test_calls_query_builder.py
weave/trace_server/trace_server_interface.py
weave/weave_client.py

These underscores were leftover from an error of experimentation and should be public now
Effects:
```
_CallsFilter 
_SortBy 
_OpVersionFilter 
_ObjectVersionFilter
_TableRowFilter
```

chore: Remove private underscores from interface classes

---

weave-js/src/components/Form/TextField.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/Notes.tsx

Internal Slack: https://weightsandbiases.slack.com/archives/C03BSTEBD7F/p1723216451475369?thread_ts=1723207818.976219&cid=C03BSTEBD7F
Internal Jira: https://wandb.atlassian.net/browse/WB-20311
Fix for IME - the Enter key is used for hiragana to kanji input on a Japanese language keyboard, we were prematurely submitting feedback notes when the user pressed Enter.

fix: Don't submit note form if Enter event pressed as part of IME

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerDirectClient.ts

Dont stream to string, javascript string buffer size is actually very small relative to data size...
Very large projects (openUI) run over this buffer currently. 
Locally tested up to 100,000 simple rows export (36MB)

chore: simpler trace server download

---

weave-js/package.json
weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/StyledDateTimePicker.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/CellFilterWrapper.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterBar.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterPanel.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterRow.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterTag.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterTagItem.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/IdList.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/SelectField.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/SelectOperator.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/SelectValue.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/TextValue.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/ValueInputBoolean.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/VariableChildrenDisplayer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/common.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/types.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/grid/filters.test.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/grid/filters.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableColumns.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableQuery.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimpleFilterableDataTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/StatusChip.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/tabularListViews/columnBuilder.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/tabularListViews/operators.ts
weave-js/src/components/UserLink.tsx
weave-js/yarn.lock

Internal weave: https://wandb.atlassian.net/browse/WB-19861
Adds a new UI for filtering calls and managing of filter state in URL.
In the header, there is a button that opens up the filter editing popup. When there are filters, we will dynamically determine what to show based on the available width:
No filters:
There are filters but none can be shown in the available space:
All filters fit in the available space
Too many filters to show in the available space, but some fit
If there's room to show a filter tag, user can one-click remove it with the 'x' button on the tag.
Clicking on the button opens up a dialog:
Each row corresponds to one filter. The 'x' button can be used to remove a filter, or you can remove all of them at once.
The available operators depend on the selected field, and …

feat: new filter UI

---

weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/trace_server_converter.py

This PR disallows cross-project reference lookups. We implicitly enabled this feature here: https://github.com/wandb/weave/pull/1967, but for a number of reasons, we want to disable it.
Please see https://github.com/wandb/core/pull/23266 for additional commentary

chore: Disallow cross-project reference lookups

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerClientTypes.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/traceServerDirectClient.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts

This PR changes the return type of the FileContent in the Trace Server YS client to ArrayBuffer. 
This should have no impact on users - this is part of Image support, trying to decouple the PR

chore: Refactor FileContent to ArrayBuffer

---

weave-js/src/components/UserLink.tsx

The user link tooltip preview is supposed to have some help text noting you can click to open a larger card. I accidentally removed this in https://github.com/wandb/weave/pull/2107

chore: accidentally removed help text

---

weave-js/src/components/PagePanelComponents/Home/Browse3.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/context.tsx

At the time we were adding the new sidebar (https://github.com/wandb/core/pull/20661/) we also added redirecting of the `/entity/project` page to the traces page when the project has Weave data and no Models data.
Browse3 has similar redirection code, taking you from `/entity/project/weave` to the traces page.
In its current state, the code always redirects you to the traces page. It was doing a query to see if the project has published data and showing a loader, but this is unnecessary if we're going to redirect regardless of the result.
The query is particularly bad because the limit parameter to useRootObjectVersions does not get passed along and used as it should, so it is fetching all of the object information for the project even though we only cared about a non-zero count.

chore: remove dead redirect code

---

weave/tests/test_op_decorator_behaviour.py
weave/trace/vals.py

Resolves:
- https://wandb.atlassian.net/browse/WB-20326
This PR automatically passes `self` into the `call` special func when attached to a `WeaveObject`.  We already do this for [`Object`](https://github.com/wandb/weave/blame/andrew/call-self/weave/flow/obj.py#L83).

fix(weave): Automatically pass self instance when using `call` special func on a `WeaveObject`

---

weave/weave_client.py

This PR removes a few extraneous objects that don't seem to be used anywhere.
The extraneous `Dataset` is particularly confusing because we have an actual `Dataset` weave object

chore(weave): Remove extraneous objects

---

weave/trace/op.py

This PR removes (what seems to be) an extraneous save during calling.
The inputs are saved inside `client.create_call` already:
https://github.com/wandb/weave/blame/andrew/remove-extraneous-save/weave/weave_client.py#L518

chore(weave): Remove extraneous save

---

weave-js/src/components/PagePanelComponents/Home/Browse2/browse2Util.ts

this makes sure that something like:
```
class Model(weave.Model):
inner_settings: dict
```
is properly flattened. As implemented, `inner_settings` will not get flattened.

chore: Fixes smart flattening to only skip custom types

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts

Are you like me and sometimes try to lookup deleted or missing ops or objects? Do you hate page crashes? Me too! 
Before: Yuk!
After: ...
Paired with https://github.com/wandb/weave/pull/2154, it actually is a nice dismissible error!:

fix: No longer crash when object or op not found in UI

---

weave/tests/test_weave_client.py
weave/weave_client.py

Here's the test case:
```
def test_ref_in_dict(client):
ref = client._save_object({"a": 5}, "d1")
ref2 = client._save_object({"b": ref}, "d2")
obj = weave.ref(ref2.uri()).get()
assert obj["b"] == {"a": 5}
```
Prior to the fix, we would actually save the Ref object itself as an ObjectRecord. After the fix we correctly save the ref as its uri string.

fix: serialization bug when a Ref is put directly into a dict

---

weave-js/src/components/PagePanelComponents/Home/Browse3/filters/SelectValue.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/TextValue.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/filters/common.ts

If you have selected a numeric operator like "<" the input element for the value should be put into numeric mode.
With this change, if you have a non-numeric operator and value, and then switch the operator to be numeric one, you will get a console warning. (The input will appear empty.) I considered handling clearing the value in this case, but it is actually convenient to have the original value there if you switched operators by mistake or to see what would happen and want to switch the operator back. It should be possible to handle state more intelligently to avoid this warning, but leaving that additional work for the future since the warning doesn't seem to hurt anything.

fix: filters with numeric operator should only accept numeric values

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTableButtons.tsx

Internal Figma: https://www.figma.com/design/mufhcDVpsRg9HJrLM61PCN/Weave-(Latest)?node-id=1089-18178&t=U28KGlyGddcrndUf-0
Internal Jira: https://wandb.atlassian.net/browse/WB-20484
We're planning to use the header space for saved view controls. Moving export and delete calls grid controls to "filter bar" area.
Need to check with design on where the Compare button should be.
Before:
After:

chore: move header buttons in preparation for saved views design

---

weave-js/src/components/PagePanelComponents/Home/Browse2/Browse2OpDefCode.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts

https://wandb.atlassian.net/browse/WB-20503
Before:
After:

fix: if code for op can't be found, show alert instead of crash

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/SimplePageLayout.tsx

Nothing is using this menu code in SimplePageLayout and it is all Material UI components so wouldn't look consistent with the rest of the site if someone did use it.

chore: remove dead code from SimplePageLayout

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx

Follow up to https://github.com/wandb/weave/pull/2191
After consulting with @adamwdraper this is where the Compare button should go in preparation for a top Saved Views header.
Before:
After:
Note that after this change I think the WeaveHeaderExtrasContext is unused and we should consider removing it.

chore: move evaluation compare button

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts

https://wandb.atlassian.net/browse/WB-20522
Query returns while internal query is still loading, so we flash the "code not found" message. 
Prod:
This branch:

fix: code query returns twice, breaking loading state

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts

Pernicious little bug that was causing me hassles. Not sure of the best way to fix this, but this does solve the problem...
`useCall` is a hook, so we expect keys to change and have the result change as well. As written in master, while we handle key changes (with deepmemo), we actually return the previous result before calling `doFetch`. We not only return the old result, but we set the cache with the **new** key to the **old result**!
Note: I think this affects all the hooks that use this pattern...

fix: useCall can set stale cache results

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/DataTableView.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-20533
To test this, I updated the `wf` script's dataset add functionality and tried with 2k and 20k row datasets. It loads slowly but under 10s for larger and UI works.

chore: update data table UI row limit to 10k

---

weave-js/src/components/LinearProgress.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/compareEvaluationsContext.tsx

Evaluation comparison was using a default styled MUI progress indicator. Add some styling to make it more harmonious with our palette.
Before:
After:

chore: update LinearProgress styling

---

docs/docusaurus.config.ts

Flipping the docs site to weave-docs.wandb.ai

chore(docs): Update host and base url

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/traverse.ts

https://wandb.atlassian.net/browse/WB-18553
This pr slightly changes the way we render refs in the object viewer. During replacement of refs with values, instead of relying on deleting refs once we see them, keep track of if we replaced. Currently we don't handle the case when we might want to replace multiple identical refs, as we have already deleted the ref from our lookup. 
Prod:
This branch:

fix: object with dupe ref not loading in ui

---

weave/legacy/arrow/list_.py
weave/legacy/artifact_wandb.py
weave/legacy/compile.py
weave/legacy/compile_domain.py
weave/legacy/compile_table.py
weave/legacy/decorator_op.py
weave/legacy/dispatch.py
weave/legacy/eager.py
weave/legacy/execute.py
weave/legacy/graph_mapper.py
weave/legacy/input_provider.py
weave/legacy/mappers_arrow.py
weave/legacy/mappers_publisher.py
weave/legacy/node_ref.py
weave/legacy/op_def.py
weave/legacy/pyfunc_type_util.py
weave/legacy/run_streamtable_span.py
weave/legacy/show.py
weave/legacy/stitch.py
weave/serve_fastapi.py
weave/tests/legacy/test_node_ref.py
weave/tests/legacy/test_stitch.py
weave/tests/legacy/test_wb.py

Split out from: https://github.com/wandb/weave/pull/2182
This slice moves the following to `legacy`:
- `eager`
- `stitch`
- `pyfunc_type_util`
- `node_ref`

chore(weave): Legacy Refactor pt6

---

weave/tests/trace/test_weave_client.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/sqlite_trace_server.py

[DD trace](https://app.datadoghq.com/apm/services/weave-trace/operations/fastapi.request/resources?query=env%3Aprod%20operation_name%3Afastapi.request%20service%3Aweave-trace&dependencyMap=qson%3A%28data%3A%28telemetrySelection%3Aall_sources%29%2Cversion%3A%210%29&deployments=qson%3A%28data%3A%28hits%3A%28selected%3Aversion_count%29%2Cerrors%3A%28selected%3Aversion_count%29%2Clatency%3A%2195%2CtopN%3A%215%29%2Cversion%3A%210%29&env=prod&errors=qson%3A%28data%3A%28issueSort%3ATOTAL_COUNT%29%2Cversion%3A%210%29&fromUser=false&graphType=flamegraph&groupMapByOperation=null&infrastructure=qson%3A%28data%3A%28viewType%3Apods%29%2Cversion%3A%210%29&isInferred=false&logs=qson%3A%28data%3A%28indexes%3A%5B%5D%29%2Cversion%3A%210%29&panels=qson%3A%28data%3A%28activePanelKey%3Atrace%2Ctrace%3A%28trace …

chore: don't resolve table refs in call_stream ref expansion

---

weave-js/src/components/PagePanelComponents/Home/Browse3/feedback/FeedbackGridInner.tsx

Internal Jira: https://wandb.atlassian.net/browse/WB-20602
Autosize to avoid cropping feedback grid type column, and hide overflow rather than having it escape into next column over.
Before:
After:

fix: feedback grid overflow

---

weave/tests/trace/test_client_trace.py
weave/trace_server/validation.py

Adds new flag:
```
SHOULD_ENFORCE_OBJ_ID_CHARSET = False
```

chore: Temporarily disable server-side object id validation until new client bakes

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTableButtons.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableColumns.tsx

Lets use the pre-computed ref columns rather than just guess. This makes everything look cleaner, and should also improve performance on the backend. We will not expand columns that have refs only in rows that aren't present on the screen. In this case they wouldn't be in the header, so I'm not sure its a big issue. 
Also tweak column management to always dump all columns when json/jsonl
Impact: 
- json export now always includes all columns
* doesn't make wonky columns when column headers include `"."`
- performance improvement for exports with many nested columns, as we avoid having to check for refs in the server
- more accurate [analytics](https://mixpanel.com/s/2ubLxe) on columns

chore: better expand ref management in export

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx

Fix regression in [this pr](https://github.com/wandb/weave/pull/2247), where we skip rendering of different refs with the same path. 
Prod: 
Branch:

fix: render nested objects with the same path

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallTraceView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CustomGridTreeDataGroupingCell.tsx

This pr:
- adds display_name to the trace query
- displays the display name preferentially
Prod: 
This Branch:

fix: display displayName in trace tree

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallTraceView.tsx

Add back query for `summary` to render cost in tree view
Prod:
Branch:

chore: add back summary to treeview query

---

.github/workflows/test.yaml

We currently expand the wrong thing.  I always have to click the one above it to see the errors!

chore(weave): CI: Remove extraneous step with linting errors

---

weave/tests/trace/test_client_trace.py
weave/tests/trace/test_weave_client.py
weave/tests/trace/util.py
weave/trace/weave_client.py

These seem to be missing, and are required to satisfy the updated tests in: https://github.com/wandb/weave/pull/2260

chore(weave): Add {started,ended,deleted}_at attributes to high level Call object

---

docs/scripts/generate_python_sdk_docs.py
weave/conftest.py
weave/trace/weave_init.py
weave/trace_server/tests/test_remote_http_trace_server.py
weave/trace_server_bindings/remote_http_trace_server.py

1. Splits out `remote_http_trace_server.py` and clarifies its role as a language binding, not part of the server
1. https://wandb.atlassian.net/browse/WB-20422

chore(weave): Split out Trace Server bindings

---

weave/tests/trace/test_client_trace.py
weave/trace/weave_client.py

1. Inlines pydantic and dataclass objects such that they don't have their own refs, unless explicitly published.
```py
class Something(BaseModel):
a: str
b: int
class WeaveObject(weave.Object):
a: str
s: Something    
s = Something('a', 2)
wo = WeaveObject('b', s)
weave.publish(s)   # `s` object gets a ref
weave.publish(wo)  # `s` object does not get a ref
```
This should speed up the write path for deeply nested objects
- https://wandb.atlassian.net/browse/WB-20357

chore(weave): Inline pydantic and dataclass objects

---

weave/legacy/weave/op_def_type.py
weave/tests/trace/test_op_versioning.py
weave/trace/op_type.py

Code saving fix.
If there were multiple paths to the same symbol we'd repeat it. This could really explode into generating tons of repeated code.
This PR just makes it so we do nothing if we've already seen a symbol. And adds a test.

fix: don't repeat code we've already seen

---

weave-js/src/common/util/fuzzyMatch.tsx

Please use conventional commits in your PR title. If you are unsure what conventional commits are or how to use them, please check out [this notion doc](https://www.notion.so/wandbai/17966b997841407b95b7c36414ae0634).
- https://wandb.atlassian.net/browse/WB-17219
This PR introduces a helper for highlighting regex matches within a string. This is an alternative to the fuzzy match that is currently implemented and will be used for section and panel names when the user searches panels with a regex.
The consumers of this new function are introduced in https://github.com/wandb/core/pull/23675
Please answer the following as appropriate, leave blank if no. If you aren't sure, ask someone!
- Testing: how was this PR tested?
- Migrations: are there frontend or backend migrations?
- On-prem: will …

chore(weave): add regex highlighting method for panel search

---

weave-js/src/common/util/fuzzyMatch.tsx

Please use conventional commits in your PR title. If you are unsure what conventional commits are or how to use them, please check out [this notion doc](https://www.notion.so/wandbai/17966b997841407b95b7c36414ae0634).
This PR fixes an infinite loop that can occur if the regex highlighting helper receives a zero-width regex (eg `^`) as input

chore(app): fix possible infinite loop in regex highlighter

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTableButtons.tsx

Now, selecting a row will populate the `call_ids` field of the filter, respecting the CallsQueryReq and CallFilter Specs:
CallsQueryReq:
```python
class CallsQueryReq(BaseModel):
project_id: str
filter: Optional[CallsFilter] = None
limit: Optional[int] = None
offset: Optional[int] = None
sort_by: Optional[List[SortBy]] = None
query: Optional[Query] = None
include_costs: Optional[bool] = Field(
default=False,
description="Beta, subject to change. If true, the response will"
" include any model costs for each call.",
)
include_feedback: Optional[bool] = Field(
default=False,
description="Beta, subject to change. If true, the response will"
" include feedback for each call.",
)
columns: Optional[List[str]] = None
expand_columns: Optional[List[str]] = Field(
default=None, …
```

fix: python code export filter respects selected rows in table

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallTraceView.tsx

Refresh the trace tree when the call in the detail page is renamed (or deleted)

chore: refresh trace tree on rename/delete call

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/OverflowMenu.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx

This pr: 
- Adds parameter to specify text "call" or "evaluation" depending on the call span name
* also handles the case of both, and both plural
- Removes the button disable when non-critical queries are loading
Prod:
This branch:

chore: delete button now accounts for call/evaluation

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/traverse.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/ObjectVersionsPage.tsx

https://wandb.atlassian.net/browse/WB-19884
Handle object `name` exactly the same as `description`, rather than always filtering out `name`. 
Prod: 
This branch:

chore: show object name if set

---

docs/docs/guides/tracking/tracing.mdx

I am not sure why, but `# highlight-next-line` is broken in prod, but not locally at least on `tracing.mdx`. Disabling for now

chore: Fix prod docs

---

weave/legacy/weave/environment.py

Changes the reaction to netrc and apikey existing to a print and not a raise when not in prod

chore(weave): change raise to print for netrc existing with api key

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableColumns.tsx

The weave summary derived fields should be used to create nice fields in the UI, but only once the SDK has been released. `summary.weave` should always be safe to hide. 
Also change the field names because they now conflict (in a weird and degenerate way) with the derived fields. 
Prod:
Degenerate case (with horizontal scrolling):
Branch:

chore: hide derived fields from trace table

---

docs/docs/guides/tracking/tracing.mdx

Adds an example to docs of how to use `weave.create_call` and `weave.finish_call` to trace function calls.
Relevant new section:

chore(docs): Document low-level Python API for creating calls

---

weave/trace_server/calls_query_builder.py
weave/trace_server/orm.py
weave/trace_server/token_costs.py

1. we were not sorting in the final cost query
2. the orm had incorrectly ordered some clauses, it is now
- group by
- order by
- limit, offset
instead of 
- order by
- limit, offset
- group by

chore(weave): correctly sort cost query

---

weave/trace_server/calls_query_builder.py
weave/trace_server/tests/test_call_lifecycle.py
weave/trace_server/tests/test_calls_query_builder.py

It is possible under a few conditions that the start event is logged after other events, thereby creating partial call objects. This can occur if the client sends the request out of order (allowed) and in such cases could actually drop the start event. Our DB layer should be robust to this and in such scenarios filter out the partial results.

fix: Fixes backend to correctly filter out results where start even is not yet processed

---

weave-js/src/components/PagePanelComponents/Home/Browse3/filters/FilterPanel.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTableButtons.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/callsTableQuery.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/tsDataModelHooks.ts
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/wfReactInterface/wfDataModelHooksInterface.ts

In this PR, I add a little refresh button to the calls table. It simply updates the table and is way way better than doing a full page refresh. I was going to implement polling, but:
a) I want to avoid a lot of server pings
b) To really make polling effective, we probably want to add more smarts to:
1. Quickly determine which ids need refreshing
2. Refetch those ids in particular
This is a little more advanced than the timebox I gave myself, so stopping with basic refresh for now.

feat: Add a refresh button to the Calls Table

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewerSection.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueView.tsx

@adamwdraper notice that we render a "Value" key for lists in the output. This is a bit of legacy code from when our viewer was not generic enough to handle lists. It is now. This PR cleans up this code path effectively removing the dummy "Value" key.
Before (above), After (below)

fix: Remove `Value` prefix from output rendering

---

weave/conftest.py
weave/trace/async_job_queue.py
weave/trace/weave_client.py
weave/trace_server/sqlite_trace_server.py

This PR is a patch to the previously reverted: https://github.com/wandb/weave/pull/2302 ... Essentially i made the exit procedure safer and tested in:
* local ipython
* local python
* colab
This is a good view to see changes on top of the previous pr: https://github.com/wandb/weave/pull/2367/files/1224f719c58b7289ecccc1cfaba8603b56893665..2316cb120567a657eb79ed1e0bc67e9b6d7db1bf
The original implementation had a bug that when running in ipython, explicitly exiting would throw:
```
Exception ignored in: <function WeaveClient.__del__ at 0x141ae9080>
File "/Users/jamie/source/wandb/core/services/weave-python/weave-public/weave/trace/weave_client.py", line 1116, in __del__
File "/Users/jamie/source/wandb/core/services/weave-python/weave-public/weave/trace/wea …
```

feat: Make Image serialization background process

---

weave/trace/table.py

Seemed odd that I could iterate over the rows in a table and access them by index but `__len__` wasn't implemented.
(I also feel like the API for Dataset should do the same thing, but that's worthy of a broader discussion.)

chore: make len(dataset.rows) work

---

weave-js/src/components/Button/Button.tsx

before: i noticed the info tooltip buttons in the workspaces overflow menu were not vertically centered
after: problem is fixed (very subtle but definitely different!)
additional testing: spot-checked various other buttons with tooltips and they all still look correct

fix(ui): Inherit display styles for Buttons with tooltips

---

docs/docs/guides/tracking/tracing.mdx
weave/flow/obj.py
weave/tests/trace/test_op_call_method.py
weave/tests/trace/test_op_decorator_behaviour.py
weave/trace/vals.py

https://wandb.atlassian.net/browse/WB-20637
This removes auto-self-binding that could sometimes bind to the wrong instance, leading to unexpected results.
Unit tests

fix(weave): Remove erroneous self-binding of weave ops on classes

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallPage.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/CompareEvaluationsPage.tsx

Reuses the evaluation comparison page as default tab when viewing an evaluation call.

feat: add Evaluation tab

---

weave-js/src/components/Button/Button.tsx

Button `tooltip` prop is typed as a plain `string`, even though it's perfectly capable of handling rich, composable contents. This change simply updates the prop type to allow this.
Use case: I have an info button tooltip where I want to apply semibold styling to a specific word and also display an icon

chore(app): Update Button tooltip type

---

weave/trace/async_job_queue.py
weave/trace/weave_client.py

Currently, our system has a few async mechanics to handle writing data to Weave in a non-blocking way. As currently implemented, I used both `atexit` handlers AND `__del__` overrides. This system was admittedly over-engineered and overkill. As a result, in some scenarios, we were running into error at exit time for some machines. 
This PR does the following:
1. Remove all the `__del__` handling. Upon reflection, this is not needed and makes everything more complicated. Remove a bunch of code relating to this
2. Refactor the code to just use `atexit`
The net effect of this PR is that:
1. The only classes that register exit functions are those that explicitly construct the threads (much much cleaner). This is in contrast to my prior approach which was trying to also execute cleanup at …

fix: Simplify the exit procedures to reduce flush errors

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/CompareEvaluationsPage.tsx

Now that the eval view is not full-screen, we need to measure the available hight for the example view to work correctly. Notice how the left browser (new) has full height of the pager when scrolled to the bottom

fix: dynamic height for eval page (particularly in drawer view)

---

weave-js/src/components/PagePanelComponents/Home/Browse2/CellValue.tsx

In cell values, if a number looks like a timestamp, give it the timestamp treatment.
Before:
After:

chore: guess cell format for timestamps

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/common/Links.tsx

- Fixes [WB-20956](https://wandb.atlassian.net/browse/WB-20956)
Simple clipping of the text
Prod: 
This branch:
[WB-20956]: https://wandb.atlassian.net/browse/WB-20956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: overflow trace name gracefully

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CompareEvaluationsPage/CompareEvaluationsPage.tsx

- Fixes [WB-20976](https://wandb.atlassian.net/browse/WB-20976)
This component was designed to just be passed in the id, now we listen to changing props even if mounted.
Prod:
Branch:
[WB-20976]: https://wandb.atlassian.net/browse/WB-20976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: dont crash when changing eval peek

---

weave/trace/weave_client.py

The dataflow for saving objects has been notoriously complex and undocumented. This PR changes that by:
1. Co-locating common functions
2. Commenting profusely
3. Re-arranging some switch statements to be grouped more logically.
There should be no logical changes as a result of this PR

chore: Refactor & Comment Saving Methods

---

weave/tests/trace/test_objs_query.py
weave/trace_server/clickhouse_trace_server_batched.py
weave/trace_server/sqlite_trace_server.py
weave/trace_server/trace_server_interface.py

This PR:
1. Adds a bunch of object query tests
2. Adds limit/offset/sort so we can paginate more effectively on the server

feat: Add pagination and sorting to object APIs

---

weave/tests/trace/test_trace_settings.py
weave/trace/op_type.py
weave/trace/settings.py
weave/trace/weave_client.py

https://wandb.atlassian.net/browse/WB-20322
Adds a setting to control code capture, either in code or by env var with `WEAVE_CAPTURE_CODE`

feat(weave): Add setting to control code capture

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueView.tsx

Makes empty objects less confusing in inputs
Before:
After:

chore: indicate empty dictionary better

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ValueView.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/traverse.ts

https://github.com/wandb/weave/commit/da7422ea593f2f6dc7126113082676cc7a1c94a5 introduced some modified logic to the expansion code. As a result, we were double expanding, breaking the expansion views.
See bug and fix here: https://app.wandb.test/a-sh0ts/evalgen_test_117112/weave/calls/0192101d-ad57-79b0-8458-9d3f3bb3293f

fix: Ref expansion crashing page

---

weave-js/src/components/Panel2/PanelString.tsx

- https://wandb.atlassian.net/browse/WB-20787
This PR updates the plain text display for table cells to format arabic/hebrew text right-to-left (RTL). A regex specifying unicode ranges for arabic, hebrew, and related scripts is tested against the text. If matches are found, RTL formatting is applied. Specifically, we set `direction: rtl` and `text-align: right` on the div containing the text.
Before:
After:
This PR adds a regex check for these character ranges for all table cells rendering plain text. The code already parses the text to detect if its a url and applies special formatting in this case, so this pr does not worsen the asymptotic complexity of the related code.

chore(weave): auto detect right-to-left text in tables

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallDetails.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewer.tsx
weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/ObjectViewerSection.tsx

This PR does a few things:
1. Auto-expand the first layer of inputs and outputs
2. Make sure that single-ref outputs are viewed in the object viewer
3. Fix the object viewer to support expanding direct child refs
Good example: https://app.wandb.test/adrian2/support-model-eval/weave/calls/01919101-4953-79e3-b797-68e9e506abf9

fix: Fix rendering of singular ref outputs

---

weave-js/src/core/ops/domain/artifact.ts

- Fixes [WB-20951](https://wandb.atlassian.net/browse/WB-20951)
- Fixes #NNNN
Updated opArtifactCreatedAt to be similar to opArtifactVersionCreatedAt. 
https://github.com/wandb/weave/blob/bb9c605b25066f34e918cc7971795274516fb3d5/weave-js/src/core/ops/domain/artifactVersion.ts#L150-L164
invoker_fe_prod.ini with w0 enabled
[WB-20951]: https://wandb.atlassian.net/browse/WB-20951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(artifacts): fix date returned by opArtifactCreatedAt in weave-js

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallPage/CallChat.tsx

Internal Slack: 
https://weightsandbiases.slack.com/archives/C05DURZNT41/p1727118627553499
When a message contains `tool_calls` then `content` might also exist but be null.

fix: chat view not showing when it should

---

weave-js/src/components/PagePanelComponents/Home/Browse3/pages/CallsPage/CallsTable.tsx

Remove feedback from the list of default pinned left columns.
Internal Notion: https://www.notion.so/wandbai/Traces-table-d0abd588c49e4a77a213db27af717b4f?pvs=4#10ae2f5c7ef38086bcd8c3cecc19b0ba

chore: remove feedback from pinned cols

---

weave-js/src/components/FancyPage/useProjectSidebar.ts

Just moving Traces button to top of nav and removing commented out code.
Internal Notion: https://www.notion.so/wandbai/Nav-bar-f9ddbab018824a59b30b0d0ff17d7de6?pvs=4#10ae2f5c7ef380a2b5fcd98e93dceed7
Before:
After:

chore: reorder nav bar, traces to top
